### ISSUE TITLE
Mobilizer setting request 

### ISSUE THREAD

**Issue by stayingretired** [yanus171/Handy-News-Reader#103]
Some articles not loading unless I manually deactivate  Mobilizer.  

While this may be a valid issue only for partially updated feeds, it would be nice if you had a global setting to ignore Mobilizer.

Otherwise, I am enjoying the app.

**Comment by yanus171** [comment]
Give me a feed url and I will tell you how to setup app mobilizer to load 
full texts correctly

**Comment by bcm314** [comment]
Although I'm not a soccer-fan, I was "gambling" a little bit with HNR and detected such an URL you can test:

Feed URL: https://rss.focus.de/fol/XML/rss_folnews_eilmeldungen.xml
Article URL: https://www.focus.de/sport/fussball/dfbpokal/live-ticker-hamburger-sv-gegen-rb-leipzig-das-halbfinale-im-dfb-pokal_id_10624090.html

When you open the article, you can see only the part from "20.10 Uhr" to "4. Minute" of the game.

I'm not 100% sure, but I believe I've tested also the "reload" function before the game was over without any result.
Maybe that belong's to the same issue (or maybe "article updated" is still not supported yet - have to check later)

**Comment by yanus171** [comment]
Add line focus.de:class=articleContent to Content extract rules setting (in additional) and reload full text.

The auto mobilizer algorithm tries to find the most bigger part of the article and treats it as a full text. This is not always get the full text correctly. So I added a possibility to set a fulltext root node of the article manually (for the site domain). There is a special Reload with tags article  context menu item, which helps to find the required class name.
