### ISSUE TITLE
Performance and freezing issues.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#104]
For a long time (at least a couple of days, probably weeks) My Handy often acts this way: while browsing articles (full article text in full screen) sometimes everything freezes (which I recognize by it can't be scrolled anymore). Then sometimes the app re-launch itself - or sometimes I need to go back to the desktop first, and then launch it by hand. Then it doesn't remember the position of reading. Besides, in those cases it constantly refreshes feeds, i.e. if the app re-launched itself - it often does the refresh, although it has been done a moment ago.

The app crash file, however, has no corresponding modification date - so this behavior is not registered there.

I remember some time ago You've mentioned a quasi-similar behavior due to using MySQL instead of saving articles directly on the device.

**Comment by yanus171** [comment]
Does this issue belong to a particular feed? Which has LONG articles for example. By the way Handy now displays article sizes near date of article in article list.

**Comment by ThomasLeigh** [comment]
I am almost sure that it isn't confined to one particular feed. It looks like it happens by random.

**Comment by yanus171** [comment]
Try to install previous app versions to see when this  bug has appeared

**Comment by ThomasLeigh** [comment]
You see, You mentioned this case long ago and I've also been experiencing it at the time. It's hard to determine if it became worse over the time or just is on the same level - because I experience it for a long time now (I don't remember the time when it acted the other way). Besides I'm not sure if it is the app's issue - because My phone is old, some other apps also have issues which seem to Me it may be connected with the phone's "antiquity", so to speak. Unfortunately this is the old one and can act wrong - for example, it may shut down by 30-40% battery level (!). :( I'm sad that after a while I can loose it.

So I'm not so sure about what is the root of the case. The only trace is that You Yourself has noticed a kind of a similar behavior long time ago, and connected it with MySQL efficiency.

**Comment by ThomasLeigh** [comment]
Now it freezes noticeably more often, even more than one time per an article. Unfortunately I don't know if it has something to do with My old phone. Is there a version (out of the past ones) You Alex prefer for Me to test in this regard?

**Comment by ThomasLeigh** [comment]
I've tried to return to the old (pre-installed) ver. of _WebView_ - it didn't help :( . It very annoying: the app freezes once for a while, and then re-launch itself, refreshing all feeds again. It happens even twice per a single article - regardless of which feed I read.

I don't know what to do, should I choice a random prev. ver. of _Handy_?

**Comment by yanus171** [comment]
How many articles do you have? It has sense to try old app version. Try to turn off show article group count in app settings

**Comment by yanus171** [comment]
I have no idea about what old app version to test

**Comment by ThomasLeigh** [comment]
I don't use article group count. Currently I have 2083 articles (643 favorites, 1362 unread).

**Is it necessary that I should go back to some older ver. of _HNR_?**

**Comment by ThomasLeigh** [comment]
I ask because it is much of a hassle to browse all those unread articles first. I would rather wait for some newer ver. which could be better in this regard.

**Comment by yanus171** [comment]
If you will the version from which this problem started I would help me to resolve the problem. Anyway I understand that it's not an easy to test tens of version, so you can wait till the problem will be fixed someway else... For example by this one https://github.com/yanus171/Flym/releases/tag/v0.8.0

**Comment by ThomasLeigh** [comment]
Thank You, I'll check it out. The whole thing is weird, because it doesn't occur regularly - it looks like it happens "by chance".

**Comment by ThomasLeigh** [comment]
v0.8.0 - so far so good, although My phone seems to be unpredictable, so I'll keep an eye on this and let You know.

**Comment by ThomasLeigh** [comment]
Just tested browsing new unread articles (full article text/full screen) - the issue still occurs. After two dozens of articles or so it freezes, and I need to wait around 20-30 sec. (My guess) for the app to re-launch the full article screen, and the whole refresh (all feeds update) in the background. I've just realized it may be a significant concern in terms of the battery being used without a need.

**Comment by ThomasLeigh** [comment]
I've tested a couple of previous versions because this issue is really annoying and much of an obstacle :( . Unfortunately it occurs even within the first version which is able to recover Favorites: 0.7.39. I think, however, that I will test some older ver. anyway - because this is much of a hassle :( .

BTW, now the old scrolling animation seems to look better to Me, mostly because is more gentle and it has some "slowing down" effect at the end. :) **Any chance to bring it back, to have a choice between the two animation styles?**

**Comment by ThomasLeigh** [comment]
0.7.15 - the same.

**Comment by ThomasLeigh** [comment]
I can't find any older ver. with an .apk file to download. Regardless of that, however, it seems that this issue occurs always, in every version. So maybe it is not the app issue, but something with My phone or WebView on older devices (I am familiar with this theme in case of other apps and other users).

Now it seems there is no hope :( :( :( :( :(

**Comment by ThomasLeigh** [comment]
@yanus171 I've managed to record this issue - maybe it helps. I've recorded how I usually read - it looks as on the video: at some point the screen freezes and I must to wait for it to relaunch itself (it also do the complete refresh each time this situation happens). Sometimes this issue doesn't occur, sometimes it may occur several times per one article. Hard to determine when exactly, in what circumstances, i.e. it's hard to point out any pattern here. It looks as follows:

https://drive.google.com/file/d/1-nAv_aRDzp-oEYSMBf2Cm31KyI9wtHyj/view?usp=sharing

**Comment by ThomasLeigh** [comment]
@yanus171 

I'm not yet sure, but I have the impression that on My device oftentimes it freezes alongside using tap gesture (random occurrence) to scroll the page - but it seems not to freeze if I do the same with volume buttons. I'll test it for a couple of days to determine if I'm right. May it be a kind of a clue?

**Comment by ThomasLeigh** [comment]
Unfortunately it's not the case - the issue still occurs, even while using volume buttons.

**Comment by yanus171** [comment]
I don't see the freezes nor the app restart on that video

**Comment by ThomasLeigh** [comment]
@yanus171 

Since around 1:24min. of the video I wasn't able to scroll the page anymore. The app has not responded to any action (tap, etc.) and after a while it reloaded its screen by itself, as in the video.

**Comment by ThomasLeigh** [comment]
I'm gonna to observe how it acts under *v0.10.0* (till now it happened only once = much better, but the time will tell).

**Comment by ThomasLeigh** [comment]
Unfortunately it's still the same: the app froze three times during reading the same article :( . Maybe it has something to do with My old phone, I really don't know :( .

Besides, it often freezes in this way (see a screenshot below) if I launch it after a longer time of not using it:

![Screenshot (Sep 30, 2019 17_08_30)](https://user-images.githubusercontent.com/26142231/66073324-252afb00-e557-11e9-8d64-5b12cc938c12.png)

**Comment by yanus171** [comment]
The last innovation with storing full text in files seems to degrade the performance when long file is readed several times from external memory. Especially from sdcard. SoI am going to implement cache in memory system...

**Comment by ThomasLeigh** [comment]
This is how it looks like when I'm just browsing articles: at the end of the video You see the real long time I need to wait for the app to reload itself due to its prior freezing.

It doesn't matter that I browsed articles during the refresh - similar issue occurs often without it. Although it does not occur always.

https://drive.google.com/open?id=1Rqo-HLu-eQ1aAPSbrVxsDfPgfyfhpKiB

**Comment by yanus171** [comment]
Does it freeze always on the article swiping? Is it concerned with edge 
article?

**Comment by ThomasLeigh** [comment]
It doesn't occur always, it seems unpredictable. It does not refer to any particular article, e.g. the edge one. It may occur both while browsing article list and reading a single article.

**Comment by SIRSteiner** [comment]
Does this problem still exist? If not, please close, because I think that due to the large number of issues it is difficult for @yanus171 to work through everything.

**Comment by ThomasLeigh** [comment]
I cannot tell because I am not able to use the older smartphone with older Android - where the issue has occurred.
