### ISSUE TITLE
Scrolling with full line-height.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#105]
For a long time now I wonder on one particular thing which I am shy to ask - because it's a kind of a crazy stuff ;) .

Jokes aside, I strongly believe in **the power of details** - in My opinion the details are something which can significantly distinguish one app from all the rest around.

When it comes to scrolling, doesn't matter if via volume buttons or tap zones, I'd love to see the feature which assure that _Handy_ **will always show Me full height of both the first and the last text line of an article**. Something like in _CoolReader_ (an e-book reader app), in which I always see full-height text lines.

In the same time, however, we should still be able to scroll "by finger" **smoothly**, i.e. to any line-height we desire. I mean that this line-height correction could be present **only during scrolling by volume buttons or tap zones** - not by Your finger.

**Comment by yanus171** [comment]
Yes, it would be great, especially not to cut the images while page up/down... But I have no idea how to realize it. The html content has many different line sizes based on font size, line intervals and so on...

**Comment by ThomasLeigh** [comment]
Maybe different engine for rendering the content? Probably much hassle, but I suppose it would give You (and the users) more room for customization, and it could work faster than standard _WebView_-based engine.

**Comment by yanus171** [comment]
Yes I periodically think about it too... But It would NOT work faster than webview engine, it would not support any web pages, it would enlarge the apk size several times... And I would not have enough life to implement it

**Comment by ThomasLeigh** [comment]
@yanus171 

I have a question about this:

Suppose _HNR_ obtains article's text and then saves it, and then renders it without _WebView_ , i.e. as a text with basic formatting. It could save us from _WebView_ freezing, as well as enable us to determine the real height of a text line. But it clearly is much hassle and effort, code-wise.

I'd like to determine are there **any** chances You'd like to give it a try someday in the future? If no, let's close this thread.

**Comment by yanus171** [comment]
I can try to make a simple text mode without webview using [textview ](https://developer.android.com/reference/android/widget/TextView), but it would be without images.

And I suppose your freezings are not concerned with webview

**Comment by ThomasLeigh** [comment]
@yanus171 

> I can try to make a simple text mode without webview using textview , but it would be without images.

It could be fantastic, **thank You that You are willing to give it a chance**. I find this idea particularly exciting, for a number of reasons. One of them is that I have had a similar freezing/crashing issue long ago, regarding another app (_ColorDict_). It was a dictionary, which rendered words' definitions via _WebView_ . But You were allowed to switch to _TextView_ - which in  My case eliminated all the freezing/crashing completely. I've also heard that many users had this issue in various apps, due to the _WebView_ at the time - because on older devices it couldn't be updated (the _WebView_ itself). Now, maybe it is not the case - but I still have a feeling that I wouldn't be surprised if the _TextView_ would make the whole thing better.

There are other things which fascinated Me in switching into _TextView_ - for example to be able to determine the true line-height, and all the  rest benefits which one can derive out of the pure text.
