### ISSUE TITLE
Clock and reading progress bar customization.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#106]
I'd love to be able to customize those elements a little bit - I mean their size and colors. I dreeeeeaaaaam about ittttt :) !!!! Really, kidding aside, the progress bar while reading is ### a great feature - a great one which I greatly regret not to use because it's too small for My vision :( .

**Comment by yanus171** [comment]
May be there should be one setting of the progress and  hyperlink color?

**Comment by ThomasLeigh** [comment]
I think it would be better to be able to set separate colors if one desire so.

**Comment by yanus171** [comment]
Try it https://github.com/yanus171/Flym/releases/tag/v0.7.53

**Comment by ThomasLeigh** [comment]
Great, thank You - now the only thing is the color, and that's it, it's great :) I'm also especially happy that the clock could be turned off.

**Comment by Spleeeno** [comment]
I would second the hyperlink color setting - that would be great.

**Comment by yanus171** [comment]
So we need a color dialog...

**Comment by yanus171** [comment]
See https://github.com/yanus171/Flym/releases/tag/v0.8.2

**Comment by ThomasLeigh** [comment]
Could You add the ability to put the progress bar on the top?

**Comment by yanus171** [comment]
And so clock?

**Comment by ThomasLeigh** [comment]
If it is not too much of a hassle, the clock could have a separate position and color settings.

**Comment by SIRSteiner** [comment]
Is there enought customization for clock and progress bar? If yes, please close this issue. Thank you
