### ISSUE TITLE
Dark share action menu.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#107]
When I tap _"share"_ icon, it shows a bunch of icons on the white background. I noticed that in some other apps similar action opens a different menu: not filled with rows of icons, but a vertical menu (icon & text, then - below it - another icon & text, and so on). If it would help, I can provide screenshots.

The thing is I much prefer dark colors (due to My vision), so I use them everywhere I can. The menu which _Handy_ currently uses for share actions is an icon group placed on the white background by default, but the other one I've mentioned above - has dark background. Would it be possible to switch to that dark-themed share action menu?

**Comment by yanus171** [comment]
Give me a screenshot please

**Comment by ThomasLeigh** [comment]
Here You are. Those screenshots aren't cover the whole list of apps because it's scrollable. The other screenshots is from the Solid Explorer app.

https://drive.google.com/open?id=1sR2sGhFbKmE6gK9awnmg7024OL5qwWXu

https://drive.google.com/open?id=1B79MjjPF8R4jtud1Mi4iuxrjPmMELJKw
