### ISSUE TITLE
Invisible notification.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#109]
This case I stumbled upon so time ago, I don't know how to make it happen again. But maybe it will come in handy.

The thing is about an invisible notification, i.e. it seems like it has no text or maybe its text is invisible (I mean the expanded view of it). It looks like this:

https://drive.google.com/file/d/1EZeOyTdHBzis55kXCj4pLxyp_z-5SQEQ/view?usp=sharing

On this video You can see how all the rest Handy notifications can be expanded, showing additional text - but not this one.

**Comment by yanus171** [comment]
Did it happen in the latest release (52) or earlier?

**Comment by ThomasLeigh** [comment]
Sorry I miss this question. It happened much earlier. ...checking... February 27, 2019.

**Comment by mrfuggy** [comment]
I caught this error too. A empty notification appears when the update process begins. Upon completion, the notification changes to "Feeds. N new entries".

**Comment by SIRSteiner** [comment]
I can confirm it also.

@yanus171 In the emulator the empty notification doesn't appear if I change in StatusText.java in line 189/190:

From: 
    if ( PrefUtils.getBoolean( PrefUtils.IS_REFRESHING, false ) &&
    ( ( new Date() ).getTime() - mLastNotificationUpdateTime  > 1000 ) ) {

To: 
    if ( PrefUtils.getBoolean( PrefUtils.IS_REFRESHING, false ) &&
    ( ( new Date() ).getTime() - mLastNotificationUpdateTime  > 100 ) ) {

I don't know exactly if it also affects on other things. Therefore I did not a pull request.
