### ISSUE TITLE
Be lazy on fetching item

### ISSUE THREAD

**Issue by Ryuno-Ki** [yanus171/Handy-News-Reader#115]
Hi,
first thanks of all for making Handy News Reader a thing!

I'm a feed junkie, so I have a couple 100s of feeds in my OPML.
Therefore I configured HNR to purge items older than one week (to save some space etc).

I noticed, that HNR is currently running the whole process (fetching, saving, mobilizing, image loading) before purging old items.

Would it be possible to skip some steps after the initial content was loaded (and found to be older than one week)?

**Comment by yanus171** [comment]
But I thought that HNR excludes from fetching and loading full text is 
items. Even if Delete old operation executes after that.

**Comment by Ryuno-Ki** [comment]
I have read the first sentence three times but didn't understand it.
Yeah, I normally tick the checkbox to load the full text (because I want to be able to read everything offline).

**Comment by yanus171** [comment]
Sorry, I missed some words :)
HNR excludes old articles from fetching and loading full text. Even if Delete old operation executes after that.
The one exclusion is the first fetching after feed creation. In such a case old setting are  ignored and ALL feed articles are loaded

**Comment by Ryuno-Ki** [comment]
Okay, let's take the easy case then (one feed in case of all at once).

1. Trigger a refresh on a single feed.
2. Observe that HNR is fetching the latest articles (say, the last 25)
3. Observe that HNR is then mobilizing all articles
4. Observe that HNR is then loading all images of all articles.
5. Observe that HNR is then purging all old articles and images (thereby wiping 2-4 from above if those happen to be too old).

My suggestion would be to do it like this instead:

1. Trigger a refresh on a single feed.
2. Observe that HNR is fetching the latest articles (say, the last 25)
3.a FOR article in articles DO:
  * IF article is older then set timeframe (seven days, in my case) THEN purging old article and images
  * IF article is newer THEN continue
4. Observe that HNR is then mobilizing for all remaining articles
5. Observe that HNR is then loading all images of for all remaining articles.
6. Observe that HNR is then purging all old articles and images (thereby wiping 2-4 from above if those happen to be too old).

I expect the process to be sped up this way (but can't tell, whether it is feasible).

**Comment by yanus171** [comment]
So your suggestion is to filter downloading articles full text and images 
to exclude old ones.

But in much part of the cases these old full texts and images were 
downloaded in past, where they were not old yet. So your propose don't 
reduce the refresh time

**Comment by Ryuno-Ki** [comment]
Maybe an example helps …
Keep an eye on what HNR is doing with this feed: https://www.toptal.com/designers/blog.rss
Keep in mind, that I want it to drop everything older than seven days.
Right now, HNR is processing _everything_ just to throw away most of it afterwards.

**Comment by yanus171** [comment]
see https://github.com/yanus171/Flym/releases/tag/v0.8.1
But not the first time feed is refreshed

**Comment by Ryuno-Ki** [comment]
Need to wait for F-Droid build.

**Comment by yanus171** [comment]
And what?

**Comment by Ryuno-Ki** [comment]
Currently, F-Droid lists the (broken) v0.8.2.
So I'm currently stuck with an unusable HNR.
I haven't forgot about this issue, though.

**Comment by yanus171** [comment]
Why can't you uninstall the existing version and try the newest? Create backup (opml) before uninstall and restore it after install

**Comment by Ryuno-Ki** [comment]
Because I don't want to install from GitHub, but [from F-Droid](https://f-droid.org/packages/ru.yanus171.feedexfork/).

**Comment by yanus171** [comment]
You could return to f Droid as soon as you will check the issue

**Comment by Ryuno-Ki** [comment]
Okay, so the new version arrived.
From my observation I can't see a difference in this regard, though.

That is, it seems to behave like before (as tested with adding a new blog).

**Comment by Ryuno-Ki** [comment]
Stress tested it this morning with updates and could see the effect 📣
