### ISSUE TITLE
Brightness adjustment turned off by default. 

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#116]
I recommend to turn it on, because this is such a great feature. I only wonder what will work most often: this feature with or without a display overlay (in My case I need the latter to be enabled) - because I would also recommend to enable an option which works most often.

**Comment by yanus171** [comment]
I have many questions about why the article text became suddenly dark while article list remains with normal brightness.

**Comment by ThomasLeigh** [comment]
Oh, indeed. I haven't noticed that. Could it be fixed (I mean, could the brightness change cover everything, not only full article text)?

**Comment by yanus171** [comment]
I mean that users often don't know air that feature, occasionally reduce the brightness and don't know how to restore the brightness

**Comment by ThomasLeigh** [comment]
Ohhh.... can't help to that :( But this thing intrigues Me: is it possible to include article lists in brightness' adjustment?

**Comment by SIRSteiner** [comment]
I also think it would be better to turn off brightness adjustment by default. Everyone who looks at the settings should find this nice feature.

**Comment by yanus171** [comment]
Yes, I am going to include it.

**Comment by yanus171** [comment]
In new release https://github.com/yanus171/Flym/releases/tag/v0.8.0 the brightness is adjusted on every app screen

**Comment by ThomasLeigh** [comment]
Great, thank You :) !

**Comment by yanus171** [comment]
Did you try to use it without Display overlay checkbox?

**Comment by ThomasLeigh** [comment]
No. Still buggy? I'll check now.

**Comment by ThomasLeigh** [comment]
Nothing happens - without _Display Overlay_ it doesn't work for Me. But with no bugs, nothing is inappropriately darkened, even if the brightness level is decreased and the app re-launched.

**Comment by yanus171** [comment]
Is brightness hint (brightness 56% for example) shown when you slide the screen without overlay mode ?

**Comment by SIRSteiner** [comment]
Here both options are working. The only difference: without overlay 0% is not black but who needs it...

**Comment by ThomasLeigh** [comment]
_"Is brightness hint (brightness 56% for example) shown when you slide the screen without overlay mode ?"_

Yes. BTW, this is a great idea, a nice detail :) Tangibly appreciated :) Alexey, if You'd be a girl... ohh :) ;)
