### ISSUE TITLE
opml is not impoted

### ISSUE THREAD

**Issue by rimugu** [yanus171/Handy-News-Reader#120]
The following was generated by flym and it does not import into handy. No error message, just does not import.
<?xml version="1.0" encoding="utf-8"?>
<opml version="2.0">
  <head>
    <dateCreated>Mon, 08 Apr 2019 18:47:55 GMT</dateCreated>
    <docs />
  </head>
  <body>
    <outline type="rss" title="Bikepacking">
      <outline type="rss" title="Con Alforjas" xmlUrl="http://conalforjas.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="Tom’s Bike Trip" xmlUrl="http://tomsbiketrip.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="ADN Ciclista" xmlUrl="http://www.adnciclista.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="BIKEPACKING.com" xmlUrl="http://www.bikepacking.com/rss" retrieveFullText="true" />
      <outline type="rss" title="Gran Sendero de la División Continental" xmlUrl="https://gransenderoblog.wordpress.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="Bear Bones Bikepacking" xmlUrl="https://bearbonesbikepacking.blogspot.com/feeds/posts/default" retrieveFullText="true" />
      <outline type="rss" title="BikePacking.US – Bicycle Touring" xmlUrl="http://bikepacking.us/feed/" retrieveFullText="true" />
      <outline type="rss" title="Bikepacking.net" xmlUrl="http://www.bikepacking.net/feed/" retrieveFullText="true" />
      <outline type="rss" title="Adventure Cycling Blog" xmlUrl="https://www.adventurecycling.org/tasks/feed/index.cfm?siteid=default&amp;contentID=2A66AE85-77CB-407F-B3FCD352EC6F64B8&amp;categoryID=50AD893E-0357-48BF-951DDFB9D8F5C407" retrieveFullText="true" />
    </outline>
    <outline type="rss" title="Schlock Mercenary" xmlUrl="http://www.schlockmercenary.com/rss/" />
    <outline type="rss" title="Thomas More Society" xmlUrl="https://www.thomasmoresociety.org/feed/" retrieveFullText="true" />
    <outline type="rss" title="RunMX" xmlUrl="http://www.runmx.com/feed/" retrieveFullText="true" />
    <outline type="rss" title="Runfitners" xmlUrl="http://runfitners.com/feed/" retrieveFullText="true" />
    <outline type="rss" title="xkcd.com" xmlUrl="https://xkcd.com/atom.xml" retrieveFullText="true" />
    <outline type="rss" title="Librería &quot;Crisol&quot;" xmlUrl="https://libreriacrisol.blogspot.com/feeds/posts/default" retrieveFullText="true" />
  </body>
</opml>

**Comment by rimugu** [comment]
Tested on 0.7.52 fro f-droid.org

**Comment by rimugu** [comment]
<?xml version="1.0" encoding="utf-8"?>
<opml version="2.0">
  <head>
    <dateCreated>Mon, 08 Apr 2019 18:47:55 GMT</dateCreated>
    <docs />
  </head>
  <body>
    <outline type="rss" title="Bikepacking">
      <outline type="rss" title="Con Alforjas" xmlUrl="http://conalforjas.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="Tom’s Bike Trip" xmlUrl="http://tomsbiketrip.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="ADN Ciclista" xmlUrl="http://www.adnciclista.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="BIKEPACKING.com" xmlUrl="http://www.bikepacking.com/rss" retrieveFullText="true" />
      <outline type="rss" title="Gran Sendero de la División Continental" xmlUrl="https://gransenderoblog.wordpress.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="Bear Bones Bikepacking" xmlUrl="https://bearbonesbikepacking.blogspot.com/feeds/posts/default" retrieveFullText="true" />
      <outline type="rss" title="BikePacking.US – Bicycle Touring" xmlUrl="http://bikepacking.us/feed/" retrieveFullText="true" />
      <outline type="rss" title="Bikepacking.net" xmlUrl="http://www.bikepacking.net/feed/" retrieveFullText="true" />
      <outline type="rss" title="Adventure Cycling Blog" xmlUrl="https://www.adventurecycling.org/tasks/feed/index.cfm?siteid=default&amp;contentID=2A66AE85-77CB-407F-B3FCD352EC6F64B8&amp;categoryID=50AD893E-0357-48BF-951DDFB9D8F5C407" retrieveFullText="true" />
    </outline>
    <outline type="rss" title="Schlock Mercenary" xmlUrl="http://www.schlockmercenary.com/rss/" />
    <outline type="rss" title="Thomas More Society" xmlUrl="https://www.thomasmoresociety.org/feed/" retrieveFullText="true" />
    <outline type="rss" title="RunMX" xmlUrl="http://www.runmx.com/feed/" retrieveFullText="true" />
    <outline type="rss" title="Runfitners" xmlUrl="http://runfitners.com/feed/" retrieveFullText="true" />
    <outline type="rss" title="xkcd.com" xmlUrl="https://xkcd.com/atom.xml" retrieveFullText="true" />
    <outline type="rss" title="Librería &quot;Crisol&quot;" xmlUrl="https://libreriacrisol.blogspot.com/feeds/posts/default" retrieveFullText="true" />
  </body>
</opml>

**Comment by rimugu** [comment]
<?xml version="1.0" encoding="utf-8"?>
<opml version="2.0">
  <head>
    <dateCreated>Mon, 08 Apr 2019 18:47:55 GMT</dateCreated>
    <docs />
  </head>
  <body>
    <outline type="rss" title="Bikepacking">
      <outline type="rss" title="Con Alforjas" xmlUrl="http://conalforjas.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="Tom’s Bike Trip" xmlUrl="http://tomsbiketrip.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="ADN Ciclista" xmlUrl="http://www.adnciclista.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="BIKEPACKING.com" xmlUrl="http://www.bikepacking.com/rss" retrieveFullText="true" />
      <outline type="rss" title="Gran Sendero de la División Continental" xmlUrl="https://gransenderoblog.wordpress.com/feed/" retrieveFullText="true" />
      <outline type="rss" title="Bear Bones Bikepacking" xmlUrl="https://bearbonesbikepacking.blogspot.com/feeds/posts/default" retrieveFullText="true" />
      <outline type="rss" title="BikePacking.US – Bicycle Touring" xmlUrl="http://bikepacking.us/feed/" retrieveFullText="true" />
      <outline type="rss" title="Bikepacking.net" xmlUrl="http://www.bikepacking.net/feed/" retrieveFullText="true" />
      <outline type="rss" title="Adventure Cycling Blog" xmlUrl="https://www.adventurecycling.org/tasks/feed/index.cfm?siteid=default&amp;contentID=2A66AE85-77CB-407F-B3FCD352EC6F64B8&amp;categoryID=50AD893E-0357-48BF-951DDFB9D8F5C407" retrieveFullText="true" />
    </outline>
    <outline type="rss" title="Schlock Mercenary" xmlUrl="http://www.schlockmercenary.com/rss/" />
    <outline type="rss" title="Thomas More Society" xmlUrl="https://www.thomasmoresociety.org/feed/" retrieveFullText="true" />
    <outline type="rss" title="RunMX" xmlUrl="http://www.runmx.com/feed/" retrieveFullText="true" />
    <outline type="rss" title="Runfitners" xmlUrl="http://runfitners.com/feed/" retrieveFullText="true" />
    <outline type="rss" title="xkcd.com" xmlUrl="https://xkcd.com/atom.xml" retrieveFullText="true" />
    <outline type="rss" title="Librería &quot;Crisol&quot;" xmlUrl="https://libreriacrisol.blogspot.com/feeds/posts/default" retrieveFullText="true" />
  </body>
</opml>

**Comment by rimugu** [comment]
xml version="1.0" encoding="utf-8"
opml version="2.0"
  head
    dateCreatedMon, 08 Apr 2019 18:47:55 GMT/dateCreated
    docs /
  /head
  body
    outline type="rss" title="Bikepacking"
      outline type="rss" title="Con Alforjas" xmlUrl="http://conalforjas.com/feed/" retrieveFullText="true" /
      outline type="rss" title="Tom’s Bike Trip" xmlUrl="http://tomsbiketrip.com/feed/" retrieveFullText="true" /
      outline type="rss" title="ADN Ciclista" xmlUrl="http://www.adnciclista.com/feed/" retrieveFullText="true" /
      outline type="rss" title="BIKEPACKING.com" xmlUrl="http://www.bikepacking.com/rss" retrieveFullText="true" /
      outline type="rss" title="Gran Sendero de la División Continental" xmlUrl="https://gransenderoblog.wordpress.com/feed/" retrieveFullText="true" /
      outline type="rss" title="Bear Bones Bikepacking" xmlUrl="https://bearbonesbikepacking.blogspot.com/feeds/posts/default" retrieveFullText="true" /
      outline type="rss" title="BikePacking.US – Bicycle Touring" xmlUrl="http://bikepacking.us/feed/" retrieveFullText="true" /
      outline type="rss" title="Bikepacking.net" xmlUrl="http://www.bikepacking.net/feed/" retrieveFullText="true" /
      outline type="rss" title="Adventure Cycling Blog" xmlUrl="https://www.adventurecycling.org/tasks/feed/index.cfmsiteid=default&amp;contentID=2A66AE85-77CB-407F-B3FCD352EC6F64B8&amp;categoryID=50AD893E-0357-48BF-951DDFB9D8F5C407" retrieveFullText="true" /
    /outline
    outline type="rss" title="Schlock Mercenary" xmlUrl="http://www.schlockmercenary.com/rss/" /
    outline type="rss" title="Thomas More Society" xmlUrl="https://www.thomasmoresociety.org/feed/" retrieveFullText="true" /
    outline type="rss" title="RunMX" xmlUrl="http://www.runmx.com/feed/" retrieveFullText="true" /
    outline type="rss" title="Runfitners" xmlUrl="http://runfitners.com/feed/" retrieveFullText="true" /
    outline type="rss" title="xkcd.com" xmlUrl="https://xkcd.com/atom.xml" retrieveFullText="true" /
    outline type="rss" title="Librería &quot;Crisol&quot;" xmlUrl="https://libreriacrisol.blogspot.com/feeds/posts/default" retrieveFullText="true" /
  /body
/opml
(xml greate than and lower than tags removed)

**Comment by rimugu** [comment]
[?xml version="1.0" encoding="utf-8"?]
[opml version="2.0"]
  [head]
    [dateCreated]Mon, 08 Apr 2019 18:47:55 GMT[/dateCreated]
    [docs /]
  [/head]
  [body]
    [outline type="rss" title="Bikepacking"]
      [outline type="rss" title="Con Alforjas" xmlUrl="http://conalforjas.com/feed/" retrieveFullText="true" /]
      [outline type="rss" title="Tom’s Bike Trip" xmlUrl="http://tomsbiketrip.com/feed/" retrieveFullText="true" /]
      [outline type="rss" title="ADN Ciclista" xmlUrl="http://www.adnciclista.com/feed/" retrieveFullText="true" /]
      [outline type="rss" title="BIKEPACKING.com" xmlUrl="http://www.bikepacking.com/rss" retrieveFullText="true" /]
      [outline type="rss" title="Gran Sendero de la División Continental" xmlUrl="https://gransenderoblog.wordpress.com/feed/" retrieveFullText="true" /]
      [outline type="rss" title="Bear Bones Bikepacking" xmlUrl="https://bearbonesbikepacking.blogspot.com/feeds/posts/default" retrieveFullText="true" /]
      [outline type="rss" title="BikePacking.US – Bicycle Touring" xmlUrl="http://bikepacking.us/feed/" retrieveFullText="true" /]
      [outline type="rss" title="Bikepacking.net" xmlUrl="http://www.bikepacking.net/feed/" retrieveFullText="true" /]
      [outline type="rss" title="Adventure Cycling Blog" xmlUrl="https://www.adventurecycling.org/tasks/feed/index.cfm?siteid=default&amp;contentID=2A66AE85-77CB-407F-B3FCD352EC6F64B8&amp;categoryID=50AD893E-0357-48BF-951DDFB9D8F5C407" retrieveFullText="true" /]
    [/outline]
    [outline type="rss" title="Schlock Mercenary" xmlUrl="http://www.schlockmercenary.com/rss/" /]
    [outline type="rss" title="Thomas More Society" xmlUrl="https://www.thomasmoresociety.org/feed/" retrieveFullText="true" /]
    [outline type="rss" title="RunMX" xmlUrl="http://www.runmx.com/feed/" retrieveFullText="true" /]
    [outline type="rss" title="Runfitners" xmlUrl="http://runfitners.com/feed/" retrieveFullText="true" /]
    [outline type="rss" title="xkcd.com" xmlUrl="https://xkcd.com/atom.xml" retrieveFullText="true" /]
    [outline type="rss" title="Librería &quot;Crisol&quot;" xmlUrl="https://libreriacrisol.blogspot.com/feeds/posts/default" retrieveFullText="true" /]
  [/body]
[/opml]
(square brakets for posting on github)

**Comment by yanus171** [comment]
You'd better attach an opml file, so I could test it

**Comment by SIRSteiner** [comment]
Same here, there is no import at all.
Logcat: java.io.FileNotFoundException: /document/primary:feedex/... (No such file or directory)

**Comment by SIRSteiner** [comment]
I tested some older versions. Since v0.7.39 it is not possible to import any opml file

**Comment by yanus171** [comment]
Try to check /uncheck settings additional - standard file manager, and import again

**Comment by SIRSteiner** [comment]
@yanus171 Thank you, unchecking this option import works. But shouldn't it also work if checked?

**Comment by SIRSteiner** [comment]
@rimugu, please look at
1. "Adventure Cycling Blog" and its url. Is this a rss url?
2. title="Librería "Crisol"" (two quotation marks)

Without these two items (and without using standard file manager) import of your opml works.

**Comment by rimugu** [comment]
The adventure cycling blog url is not current, but even without it, it won't import. The one with double quotations may be the copy/pasting. The word "Crisol" in the title has quotations around it. In the original opml is & quot ; (added spaces before and after quot to prevent it from rendering) but even without it still no import.

**Comment by rimugu** [comment]
The last comment is with standard file manager, directly from feedex directory and not using standard file manager it imported with double quotations and deprecated url

**Comment by SIRSteiner** [comment]
@yanus171 Can we close this issue?
