### ISSUE TITLE
Error messages still visible.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#122]
Although progress technical information are disabled - these error messages are still visible on top of the article text or article list:

https://drive.google.com/file/d/1oP-6h4FZjEn3dB3XC1Ex28RS1PP9yeqc/view?usp=drivesdk

**Comment by yanus171** [comment]
The error message is very important and I think it should be shown 
regardless of settings

**Comment by ThomasLeigh** [comment]
The thing is it disturbs the whole reading experience. I can't treat those error messages so seriously because most of the time articles are obtained without problems - only sometimes some articles haven't been loaded properly (there were some strange errors), while other (out of the same feed!) are right. I find it strange because I use proper feed RSS addresses, which - as I said - are working most of the time. Only sometimes something is not right - but most of the time it is ok, so I don't remove the feed indicated by the error message. The problem comes down to the fact that this messages seriously disturb reading.

**Comment by Ryuno-Ki** [comment]
Same.
Fun thing is, even if opening the article shows that error message (unresolved hostname), I can read the artucle after toggling to full text (the button).

For me, I can see the error message most of the time (but my OPML is quite big...)

**Comment by yanus171** [comment]
May be this error is from another article?
Why an OPML?

**Comment by ThomasLeigh** [comment]
What do You think to arrange error messages this way:

if an error occurs, instead of showing a red error text on top - let an additional red explanation mark icon be displayed somewhere next to the share icon on the top right. If tapped, this icon would provide an actual error message served as a pop-up window.

**Comment by Ryuno-Ki** [comment]
Or do it like Flym and display the error message in the list of feeds. This way the context is close …

**Comment by yanus171** [comment]
see https://github.com/yanus171/Flym/releases/tag/v0.8.1
