### ISSUE TITLE
Filter: 'Accept' and 'Reject' don't work together

### ISSUE THREAD

**Issue by bcm314** [yanus171/Handy-News-Reader#127]
'Accept' overrides 'Reject' is not working as it should be.

When you have at least ONE rule of kind 'Accept', all 'Reject' rules are completely ignored: as a result you get only articles fitting the 'Accept' rules.

Maybe better say: 'only fulfilled Accept' overrides 'Reject'

Make an example, how it should work:
assume, there is a feed with a lot of news - you don't like to see "sport" articles, but maybe there is one sport you like to see (maybe football).
so you create two rules:
- reject "sport"
- accept "football" (for Info: overrides reject "sport")

In the current version, you'll see only articles with "football", not any other you like to see.
The correct procedure should be the following:
for each article, check if it fulfill any accept-rule
a) if so, add this article to the list: (fulfilled)'Accept' overrides 'Reject', 'Reject' not needed to check, in such cases
b) BUT (!!!) if not, check if it fulfill any reject-rule and if not any, add also this article.

(Or vice versa: first check all reject-rules and all articles filtered out check if any accept-rule override it)

**Comment by yanus171** [comment]
Now Accept means accept only, so where will be loaded only articles 
matching any of accept rules. May be there is a need for more information 
about it in filter dialog. And this is a common case for a filter.

In your case the meaning of Accept rule changes significally. It's look 
like another filter mode. Do we really need it?

Maybe just block reject rule if accept is set?
