### ISSUE TITLE
"all articles" list not updated

### ISSUE THREAD

**Issue by bcm314** [yanus171/Handy-News-Reader#129]
First select "All articles".
When you make a "refresh", this list isn't updated.

**Comment by yanus171** [comment]
I can't reproduce it. I tried it, update stated, notification was shown.

**Comment by bcm314** [comment]
Even not an umportant thing (I believe so) ...

Indeed, there is something more I've investigated:
this behavior is only, if you've turned off "Load full article".

About the screenshots:
1 Teststart, always deleted all articles from Tagesschau
2 Test 1 - options
3 Test 1 - result
Left side shows the number of new articles, but nothing changed on the right side.
Pushing refresh again doesn't change anything
4 Test 2 - options
5 Test 2 - result
This should be the result

![1 Teststart](https://user-images.githubusercontent.com/30076623/56910747-97307d00-6aab-11e9-9926-bafd8ce21c7a.png)
![2 Test 1 - options](https://user-images.githubusercontent.com/30076623/56910754-9a2b6d80-6aab-11e9-9ba3-1140d6146281.png)
![3 Test 1 - result](https://user-images.githubusercontent.com/30076623/56910758-9d265e00-6aab-11e9-9ece-9ddfaa500e67.png)
![4 Test 2 - options](https://user-images.githubusercontent.com/30076623/56910763-9ef02180-6aab-11e9-8ae6-52eccee0d870.png)
![5 Test 2 - result](https://user-images.githubusercontent.com/30076623/56910768-a1527b80-6aab-11e9-94ff-d1a024d62aa5.png)

**Comment by yanus171** [comment]
Try to uncheck refresh only selected setting

**Comment by SIRSteiner** [comment]
Does this problem still exist? If not, please close, because I think that due to the large number of issues it is difficult for @yanus171 to work through everything.
