### ISSUE TITLE
mix "All articles" and "Unread" together

### ISSUE THREAD

**Issue by bcm314** [yanus171/Handy-News-Reader#130]
Maybe on (small) phones, when you have some lists, it would be good to save space.

Why not eliminate the "Unread" category?

You can use the "All articles" and there should be the same checkbox at top, where you can switch if you like to see only new articles or also read ones.

**Comment by yanus171** [comment]
Yes, It makes sense, but unread checkbox is not so intuitive. Users ask me why their read articles disappear, and I advice them to uncheck strange checkbox in the top action bar.

May be we need to make this checkbox more descriptive... But how?

**Comment by bcm314** [comment]
> May be we need to make this checkbox more descriptive... But how?

Indeed, a checkbox without any text could be obscure.
You can make a long-tap to get a toolip, but I guess I'm (almost) the only one who did it.

Here one idea, but maybe it will entail other problems:
instead a checkbox use two images, an 'open letter' and a 'closed letter' similar email programs are using

But do people than better know about it? Maybe they guess thats only an information about unread articles?
At least at the position between the 'refresh'- and 'menu'-button, people could think about tapping on it and than the changed image would be more understandable than a checkbox.

**Comment by yanus171** [comment]
It's not the checkbox - Here are is two images already. Show me these 
open/close images please

**Comment by bcm314** [comment]
Yes, indeed two images (guess rounded_checbox_white.png and rounded_empty_white_.png), but they are displaying nothing else then a checkbox (selected and unselected).
(Also on https://github.com/yanus171/Flym/issues/131 you can see screenshots of the checkbox at the top.)

I thought, replace this two images with pictures of something like new-/nonew-mail could be more understandable.
Or did I missunderstood something?

But while trying to find good one, I'm no longer sure, if 'new mail'-icon will give understanding of 'only new articles'.

**Comment by yanus171** [comment]
Give a picture with these new mail icons

**Comment by bcm314** [comment]
Here they are:
https://yandex.com/images/search?text=mail%20read%20unread&wp=off&type=lineart

But as said, I'm not sure if it will be better.
So for example, a closed envelope for 'unopened articles' = unread articles only.
Tapping to show an opened envelope for also old, already read articles.
