### ISSUE TITLE
Please improve settings menu

### ISSUE THREAD

**Issue by SIRSteiner** [yanus171/Handy-News-Reader#133]
Maybe it should be better to structure settings in submenus because i. e. if you want to change language setting you have scroll down at the end of all settings/options.
Also "Tap Zones preview" should be after "Tap Zones are visible" and preview only active if visible (in my opinion)

**Comment by bcm314** [comment]
Oh yes, very good idea - this is (or exactly 'was') also on my ToPost-list.

**Comment by yanus171** [comment]
May be to move Language at the top?

**Comment by bcm314** [comment]
Language seems not important to me.

It's a very long list, so "structure settings in submenus" would be really great.
On the first page show only the (currently) gray lines and by taping on them switch to the submenu.

**Comment by yanus171** [comment]
By the way you can try to make it by yourself via a pull request. You should edit the file https://github.com/yanus171/Flym/blob/master/FlymFork/src/main/res/xml/general_preferences.xml and may be add some strings if needed to https://github.com/yanus171/Flym/blob/master/FlymFork/src/main/res/values/strings.xml

**Comment by bcm314** [comment]
Without testing, pulling wouldn't be a good idea and (currently) I don't like to set-up a gradle environment.
I still have a good-old Eclipse environment ...

Maybe SIRSteiner will ...

**Comment by SIRSteiner** [comment]
Okay, I will look at it. BTW "language" setting is only an example.

**Comment by yanus171** [comment]
It is common xml file. You can edit it via text editor. You can open it in browser to check that syntax is correct

**Comment by SIRSteiner** [comment]
Please look at my pull request https://github.com/yanus171/Flym/pull/138
Thank you

**Comment by yanus171** [comment]
Thank you. Its much more logical now.

**Comment by yanus171** [comment]
But there is a problem now that in sub categories there is no brightness slider and its changes there. I will try to inherit PreferenceScreen...

**Comment by yanus171** [comment]
see https://github.com/yanus171/Flym/releases/tag/v0.8.1

**Comment by yanus171** [comment]
Can we close it?

**Comment by SIRSteiner** [comment]
Yes, I think so....
