### ISSUE TITLE
Feed setting "Custom refresh time"

### ISSUE THREAD

**Issue by bcm314** [yanus171/Handy-News-Reader#135]
You'll have different feeds, maybe one about news, and other about discussion, special offers, ...

News should be refreshed very often while other feeds would be enough to check 1 each day.

So "refresh time" should be defined for each thread.

**Comment by yanus171** [comment]
This feature is usefull if we want to define very frequent (once a minute) refresh for some important feeds with "hot" information (like soccer match log). While the rest of the feeds will be refreshed rarely (once a day) But what about battery drain?

**Comment by bcm314** [comment]
If someone is afraid of battery drain, he/she shouldn't use it.
BTW, belonging the other issue, you seem to have set "Load full article" - I guess this is also more battery drain.
Some using the phone for listening internet radio or only local mp3 and I guess this will also eat more battery.

But take care: this feature does NOT increase battery drain, it will DECREASE ist.
(currently) you have to set the general settings to the smallest value, so if you like to see news often (maybe each minute, or only each 5 or even 15 minutes).
this is like you want and what you have to do
But in this case you'll waste battery drain for all the other feeds you won't any update so often.

Or you can decide to read news also only 1 time each day ...

**Comment by yanus171** [comment]
OK, you was convincing :)
