### ISSUE TITLE
Custom selection

### ISSUE THREAD

**Issue by Dreamer-4pda** [yanus171/Handy-News-Reader#139]
Please, add ability to select several articles in list.
Ability to select from some to some article is better solution. 
Why it needs?
Example: I accidentally noted all the articles as readed (more than a hundred) and want mark it back to unreaded.

**Comment by yanus171** [comment]
Didn't you have time to press undo button?

**Comment by Dreamer-4pda** [comment]
> Didn't you have time to press undo button?

Yep I miss that moment 😅

Another situation:
I want delete some readed and keep other articles, but I don't want add it to favorites.

**Comment by yanus171** [comment]
There was a user request to add a menu item to delete all showing unstarred read articles. I think that feature is more practical. And has no need to implement multi select...

And I don't understand why should we generally delete articles? If article is important, we star it, overwise read our unread it will be delete automatically when it become old

**Comment by Preformer** [comment]
Please also implement this feature in the Read later list.
