### ISSUE TITLE
[Bug] Toggle fullscreen is not working if "Brightness change gesture" is on

### ISSUE THREAD

**Issue by SIRSteiner** [yanus171/Handy-News-Reader#142]
No additional comments necessary...

**Comment by yanus171** [comment]
Yes, but regardless of brightness setting. Seems that brightness slider overlaps the full screen button...

**Comment by SIRSteiner** [comment]
I think so but here toggle fullscreen works if brightness change gesture is off.

**Comment by yanus171** [comment]
see https://github.com/yanus171/Flym/releases/tag/v0.8.1
