### ISSUE TITLE
[Feature request] Switch between items by tapping on the left or right top corner.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#145]
Original message:

> Bequemes und einfaches Wechseln zwischen den Artikeln durch Antippen auf  das linke oder rechte obere Ecke (vorherige beziehungsweise nächste  Artikel), ähnlich wie die unteren Ecken mit Größe verstellbaren Tippzonen.

**Comment by yanus171** [comment]
Translation: Convenient and easy switching between items by tapping on the left or right upper corner (previous or next item), similar to the lower corners with adjustable size tip zones.

**Comment by yanus171** [comment]
Ask him, Why is it not enough to switch between articles by left/right swipe?

**Comment by ThomasLeigh** [comment]
> The left / right wipe consumes a lot of power with e-ink readers.

**Comment by ThomasLeigh** [comment]
I didn't know that _HNR_ may work on e-ink readers, wow... sounds very interesting.

**Comment by yanus171** [comment]
see https://github.com/yanus171/Flym/releases/tag/v0.8.1

**Comment by SIRSteiner** [comment]
I think we can close this issue.
