### ISSUE TITLE
Allowing multiple keyword(s)-lines in Feed Filter rule

### ISSUE THREAD

**Issue by crti** [yanus171/Handy-News-Reader#146]
For convenient management of the Feed Filter rule I would like to propose allowing multiple rules in the keyword(s) input field instead of setting up multiple rules. 
![Feed-Filter-rule](https://user-images.githubusercontent.com/1004113/56847043-a4e0d980-68d6-11e9-87d3-d912a92c9b52.jpg)

So similar then in Settings / Notifications > Global filter... > Rule's text (a rule per line) 
![Global-Notific-filter](https://user-images.githubusercontent.com/1004113/56847051-b924d680-68d6-11e9-9e1b-b44266442caf.jpg)
May I note that "Apply to title or link address" is not clear to me if active when ticked or not. 

Probably with regular expression(s) my wish could be accomplished, but so far I was not able to use them extensively (without using predefined examples) and I think normal users do not know what they are.

**Comment by yanus171** [comment]
For my feeds I rare more than 3-4 filters and its not too hard to add them. But if the feed  filter count is great, then... 

May be someone else will vote for this feature?

**Comment by crti** [comment]
The reason I have a lot more then 3-4 is that I want to read about certain internationally popular topics only from one source/feed and like to exclude it from almost all other (that may include such topics), so that I have to scan trough less.

**Comment by yanus171** [comment]
Global Accept our Reject filter?

**Comment by crti** [comment]
[Global rejecting filter](https://github.com/yanus171/Flym/issues/39)

**Comment by yanus171** [comment]
@seth100 maybe it's better to add Ignore case ☑

**Comment by seth100** [comment]
@yanus171 what do you mean with "adding Ignore Case"?

I need to set a filter for multiple words that would be also case insensitive, e.g. I tried to set multiple filters like the following, for each word:

```
(?i)\test1\b
```

```
(?i)\test2\b
```

...

but it does not match my words even if they exist in the title or content.
So, since multiple keywords-lines is not implemented how can I match something like 20 words without adding a single filter for each word with all possible capital letters (case insensitive)?

Thanks

**Comment by yanus171** [comment]
I will make multiple keywords filter separated by space (in non regex mode)

**Comment by seth100** [comment]
@yanus171 tried that but it still does not work

**Comment by yanus171** [comment]
With introduction of global filter this enchantment is not important
