### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#148]
This one is highly requested because it can bring a lot of aesthetics to the app and user-experience.

**Ability to change fonts** (both in articles and article list - _"Lato Light"_ (I mean its particular variant called _"Light"_ - be careful: it has many variants to choose, and on;y this one looks so great, it has all the beauty of Google _"Roboto"_ font, but is more gentle, subtle... imho just looks better) font especially recommended https://fonts.google.com/specimen/Lato ).

**Comment by SIRSteiner** [comment]
I also can confirm this is an essential feature for all "power-readers".

**Comment by yanus171** [comment]
What about fonts in html? We place attribute Family in tag font. Should font files (*. tft) exist on client side (phone) or they should be known by browser (Webview)?

**Comment by ThomasLeigh** [comment]
>Should font files (*. tft) exist on client side (phone)

I personally like this idea because it gives much possibilities and freedom.

If You, however, would include some fonts within the app itself (so that the user don't need to put a font file on the phone memory) - more users will be able to change the font because not everyone can do it by themselves (finding a font file somewhere and putting it on the phone memory), but (almost?) everyone can choose a font out of the font list somewhere within the app settings.

So the ideal choice would be both: give the ability to choose a font from the list of several additional fonts within the app settings - and in the same time allow to use any font file placed on the phone memory.

**Comment by yanus171** [comment]
I mean technical aspect. Where these files should exists to display html properly?

**Comment by ThomasLeigh** [comment]
When I'd like to use those fonts on a website - I put a code obtained from Google Fonts (Google hosts a lot of them). I can help with those codes if You like. But I saw apps which could use fonts which have been already placed on the phone's memory, directly or within some folder. Again, I think the best solution is to provide the both.

**Comment by b16r05** [comment]
Since Android is from Google... aren't these font files included in the OS? Windows has Consolas, which I like, and, Inconsolata is an alternative for *nix users. I like Source Code Pro from Google: https://fonts.google.com/specimen/Source+Code+Pro

**Comment by b16r05** [comment]
Default font is not bad, what is it?

**Comment by yanus171** [comment]
So there should be some mechanism to use embegged fonts and to install custom ones

**Comment by b16r05** [comment]
Mechanism, yes. I will leave checking the technical details to you : )

Resources: 

Quick Tip: Working With Custom Fonts in Android O: https://code.tutsplus.com/tutorials/quick-tip-working-with-custom-fonts-in-android-o--cms-28625

Custom Fonts on Android with Android Support Library: https://segunfamisa.com/posts/custom-fonts-with-android-support-library

How to use custom fonts in Android apps (and not get fat): https://blog.goyello.com/2014/08/01/how-to-use-custom-fonts-in-android-apps-and-not-get-fat-3/

**Comment by afmbsr** [comment]
It would be great and fun to read the articles in your favorite font..I hope this feature is included soon, if possible

**Comment by ThomasLeigh** [comment]
**Also looking forward to this :) !**

**Comment by ThomasLeigh** [comment]
Introduced with ver. 0.15.1.

**Comment by afmbsr** [comment]
Yes, I'm using this version, I am very happy with that, thank's
