### ISSUE TITLE
[Feature request] Show author of article

### ISSUE THREAD

**Issue by Ryuno-Ki** [yanus171/Handy-News-Reader#150]
Hi,

would there be a possibility to show the author of an article in the feed list?

My motivation: I'm reading Boing Boing mainly because Cory Doctorov is publishing there.
Vut he's not the only one.

In my former feed reader (simpleRSS) I could see, which articles were by him.

**Comment by yanus171** [comment]
Okay, I will.

**Comment by yanus171** [comment]
see https://github.com/yanus171/Flym/releases/tag/v0.8.1

**Comment by Ryuno-Ki** [comment]
Hi @yanus171,
yesterday I was able to download v0.8.2 from F-Droid. I could see the author names.
However, that version has a bug which make the app crash on start. But I know, you already fixed it so I'll have to wait some more days.

Since this request is fulfilled, I'm closing it.

**Comment by yanus171** [comment]
Ok
