### ISSUE TITLE
Article text sometimes doesn't match the article title.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#155]
I experience this issue for a very long time now, I have the impression that it was always present. It looks exactly like in the title: sometimes full article text doesn't match its title - while if I use _"Open link"_ option in _HNR_, it opens the proper article in an external web-browser. Furthermore, if I use _"share"_ option in this web-browser and choose _"Read now"_ (_HNR_), _Handy_ still displays inappropriate article. I have the impression that it has something to do with the _MySQL_.

An example of such an article:
https://android.com.pl/artykuly/183333-android-q-nowosci-lokalizacja-aktualizacja/

It should begin with 

> "Z dnia na dzień dowiadujemy się"

but in _HNR_ it begins with 

> "Internet to świetne miejsce..."

This issue occurs regardless of any particular feed.

**Comment by Ryuno-Ki** [comment]
Have you looked at the title in RSS feed vs. on the website?

IIRC it was mentioned somewhere here, that HNR parses the website in some cases.

Plus, if an author updates the article („clickbait”? A/B tests), some CMS don't regenerate the feed.

**Comment by ThomasLeigh** [comment]
> Have you looked at the title in RSS feed vs. on the website?

Yes - it was the same, even in the full article text view.


> Plus, if an author updates the article („clickbait”? A/B tests), some CMS don't regenerate the feed.

Yes, but this article still remains appropriate to its title on the website, while within _HNR_ it's only the title correct, with the text of some completely other article.

**Comment by ThomasLeigh** [comment]
I've just stumbled upon a very interesting thing. Here You are [an article](https://android.com.pl/programowanie/182482-poczatki-programowania-java-kotlin/) (its content doesn't matter).

I use _Chrome_ (desktop) and _[Clearly](https://chrome.google.com/webstore/detail/clearly/odfonlkabodgbolnmmkdijkaeggofoop?hl=en-US)_ - an extension to provide a clear reading experience on the desktop.

And now, when You read this article **without _Clearly_**, it begins with: 

> "Witajcie w kolejnym odcinku. W ramach tej serii nie miałem na celu pisania kolejnego kursu"

. When You read the same article **with _Clearly_**, it begins with 

> "Witajcie ponownie. Jak już wiecie, niedawno została wydana wersja testowa najnowszej"

. **Further reading assures You that those are two completely different articles.**

So this is the very same issue which I observe within _HNR_ for a long time. I thought it has something to do with _RSS_ - but now I'm not so sure. Could anyone point out what causes this difference? And, more importantly, could we avoid those issues within _HNR_?

**Comment by Ryuno-Ki** [comment]
I can see two different articles:

> Witajcie w kolejnym odcinku.

referring to „Początki programowania na Androida – Java czy Kotlin?” by Paweł Dedio from 2019-02-02.

> Witajcie ponownie.

referring to „Nowości w Androidzie Q z perspektywy programisty” by Paweł Dedio from 2019-03-30.

(the markup is a mess - but it looks like to be controlled by JavaScript).

**Comment by ThomasLeigh** [comment]
So the problem is that something causes _Handy News Reader_, _Clearly_ and maybe other apps/extensions to display wrong article text. It is confusing because in _HNR_ I see a title of the first article - but the following text is the text of the other article.

You sounds like it is due to the website's author... could we do anything to avoid it in _HNR_?

**Comment by SIRSteiner** [comment]
Does this problem still exist? If not, please close, because I think that due to the large number of issues it is difficult for @yanus171 to work through everything.
