### ISSUE TITLE
Does "export/import OPML" act the same way as "Create auto backup"?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#160]
As in the title.

**Comment by yanus171** [comment]
Yes, except the OPML  file name

**Comment by ThomasLeigh** [comment]
So export .opml file is only about feeds - while backup exports feeds, favorites and app's settings?

**Comment by yanus171** [comment]
No expert opml also writes settings and articles info on file

**Comment by ThomasLeigh** [comment]
So it could be a good idea to remove this option since we have app backup. What do You think?

**Comment by yanus171** [comment]
Export opml saves the file with current date and time while Create audio 
backup not

**Comment by ThomasLeigh** [comment]
What about the auto backup including the current date and time - and then remove "export opml"?

**Comment by yanus171** [comment]
Export opml creates a file includeing date and time which will not be overwriten by next export, while autobackup is rewrtitten every time. If we include current date and time the file name will alays de different and the file will not be overritten and with the time these files will occupy all the remaining SD card free space

**Comment by ThomasLeigh** [comment]
What is the reason for the export opml feature - regarding that we already are able to have a similar feature within auto backup?

**Comment by yanus171** [comment]
I made Create auto backup menu item for testing purposes. I can remove it now.

**Comment by ThomasLeigh** [comment]
No no, please don't remove this menu item - it is much better understandable than "export an .opml file". I would suggest to remove the latter.

**Comment by yanus171** [comment]
May be we can leave menu item Export /Import from opml in Edit feeds screen menu. And also have a Create Backup / Restore from backup menu items in Article list menu,which would do the same functionality.

But Create AUTO backup menu item I want to remove.

**Comment by ThomasLeigh** [comment]
I'm not sure if we're talking on the same thing.

What I find the most important is to have a menu item which can trigger the whole backup process (feeds, app settings, favorites). Would You agree to that? If so, could we call this item _"Backup/Restore"_?

If You, however, want to include _"Restore"_ feature - it should open a window to choose a backup file - or find it automatically, without a need for the user to pointing this file out.

Why do You want to maintain _"Export/Import .opml"_ since we have the same feature within the backup?

**Comment by yanus171** [comment]
This is single (the same) operation, which created the backup file in opml 
format with extention that includes app settings and articles info. But 
this operation has different menu caption in Article list screen and in 
Feed edit screen.
>

**Comment by ThomasLeigh** [comment]
So:
1. Does _"import from an .opml"_ file **restores** everything, not only the feeds list?
2. Do You mind to maintain this feature in both places in the menu - but with the same name (_"Backup/restore"_)?

Ad.2:
If You don't like the idea of maintaining this feature in both places, what about removing it from the article list screen menu - and again, renaming the one existing in the feed edit screen into _"Backup/restore"_?

**Comment by yanus171** [comment]
1. Yes
2. But with different names so users could see two features in app.

I want to maintain it in two places

**Comment by ThomasLeigh** [comment]
>so users could see two features in app

What do You mean by "two features"? 1. Backup and 2. exporting the feeds list?


Do You mind changing the name of _"Create auto backup"_ to _"Backup"_?

Could You split it into the two items (like in case of export/import .opml): in the article list screen menu: _"Backup"_ and _"Restore"_?
