### ISSUE TITLE
Social Network feeding

### ISSUE THREAD

**Issue by RAMAR-RAR** [yanus171/Handy-News-Reader#162]
Ex. 
1.X posted a photo with description on Facebook
2. Flym send a feed with photo with under the text

**Comment by ThomasLeigh** [comment]
Hello  @RAMAR-RAR :)

Ad.1:
Do You mean that Handy News Reader could notify when someone posts a photo on Facebook?

Ad.2:
Could You please describe this one in more details?

**Comment by RAMAR-RAR** [comment]
Ad.1: Yes

Ad.2: 

title: "name of a page/account"

-
date:"yyyy/mm/dd" "hh/mm"
-
• Description of post
• Photos/video
• Links

**Comment by ThomasLeigh** [comment]
@RAMAR-RAR 

Please tell Me if I got it right:

1. You would like _HNR_ to be able to handle _Facebook_?
2. So if this feature would be added, first I should login to _Facebook_ within HNR, and then each time My friend posts anything.... what then? Just notification on the Android notification shade - or the whole post visible in the same manner as a regular article within _HNR_?
3. All posts in one _"Facebook"_ feed, consisting of all Your Friends' posts?

**Comment by RAMAR-RAR** [comment]
1. Yes

2.Without login, I would like works with link of account. Yes, that appear the whole post visible in the same manner as a regular article.

3. Only the accounts that I add with link connected to them

**Comment by yanus171** [comment]
I am not much familiar with Facebook. Can you add such a link with web feed type?

**Comment by yanus171** [comment]
And we need first realize #131

**Comment by RAMAR-RAR** [comment]
I think this can help:
https://developers.facebook.com/search/?q=feed

**Comment by ThomasLeigh** [comment]
@RAMAR-RAR I always get the impression that _Facebook_ often doesn't allow to browse users' profiles/accounts without being logged in first.

**Comment by RAMAR-RAR** [comment]
:/ so neither Instagram, Twitter or others... I suppose

**Comment by ThomasLeigh** [comment]
But if it could be possible to log in via HNR - it could be a game changer, because it could work incredibly faster than Facebook itself, obtaining only key pieces of information:  a photo, a label, a date. Facebook can be obtained and served as a webpage - which is already handled within HNR.

**Comment by ThomasLeigh** [comment]
In fact, I would love to be able to use HNR to be up to date with YouTube, etc.

**Comment by yanus171** [comment]
You should check if these sites lack RSS reeds

**Comment by Ryuno-Ki** [comment]
Hm, not sure, whether you would want to go this way …
Because Facebook, Google etc. shut down APIs in that respect (think XMPP).

**Comment by yanus171** [comment]
For example YouTube channels have rss feeds
