### ISSUE TITLE
Allow to bring forth the sidebar via swipe in full article/full screen mode.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#164]
As in the title. **It will decrease the number of steps required to switch between _favorite/unread/all_ articles** while browsing articles in full screen mode - to one.

**Comment by yanus171** [comment]
Describe it more please

**Comment by ThomasLeigh** [comment]
Now I can make the sidebar visible by swipe from the left edge of the screen to the right. It can't be done while browsing articles in full screen/full text mode - I'd like it to be possible in this case, too.

**Comment by yanus171** [comment]
It will conflict with swipe left right for article switching

**Comment by ThomasLeigh** [comment]
Even if it could react only from the left edge? Article switch could be remapped to work any other way but not from the edge.
