### ISSUE TITLE
Crash while adding widget 4x3

### ISSUE THREAD

**Issue by SIRSteiner** [yanus171/Handy-News-Reader#17]
I sent a feedback. Can you look at?

Smartphone: BQ M5, LineageOS 14.1

**Comment by yanus171** [comment]
Google forced me to enforce security restrictions on the app in Google play which has damaged the widget. May be in the future I will make it work again

**Comment by yanus171** [comment]
Yes android:exported="true" resolves the issue, but I was forced to set it to false (which has broken the appWidget) because of mail from Google play: 
> Your app(s) are using a content provider that contains a SQL Injection vulnerability.
> https://support.google.com/faqs/answer/7668308

Another solution is to using by using strict mode with a projection map, but the app contentProvider should be rewritten in many places.

**Comment by SIRSteiner** [comment]
Because there is no widget this issue isn't an issue anymore. If anyone needs a widget you should add a feature request.
