### ISSUE TITLE
Rename "Favorites" into something more comprehensive.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#170]
I think we could improve wording in this case. Some time ago we've discussed two reasons why we use _"Favorites"_: either for **"read it later"** or **preserving chosen articles** for ever. **The name _"favorites"_ does not fit those two scenarios well** - although it's kind of close to preserving articles (but only kind of), it is far away from rendering _"read it later"_ purpose. I'd like it to be called the way which could render the both. Something which could be **more comprehensive, less abstract**.

I propose _**"the Pocket"**_. One can easily associates it which the place for either preserving articles or just putting them on the back burner to read later.

Then, it could be great to rename _"Mark as starred"_ within _Global filter_ into _"Add to the Pocket"_ - and _"The article was marked as starred"_ into _"The article has been added to the Pocket"_.

I'd love to correct all the phrases alongside this change - if You allow Me to do so.

**Comment by yanus171** [comment]
OK, I agree that favorities is not the best variant. But neither pocket. Some people don't have pockets at all. Try to think about another variant.

**Comment by yanus171** [comment]
May be Fixed, or Persistent or... This variants are also worse that Favorites

**Comment by ThomasLeigh** [comment]
How many people doesn't know what a pocket is?

**Comment by ThomasLeigh** [comment]
I think it would be hard to invent anything better (than the pocket).

**Comment by ThomasLeigh** [comment]
A drawer?

**Comment by ThomasLeigh** [comment]
Or an obscure "Saved" :(

**Comment by Ryuno-Ki** [comment]
[Treasured](https://www.thesaurus.com/browse/favorite)?

**Comment by ThomasLeigh** [comment]
Oh, I like that *.*

**Comment by yanus171** [comment]
I think is should not be so poethetic ... It should be simple and understandable to all ... By the way look at the top of current github page, at word "unstar" (star). This word you can find on quite every web page. The synonim is marked. But it leaves some questions, while star is sufficient. 

But verb and noun star has a different meaning in literature lenguage. But in handy situations star is clear. Just like favorities :)

I suppose this issue has not resolving

**Comment by Ryuno-Ki** [comment]
Keep in mind, that Twitter changed the star to a heart.

Maybe we could ask around / research what different cultures associate with a star?

@yanus171 If it gets too offtopic, close this repo. I hope, a lock won't be necessary...

**Comment by ThomasLeigh** [comment]
I think that _"star"_ is not understandable enough - especially when I think on average users who often don't know what _"RSS"_ is. There are a great many of those who don't know what OS ver. they use. But they use smartphones, but without all the "IT" nomenclature.

Besides, again, it could not be a good idea to follow all the rest. I'd encourage You to involve as much innovative and original ideas as possible - following already existing copy&paste behavior this app won't be much of a difference, won't stand out in the crowd. I'd love to see this app more ambitious.

The point is that a geek should understand what "the pocket" or "treasured" means - but it doesn't work the other way, i.e. a non-techy user often won't get the 'star' idea. Of course this is not a brain surgery, but I am a strong believer in the _"Don't make me think"_ approach, because only this can make Your app usable for many more users, only thanks to that the developer kept in mind their own perspective.

I know that You don't like the idea much. I tell You what will be working better, believe it or not. There is no way to invent something significant, staying in place within the status quo.

**Comment by yanus171** [comment]
@Ryuno-Ki what lock?

**Comment by Ryuno-Ki** [comment]
https://help.github.com/en/articles/locking-conversations

**Comment by SIRSteiner** [comment]
Maybe: archiv or collection?

**Comment by ThomasLeigh** [comment]
What about "Saved"?

**Comment by ThomasLeigh** [comment]
@yanus171 

Some time ago I've told You that some other apps do **distinguish the two purposes of preserving articles** - although they may call it differently, they recognize the need to do so. I remind You on *[Raven](https://github.com/hello-efficiency-inc/raven-reader)* - see its *"Favourites"* and *"Saved articles"*:

![](https://github.com/hello-efficiency-inc/raven-reader/raw/master/newscreenshot.png)

Today is even better: I've installed *Microsoft's* *Edge* on My smartphone and here what I've seen within it: *"Favorites"* and... *"Reading list"*:

![Screenshot_20190619-004628](https://user-images.githubusercontent.com/26142231/59725498-1d587c80-922e-11e9-9cc2-03115f18fad7.png)
![Screenshot_20190619-004631](https://user-images.githubusercontent.com/26142231/59725502-1d587c80-922e-11e9-8ae3-0bc8da2f9845.png)

     
Again, **I dream *Handy NR* could apply a similar distinguishment**s.

**Comment by yanus171** [comment]
HNR is not todo manager. And it's not purpose to store information. Returning to article reading I don't see why we can't use Favorities as Read later list.

**Comment by ThomasLeigh** [comment]
> HNR is not todo manager. And it's not purpose to store information

I think many users could find handy and useful the possibility to put articles on the back burner to read later - or to save it in order not to vanish over the time. Though You could do the both via *Favorites*, **this name doesn't render those purposes clearly enough**, let alone there is no separate places for articles which I want to read later - and those I want to preserve, so I am forced to mix them together.

**Comment by yanus171** [comment]
What is the difference between Preserve and Read later?

**Comment by ThomasLeigh** [comment]
> "What is the difference between Preserve and Read later?"

***Read it later*** - articles which I want to read when I have more time.

***Preserved*** - articles which I've already read and find worth keeping. You have described it some time ago in following words:

> "I often star an article which is interesting for me and I don't want it to disappear after old period. But I don't want to Read it LATER. I want to read it right NOW."

Regardless of *preserved* articles being present in *Handy NR* or not - I still would like to rename *Favorites* into something more comprehensive. *"Read it later"* sounds good to Me - although it's not the best, but definitely better than *"Favorites"*.

**Comment by yanus171** [comment]
Currently I see only enforcing more difficulties for user. Instead of just starring the article, user should think every time what he suppose to do with it: preserve or read later. And when user want to find that article after some time he should try both places: Preserve list and read layer list.

**Comment by ThomasLeigh** [comment]
I understand Your point. It's not so important for Me to have separate places for *Read it later* and *Preserved* - but what about renaming *Favorites* into *Read it later* in order for it to be **more intuitive**?

**Comment by SIRSteiner** [comment]
Can we close this issue?
