### ISSUE TITLE
More readable UI text.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#173]
I use dark theme, unfortunately there are a lot of blue-ish labels on the dark-gray background, which is very hard for Me to read. Could You please change the color of those labels to something much brighter? Labels like "OK", "CANCEL", and all the rest which now have blu-ish color.

**Comment by yanus171** [comment]
Screenshot please

**Comment by ThomasLeigh** [comment]
https://drive.google.com/file/d/1H6z1modlUV_rZsMQwCM24Gyr6BPKs29x/view?usp=sharing

**Comment by yanus171** [comment]
What about long tap on article in list? Same problem?

**Comment by ThomasLeigh** [comment]
Yes
