### ISSUE TITLE
Brightness doesn't cover everything.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#177]
It already covers both article text and article list, and also the initial setting page. If, however, You enter any settings category - it reverts into the "normal" mode (brightness-wise). The same with the sidebar.

So - could the sidebar and every settings page be covered by the brightness adjustment as well?

**Comment by yanus171** [comment]
It's very hard to implement brightness support in preference subfolders. I only manage to update current brightness level there and only when Software overlay pref is off.

We'd better resolve the problem of this brightness mode on your phone.

**Comment by ThomasLeigh** [comment]
@yanus171 > We'd better resolve the problem of this brightness mode on your phone.
What do You mean?

**Comment by yanus171** [comment]
I mean https://github.com/yanus171/Handy-News-Reader/issues/116#issuecomment-485744788

Does not it still work? Do you use some auto brightness apps? Try to turn off auto brightness

**Comment by ThomasLeigh** [comment]
I don't use auto brightness. Yes, it still doesn't work without software overlay.

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.8.5 now controls brightness in color prefs too, but only without sofware overlay.

May be you use some autobrightness apps?

**Comment by ThomasLeigh** [comment]
>May be you use some autobrightness apps?

No, I don't use it because I much need the brightness to be fixed as I set it at the moment.
