### ISSUE TITLE
Increasing custom article keep time doesn't add the additional articles

### ISSUE THREAD

**Issue by CaptainFrosty** [yanus171/Handy-News-Reader#178]
When decreasing the keep time the feed is truncated, which is good, but the only way I can get the older articles to download after increasing the time is to delete the feed and re-add it. A time-consuming process that ruins my unread count.

**Comment by yanus171** [comment]
You can also tap Delete all in article list context menu, and then Refresh to load older ones

**Comment by CaptainFrosty** [comment]
Ok thanks
