### ISSUE TITLE
Rename "Global filter - mark as starred" into "Notify on important articles".

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#191]
I suppose this feature (_global filter - mark as starred_) is often (if not always) used to preserve articles we find important enough to be automatically placed into _"Favorites"_ and be notified on them on top of that.

Hence I propose to rename this whole feature into a **more comprehensive manner**: _"Notify on important articles"_. And then, if an article has been added to _Favorites_ by this feature, the notification would be called _"There is x important articles"_ instead of the message that _"Articles has been marked as starred"_ (or something like that).

I think thanks to this way the feature of automatically preserving/starring articles **would be understandable for much more users** (now it is definitely not obvious).

**Comment by ThomasLeigh** [comment]
@yanus171  What do You think? Can I rename this?

**Comment by yanus171** [comment]
There is only one category in it - Mark add starred.  But there may (or should) be other ones

**Comment by ThomasLeigh** [comment]
**Sounds interesting.** Do You think on something specific...?

**Comment by yanus171** [comment]
For example Global reject filter or Global remove filter
