### ISSUE TITLE
Improve the color picker.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#192]
Now in My subjective opinion:
- it could be great to have much more "space" to switch between text/background - it could be much easier than now (which I find pretty difficult),
- a larger  text/background preview would give a better idea of the result of color changing;

Here is what I mean:
https://drive.google.com/file/d/1aHRdEncgPF8dHLEp9Cn4RC6Naf9V6DQR/view?usp=sharing

**Comment by SIRSteiner** [comment]
My latest commit https://github.com/yanus171/Handy-News-Reader/commit/c8b4f3975ee664344cc9f53815bf3bf48d2718a7 I did some small improvements. @yanus171 should I try more improvements or are you already working on it?

**Comment by yanus171** [comment]
Yes you can. I do not working on it now

**Comment by SIRSteiner** [comment]
![Screenshot_1557783066](https://user-images.githubusercontent.com/3488638/57656203-0ba10b00-75d8-11e9-8f8d-846599669d6b.png)
![Screenshot_1557783179](https://user-images.githubusercontent.com/3488638/57656226-18256380-75d8-11e9-9e6b-8803357d1578.png)
![Screenshot_1557783207](https://user-images.githubusercontent.com/3488638/57656233-19ef2700-75d8-11e9-81b8-41601a2d4eba.png)

**Comment by SIRSteiner** [comment]
https://github.com/yanus171/Handy-News-Reader/pull/193/commits/4ae4c2856640cc4fd27f929f990c29ecf195a683

I hope it works for everybody

**Comment by ThomasLeigh** [comment]
@SIRSteiner Wow, You also can program? It wasn't so obvious for Me, I don't know this matter much.

Anyway, You've surprised Me. Thank You for this improvement, seems to look better, I'd like to give it a try in action.

**Comment by SIRSteiner** [comment]
Only a little bit. In the past I tried many languages (Clipper, Turbo Pascal, Free Pascal, PHP, Java/Android and other script languages) but often only for small things. I have to many interests...

**Comment by ThomasLeigh** [comment]
In what language _HNR_ is written? What software do You use to do it?

**Comment by ThomasLeigh** [comment]
Is this ver. available to download?

**Comment by ThomasLeigh** [comment]
I'm on chat, just in case...

**Comment by SIRSteiner** [comment]
Good morning Thomas. Please look here
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.8.3

**Comment by ThomasLeigh** [comment]
Fantastic, now it is much better, everything easily available.

Regarding progress bar color change - could it have a live preview of the progress' height?

**Comment by yanus171** [comment]
Preview where?

**Comment by ThomasLeigh** [comment]
On the progress bar color change screen.

**Comment by SIRSteiner** [comment]
I think @ThomasLeigh means that the height of the preview in progress bar color picker should be like defined in settings?

**Comment by SIRSteiner** [comment]
I will look at it in the evening

**Comment by ThomasLeigh** [comment]
I mean that this element could reflect the progress bar height defines in settings:

https://drive.google.com/open?id=1p5yfdrTK1qTxQIZJuNAZ2lQGQS2Gcm-5

**Comment by yanus171** [comment]
Now the class ColorPreference is quite independent. I don't like the idea to make one preference depends on another.

**Comment by SIRSteiner** [comment]
Maybe we can only set the height of the sample progressbar to a fix smaller value (independent from the setting) or do you prefer no changes at all?

**Comment by Ryuno-Ki** [comment]
> In what language _HNR_ is written? What software do You use to do it?

100% Java. On the code tab of a repo you can click the coloured bar to make GitHub show you the fractions of languages of that repo.

**Comment by ThomasLeigh** [comment]
Alexey, I've got Your point. Consider that it could be of a great advantage each time You care about Your Users by providing Them a WYSIWYG experience. I believe such details make significant difference in terms of how Your Users can feel while using Your app. I believe that the more convenient the experience - the more happy users with the impression of a really well-made app, which has been constructed and developed with the users on the first place. Details do matter.

**Comment by yanus171** [comment]
@SIRSteiner but @ThomasLeigh want it's height to be as in settings, not smaller

**Comment by yanus171** [comment]
@ThomasLeigh the existing progressBar setting corresponds to read bar in article's text view only.

The red blue green color progress bar is a type of Crutch, not in intendent for often use. It can't be just friendly.

We should turn our willing to another side: there are not so many color that really view pleasant. And often it's a problem to find them. So the color grid should help here. But how can we fill it by default?

On web? But there should be possibility to enter and view  color in #rrggbb format

**Comment by ThomasLeigh** [comment]
@yanus171 

>The red blue green color progress bar is a type of Crutch

What do You mean by _"Crutch"_?

**Alexey**, I know that I don't think so much on the programmer's perspective - in this respect I highly appreciate how open mind You have (You've already introduced many fantastic things, thanks to which _HNR_ become the app of My dreams). Most time I propose You something - You seem to be open to consider it. From My experience this is a rare occurrence among developers.

I know, however, how is it like to faced the hassle while the user is completely not aware of that (i.e. what happens under the hood, how something influences the code architecture, etc.) - because I've handled those things many times as a web-designer and web-developer. I'd love You to see My input as a totally free proposals, just to consider - not to convince (although I may sometimes sound like trying to convince).

In this particular case of the progress bar, I'll tell You what is the matter. When You introduced the ability to change its height, what I have to do to find My best setting was:

1. Guess what would be the proper choose and pick it.
2. Return several times from settings screen to some full article - to preview how it looks like now (the progress bar with a new height).
3. Return several times from the article to the settings screen - to adjust the settings, if needed.

In case of choosing a color for the progress bar - it's not so much a different case: although I can see the live preview, it's not 100% accurate.

Why it could be 100% accurate? In that case I - as a user - would not need any "testing", going back and forth through app screens. This, however, is not always possible to achieve - but wherever it is, I think it is a good idea to make a user's life easier, and the app more convenient. Unfortunately I am aware that sometimes it requires more work in terms of the code - I don't want to make You feel disheartened about developing _HNR_, or programming as such. Of course You always decide, what is worth to at least give it a try. I can only have the hope that it is possible to reconcile convenience from a user perspective with well-being of the developer :) .

Back to the progress bar, this concept could be achieved if both height and color could be set on one screen, with truly live preview, i.e. reflecting the color, the height, and the position. The color and the height are most important, but it's still not the same as seeing the progress bar in action on the very bottom or the top of the screen. But if we take text preview from the screen of changing text color - and add a progress bar within its area (on top/bottom) - then it gives much better idea of how it will look like in full-screen experience, i.e. regular app's usage.

I see two possible approaches here: either we could have one screen for the progress bar settings, much resembling the screen of text color settings - or we could have one screen to handle the both (three switches instead of the two ("text"/"background"/"progress bar") and a progress bar line drew within the text preview area with the Einstein's quote.


>We should turn our willing to another side: there are not so many color that really view pleasant. And often it's a problem to find them. So the color grid should help here. But how can we fill it by default? On web? But there should be possibility to enter and view color in #rrggbb format

I'm sorry but I don't get Your point here. Are You cynical or I really don't understand something here?

**Comment by yanus171** [comment]
@ThomasLeigh Seems that I understood you :) And I see we downt understand each other. You mixed up the color dialog and Article's text preview dialog. The preview should be  in Tap zones preview

**Comment by ThomasLeigh** [comment]
Oh, this way it seems to be much more complicated. I would propose not to involve Tap Zones Settings screen. It's not so bad, but I think it is much much more complicated - have such many things in one place (text color, progress bar color and tap zones descriptions and sizes).

**Comment by yanus171** [comment]
Color dialog is intendent only for setyp ONE color, while articke text preview windows (tap zones preview) should include copmponents of diffrerent colors

**Comment by ThomasLeigh** [comment]
Do You mean that You'd like to add more functionalities to the Tap Zones' preview screen which already exists? Or that You'd like to create a completely new config-screen?

**Comment by yanus171** [comment]
I think we should move that to new issue and delete last several posts

**Comment by ThomasLeigh** [comment]
I've created a separate issue here: https://github.com/yanus171/Handy-News-Reader/issues/209 . I think those last posts could be helpful, though. But decide Yourself.
