### ISSUE TITLE
Can't cancel the refresh.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#194]
I don't remember since when I encounter this issue. It consists of that I never am able to cancel the refresh by the "x" button or any other way.

**Comment by yanus171** [comment]
The refresh can not be canceled immediately. It can be canceled only between sub operations like refreshing a feed, mobilizing article, downloading an image. Try to test this button on refreshing of the group of feeds

**Comment by ThomasLeigh** [comment]
Could it be done that this feature assure a user that the refresh will be always canceled? For Me it doesn't work, regardless of when I tap on "x". But if it doesn't work always - then it doesn't make sense, it is rather confusing and gives the impression of a bug.

**Comment by yanus171** [comment]
It works. Give me exact steps to reproduce it
