### ISSUE TITLE
Improve "Download the image" feature.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#196]
The main thing is that I never know if tapping on this text button will work. Sometimes I see the picture after a while, but **often I can't see anything changing**. It could be much better to know what is happening: to see **some message and progress bar (or percentage)** accompanying the image downloading - and in case of a failure to be noticed that the image can't be downloaded. 

Another thing is that: if the picture has been downloaded, **the article text terribly "jumps" while showing the picture**, which is horribly disturbing. It would be enough to place particular-image sizes areas instead of a sole text _"Download the image"_ (**each size with width and height according to the image it should consist**) - one: this could be much more indicative that here it should be an image -and two: it avoids this "jumping", because regardless of an image to be downloaded or not, the place for it is always "reserved". As an additional feature showing image areas could be turned off in app's settings (in case someone would like to have only the text without being even noticed that there are some images). 

It could make a significant difference because for a long time now **the whole experience with images in articles is pretty confusing and disturbing.**

**Comment by yanus171** [comment]
I don't know image size until I download it, so I can't put an image stumb of required size

**Comment by yanus171** [comment]
Did you try to turn on Detailed progress technical info to see what's happening?

**Comment by yanus171** [comment]
There is also a setting of maximum image download size which can not permit image downloading

**Comment by yanus171** [comment]
There is a menu item Download all images which can minimize jumping

**Comment by yanus171** [comment]
Anyway let's try to reproduce this bug on a concrete feed /article

**Comment by Ryuno-Ki** [comment]
Would it be possible to download the first couple of bytes of each image?
Most formats should have the dimensions written in their as part of some Magical Bytes / format.

Also, what happens if the image gets downscaled? I believe, the ratio is more important than the actual size.

**Comment by yanus171** [comment]
This would decrease perfomance much while opening the article

**Comment by Ryuno-Ki** [comment]
Ok.

**Comment by ThomasLeigh** [comment]
@yanus171 

>Did you try to turn on Detailed progress technical info to see what's happening?

Yes, but it displays nothing.


I set the app the way which ensures Me that each and every image will be downloaded. But I've realized that there are cases in which it doesn't happen (maybe it's only one particular feed) - let's see those articles:


In [the first article](http://feedproxy.google.com/~r/Antyweb/~3/hs89Y-rUdbE/) there are some pictures visible - but on the top there is still a _"Download the image"_ text - I can't tap on it (regardless of software overlay).

![Screenshot (May 22, 2019 12_51_10)](https://user-images.githubusercontent.com/26142231/58172477-09564500-7c99-11e9-900a-5a4e1ee307f0.png)


In [the second article](http://feedproxy.google.com/~r/Antyweb/~3/aBv7tq83krI/) a similar situation, but this time _"Download the image"_ text is colored as if this is a hyperlink. Still nothing happens after tapping it.

![Screenshot (May 22, 2019 13_44_11)](https://user-images.githubusercontent.com/26142231/58172475-09564500-7c99-11e9-9d8c-e4bf4d491846.png)


_"Load all images"_ didn't change the situation.

**Comment by ThomasLeigh** [comment]
Another strange behavior but a different feed - [here](https://lifehacker.com/prevent-your-windows-pc-from-sleeping-with-caffeinated-1832271248): instead of an image just a text _"Illustration for article..."_ - although there is an image on the page:

![Screenshot (May 22, 2019 13_45_01)](https://user-images.githubusercontent.com/26142231/58173191-00667300-7c9b-11e9-8e88-703398861d28.png)

**Comment by yanus171** [comment]
What's your app version?

**Comment by Ryuno-Ki** [comment]
Same here. Have you looked, whether you could find the image path in the XML file (= the feed)?
I'd check, how they point to it.
Say, they have `/path/to/image.png` instead of the full qualified domain, then a request would fail.

**Comment by ThomasLeigh** [comment]
I use 0.8.5 ver.

**Comment by yanus171** [comment]
I see an image in the second article. [https://drive.google.com/file/d/1kcPk8SJ4bWyWjQaUvBrlhvDf_LrzUjzH/view?usp=drivesdk](url) Send me a source html of that page.

**Comment by yanus171** [comment]
@Ryuno-Ki, Tha app should process such a cases

**Comment by ThomasLeigh** [comment]
I'm not sure if the latest build should solve this problem - but it has not. [The two articles I've mentioned earlier on](https://github.com/yanus171/Handy-News-Reader/issues/196#issuecomment-494773227) act the same way as before - even if I use *"Reload full text"* or *"Load all images"* commands.
