### ISSUE TITLE
Langue settings are ignored

### ISSUE THREAD

**Issue by userdimi** [yanus171/Handy-News-Reader#197]
On my Huawei Mate 20 Pro the language settings are not affecting in the UI. 

**Steps to reproduce:**

- go to the Setting 
- click on language
- select my favourite language

 **Expected result:**
- the language choice is affected and the shows in the selected language

**Actual result:**
- the language is still the same 

**Appversion**
0.8.2 (from F-Droid store)

**Android Version**
9 Pie (SDK 28)

**Comment by yanus171** [comment]
Same as #36

**Comment by SIRSteiner** [comment]
Alexey, this is not the same. While #36 problem is by changing orientation here this issue occures everytime. With API 28 you cannot set language in general. I can reproduce it within Android Studio.

**Comment by SIRSteiner** [comment]
Toast error message: "Cannot create dir:/date/user/0/ru.yanus171.feedexfork/cache/feedex"

**Comment by yanus171** [comment]
OK, I will see it

**Comment by userdimi** [comment]
Thank you. Il' try to reproduce this error with Android Studio tomorrow and give you more logs and a stacktrace

**Comment by SIRSteiner** [comment]
Alexey, this issue happens since Oreo (API 26). Maybe you can look at the following links and fix this bug as soon as possible.
https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758
https://stackoverflow.com/questions/47165311/how-to-change-android-o-oreo-api-26-app-language

**Comment by yanus171** [comment]
Why so soon?

**Comment by SIRSteiner** [comment]
More than 28% of Android devices uses Oreo.

**Comment by yanus171** [comment]
But not so many users change system language. Of cause I will try to fix it 
soon. But may be I don't understand something?

**Comment by SIRSteiner** [comment]
That's right. But if we have a feature then it should work ;-)

**Comment by userdimi** [comment]
Is it possible to make a request when I fix the issue by my own?

**Comment by yanus171** [comment]
Of cause.

**Comment by yanus171** [comment]
@SIRSteiner, can you pull current master branch, compile, and test this issue on API26 and even better on API29 ?

**Comment by userdimi** [comment]
Sure, I will do this Sunday.

**Comment by SIRSteiner** [comment]
@yanus171 I am not at home for the next 7-8 days. @userdimi Thank you.

**Comment by userdimi** [comment]
The language settings are working fine. Tested with API 26, 28 and 29 (Q). 
To the issue that @SIRSteiner has noticed: In the `HomeActivity` in the `onCreate` method at Line 196 you check if the file exists, before requesting the permissions to write. So you get the Toast error message: "Cannot create dir:/date/user/0/ru.yanus171.feedexfork/cache/feedex"

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.8.6

**Comment by yanus171** [comment]
@userdimi, thank you for permission notice

**Comment by userdimi** [comment]
Works like a charm. Thanks for the fixing!
