### ISSUE TITLE
Mark as read only visible articles

### ISSUE THREAD

**Issue by M-Faust** [yanus171/Handy-News-Reader#204]
Mark as read only visible articles, or Up/Down from current selected article.

**Comment by yanus171** [comment]
I am going to make a mode of auto mark articles as read while scrolling article list (just like new article plus sign). But should this mode be enabled by global setting or should be setup for each feed?

**Comment by yanus171** [comment]
By the way such a mode is already implemented for feeds with Show original text in article list checked

**Comment by M-Faust** [comment]
Yes, but mode of auto mark articles as read while scrolling article list doesn't work on global tab "Unread" and it's pity.
