### ISSUE TITLE
Filter not working for lifehacker.com + request to start in last used view

### ISSUE THREAD

**Issue by beatstick** [yanus171/Handy-News-Reader#207]
Hi, I tried to filter the rss-feed from lifehacker.com/rss, but I am still seeing "Saturdays best deals" and other topics that are basically just adds. I filtered the words "Deals, deals, Best Deals, best deals, etc." but these topics are still shown. The global setting to "star" or favorite these articles worked well (I used it by accident because I thought it was a filter). 

Another improvement would be to set the users preferred "view" when you start the handy-news-reader-app. I always shows "unread" articles but I'd like to start in "all articles" view. That way it's a lot easier to find what topics I've read already.

**Comment by yanus171** [comment]
Filter works only on the new articles. To apply it for existing articles tap Delete all in feed menu and refresh feed

**Comment by yanus171** [comment]
Also see #126

**Comment by yanus171** [comment]
See also #56

**Comment by beatstick** [comment]
Ah, ok. But I meant new articles. New articles with banned words are still downloaded and show up in my feed.
