### ISSUE TITLE
New Article Text  Config and Preview Screen.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#209]
Now we have separate config screens for the progress bar height and color. I propose to unify it into a single config screen, which could include live and real progress bar preview, i.e. so that I could set the progress bar height and color, and preview those changes **while I'm doing it** - i.e. on the fly.

I propose either to improve the already existing progress bar config screen - or to unify it with the article text color config screen, so that instead of two config screens (for article text and progress bar) we could have a single one, allowing to change article text color, article text background and progress bar color and height - all of it reflected within the preview area (with the Einstein's quote).

**Comment by yanus171** [comment]
Now https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.8.5 we have seleral color, font size and other settings so we can discuss Article Text Config and Preview Screen

**Comment by ThomasLeigh** [comment]
So what do You think on the post above?
