### ISSUE TITLE
Could hyperlinks be not underlined?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#213]
Would it be possible to turn off hyperlinks underlining? Once it is possible to change their color, they are finally well-readable for Me - and this underlining is not necessary. The whole text would look much better without those thick lines accompanying hyperlinks. I know that many users regard this as a standard rule - I'd just love to be able to turn them off somewhere in settings.

**It is fantastic to be able to read hyperlinks freely. Thank You, Alexey.**

**Comment by yanus171** [comment]
OK I will try

**Comment by yanus171** [comment]
Should they still remain clickable?

**Comment by ThomasLeigh** [comment]
I think it is a good idea.

**Comment by yanus171** [comment]
Why? May be its a bad idea? :)

**Comment by ThomasLeigh** [comment]
I get the impression that You are cynical.

**Comment by yanus171** [comment]
So thats the quiestion: should we transform links to simple (not clickable) text

**Comment by ThomasLeigh** [comment]
I think preserving in-text links is a must-have, because they have much more important reason than the link with the article's title.

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.8.5

**Comment by ThomasLeigh** [comment]
>So thats the quiestion: should we transform links to simple (not clickable) text?

After a second thought I think that You've pointed out an important idea: there are some people who would highly appreciate a plain, clean reading experience, i.e. without any distractions, including hyperlinks. So You could add an option to disable hyperlinks if one wishes so. As a result hyperlinks would be indistinguishable from all the rest of the text. And You could call this feature _"Zen Mode"_ :) .

What do You think?

**Comment by yanus171** [comment]
Maybe. But I wish to hear about the usefullness of this idea from thouse people

**Comment by ThomasLeigh** [comment]
Unfortunately I can't see the way to reach them.

@SIRSteiner , @Ryuno-Ki  , @Spleeeno , @paulle - could You please share Your take on this one?
