### ISSUE TITLE
Is Kotlin the future for HNR?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#215]
Although I am not a Java programmer, recently I've heard of some interesting things about Kotlin, which make Me wonder would it be a more convenient choice for _Alexey_ and all of You Who also programs?

**What I've heard:**
- it is much nicer experience to write code in _Kotlin_ in comparison to Java,
- the code may be significantly shorter,
- You'll see the difference while writing a couple of classes in _Kotlin_,
- there is no need to put ";" at the end of each line,
- You don't need to double a variable type each time You declare a variable,
- _Kotlin Native_ allows You to write an app simultaneously for _Android_ and _iOS_;

[Here](https://img.android.com.pl/images/user-images/2019/01/kotlin-java-uzycia.png) You can see how _Kotlin_ is going on among the open source developers. [(the source)](https://medium.com/@victoralbertos/kotlin-adoption-on-the-android-open-source-community-fe01d00a8bb3 )

What are Your thoughts?

**Comment by Spleeeno** [comment]
HNR is a Fork of Flym 1.x and Flym 2.x was rewritten in Kotlin afaik.
So basically every feature added to HNR would have to be rewritten in Kotlin - but having a rather active codebase (Flym 1.x doesnt change, Flym 2.x sure does) might break some things at rather random times for HNR after such a rebase.

Just a random thought:
If Kotlin is a priority, it might make sense to add HNRs features to Flym 2.x directly.
But maybe HNR was solely created because that never was an option...

**Comment by yanus171** [comment]
I currently see no much enough practical reasons to rewrite the hole application.

Maybe in far future...

**Comment by yanus171** [comment]
And Flym v2 is not just converted to Kotlin. It was rewritten from the beginning. It is a different app with different features and UI

**Comment by userdimi** [comment]
But why not to start whit smaller steps. Nobody want to rewrite the whole app. Let's beginn with unit test, that sould be written with Kotlin and after that continue with small Utils classes.

**Comment by yanus171** [comment]
O, that's a good idea:) Would you pull request some unit tests?

**Comment by userdimi** [comment]
Sure, I will write some Unit tests. Should I start a new issue for this?

**Comment by yanus171** [comment]
No need for issue, just a pull request. And be ready for discussion

**Comment by ThomasLeigh** [comment]
Do You mean that now _HNR_ will be written partly in Java and partly in Kotlin **in the same time**?

**Comment by ThomasLeigh** [comment]
Besides, _Alexey_, if You'd have the time to re-write the app from scratch either in _Java_ or _Kotlin_ - don't You think You could do it better?

**Comment by Ryuno-Ki** [comment]
No. I'm against the idea of rewriting everything.
You'll throw away all the knowledge (and mistakes) you made so far.
Better to transition gradually.

**Comment by ThomasLeigh** [comment]
I've just read a very interesting announcment on *Kotlin* via *[Android Developers blog](https://android-developers.googleblog.com/2019/07/kotlin-named-breakout-project-of-year.html)*. What drew My attention is that *Kotlin* has been described as ***"programming language that lets you write better code, faster"*** and ***"#1 fastest growing language on Github."***. Pretty surprising was also that 

> *"We're already seeing adoption in apps such as Google Home, Google Drive, Android System UI, Nest, with many more to follow."*

and finally:

> *"Android is going increasingly Kotlin-first, "*

**There are also some learning stuff attached:**

- https://developer.android.com/kotlin/learn
- [free *Kotlin* course on Udacity](https://eu.udacity.com/course/developing-android-apps-with-kotlin--ud9012)
- [*Kotlin* Bootcamp for Programmers](https://eu.udacity.com/course/kotlin-bootcamp-for-programmers--ud9011)

**Comment by Ryuno-Ki** [comment]
Have you ever heard of the [hype cycle](https://en.m.wikipedia.org/wiki/Hype_cycle)?

I'd wait until Kotlin gets mature. Messages like fastest growing language sounds like people jumping onto a hype train...

**Comment by ThomasLeigh** [comment]
Is _Google_ rewriting their apps into _Kotlin_ also a hype in Your opinion?

**Comment by Ryuno-Ki** [comment]
Yes.
And they're trying to evade their patent fight with Oracle.
