### ISSUE TITLE
Youtube channel feeds

### ISSUE THREAD

**Issue by RAMAR-RAR** [yanus171/Handy-News-Reader#217]
Youtube channels rss file is saved like a bin file so isn't possible import all the channels with a single import.

**Comment by Ryuno-Ki** [comment]
Hi @RAMAR-RAR,
could you share a link to a RSS feed for testing purposes?
What do you mean with „like a bin file”?

**Comment by RAMAR-RAR** [comment]
https://jirafeau.net/f.php?h=2OGXvgMi

**Comment by yanus171** [comment]
It's not a YouTube link. 

You can add as a feed any YouTube web page with a Web type in add feed dialog

**Comment by ThomasLeigh** [comment]
@RAMAR-RAR 

> Youtube channels rss file is saved like a bin file so isn't possible import all the channels with a single import.

Do You want to add a _YouTube_ channel as another _RSS_ feed? If so, please share the address of a channel You want to add.
