### ISSUE TITLE
What is the most difficult part in developing HNR?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#234]
I'd like to know the answer both in terms of general work's any facet - and also in terms of the code specifically. I'm curious how it looks like behind the scenes.

Alexey, could You share some screenshots how _HNR_ is created? Some "snapshots" behind the scene, from a typical developer's day - i.e. Your day working on _HNR?_

P.S.:
Can I label posts on _GitHub_?

**Comment by Ryuno-Ki** [comment]
> To create, edit, apply, or delete a label, you must have write access to the repository.
https://help.github.com/en/articles/about-labels

**Comment by ThomasLeigh** [comment]
@Ryuno-Ki Thank You for pointing this out.

@yanus171 Thank You for allowing Me to label posts.

**Comment by yanus171** [comment]
The most difficult part now is to break away from github conversations and snatch some time for development :)

**Comment by yanus171** [comment]
@ThomasLeigh, can I ask you to use a newly acquired label power to color all the rest issues with labels bug, quiestion, and enchchment?

**Comment by ThomasLeigh** [comment]
@yanus171 

> can I ask you to use a newly acquired label power to color all the rest issues with labels bug, quiestion, and enchchment?

All right I'll label everything which is clear enough for Me to categorize.
