### ISSUE TITLE
Не загрузились почти все картинки

### ISSUE THREAD

**Issue by Penelopen** [yanus171/Handy-News-Reader#235]
Сегодня после окончания цикла обновления новостей, почему-то у большинства новостей не загрузились картинки (ни одной). Я нажал обновить всё ещё раз. Дождался окончания и снова нет картинок. Тоесть из 50 новостей, картинки есть только у 5-10

Однажды когда-то такое уже было, но я не придал этому значения. Обновлял по Wi-Fi 50 мегабит.

**Comment by yanus171** [comment]
Картинки ставиться в очередь на загрузку только для новых статей. Если по каким-то причинам при обновлении они  загрузились, то загрущятся при следующем обновлении (из очереди). Однако кнопка Отменить обновление очищает очередь. И тогда картинки загрузятся только при открытии статьи

**Comment by Penelopen** [comment]
Понято. Благодарю!
Предлагаю в настройке по автообновлению внедрить выбор времени, КОГДА
автообновление будет происходить

**Comment by yanus171** [comment]
Только один раз в сутки? А если в заданное время не получилось? Заряд 
маленький, телефон выключен,...

**Comment by Penelopen** [comment]
Тогда можно просто пытаться ещё через 5 минут например. И так несколько попыток..
null

**Comment by yanus171** [comment]
А не проще раз в 3-4 часа?

**Comment by Penelopen** [comment]
Так ведь постоянно каждые 3-4 часа нагрузка будет. А если мне, например
нужно, чтобы новости загружались ночью, когда телефоном никто не
пользуется, он на зарядке... Утром проснулся, а у тебя всё загружено

**Comment by yanus171** [comment]
Тогда мне лучше сделать галку Обновлять автоматически только при зарядке. И 
ещё одну для WiFi. Подставите раз в сутки, А Android уж сам позаботиться, 
когда её запускать

**Comment by Penelopen** [comment]
Хмммм хорошая идея. Только нужно оставить "ручное обновление". Чтоб можно было нажать на кнопочку и независимо от Wi-Fi и зарядки обновиться
null

**Comment by yanus171** [comment]
Try (Попробуйте) https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.8.6

**Comment by Penelopen** [comment]
Only when charging. Отлично!)) А с самсунговской галереей и открытием новости по нажатию на мини картинку сделаете?))
null

**Comment by yanus171** [comment]
Буду думать. Но тут быстро не обещаю.

**Comment by Penelopen** [comment]
А как работает "только на зарядке?. У меня выставлен интервал обновлений 6 часов. Если к моменту срабатывания таймера телефон не будет на зарядке, то понятное дело, синхронизации не произойдет. Но если через минуту я подключу кабель, то все-равно следующая синхронизация будет через 6 часов или же какое-то время попытки совершаются?
-------- Исходное сообщение --------От: yanus171 <notifications@github.com> Дата: 26.05.19  7:06  (GMT+03:00) Кому: yanus171/Handy-News-Reader <Handy-News-Reader@noreply.github.com> Копия: Penelopen <silapil@yandex.ru>, Author <author@noreply.github.com> Тема: Re: [yanus171/Handy-News-Reader] Не загрузились почти все картинки (#235) Буду думать. Но тут быстро не обещаю.









—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/yanus171/Handy-News-Reader/issues/235?email_source=notifications\u0026email_token=AMCUVBQCGZ4QULXFBOU7K5TPXIECXA5CNFSM4HO3BACKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWH5WBI#issuecomment-495966981",

"url": "https://github.com/yanus171/Handy-News-Reader/issues/235?email_source=notifications\u0026email_token=AMCUVBQCGZ4QULXFBOU7K5TPXIECXA5CNFSM4HO3BACKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWH5WBI#issuecomment-495966981",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by yanus171** [comment]
Скорее всего повторная попытка будет. Вообще все это определяется системой, 
я в программе задаю только допустимые условия и периодичность
