### ISSUE TITLE
Free Software should not use "Open Source" wording.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#237]
If You've decided to publish _HNR_ under the _GNU GPL_ license, it could be highly appreciated **not to use _"Open Source"_ wording**, although I'm aware that it is often used anyway. The point is that - although _Free Software_  and _Open Source_ share a common ground - **they are not synonyms**. There are crucial differences between the two, which deserve to be concerned.

> "The two now describe almost the same category of software, but they stand for views based on fundamentally different values. For the free software movement, free software is an ethical imperative, essential respect for the users' freedom. By contrast, the philosophy of open source considers issues in terms of how to make software “better”—in a practical sense only. It says that nonfree software is an inferior solution to the practical problem at hand." ([Richard Stallman](https://www.gnu.org/philosophy/open-source-misses-the-point.en.html))

Read [this](https://www.gnu.org/philosophy/open-source-misses-the-point.en.html) for further explanation.

**Comment by yanus171** [comment]
Free means that you should not pay for it. 

Open source means that you can compile it from source code (optionally edit the code or check for the  absence of malware for example)

**Comment by SIRSteiner** [comment]
To prevent a discussion about these two terms you should use FOSS or FLOSS like F-Droid do it.

**Comment by Ryuno-Ki** [comment]
No.

The [Open Source Definition](https://opensource.org/osd) lists some criteria:

* Free Redistribution
* Source Code
* Derived Works
* Integrity of The Author's Source Code
* No Discrimination Against Persons or Groups
* No Discrimination Against Fields of Endeavor
* Distribution of License
* License Must Not Be Specific to a Product
* License Must Not Restrict Other Software
* License Must Be Technology-Neutral

In contrast, Free Software is characterised by the [Four Freedoms](https://www.gnu.org/philosophy/free-sw.html.en)

> * The freedom to run the program as you wish, for any purpose (freedom 0).
> * The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). Access to the source code is a precondition for this.
> * The freedom to redistribute copies so you can help others (freedom 2).
> * The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

Free Software was first. But people confused „Free as in freedom” with „Free as in beer“. That's why the marketing term „Open Source” was coined. (Let me know if you want to read more about it).

**Comment by Ryuno-Ki** [comment]
+1 for FLOSS (= Free, Libre and OpenSource Software)

**Comment by yanus171** [comment]
I still don't understand: what shall I do?

**Comment by Ryuno-Ki** [comment]
@ThomasLeigh _Where_ should those two terms not be mixed?

**Comment by ThomasLeigh** [comment]
@Ryuno-Ki 

> _Where_ should those two terms not be mixed?

Within the app's description both in _"ReadMe"_ on _GitHub_ and for _Google Play_ and _F-Droid_.


@SIRSteiner 

>To prevent a discussion about these two terms you should use FOSS or FLOSS like F-Droid do it.

I still think that those two terms (_"Free Software"_ and _"Open Source"_) shouldn't be put together, because this is not like _"Open Source"_ is **always** a part of _Free Software_.


@yanus171 

> I still don't understand: what shall I do? 

Decide if those four freedoms mentioned by André are important for You. To be more precise: what is more important for You: to allow other people to access the source code - or to do it, but given that those freedoms will be maintained?


You can publish as _Open Source_, maintaining all those freedoms, **but** sticking **only** to _"Free Software"_ and avoiding _"Open Source"_ (I mean only the wording now) is an expression that those Freedoms are key for You and important enough to put a strong emphasis on them.

**Comment by SIRSteiner** [comment]
I do not think much of this discussion. We're releasing this app on F-Droid, and there you can read: "F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The client makes it easy to browse, install, and keep track of updates on your device." With FOSS / FLOSS you can live up to both opinions. FLOSS is the better choice I think.

**Comment by ThomasLeigh** [comment]
@SIRSteiner 

> With FOSS / FLOSS you can live up to both opinions.

The thing is they could be contrary to each other.

**Comment by SIRSteiner** [comment]
Why? HNR is licensed under GNU GPL -> Free/Libre. And HNR is open source or not?

**Comment by ThomasLeigh** [comment]
I mean that if You label something as _"Open Source"_ it doesn't **clearly** render the values of _Free Software_:

* _Free Software_ is for those who highly care about _the Four Freedoms_,
* _Open Source_ consists both of developers who care about it - **and for those who not** (because You don't need to care about it to make Your code open);

So - if for Alexey _the Four Freedoms_ are highly important (which I don't know if they are), _"Open Source"_ will fit _HNR_, yes, but it fits **partly**.

It resembles a metaphorical question: with whom You wanna be hanging around: with someone who wants to be always good and think that being bad is not right? Or with someone who - even if wants to be good - accepts that it's not so much of a difference, it's not so important.

For Me it doesn't matter, because I am not the one who creates _HNR_, so the case doesn't refer to Me. This is just a matter of one's personal values and how much one finds it important.

**Comment by SIRSteiner** [comment]
> So - if for Alexey the Four Freedoms are highly important (which I don't know if they are)

This is not the question. See the fact: HNR is licensed under GNU GPL https://github.com/yanus171/Handy-News-Reader/blob/master/LICENSE
Therefore HNR is free/libre (open source) software.

**Comment by ThomasLeigh** [comment]
_GNU/GPL (_Free Software_)_ is _open source_ - but not all _open source_ is _Free Software_ . It depends on the developer's values, approach, priorities in life, You name it. I know that _HNR_ has opened source - the point is what is its creator's attitude, value system. _Free Software/GNU GPL_ has been created **on the purpose** much higher than opened code. If it doesn't matter so much, it is a better idea to leave _Free Software/GNU GPL_ and choose any other license (there are plenty out there) - and it won't interfere.

**Comment by SIRSteiner** [comment]
Again: HNR is licensed under GNU GPL. It is indepentent from Alexeys wishes. HNR is Free/Libre software.

**Comment by ThomasLeigh** [comment]
Oh, yes, in case the original app has been published under _GNU GPL_ - if I remember correctly, the fork must to be published the same way. So, yes, in such a case the attitude doesn't matter so much  What remains is that it could be a good turn to leave _"open source"_ wording, in order to honor _Free Software_ values.

**Comment by SIRSteiner** [comment]
My final statement: Many people associate free software with freeware and don't care about definitions. But if they hear open source they associate much more. That's why I always prefer Free/Libre and Open Source Software (FLOSS) as many other (e. g. F-Droid). In german I prefer "Freie, quelloffene Software"
