### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by yanus171** [yanus171/Handy-News-Reader#239]
Let's discuss labels here

**Comment by yanus171** [comment]
@ThomasLeigh, they're is a standard label enchachment. Why we need additional feature request?

**Comment by ThomasLeigh** [comment]
I've tried to make things more precise: some requests are referring to improvements in already existing features, layout, etc. - while some are referring to new features. 

If You, however, don't like it, I will replace all those labels with "enhancement".

**Comment by Ryuno-Ki** [comment]
Perhaps overkill, but ... https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63
