### ISSUE TITLE
Mobilizer is not working properly. 

### ISSUE THREAD

**Issue by ognjen73** [yanus171/Handy-News-Reader#240]
Mobilizer is not working as it used to.

In latest several versions it ommits first picture in the article. It does not display it.

The last version with perfectly working Mobilizer was 0.8.0.

Thank you.

**Comment by yanus171** [comment]
Give me a link to article

**Comment by ognjen73** [comment]
Here are the typical rss feeds.
Articals are crippled as the first picture, and therefore sometimes, some 
text are omitted.

http://www.advance.hr/vijesti.rss
https://www.logicno.com/feed

Thank you.

**Comment by ognjen73** [comment]
The another typical rss feed example.
Image is crucial but not displayed.

https://rs.sputniknews.com/export/rss2/cartoons/index.xml

Thank you.

**Comment by yanus171** [comment]
Where is the text ommited?

**Comment by ognjen73** [comment]
Sometimes when article has very little of text right after picture, the text is being ommited. It happens probably as result of omitting the first picture.
Right now I am not able to find article sample, because they are rare.
Could you please solve first picture ommiting, then, after some time of using Handy, I will tell whether text dissappears in such articals when I run to some.
Thank you very much.
BTW, excellent news reader. I am using it from almost the beginning.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.8.6

**Comment by ognjen73** [comment]
It works excellent except for some feeds like this one which has two first pictures at the beginning.

http://vestinet.rs/feed

Thank you.

**Comment by yanus171** [comment]
Two is better than none :)

**Comment by yanus171** [comment]
I suppose we need per feed setting for include ob:image to article text

**Comment by ognjen73** [comment]
Good idea!

**Comment by ognjen73** [comment]
Here is the feed whose text is omitted. The introducing bolded paragraph is omitted.

https://rs.sputniknews.com/export/rss2/archive/index.xml

**Comment by yanus171** [comment]
I see nothing omitted. Give me a article url

**Comment by ognjen73** [comment]
Here it is.
https://rs.sputniknews.com/svet/201905261119916720-tramp-abe-golf/

**Comment by yanus171** [comment]
Add string "sputniknews.com:class=b-article__text" to settings, advanced, content extract rules and reload article

**Comment by ognjen73** [comment]
I did it.
Now the introducing paragraph, shown in bold right under title, is not 
displayed.
It was the only text displayed before the rule was added.
All other other text, that was not displayed before, is displayed now.

**Comment by yanus171** [comment]
Then try sputniknews.com:b-article

**Comment by yanus171** [comment]
Also try to tap Reload with tags in article context menu and choose a better class

**Comment by ognjen73** [comment]
It worked. Thank you!

What do you mean by choosing a better class?
How could I do it and where?

**Comment by yanus171** [comment]
> Also try to tap Reload with tags in article context menu and choose a better class

In this mode the article text is displayed with html nodes which have class attribute. So we should choose the best node which contains only article full text and nothing else (header, menu, footer, share etc) and paste that class name to Content extract rule setting

**Comment by yanus171** [comment]
And please don't quote my text in mail for it's automatically publishes on github thread
