### ISSUE TITLE
Progress bar height doesn't work.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#243]
It doesn't react on any change, even if I restart the app. (ver. *0.6.8* - I'm not sure since when it doesn't work because I've just tried to change the height yesterday)

**Comment by yanus171** [comment]
I can't reproduce it. Did you try many different size settings?

**Comment by ThomasLeigh** [comment]
Yes, and with _"Software overlay"_ on and off.

**Comment by ThomasLeigh** [comment]
Do You want Me to show this on the video (screen recording)?

**Comment by yanus171** [comment]
Yes, video can be useful

**Comment by ThomasLeigh** [comment]
[Here You are,](https://drive.google.com/open?id=1DMPQjzJncZiTvE8YVT3HXJ-jg5Ijebo6)

**Comment by SIRSteiner** [comment]
I can confirm this bug. BUT it works if footer clock is visible. Maybe this information helps...

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.1

**Comment by ThomasLeigh** [comment]
@yanus171 

If I set it to "8", preview it, then set it to "4" and preview it - "4" looks the same as "8". "1" makes the difference, but it doesn't look like hair-thin (I suppose it was that way before).

**Comment by yanus171** [comment]
And what if you enable the clock?

**Comment by ThomasLeigh** [comment]
It acts the same way.

**Comment by yanus171** [comment]
Please send me a screenshorts for several settings (Even if you think that they are identical)

**Comment by ThomasLeigh** [comment]
Sure, here You are (1x-8x;every size change preceded by re-entering the article):

![1x](https://user-images.githubusercontent.com/26142231/59567613-3c111480-9070-11e9-8e6d-097e0d0d366d.png)
![2x](https://user-images.githubusercontent.com/26142231/59567614-3c111480-9070-11e9-8ed6-7a137131bac8.png)
![3x](https://user-images.githubusercontent.com/26142231/59567616-3c111480-9070-11e9-9fed-b34ffa8d70f6.png)
![4x](https://user-images.githubusercontent.com/26142231/59567617-3c111480-9070-11e9-9ea8-65a0cea51867.png)
![5x](https://user-images.githubusercontent.com/26142231/59567618-3ca9ab00-9070-11e9-9c84-6731a67c669e.png)
![6x](https://user-images.githubusercontent.com/26142231/59567619-3ca9ab00-9070-11e9-9edf-4c840f30ad3e.png)
![7x](https://user-images.githubusercontent.com/26142231/59567620-3d424180-9070-11e9-9af0-93f2c6f75266.png)
![8x](https://user-images.githubusercontent.com/26142231/59567612-3c111480-9070-11e9-9c6b-973f9f038b1e.png)

**Comment by yanus171** [comment]
What about now?

**Comment by ThomasLeigh** [comment]
It works, thank You.
