### ISSUE TITLE
Remove particular elements from article's text.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#245]
In some articles there are parts which I don't need to see. For example, some articles have *"Share on Facebook"*, etc. header (there are other examples of such unimportant text snippets which are unrelated to the actual article's content). **It could be great to be able to remove those parts in order to see only the actual article's text**.

Since there can be many different instances of such unimportant text snippets - it could be great to be able to remove them in app's settings - let's say we could have a setting (*"Advanced/Remove unwanted text snippets"*). I recommend for it to be **a global setting** for all feeds at once (to simplify the thing from a user's perspective).

THen there could be a text area which a user could fill with rules which will point out the *HTML* elements which consist of those unwanted text snippets. I mean something like in *jQuery*, when I can simply write:

	p:consists("share on Facebook").remove;
	
and it's done. Of course a user needs to posses some *HTML* knowledge to be able to point out those elements.

**Comment by yanus171** [comment]
See recent posts in #240

**Comment by ThomasLeigh** [comment]
I've read it. So what's now?

**Comment by yanus171** [comment]
So for every web domain you can define the html class, containing the root text element. This will remove all pet rubbish texts

**Comment by ThomasLeigh** [comment]
What if some rubbish text is inside the root text element?

**Comment by yanus171** [comment]
Am your examples (header, fotter, share) are not inside

**Comment by ThomasLeigh** [comment]
I'm not sure about [this case](https://android.com.pl/news/220460-qualcomm-prawo-antymonopolowe/): here You are two share-buttons (*Facebook* and *Twitter*), inside *.post-content* container, how to handle this?

**Comment by yanus171** [comment]
On my phone it's loaded without share buttons by default, without using Content extract rules setting

**Comment by ThomasLeigh** [comment]
I have this (all articles in this feed have this green part):

![Screenshot_20190527-220721](https://user-images.githubusercontent.com/26142231/58437936-7c622000-80cc-11e9-9704-19bc4f20ccc4.png)

**Comment by yanus171** [comment]
So this green text we should remove? It's only from the beginning?

**Comment by ThomasLeigh** [comment]
No, it is also placed on the bottom (also within the root node) - as well as `a.info-post-author`- which I also don't need to see.

**Comment by ThomasLeigh** [comment]
This is [another example](https://zenhabits.net/meaning/): there is additional (*"By Leo Babauta"*) text which I don't need to see, and it is placed **within** the root node (I suppose the *.post* class in this case).

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.1

**Comment by ThomasLeigh** [comment]
@yanus171 

Ok. Could the effects of hiding particular elements act within normal view ("Reload full text" - no tags visible, only the actual content)?

**Comment by yanus171** [comment]
Yes, of cause. At first you set visibility of elements in tags mode, and 
after that you should switch to normal mode (reload full text)

**Comment by ThomasLeigh** [comment]
Speaking of a feed for which I set what elements to remove:

could the effects be visible in other articles of this feed **without a need to use *"Reload full text"* every single time** I want to see the cleaner text?

**Comment by ThomasLeigh** [comment]
In case of [this feed] (http://android.com.pl/feed/) *"Reload with tags"* seems to do/ nothing, no green or blue elements.

**Comment by yanus171** [comment]
No, the effect will be only after reloading. Such heavy  processing of 
article text every time of article displaying would have a bad impact on 
perfomance.

**Comment by ThomasLeigh** [comment]
Could You add an option in settings for this feature to work by default? It could be described as *"Cleaner text, less performance"* - and be unchecked by default.

The reason I ask for it is that the whole point of the ability to clean the text is to have better reading experience right off the bat. Being able to have it, but only after choosing additional command each and every time, which, btw, makes the text skipping and jumping while reloading, is definitely not a convenient solution.

**Comment by yanus171** [comment]
After you set some element as hidden the info about that class is written 
to the Remove text rules setting. And all subsequent actions of loading 
full text will remove elements with that class  from any loading article.

So behaves the Choose text root menu item. It writes rule (class attribute 
value) for text root into Content extract rules settings, but it also 
respects the web page domain, to have one rule for all articles of that domain.

Look at these settings.

**Comment by ThomasLeigh** [comment]
The point is I still need to use *"Reload full text"* every time I want particular parts to be removed/hidden.

**Comment by ThomasLeigh** [comment]
@yanus171 

What do You think about the idea of the option in settings, which I've described [above](https://github.com/yanus171/Handy-News-Reader/issues/245#issuecomment-500409279)?

**Comment by yanus171** [comment]
You should do it once for a feed. And this is not so often operation

**Comment by ThomasLeigh** [comment]
@yanus171 

> The point is I still need to use "Reload full text" every time I want particular parts to be removed/hidden.

> You should do it once for a feed. And this is not so often operation

I need to do it within **each article** of this feed. It would be fantastic to have those rules active automatically. Then I could just open an article and see its clean text.

**Is there a chance it could be done that way?**

**Comment by yanus171** [comment]
You should do it only ONCE for a feed. No need to do it for every article. 
It will be applied for all newly loading articles. If you want to apply 
rule for all existing articles, just tap Delete all articles and refresh.

**Comment by ThomasLeigh** [comment]
@yanus171 

> It will be applied for all newly loading articles.

What exactly will be applied for all newly loading articles? *Content extract rules*, *Remove text rules* - or both of them?


> If you want to apply rule for all existing articles, just tap Delete all articles and refresh.

Will this remove the *Favorites* also?

**Comment by yanus171** [comment]
Both of them will be applied.

The Delete all operation does not delete favorites

**Comment by ThomasLeigh** [comment]
@yanus171 

Wow, indeed :D *.* !!!!!!!!! *Alexey*, You are ***fantastic*** :) ! Another dream came true!!!!!!! Wooooow, I still can't believe it ;) !

**Comment by ThomasLeigh** [comment]
@yanus171 

For curiosity: do You Yourself use this option (*Remove text rules*)?

**Comment by yanus171** [comment]
Don't hurry to close it. I read meant pages where ads are inserted in the text without special classes (neither id attr) - so we need another remove algorithm for them (regex?).

Also I thought about auto Reload full text (without tags) after show/hide menu was tapped (as in Choose text root).

Our long conversation tells about lack of intuitiveness in this feature's GUI.

...

**Comment by ThomasLeigh** [comment]
@yanus171 

> Also I thought about auto Reload full text (without tags) after show/hide menu was tapped (as in Choose text root).

I think this is definitely a good idea.

**Comment by yanus171** [comment]
Done in https://github.com/yanus171/Handy-News-Reader/releases/tag/0.9.2

**Comment by ThomasLeigh** [comment]
Fantastic :) .

There is one thing which may be confusing. Let's say that You have an element within an article, which You want to hide. Let's say that this element is placed somewhere at 30% of its content.

In order to hide this element, You tap *"Reload with tags"*, scroll to that place (around 30% of the content), tap the proper element and choose *"hide"*. Then it reloads the article, but **the text is not necessarily placed where it was before -** it may be placed at completely different point of its content. Although it's not much of a problem, it may be confusing.

**Comment by ThomasLeigh** [comment]
I've just finished the [how-to](https://handynewsreader.blogspot.com/2019/07/pure-reading-experience-next-step.html) dedicated to this feature.
