### ISSUE TITLE
Those labels ("Settings" and "Feeds") are constantly in English.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#248]
Regardless of *HNR* UI language change, the labels of Settings (a gearwheel icon) and Feeds (a pencil icon) remain unchanged (= still in English). Translations on *Crowdin* seem to have those labels already translated.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.0

**Comment by ThomasLeigh** [comment]
Thank You.
