### ISSUE TITLE
Unexpected black background.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#249]
Here You are a screenshot from *HNR* with light theme. I'm not sure if the black elements should be black? If they are hyperlinks - they look differently than I've set it up (My hyperlinks are green).

![Full article view - light theme](https://user-images.githubusercontent.com/26142231/58736239-6bcbe580-83fd-11e9-85ec-2f5017042fd8.png)

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/0.9.2

**Comment by ThomasLeigh** [comment]
It is fixed now, thank You. In the meantime I've noticed similar issue within dark-theme, both custom or standard - could You fix it too?

![Screenshot (Jun 16, 2019 19_55_25)](https://user-images.githubusercontent.com/26142231/59567688-19cbc680-9071-11e9-982b-8894529735ab.png)

**Comment by yanus171** [comment]
Try to uncheck Settings, Theme, Common settings, Custom font colors, reopen the article and show me a screenshot again please

**Comment by ThomasLeigh** [comment]
Here You are:

![Screenshot (Jun 17, 2019 22_13_18)](https://user-images.githubusercontent.com/26142231/59633698-5ec52b00-914d-11e9-98e3-f813953b8cf6.png)

**Comment by SIRSteiner** [comment]
@ThomasLeigh Is this bug gone?

**Comment by ThomasLeigh** [comment]
Currently I can’t tell because I am not able to load this website into HNR anymore, see https://github.com/yanus171/Handy-News-Reader/issues/508 .

**Comment by yanus171** [comment]
In the black background tap reload full text menu item
