### ISSUE TITLE
No articles at feeds from "Freie Presse" since 0.8.6

### ISSUE THREAD

**Issue by SIRSteiner** [yanus171/Handy-News-Reader#250]
**Describe the bug**
No articles at rss feeds of german "Freie Presse" since release 0.8.6.

**To Reproduce**
1. Add new feed https://www.freiepresse.de/rss/rss_erzgebirge.php
2. Refresh article list -> no articles
3. Go back to 0.8.5
4. Refresh article list -> many articles

**Additional**
Issue also happens in Android Studio (Emulator)

**Comment by Goran88** [comment]
Also no articles from dw.com and theatlantic.com since 0.8.6.
https://rss.dw.com/rdf/rss-en-all
https://theatlantic.com/feed/all
Same steps to reproduce, works on 0.8.5
Thank you for the great news reader

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.0

**Comment by SIRSteiner** [comment]
Thank you it works for me with v0.9.0. @Goran88 can you confirm it?

**Comment by Goran88** [comment]
Works for me also with v0.9.0. Thank you.
