### ISSUE TITLE
Support 'Delete all' in all places.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#252]
A user request from *Google Play*:

>  pls add a feature so that i can delete all the read articles from "All Article" tab of your app. Point to be noted that "delete all" option present in your app does not working which is currently provided in "All article" tab.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/0.9.2

**Comment by AndroKev** [comment]
I think this is not done

For example i keep all articel forever so that i don't Miss any. But with this Option enabled HNR become slower and slower 

So please add an Option to delete only read articels. Even maybe automaticly?

**Comment by yanus171** [comment]
This is not option. It's an operation. You decide yourself wherever to exec it.

To delete all read articles... I should implement read /unread checkbox in 
All articles, so we could use Delete all operation there

And of cause if you're articles are stored forever HNR would work slower 
and slower over time

**Comment by yanus171** [comment]
Or another idea: add an item "Keep unread only" to the Keep time lists (per feed and in settings)

**Comment by ThomasLeigh** [comment]
> add an item "Keep unread only" to the Keep time lists (per feed and in settings)

I like this one.
