### ISSUE TITLE
Ability to hide all the blue buttons on the bottom of an article.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#254]
Now I have the impression that there is even one more buttons displayed there  (*"Reload full text"*). It could be great to be able to **turn off/hide those buttons in app's settings** (another step to have the pure text experience :) ).

**Comment by yanus171** [comment]
May be it would be better to have color settings from these buttons?

**Comment by ThomasLeigh** [comment]
It is a good idea, however it still would be great to be able to hide those buttons completely.

**Comment by Ryuno-Ki** [comment]
I'd need the „Load Original Text “ button at the very least.

**Comment by ThomasLeigh** [comment]
It could be present within app's settings, something like:

`Article text/Settings/Text Mode Buttons/Show/Hide.`

or just replace those buttons by their icons on the top bar (next to the star and share icons) - this way it won't be disturbing and there is no need to make additional settings for them (although it could be useful to allow users to choose which icons should be present on the top bar - another story).
