### ISSUE TITLE
Multiple keywords in a filter

### ISSUE THREAD

**Issue by seth100** [yanus171/Handy-News-Reader#258]
Hi,

How is it possible to specify multiple keywords in a "accept" filter?
I tried to put comma-separated keywords but it does not work.

E.g. I want to match:

```
home,Home,HOME,house,House,HOUSE,cat,Cat,CAT
```

do you also know a case insensitive regular expression I could use im this case?

Thanks

**Comment by yanus171** [comment]
Currently just its unavailable. See #146

**Comment by yanus171** [comment]
It's a dublicate of #146
