### ISSUE TITLE
View an image within an article - a strange example.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#260]
I've just stumbled upon [this article](https://techcrunch.com/2019/02/12/how-i-podcast/), in which whatever image I tap, it shows this:

![Screenshot (Jun 6, 2019 16_21_56)](https://user-images.githubusercontent.com/26142231/59041955-e7a0b480-8879-11e9-8416-16053c6f339a.png)

In case of other articles it works fine. I suppose this is not a bug, but... may be worth pointing out?

**Comment by yanus171** [comment]
Try to Reload full text

**Comment by ThomasLeigh** [comment]
Didn't help.

**Comment by yanus171** [comment]
Can you see in browser what's the filename of img tags of that page?

**Comment by ThomasLeigh** [comment]
Yes:
