### ISSUE TITLE
Rotate screen refresh issue

### ISSUE THREAD

**Issue by mrfuggy** [yanus171/Handy-News-Reader#261]
The selected and opened feed is closed when you rotate the screen. After that, feeds update starts immediately.
In the horizontal orientation, you have to open the channel again.

Expected behavior:
The selected and open feed should remain open.
The second but not least, feeds update should not start after screen rotation.

OS: Android
Version: 0.8.6

**Comment by yanus171** [comment]
I can't reproduce it

**Comment by SIRSteiner** [comment]
@mrfuggy Is this bug gone?

**Comment by mrfuggy** [comment]
I think it depends on my specific Android version. Some apps do repaint after rotate.
Actually the bug persists. (Version: 0.13.4) But I blame my version of Android.
You can close the issue, if you seem it necessary.
