### ISSUE TITLE
Open link also downloads the full text

### ISSUE THREAD

**Issue by mrfuggy** [yanus171/Handy-News-Reader#262]
When you click to "Open link", the full text of the article is also downloaded.

Actual behavior:
The link is open in an external browser and HNR downloads the full text as well.

Expected behavior:
Only the link should be open in an external browser. Full text should not be uploaded.
	
OS: Android
Version: 0.8.6

**Comment by Ryuno-Ki** [comment]
Can't reproduce.

Maybe the HTTP headers are set wrong? Can you share a link?

**Comment by yanus171** [comment]
I CAN reproduce it. So I have attracted the Accepted label

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/0.9.2

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.3
