### ISSUE TITLE
OPML Import does not work

### ISSUE THREAD

**Issue by JohnPaden** [yanus171/Handy-News-Reader#265]
Issue: Import OPML files does not work
(mug - pen - 3 dot menu - import OPML)

Even exporting and re-importing the opml file from within th HNR does not change anything. 

There is a comment in another issue description about 'Checking / unckecking the opml file' - can you re-elaborate of what to do on a non rooted phone if this is a workaround?

Imho being able to import rss from other tools is critical for user adoption.

Huawei V10 - Lineageos16 - no root
HNR V 0.90 and V0.91beta

**Comment by yanus171** [comment]
Try to uncheck Settings, Advanced, use standard file manager

**Comment by JohnPaden** [comment]
Sorry, can not follow you. Lineage OS 16 - standard file manager has no Advanced settings. I use total commander, too. Any way to do this in command line?

**Comment by tasmo** [comment]
Unchecking the standard file manager option needs the opml file in the `/storage/emulated/0/feedex` directory.

**Comment by yanus171** [comment]
@JohnPaden, I mean Handy News Reader settings

**Comment by RMKD** [comment]
This worked for me.To summarize for others trying to import:
- tap the gear icon to enter Settings
- tap Advanced
- uncheck "Use a standard file manager"
- copy `my-exported.opml` into `/storage/emulated/0/feedex/`
- return to main screen
- click the pencil icon to edit Feeds
- click the three dots in the upper right and select "Import from an .opml file"

If you have your opml file(s) in the correct directory, you should get a menu that says "select a file" which allows you to select from a list of files in the feedex directory. 

It'd be great to have import as part of onboarding and/or more easily discoverable.
