### ISSUE TITLE
[user request] Reading a group improvements.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#266]
"I have a number of groups which in turn contain a number of feeds.

When I look at the group article list I can see which feed an article comes  from. If I want to see how many unread articles remain I can swipe to  the summary screen,

However, if I am reading a group by swiping to each article there is  nothing to tell me which feed the article comes from or how many unread  articles are left in the group. I would like to have this information  available as I swipe through articles (this is available in *Feed+*)

I am using a *Moto Z Play* on *Android 8.0*. using *Handy News Reader 0.9.0*.

Regards,
Tony"

**Comment by yanus171** [comment]
I suppose we should move the Delete issue to #252 and rename it to support Delete all in all places

**Comment by ThomasLeigh** [comment]
@yanus171 

> I suppose we should move the Delete issue to #252 and rename it to support Delete all in all places

Done.
