### ISSUE TITLE
[user request] Entries kept time seems not to be working.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#267]
"The *‘Time that entries will be kept’* option under the *‘Automatic refresh’*  menu does not appear to be working. I have this currently set to two days,  however, I still see Read articles that are over 1 week or more old after I  do a refresh.

NB: this function should retain starred and unread articles.

I am using a *Moto Z Play* on *Android 8.0*. using *Handy News Reader 0.9.0*.

Regards,
Tony"

**Comment by Ryuno-Ki** [comment]
I can observe a similiar pattern. However, for me it is about too many feeds -> OOM after about 22MB of download.
Then, when I updated a single feed (instead of all), it will remove old articles of all feeds after the single feed was updated.

@ThomasLeigh Do you see the hint, that old articles were removed when updating?

**Comment by ThomasLeigh** [comment]
@Ryuno-Ki 

Is it really a question for Me, or maybe You'd like to ask _Tony_?

**Comment by yanus171** [comment]
Why Tony can't participate himself here?

**Comment by yanus171** [comment]
And this function retain only starred articles. Unread are removed.

**Comment by yanus171** [comment]
And we should not forget about feeds custom keep time

**Comment by yanus171** [comment]
And one more exclusion: the old articles are not deleted during FIRST Refresh after feed creation or after Delete all articles operation

**Comment by ThomasLeigh** [comment]
@yanus171 

> Why Tony can't participate himself here? 

Not everybody has the will to engage with *GitHub*, whereas I have the will to take every opportunity to make *Handy NR* the best app :) .

In such case in which a user provides feedback through the *HNR* website, I create *GitHub* threads for it and invite this user to participate.

**Comment by Ryuno-Ki** [comment]
> Is it really a question for Me, or maybe You'd like to ask _Tony_?

Who's Tony?

> Not everybody has the will to engage with _GitHub_, whereas I have the will to take every opportunity to make _Handy NR_ the best app :) .
> 
> In such case in which a user provides feedback through the _HNR_ website, I create _GitHub_ threads for it and invite this user to participate.

I have heard about pages, who offer a form on their website, which will create GitHub issues in the background…

**Comment by ThomasLeigh** [comment]
@Ryuno-Ki 

> Who's Tony?

Tony is a user who sent Me this request, which then I published here.
