### ISSUE TITLE
[user request] Open an image results in blank screen.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#268]
*Handy News Reader* allows me to open an image in my Gallery app (currently *Simple Gallery* from *F-Droid*).  This is a great feature that a number of  other RSS readers cannot do (*Feed+* does this also).

Sometimes when I click on an image to open it in Gallery the screen goes  blank (or dark) - the tap zones remain visible as does the progress bar, If I scroll to the previous article or the next article and back again the  screen remains blank. However, if I view the read version of the article,  the image loads normally in the gallery app.

I have been able to replicate this behavior on other gallery apps.

I am using a *Moto Z Play* on *Android  8.0*. using *Handy News Reader 0.9.0*.

Regards,
Tony"

**Comment by yanus171** [comment]
May be it corresponds to special feed (s)?
