### ISSUE TITLE
Non-RSS articles periodically repeat themselves.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#27]
In case of **non-RSS websites** articles are repeat themselves once for a while. It seems that _Handy_ doesn't remember that they have been read.

It looks as follows: let's say that I have three new articles from a non-RSS website. When I finish reading them, they are marked as read as it should be. But after some time (hard to determine - a couple of days?) **those same articles pop up as new**, regardless of how many ***real*** new articles from this particular website has been published.

This issue is only about non-RSS websites.

It seems those non-RSS websites just don't be updated so often - so those articles are constantly present on those websites, but _Handy_ shows them once in a while as new, regardless of marking them as read.

**Comment by SIRSteiner** [comment]
Does this problem still exist? If not, please close, because I think that due to the large number of issues it is difficult for @yanus171 to work through everything.

**Comment by ThomasLeigh** [comment]
Yes, it does still exist.

**Comment by rqkeating** [comment]
Are links to YouTube considered "non-rss"?  I've noticed old Youtube posts showing up even though I've marked all read.  I was going to open a bug on this, but after looking through the list, this bug may cover my issue.

**Comment by yanus171** [comment]
Give me a link to feed

**Comment by rqkeating** [comment]
I don't think it is tied to any one link, but here is one.

This channel been in my feed for a long time.  Everyday I mark all feeds read even if I haven't viewed them.  This particular video  showed up as unread this morning.  [https://www.youtube.com/watch?v=8vIbbAbPqDE ](https://www.youtube.com/watch?v=8vIbbAbPqDE) It was released 4 weeks ago yet shows up today as unread.

I thought maybe this was being triggered by someone commenting on the video, but the last comment (as I am writing this) was 5 days ago.

Let me know if I can be of more help.  Thanks.

**Comment by ThomasLeigh** [comment]
The very same thing I experience for a long time now, fingers crossed it can be worked out.
