### ISSUE TITLE
Changing article font size requires re-opening it to see the changes.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#271]
1. Open any article,
2. Open the menu (top right corner), choose *"Settings ➜ Article's text ➜ Text size"*.
3. Change the font size and go back to the article.

In such a case **I don't see any difference**. In order to see it I need to leave the article and open it again.

Could the font size be applied right away?

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.4

**Comment by ThomasLeigh** [comment]
Thank You, it works now.
