### ISSUE TITLE
Improve sharing text feature.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#273]
I observed a very interesting thing. I use *Microsoft To-Do* as a notepad to collect various things (not only tasks to do - but various ideas, quotes, and so on). Besides I use *MoonReader* to read e-books.

I often share an interesting piece of selected text to the *Microsoft To-Do* app. A single item within this app has several fields. Besides the main field with an item name there is, for example, a field called *Add a note*.

And now: if I share selected text from *MoonReader* (or *CoolReader* which I used earlier on) - **it saves the book title as a content of the main field, while the actual quote (the text I've selected) is saved within a field for notes.** It was a very nice surprise that every time I save a quote this way - there is the book title automatically attached, so I always know, from where the quote is. And, moreover, the quote and the book title are separated (separate fields) - so **it is more readable**.

I wonder could a similar thing be done within *Handy NR*? Now the same procedure results only in saving the text as a content of the main field (a note field remains empty).

**Comment by Ryuno-Ki** [comment]
Would break my usecase of todo.txt, where every line makes a separate note.

**Comment by ThomasLeigh** [comment]
Alternatively an article's title and link could be attached at the end of the (shared) text. An ideal solution would be to choose (in settings) which variant of sharing a user would prefer (the one with separate content placed into separate fields is very handy and it would be a great loss to skip it).

It could be done as follows:

*Settings/Article's text/Sharing Mode*

> **feature name:** Sharing Mode  
**feature description:** Share Selected Text Mode

Tap on *"Sharing Mode"*, then You will see two options to choose:

1. *Article's title and link attached to the shared text.*
2. *Article's title and shared text placed into separate fields.*

**Comment by Ryuno-Ki** [comment]
Hm, not sure, whether making _everything_ configurable is that good of a software architecture.
I mean, debugging will become harder, because the matrix of possible combinations increases exponentially.

Maybe it's worth to take a clear stance and reject certain opinions?
Can't tell, because I'm only an user here.

**Comment by ThomasLeigh** [comment]
I think about what could be useful and handy for users - not developers. Ultimately we could stay at one particular way to handle shared text - but it will result in lowered user-experience. I don't think that providing those details would decrease the app performance in a significant way. Either way, however, one could ask which app describing adjective is more important: fast or useful? I strongly believe that *Handy NR* still may be fast **being surprisingly useful** in the same time. Of course not everyone could want their app to be **surprisingly** useful - I am the one who prefer it above all. Thanks to this and *Alexey's* will - we have already the app which I find incredible. But this is not the end, Folks :) .

**Comment by Ryuno-Ki** [comment]
I am not against your suggestions!
Just want to highlight, that they come with a cost.
I hope, the request won't turn HNR into an unmaintainable mess so @yanus171 would drop the project.

Would it might be an option, to have the formatting done in another app, for example?
Yeah, not optimal. But this way you could have the core app smaller.
Or via plugins (I know, termux allows you to extend its functionality by installing additonal applications from the app store).

Just want to stress, that not everything has to / should be implemented in the „core”.

**Comment by yanus171** [comment]
It is not a problem to add one more preferences to advanced category and a 
few lines in code. But I don't know yet how to send such intent (share) to 
other apps...

**Comment by Ryuno-Ki** [comment]
Hm, I was thinking along the lines of [Share to Clipboard](https://f-droid.org/packages/com.tengu.sharetoclipboard/) or [Copy to Clipboard](https://f-droid.org/en/packages/se.johanhil.clipboard/). Should be small enough to get an idea on how to use the share intent and then do other stuff with it.
