### ISSUE TITLE
Some feeds brought back articles from well in the past.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#274]
***Tony*** has reported another thing:

> "When I did a refresh today some feeds brought back articles from well in the past., From [this address](https://feeds.megaphone.fm/PP3921129017) there were well over 600 articles (from June 2014). This outcome was not replicated in *Feeds+*. NB: when I use *Delete All* the status of the feed is set to *Never Updated* - I do not know if this is related."

**Comment by b16r05** [comment]
I know Flym did not have a way to control this. Flym displays articles published MAX from the last 7 days. I am still learning my way around feature-rich Handy. Is there a way to control this? 

For me, it is nice to be able to see everything (ALL) from some websites (like blogs), but not others (one has upto 473 pages : ) This might be out of scope, but, maybe, having a per feed setting is a good idea in addition to global setting!

**Comment by yanus171** [comment]
It's already implemented. Long tap on feed, Custom keep time
