### ISSUE TITLE
Make it possible to just use wifi and not mobile data

### ISSUE THREAD

**Issue by rimugu** [yanus171/Handy-News-Reader#277]
I would like to be able to use Handy without data (it expensive when you are in international roaming). Let it refresh/update on wifi, but when I am out of wifi and read the articles, not load anything on data.

A setting just for that to avoid confusion would be nice.

I have tried settings in automatic refresh, refresh only over wifi, preload only over wifi, max image size 1 Mb, max single refresh traffic 1 Mb (perhaps setting this to 0Mb does what I want?!) But still has used 43Mb in the last 15 days.

Using version 0.9.2

**Comment by yanus171** [comment]
Did you try to turn off mobile data in roaming?

**Comment by rimugu** [comment]
I need to have mobile data while roaming, I just would like to use that for the inevitable (like work apps).  If there were an option for handy I could read news offline while roaming without fear of incurring on non reimbursable charges.

**Comment by yanus171** [comment]
You can setup this in app system settings for HNR

**Comment by rimugu** [comment]
Could you tell me were in HNR?

**Comment by yanus171** [comment]
It's depend on your Android version. What is it by the way? Go to phone 
system settings, apps settings, Handy News Reader, traffic,... Limit,...

**Comment by rimugu** [comment]
Sorry, I thought you meant inside HNR. I will check on my data saver settings. Thanks

**Comment by xandro0777** [comment]
You can also use the netguard app to control what apps can use data roaming
