### ISSUE TITLE
Handy NR Press

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#278]
I've just done [this short post](https://trailofthelight.blogspot.com/2019/06/meet-your-ultimate-dream-magazine.html), wondering does anybody of You has similar associations (e-zines)?

**Comment by Ryuno-Ki** [comment]
Sorry, I can't read your blog without JavaScript :-(

After granting permissions to it, the content reminded me on paper.li ([example](https://paper.li/smallbiztrends#/)).

The „problem” today is, that you get *too much* content, so processing it is hard.

Some people experimented with alternative approaches [like one-share-per-day](https://www.niemanlab.org/2016/07/the-share-one-link-per-day-platform-this-is-shutting-down/), but ultimately failed.

I don't see, how HNR can help you here. Maybe with stats on reading time per day… but the conclusion has to be done by you.

**Comment by yanus171** [comment]
And thats one if the big problems today, that people can't read long texts anymore. They just want to see high speed changing pictures. In many cases its impossible to transfer interesting things to others minds in a few words. And although I don't know what is e-zines, after reading this post I seem to have felled the spirit of the post. And that spirit can't be delivered in a few words.

**Comment by yanus171** [comment]
By the way one if main purpose of Handy news reader is to reveal a perl in tons of rubbish to be enjoying it for long time from begin to end without disturbing.

**Comment by yanus171** [comment]
And I always thought that you were younger than me, Thomas. I was mistaking :)

**Comment by ThomasLeigh** [comment]
> after reading this post I seem to have felled the spirit of it. And that spirit can't be delivered in a few words.

I personally like reading, but for various reasons it became harder over the time to read as much as years ago. But I still believe it is possible on a scale which won't be sad - so I've decided to motivate Myself a little bit by using a habit tracking app (*HabitHub*) **to encourage Myself to read at least one hour per day**. Not every day I manage this, but more often than not - and this I consider a success.

> one if main purpose of Handy news reader is to reveal a perl in tons of rubbish to be enjoying it for long time from begin to end without disturbing.

Oh, I love that `*.*` . This is the reason why I've associated this app with e-zines from the past: for Me *Handy* is much more than an *RSS* reader - **I consider it *My Dream Magazine*** because of what You've pointed out: this carefully derived "perl". And it has a significant advantage over the past experience: that **I can enjoy it all the time**: whenever I reach for *Handy* - it constantly provides Me with many articles **with the high probability that they will be interesting for Me**. This is also the reason I enthusiastically await for *the rejecting filter* :) - the last piece which can make a huuuuge difference in terms of content clarity/pureness/fitness/You name it.

The other day I invented a new idiom:

## ***read Handy***

:) . **Have You read Your Handy yet?**


> And I always thought that you were younger than me, Thomas. I was mistaking :)

Funny thing, I thought the same of You :) . So You haven't experienced analog modem connections :) ?

**Comment by Ryuno-Ki** [comment]
> So You haven't experienced analog modem connections :) ?
Oh Gosh, what that makes to me when I know that?
But I skipped the Gopher and usenet stuff …

**Comment by yanus171** [comment]
I used modem connections, but not so actively for it was a bit expensive that time
