### ISSUE TITLE
No pictures displayed.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#280]
[Here](https://www.wired.com/story/life-without-exclamation-points/) is an example in which *Handy* does not load some images (the very first image in the article **is visible** in *Handy*). I tried *Reload full text* or *Load all images* - to no avail. This is how it looks:

![HNR No Pic](https://user-images.githubusercontent.com/26142231/59975791-5ab96300-95bc-11e9-9b3c-c8bc5f009a6f.jpg)

**Comment by yanus171** [comment]
Can you confirm this bug on the latest app version?

**Comment by ThomasLeigh** [comment]
Yes, it still exists in v.0.9.3.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.4

**Comment by ThomasLeigh** [comment]
The issue still remains.

**Comment by yanus171** [comment]
Did you try to enlarge the max image size pref?
