### ISSUE TITLE
Rename "External Links" into "Read it later".

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#282]
The newest release finally encouraged Me to give a try to the *Read it later* feature. It astonishes Me...

This time, however, I'd like to point out that whenever I tap on *Read it later* (after tapping on a link), the article lands within so-called *External Links*. I think **it could be much more intuitive** to rename it into *Read it later*. Wouldn't You mind?

**Comment by yanus171** [comment]
Let's try.

**Comment by ThomasLeigh** [comment]
I've updated translation files.
