### ISSUE TITLE
Enable/disable the "brightness update time" feature.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#283]
My text brightness level is usually different than the one I use on the _Android_ - could You please make possible to enable/disable this feature?

**Comment by yanus171** [comment]
When I get outdoors after reading indoors and turn on my phone screen  the HNR brightness level is too dark (until I switch to other app), so I introduced that function.

To disable it just enter some BIG number in that setting

**Comment by ThomasLeigh** [comment]
Will it be using more battery counting down this big number?

**Comment by yanus171** [comment]
No

**Comment by ThomasLeigh** [comment]
@yanus171 Wouldn't You mind to add an option to disable this feature by checking or unchecking something? It would be more intuitive for average users than entering a huge number.

**Comment by yanus171** [comment]
It would be intuitive to most users not to bother with this feature. It's 
default value needs to be changed in very few cases

**Comment by ThomasLeigh** [comment]
> It's default value needs to be changed in very few cases

I don't think it is so rare occurrence one would need to maintain a separate brightness level with the reading app - especially given that this is totally different case than other apps which display much different kind of data on the screen than mostly text.

**Comment by yanus171** [comment]
Seems like I don't understand you. Try to use some other words please

**Comment by ThomasLeigh** [comment]
@yanus171 

**I think that one brightness level may be not universal**, because the content of Your smartphone screen may vary pretty much. Compare *picture viewing* with *text reading*, for example: it may be that You could prefer separate brightness level for each of those cases.

I mean that the brightness level which I use for picture viewing may be not the optimal one for text reading. And this could be the reason for some users prefer to maintain a separate brightness level for *Handy*. In such a case it would be good to provide them with an intuitive way to disable automatic brightness restoration after xxx time span.

I'm not sure if I render this clearly enough, bear with Me and let Me know.
