### ISSUE TITLE
Иногда не загружаются картинки, много

### ISSUE THREAD

**Issue by Penelopen** [yanus171/Handy-News-Reader#284]
Как-то давно заметил проблему, что иногда выходишь утром в метро, связи нет, достаёшь телефон, а там много загруженных статей, но нет картинок. Сначала я подумал - глюк, ничего страшного.. Потом ситуация повторилась. Потом ещё. И сегодня мне удалось лицезреть, как этот глюк случился:

Еду в метро, появилось LTE, жму "обновить" - началась загрузка 1/250 статей и побежало вверх. Загрузка статей закончилась и началась загрузка картинок 1/970...2/970...3/970... ~ 106/970...107/970... и связь пропадает. Пишет "Установка соединения" и стоит на месте... Связь снова появляется и процесс продолжается 108/970...109/970...110/970... и связь снова пропадает и пишет "установка соединения". После чего бац и перечисление (якобы загрузка) картинок от **111**/970 до **970**/970 проходит буквально секунд за 10 и всё. Приложение завершило обновление. В итоге большинства картинок так и не загрузилось.

Вот собственно здесь думаю есть смысл какую-то паузу сделать или окно с подтверждением "подождать/отменить"?

**Comment by Dreamer-4pda** [comment]
У меня вообще только при открытии статьи начинают подгружаться картинки. При этом текст статьи дёргается, пока все не загрузится.

**Comment by Penelopen** [comment]
У меня тоже. Это если просто открыть новость. Тогда она загружается и дёргается... Но если нажать кнопку "обновить", тогда начинают загружаться ВСЕ статьи
null

**Comment by yanus171** [comment]
@Dreamer-4pda проверьте стоит ли в настройках ленты галка Загружать картинки при автоматическом обновлении, а также общие настройки автоматического обновления

**Comment by yanus171** [comment]
@Penelopen если обновление прервано, то следующее обновление должно загрузить оставшиеся картинки. (Только если между обновлениями не была нажата кнопка Отменить обновление)

**Comment by Dreamer-4pda** [comment]
> @Dreamer-4pda проверьте стоит ли в настройках ленты галка Загружать картинки при автоматическом обновлении, а также общие настройки автоматического обновления

Да, все настроено и включено. Удалил все картинки из папки feedex для чистоты эксперимента.
Нажимаю "обновить" и ничего не загружается. Спустя пару автоматических обновлений все также.
Если открыть статью то картинки подгрузятся для неё и для одной следующей.

Началось это после обновления до версии, где можно открыть изображение из статьи как картинку.
Файлы стали загружаться с расширением png и пришлось добавить в папку файл .nomedia, чтобы андроид не индексировать их в медиатеку.

**Comment by yanus171** [comment]
Пишите мне файл автоматической резервной копии, там есть раздел с 
настройками. Можете его одного вырезать. И ещё можно попробовать стереть 
данные приложения. И попробовать удалить файл nomedia.

**Comment by Dreamer-4pda** [comment]
Стереть данные не вариант, т.к. много непрочитанных статей за прошлые месяцы.
Убрать nomedia попробую.
Файл бэкапа прикрепил.

[feedex.zip](https://github.com/yanus171/Handy-News-Reader/files/3329199/feedex.zip)

**Comment by Dreamer-4pda** [comment]
Игры с nomedia не повлияли на проблему.

**Comment by Dreamer-4pda** [comment]
Поправка.
Для новых статей всё загружается, а для старых нет.
Т.е. приложение не проверяет есть изображение в кэше или нет.
Нужна кнопка "перезагрузить все картинки"

**Comment by yanus171** [comment]
Эта операция будет ОЧЕНЬ дорогой

**Comment by Dreamer-4pda** [comment]
Дорогой для безлимитного трафика интернета?
Или для свободного места в памяти?
В принципе, если бы статья не дёргалась, как эпилептик, при подгрузке картинок, то я бы и не парился о предварительном скачивании.

**Comment by yanus171** [comment]
Эта операция будет ОЧЕНЬ долгой

**Comment by Dreamer-4pda** [comment]
Это понятно :)
Ну что же, буду ждать исправления эпилепсии при подгрузке картинок.

**Comment by yanus171** [comment]
Дождались  https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.4

**Comment by Penelopen** [comment]
Вот спасибо большое! Еще бы решить проблему с "поделиться" через самсунговскую галерею...)))В данный момент получается делиться только так: фотография-поделиться-email-открывается стандартное почтовое приложение (родное самсунговское, не gmail)-в письмо вкладывается нужное изображение-нажимать на вложение-снова открывается эта же картинка-опять нажимаю поделиться-и уже если поделиться из почты, то нормально все отправляется в вотсап и куда угодно..
-------- Исходное сообщение --------От: yanus171 <notifications@github.com> Дата: 21.07.19  16:57  (GMT+03:00) Кому: yanus171/Handy-News-Reader <Handy-News-Reader@noreply.github.com> Копия: Penelopen <silapil@yandex.ru>, Mention <mention@noreply.github.com> Тема: Re: [yanus171/Handy-News-Reader] Иногда не загружаются картинки, много (#284) Дождались  https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.4



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/yanus171/Handy-News-Reader/issues/284?email_source=notifications\u0026email_token=AMCUVBWQN4NCXGLZCTUDGRLQARTOHA5CNFSM4H23RHQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2OECXA#issuecomment-513556828",

"url": "https://github.com/yanus171/Handy-News-Reader/issues/284?email_source=notifications\u0026email_token=AMCUVBWQN4NCXGLZCTUDGRLQARTOHA5CNFSM4H23RHQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2OECXA#issuecomment-513556828",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by yanus171** [comment]
Т.е. дергания ушли? С самсунгом я знаю, что делать, но это не раньше осени

**Comment by Penelopen** [comment]
Дёргания только утром проверить смогу
null

**Comment by Penelopen** [comment]
Хотя не, проверил сейчас. Включил режим 3G, отключил wifi, открыл новость https://bigpicture.ru/?p=1170236И картинки начали грузится по одной-две. Таким образом, комфортно пролистывать вниз не получалось, потому что грузились новые картинки.. или не об жтих дёрганиях речь?
null

**Comment by yanus171** [comment]
Обновление должно стучаться не более раза в секунду. При загрузке всех 
картинок статьи идеальной плавности даже браузер добиться не сможет... 
Вообщем в вашем случае нужно разбираться с автоматической загрузкой картинок..

**Comment by Penelopen** [comment]
Да меня это и не напрягает даже)) просто хотел помочь проверить новые плюшки))
null

**Comment by Penelopen** [comment]
Хорошие новости! "Поделиться" заработало на Самсунге  теперь галерея не выдает ошибку. Заметил новую проблему - Особое время хранения новостей не работает. У меня куча новостей есть аж от 30 июля. На этом канале установлено особое время хранения 2 дня... А они до сих пор не удалены. Синхронизации подходят нормально
null
