### ISSUE TITLE
Make "Auto unstar when finished reading" more accurate.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#286]
This is one of My favorite *Handy's* features - highly useful while reading *Favorites*. There is one thing which prevent it to work in a desirable way: it unstars an article the moment **its very bottom** has been reached. There are, however, plenty of times when automatic page scrolling will lead to to the end of the article - **but not its very (technically-wise) end**. You may see the end of the text and blue buttons always present there - so You are sure that this is the end and there is nothing to scroll further - but **still You need to do it one more time** if You want the article to be unstarred automatically.

It would be much better if an article could be auto-unstarred **while reaching its last page of text** - instead of its very bottom per se. "The last text page" would mean the one in which blue buttons are positioned within **the bottom half of the screen**.

Could anything be done to improve this fantastic feature in order for it to act more accurately, i.e. without forcing a user to scroll till the very end?

**Comment by yanus171** [comment]
What will be after implementing #254 where would be no buttons?

**Comment by ThomasLeigh** [comment]
I think the issue will remain, the question is could we detect **the last bottom half of the last article text page**? Then it could act better.

**Comment by yanus171** [comment]
I suppose it's time for screenshot :)

**Comment by ThomasLeigh** [comment]
What exactly You'd like to see?

**Comment by yanus171** [comment]
I can't understand why we should unstar the article if some half of screen is not read yet.

**Comment by ThomasLeigh** [comment]
.> I can't understand why we should unstar the article if some half of screen is not read yet. 

Imagine this: You are reading an article, after a while You notice that You've reached its end, because You see blue buttons on the bottom (or in case there are disabled in settings - You've read the article's last words definitely signifying that this is its end).

In such a situation it's obvious for You that there is nothing to scroll further, there would be no sense to do so. **But** this is not a rare case in which in the same time **You don't reach the very bottom of the article** which is currently the only point to trigger auto-unstar action. So, in order to benefit from it You have to scroll one more time - regardless of that You don't have a reason to do so, text-wise.

This is the reason that I would propose for auto-unstar action to be triggered not only by reaching this very very end of the article page (which not always occurs in pair with the last page of the article's text You've naturally scrolled) - but by last half of text page, or something like that. I would welcome any way which could be less restricted that the very bottom of the article, since the very bottom of the article is not always reached by the last scroll move leading to the last portion of the text.

**Comment by yanus171** [comment]
Try it https://drive.google.com/file/d/11SpmsE-gGEDbrPDLkgeOuapgF0YNpuEk/view?usp=drivesdk

**Comment by ThomasLeigh** [comment]
**F-A-N-T-A-S-T-I-C!!!** Works like a charm, thank You very much, it's much much better now.
