### ISSUE TITLE
Can't add a new feed to a group.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#287]
I just wanted to add a new feed and, to My surprise, I've noticed that I can't check a "group" box in order to add this feed to a group. **The check box can't be checked** even if I don't paste anything within the feed address.

**Comment by yanus171** [comment]
It's because of brightness swipe. Tap on the text Group, not on the the square.

**Comment by ThomasLeigh** [comment]
I think this text is too short to be tappable. :(

**Comment by ThomasLeigh** [comment]
@yanus171 
Maybe temporary decreasing Tap Areas' size could help, but would You make this screen (add a feed) not be affected by Tap Areas at all? It could save the unexpected trouble for users, not everyone will come to this idea how to solve this (= "connects the dots").

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.4

**Comment by ThomasLeigh** [comment]
It works now, thank You.
