### ISSUE TITLE
Articles and articles list using URL shows social media and other items

### ISSUE THREAD

**Issue by b16r05** [yanus171/Handy-News-Reader#288]
**Describe the bug**
URL websites with filters, tabs and footers produce uneven, duplicate and bogus articles. In place of dates and time, sometimes, no month and just, time and size are displayed. 

**To Reproduce**
Add these sites: 
1. https://www.ally.com/do-it-right/ [filters produce issues]
2. https://www.bankrate.com/financing/feed/ [available here: https://www.bankrate.com/finance/rss-directory.aspx]

**Expected behavior**
Clean articles list and no duplicate footers or social media... twitter, Instagram, Facebook and other items. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
Tablet running LineageOS... android 16... Pie.

**Additional context**
I think because these websites don't provide a dedicated RSS feed, parsing the URL in just one way, is not going to work perfectly for all sites. I am not sure where and how to make edits to get the list displayed with just articles, no social media and no extra footer information.

**Comment by ThomasLeigh** [comment]
@b16r05 

Try [the newest *Handy NR* release](https://github.com/yanus171/Handy-News-Reader/releases), load an article and choose from the menu (top right) *"Reload with tags"*. After a while You should see the text with many colored tags. You can tap on tags which contain unwanted parts of content (like social media) and hide them. You can also choose which tag refers to the actual content of the article (setting it as the root).

**Comment by b16r05** [comment]
I appreciate it. It is not easy going through these. I don't understand -- some of tags are highlighted and others are not. Also, correct me, but when I select this option (hide) for an article it applies to the feed URL, but is not global, so other feeds are not affected. I have made changes and been running it for 3 days now. 

Do new articles get affected?
I have manually deleted some of the legalese, header, footer, social media (twitter, facebook, instagram, etc.) "articles"... I hope they don't show up again as articles.

**Comment by ThomasLeigh** [comment]
@b16r05 

> some of tags are highlighted and others are not

This one I also don't know the answer - maybe @yanus171 will help?


> when I select this option (hide) for an article it applies to the feed URL, but is not global, so other feeds are not affected.

I think it is global feature, because all the hidden tags land within ***"settings/Advanced/Remove text rules"***, so it should affect all the feeds. Please let us know if the feature covers all Your feeds, not only a single one.


> Do new articles get affected?

Yes, and also those which have already been loaded - but in this case You need to apply *"Reload full text"* command from the menu while reading such an article. In case of future (new) articles after You've set some parts to hide - they should be already clear of those parts.

**Comment by yanus171** [comment]
Hide rules applies globally to all new articles, Root context applies to 
new articles of that web page domain. You can see the current rules in 
settings - advanced - Content extract rules and Remove text rules.

**Comment by b16r05** [comment]
Okay, thank you both. There is a little bit of a learning curve. I will carefully make changes and note what I am doing. I am pleased how it applies to old articles and new ones coming through the feed.
