### ISSUE TITLE
Allow to confine search feature to a single group of feeds.

### ISSUE THREAD

**Issue by RAMAR-RAR** [yanus171/Handy-News-Reader#289]
Research of an article focused on a rss or a group.

**Comment by yanus171** [comment]
Explain it more please

**Comment by RAMAR-RAR** [comment]
When I search an article search in the entire list of rss, but I believe that should more comfortable that if you have selected a group and search in the group.

Ex. 
-If I search an article in "All articles" the search engine search in the entire list of rss

-If I have selected  "Group 1" and I search an article the search engine search in "Group 1"
