### ISSUE TITLE
Get ALL articles from a feed

### ISSUE THREAD

**Issue by b16r05** [yanus171/Handy-News-Reader#290]
**Is your feature request related to a problem? Please describe.**
I don't think so.

**Describe the solution you'd like**
I want to be able to retrieve all articles from a feed, but maybe limit it to number of articles or by date (no earlier than...).

**Describe alternatives you've considered**
One idea is to edit the URL using php type code` /?page=2` , then change to 3, 4, 5, etc. but is intensive and takes time to go through a lot of pages.

**Additional context**
None.

**Comment by b16r05** [comment]
Some ideas here: https://stackoverflow.com/questions/576552/how-do-i-fetch-all-old-items-on-an-rss-feed

**Comment by yanus171** [comment]
Didn't find any ideas there

**Comment by yanus171** [comment]
If you don't clear HNR data all loaded articles are kept (corresponding to keep old settings)

**Comment by yanus171** [comment]
If you want to grab all site articles you can use feed with Web type.

**Comment by yanus171** [comment]
We can introduce some special key in web page url, indicating that we need to load all links (articles) from range of urls. For example www.articles.domain?page={#1..#20}. (it's not implemented yet)

**Comment by b16r05** [comment]
Okay, that sounds good. Thank you and I will look out for this feature in a future release. 

I see what you did with the URL code... nice! 

I am just curious, how it going to work if pages use a different format, for example:

www.website.com/articles/page/1/
www.website.com/articles/page/2/
www.website.com/articles/page/3/

**Comment by yanus171** [comment]
There is an opportunity in https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.0 to load pages recursively via setting class name for the "Next" button
