### ISSUE TITLE
Use googleweblight to speed up getting full text

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#292]
googleweblight is a (not transparent) proxy that reduces complex/heavy html pages to lightweight mobile pages

Example: https://googleweblight.com/?lite_url=http://www.sueddeutsche.de/bayern

Could be highly useful to retrieve full text of articles or parse html only pages.

Should probably be configurable on a per feed setting.

 Does not work for all sites but the failure can be easily detected.

**Comment by yanus171** [comment]
The manual setting of Text root and Hide elements for web page domain in Reload with tags mode should work well for all cases and gives more control especially in ads remove tasks. 

Do we need to increase the complexity of app management by using  the third party tool that is always subject to changes?

**Comment by xandro0777** [comment]
I hope to save significant bandwidth with it.

It may always change but as long as it works it does produce usable output for many websites out of the box without specifying text root and hide elements separately. If it changes chances are finding a new suitable text root will be easier than for nzz.ch and again work for all sites that goigleweblight supports? 

So as an option it would be great to have.

**Comment by yanus171** [comment]
Bandwidth argument is sensable. And what about adds in Google web light? 
Does it has any limitations? May be limit on requests count per day or hour?

**Comment by Ryuno-Ki** [comment]
I'd like to have a way to tell HNR to not use Google services if possible.

**Comment by xandro0777** [comment]
As of adds, I have never seen any perhaps because I use some add blocker;) 

Yes,  google weblight should be clearly optional for "philosophical" and technical reasons.

**Comment by xandro0777** [comment]
Have not experienced any limitations so far and never used it in any automated way.

**Comment by xandro0777** [comment]
FYI,  I became aware of Google weblight approximately 10 years ago at a time when Android 2.3.3 was modern, a very early version of the Zirco browser used it. Since than the URL changed once and the old one has been forwarded to the new service for pretty long time.  So while there is no guarantee it won't change or get discontinued without any warning we might be lucky another 10 years.

Google most likely uses it to track what people read - it is a tradeoff of my bandwidth vs Google tracking me or the "original" website tracking me.
