### ISSUE TITLE
Getting full text of articles from nzz.ch does not work

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#293]
Only the introduction of the article is shown, happens consistently for all articles.

**Comment by yanus171** [comment]
In the article screen menu tap Load with tags. Then try to find blue tag 
corresponding to all full text, tap on it and then Choose as text root. 
This would be applied to all NEW articles of that domain. To apply it to 
existing article select Reload full text

**Comment by xandro0777** [comment]
Thanks,  mostly works. The text is in several separate  fragments bracketed with "regwalled text", so far I only found the possibility to include the whole page and exclude unwanted parts. Would the opposite approach  somehow work - select only tags that should be included? Setting "regwalled" as root appears to include only first block?

**Comment by xandro0777** [comment]
Problem with this feed:  http://www.wettermail.de/wetter/current/wettermail.rss

There is no tag at all that would load the whole page.

Thinking there probably is.. for example  "body" or "html" but isn't selectable in the current interface. 

Also with the nzz.ch articles, "body" or "html" would be easier than any other tags that are selectable - the articles have fairly variable structure so quite a few things I tried worked only for a fraction of the articles.

**Comment by yanus171** [comment]
Resolved by #300
