### ISSUE TITLE
Per feed specific refresh settings

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#294]
It would be nice to be able to exclude some feeds from automatic refresh.

Also manual update of a single feed doesn't appear to be possible?

**Comment by yanus171** [comment]
To exclude some feeds from automatics refresh check settings - automatic 
refresh - only selected. Then in the needed feeds settings (long tap on 
feed) check /uncheck auto refresh feed.

Manual feed refresh is always available

**Comment by xandro0777** [comment]
Will manual refresh always refresh all feeds whether checked or unchecked?

**Comment by yanus171** [comment]
Yes, It will
