### ISSUE TITLE
Rename "Reload with tags" into "Clean the content" and add a short introduction.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#296]
Since this feature serves as a way to clean articles' content into the more pure form, **could we please rename it into more intuitive form**: _"Clean the content"_ instead of _"Reload with tags"_?

Additionally, we could introduce a short description on what is all about (how to use it) **the moment a user picks this feature the first time** (with a checkbox _"Don't show again"_).

Thanks to all of the above we could reach more people, **make more people aware that such fantastic feature is present in the app.**

**Comment by ThomasLeigh** [comment]
The short description I've mentioned above could be as follows:

> **To hide unwanted parts of content:**
Locate the tag (a blue-marked text) preceding a part You want to hide - tap on it and choose _"Hide"_.

> **To point out what is the actual article's content:**
Locate the tag (a color-marked text) which is the closest predecessor of the first words of the article - tap on it and choose _"Choose as full text root"_.

**Comment by yanus171** [comment]
The introduction should be as short as possible. Few users read it, 
especially if it is long.

Such need of hint tells about the lack of intuitiveness in GUI. And we 
first need to struggle with that.

Otherwise I wanted to add several short hints to different places in app or 
j just useful hints that appear periodically on app start or in some other 
way...

You touched the top of iceberg, Thomas :)

**Comment by ThomasLeigh** [comment]
The point is I've tried to make it as short as possible - or in order words: to include only the necessary information for users (especially non-techy ones) to understand the feature.

**Comment by ThomasLeigh** [comment]
@yanus171 And do You mind to rename _"Reload with tags"_ into _"Clean the content"_?

**Comment by yanus171** [comment]
Let's try to cover also the case when we want to enlarge the content by specifying the root text mode of more upper level

**Comment by ThomasLeigh** [comment]
@yanus171  Could it be _"Improve the content"_?

**Comment by ThomasLeigh** [comment]
@yanus171 Please let Me know, a kindly reminder :)
