### ISSUE TITLE
Reload with tags: cache "raw html"

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#299]
Frequently when figuring out how to extract the full text of an article I need a couple of tries. Caching the raw html between reloads would not only speed up the process but also prevent non-rerpoducible problems if the html of articles changes between reloads.

**Comment by yanus171** [comment]
What reproductive problems do you mean?

**Comment by xandro0777** [comment]
Referring to the possibility that the article html changes on server between two reloads.

Seen only once so far when the article apparently was replaced by a completely unrelated one.

**Comment by yanus171** [comment]
If the article is changed on server site we need to tag it again according 
with new strictness

**Comment by xandro0777** [comment]
I would rather prefer to see the results of my action on exactly the same data that I wanted it to apply to. New version of the article may work just by coincidence or the intended change may not work even though it would have worked on the original data and might still be useful for other articles. Such behaviour can be heavily confusing.

While at it.. might would be useful to :
* have the possibility to easily undo the "last tag related change", eg hide or setting root
* hide multiple elements without reloading..perhaps the sections can be striked through so it will be immediately visible what will be hidden.
* some kind of folding.. the strike through sections are often pretty long

**Comment by yanus171** [comment]
Done
