### ISSUE TITLE
Reload with tags: make whole page selectable

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#300]
Currently not all tags are displayed/selectable and I found no way to extract full text for some sites like http://www.wettermail.de/wetter/current/wettermail.rss

**Comment by yanus171** [comment]
Look at the source html of that feed pages. How can we distingwish the root node or determine the principle which   html elements include and which not?

**Comment by xandro0777** [comment]
I am not asking for magic. But if you reload eg http://www.wettermail.de/wetter/current/wettermails/1562936332_wettermail.html
 "with tags " you can't do it manually either.

Either don't filter tags like body or html or offer an explicit option to select the whole page as root.

**Comment by yanus171** [comment]
I show only tags with class attribute. And yes, one of the solution is to 
explicitly add root attribute with class,so we could choose all text as 
root. I am going to implement it.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.4
