### ISSUE TITLE
Allow storing of cached images on the SD Card

### ISSUE THREAD

**Issue by Septolum** [yanus171/Handy-News-Reader#302]
My phone's internal storage is rather limited, and the cached images take up a non-trivial amount of it

An option to store the cached images from (full) articles on the sd card instead of the internal storage

**Comment by yanus171** [comment]
Yes, It can be implemented. The only difficulties is to move cache files in case of changing such a setting

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.4

But there can be problems with permissions on the latest Android versions. See https://www.titaniumtrack.com/kb/titanium-backup-kb/titanium-backup-troubleshooting.html#sdcard-issues for example

**Comment by ThomasLeigh** [comment]
It displays following message:

![Screenshot (Jul 21, 2019 02_46_08)](https://user-images.githubusercontent.com/26142231/61590293-ff789180-abb6-11e9-85f0-374f4aa28254.png)

I suppose that it has to do with permission to access SD-card, but I couldn't find such permission to enable within the app's permission list on *Android*.

Another interesting thing is that **the path visible in the message is completely different than the path I've entered into the settings**.

I use _Android 6_.

**Comment by yanus171** [comment]
If I have no access to custom path specified, I try to use default cache folder

**Comment by ThomasLeigh** [comment]
Ok.
 
 So do You want to offer this feature only for those users who have access to SD-card without granting permission?
 
 Or in other words: could *Handy NR* ask for those permissions, allowing users to choose what is "SD-card" in order to grant them? (I see similar scheme in various other apps when it came to use external storage)?

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.10.0

**Comment by ThomasLeigh** [comment]
Thank You :) !
