### ISSUE TITLE
SD-card backup cannot be done.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#307]
It displays following message:

![Screenshot (Jul 21, 2019 02_46_08)](https://user-images.githubusercontent.com/26142231/61590293-ff789180-abb6-11e9-85f0-374f4aa28254.png)

I suppose that it has to do with permission to access SD-card, but I couldn't find such permission to enable within the app's permission list on *Android*.

Another interesting thing is that **the path visible in the message is completely different than the path I've entered into the settings**.

I use _Android 6_.

**Comment by yanus171** [comment]
Move it to #302 please
