### ISSUE TITLE
"Malicious" js is able to open phone page

### ISSUE THREAD

**Issue by 0x696c4f** [yanus171/Handy-News-Reader#308]
**Describe the bug**
Webpages/JS are able to open the phone page repeatedly (where you only need to click "go" to call someone) , which can cause a non responding phone (you won't even be able to open settings) and you aren't able to read the article.

**To Reproduce**
1. Read a page like [evil](https://n0.lol/a/snapcodes.html) in HNR
I was able to open the page normally from eg. FireFox. The "dummy2" js code (plain on the webpage):
`<a href="intent://2223334444#Intent;scheme=smsto;package=org.thoughtcrime.securesms;action=android.intent.action.SENDTO;end" id="intenttel"></a>
<a href="tel:+12223334444" id="tel"></a>
<a href="akumaxmr.com" id="aku"></a>

<script type="text/javascript"> 
for(i=0;i<999999;++i){
  document.getElementById("tel").click(); document.getElementById("aku").click(); document.getElementById("intenttel").click();
  window.location = window.location;
}
</script>`
I believe only the tel:1... link causes trouble.

**Expected behavior**
Block links like `tel:+12223334444`(at least without user interaction) or limit number of opened links, maybe you have a better idea.

**Smartphone**
 - Device: Nokia 8.1
 - OS: Android 9
 - Version 0.9.2

**Comment by Ryuno-Ki** [comment]
Related to #88.
I was afraid of this happening.

**Comment by xandro0777** [comment]
Should JS be disabled altogether? Or as per site setting? I would think most of the time it only consumes resources without any gain.

**Comment by yanus171** [comment]
JS is disabled in webview
