### ISSUE TITLE
"Reload with tags" seems not to influence "original text".

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#309]
I used *"Reload with tags"* feature to hide several article's elements. Those elements are hidden successfully. However, if I tap on the *"Show original text"* button on the very end of this article, those rules seem not to be applied (although I've chosen proper elements to hide - which are present on this "original" text as well).

**Could the rules of hiding chosen elements be applied in every text ver.**, i.e. both original and... the other one?

**Comment by yanus171** [comment]
Original text often consist of single html element so there is no sense to 
hide it. And this single element has no class attribute, so camber identify 
it for hiding
