### ISSUE TITLE
Stay inside an article after unstar.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#310]
While reading articles I often unstar some of them, either by swipe down or by itself (unstar when reaching bottom of an article). In such cases the only thing which happens is that the article has been unstarred - and this is correct.

However, if I do the same (i.e. unstar the currently displayed article) **by tapping a star icon from the top bar** - **the screen goes back to the article list**. Here how it looks:

https://drive.google.com/open?id=16EEcuR3UWy3T5Lfo4PWGzNMwcY8ldBs7

**Could unstar from the top bar act the same as the two previosly described methods?**

**Comment by Ryuno-Ki** [comment]
Yupp, pretty annoying. Especially if it affects an old article, which would then be deleted due to my setting „delete everything older than N days”.

**Comment by ThomasLeigh** [comment]
**Thank You! :)**
