### ISSUE TITLE
Hot Stories.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#311]
As far as various news and articles are concerned, **I like to have a wider perspective on the matter**. This becomes possible if You subscribe more than one feed within the same genre area. As a result, whenever something of more importance happens, usually it will be reflected within a bunch of various feeds, providing You with **a topic perceived with several different angles**.

This may be pretty valuable trick to free Yourself from, say, a journalist's lack of objectivity - or may give You more information that You haven't reached with previous articles, and so on. Last but not least, **You may quickly recognize what topic is on the lips of everyone now, being more important than Your average "news article".**

There is one catch, however: when it comes to RSS reader which grabs all the news either way: **all articles are mixed**. So, although in theory You could recognize "the main themes" - it's much harder to tell what subjects stand out from the crowd, because **everything is pretty mixed up** and You need to flick through dozens of articles in order to say what are the current main themes about.

**What if, however, those main themes could be highlighted and separated from all the rest?**

Imagine that we have a feature called *"Hot Stories"* within *Handy NR*. It could be disabled by default (for performance). If enabled, *Handy* detects and groups together all the new (unread) articles which share the same word or phrase within their titles.

So, under the hood it could work like that: while the feature is enabled, *Handy* scans all the new/unread articles' titles and check if any words or phrases repeats themselves. If a word or a phrase is present in more than one article, *Handy* creates a group of articles and put it on the top of *the Unread* list - or within the separate category displayed on the sidebar (*"Hot Stories"*).

As an example, let's say that among dozens of various unread articles are the ones titled: *Jony Ive leaves Apple* and *Which Jony Ive's design are the most significant?*. With *Hot Stories* enabled You'll see *"Jony Ive"* title on the top of Your *Unread* list (or after tapping a separate category from the sidebar - I would prefer the first way), maybe as the first item on the unread list. Next would be all the rest articles from various feeds, but the first item is that *Jony Ive*. Tap on *Jony Ive* and the list will be unfolded into the two-item form (like a thread: all the rest articles are still below) - or maybe You'll see a completely new list, displaying only those two articles on Jony Ive (that way it would be more readable).

Imagine what would be the result of using this feature on the long run: You have, say, 500 unread articles, and then (i.e. with this feature enabled) *Handy* created several themed-groups on the top of the unread list - **look at this list and You instantly know what the current hot stories out there are all about** - so You can read the more important stuff first. Moreover, it's much easier to deep into a subject which You find interesting - or to reject several uninteresting articles at once - if You have them grouped.

By default *Handy* would search for words and phrases which could be repeated within articles' titles - by its own. But there could be also **an option to switch only to Your Own set of words or phrases** to be considered to create "themed groups" (this way You could have more certainty that *Handy* will always create right groups for You).

Besides, it could be great for this feature to act not only within *the Unread* list - but within *the Favorites* also. Maybe it's much more hassle code-wise, but much more convenience down the road, using the app day by day - if I have everything well-organized within both lists, not only *the Unread*. It could require a separate groups: for example, if My "Jony Ive" group within *the Unread* has 5 articles and I add to *Favorites* only two of them, there should be a Jony Ive group within *Favorites*, but only with those two articles - not 5.

**I think the *Hot Stories* feature could significantly improve the reading flow**, especially due to less switching attention between so many different subjects within Your feeds. And, on the other hand, much more focus on various significant matters which arises from time to time out of Our "ocean of articles".

**Comment by yanus171** [comment]
The solution is to have a few (one or two) news feeds, so we would have no 
news duplicates.

**Comment by ThomasLeigh** [comment]
Yes.

Would You like to implement such a feature?

**Comment by yanus171** [comment]
Proposed solution leaves no sense in this feature

**Comment by ThomasLeigh** [comment]
> Proposed solution leaves no sense in this feature. We don't need an ocean of news articles

I usually have a lot of new (unread) articles, as well as Favorites. It would be great to have them grouped by more popular topics, i.e. such ones which are covered in more than one article in My sets.

Besides, it could be fantastic to see at one glance what are those "hot subjects" are, and be able to deep into them without a need to browse all the unread articles to pick them up, or use a search option.

**Comment by ThomasLeigh** [comment]
@yanus171 
It could be really innovative feature, Alexey. A step forward. I'm sure it could be greatly appreciated.

**Comment by ThomasLeigh** [comment]
@yanus171 

The point is that I think it's not a rare occurrence to have many new (unread) articles provided by each update (feed refresh). Among those articles there may be some on the same subject. If those articles could be grouped, the whole list would be much more readable, providing users with more convenience in reading.

**Comment by Ryuno-Ki** [comment]
How do you avoid having groups of stop words?

@yanus171 How much effort is it to calculate a histogram of words and throw away the ends? Could be the fastest approach here.

**Comment by ThomasLeigh** [comment]
@Ryuno-Ki 

> How do you avoid having groups of stop words?

Could You please explain what the *"stop words"* are...?

Besides, I thought about words which could not be the right fit for this (*"Hot Stories"*) feature, some universal words or phrases not necessarily linked to any particular subject, but simply sole parts of a language. For such words/phrases we could develop in-built black lists (I could develop both English and Polish).

I wouldn't resign from *Handy's* "AI" here, because it's too fantastic (in comparison to user-defined keyword list as the only source).

Imagine *Handy* could prioritize what is the hottest story within our brand new feed refresh, and what are the rest stories which are standing out from the crowd. One glimpse and You know what the current themes are! :) I am repeating Myself - because the whole thing fascinates Me :) .

**Comment by ThomasLeigh** [comment]
@yanus171 , @Ryuno-Ki 

I've prepared some mockups to illustrate how this feature could look like:

![Hot Stories](https://user-images.githubusercontent.com/26142231/62480817-22a76180-b7b1-11e9-9f28-0675c685349c.png)

![Hot Stories 2](https://user-images.githubusercontent.com/26142231/62480820-22a76180-b7b1-11e9-86c6-ae092ea6d46e.png)

Wouldn't be nice to browse articles like this?

**Comment by Ryuno-Ki** [comment]
[Stop words](https://en.wikipedia.org/wiki/Stop_words)

I prefer a chronological timeline. I'm not using any group feature (wouldn't know how to to start with).
