### ISSUE TITLE
Make translation ability more visible.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#315]
I would propose two ways of making this more visible - either one or the other **within the app settings** (info within *About* section may be still present):

1. Instead of *Language* item make *Language & translations*. Inside it let it be, say: 
- *Language* (to switch between all the languages),
- *Info for Translators* (a link to this *GitHub* thread: https://github.com/yanus171/Handy-News-Reader/issues/246),
- *Translate the app* (link to the proper *Crowdin* page),
- *Translate the website* (link to the proper *Crowdin* page);

or

2. Add *Translations* item at the very bottom of all the current settings categories. Inside it let it be as described above.

**Comment by SIRSteiner** [comment]
What about changing summary of "About Handy News reader" to "License, support, translations etc."?

**Comment by ThomasLeigh** [comment]
Good idea.
