### ISSUE TITLE
"Read it later" does not always work.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#316]
Yesterday I added two links (out of the same article read in *Handy*) to _"Read it later"_ and I noticed that only one of them has been added. Today I repeated the process (removing those links before) with the same result. Below You have a video illustrating this.

- [the article with two links I added to _"Read later"_](https://lifehacker.com/how-to-remember-what-youve-learned-each-day-1836820219),
- [link #1](https://lifehacker.com/why-you-should-write-three-pages-of-garbage-every-morni-1820345218)
- [link #2](https://lifehacker.com/keep-a-single-sentence-journal-if-you-don-t-have-time-1694427601);

video:
https://drive.google.com/file/d/1BEZ0m33oQNHDm_bakbIwighNEe7hN3yM/view?usp=sharing

(I surely tapped two of them :) )

**Comment by yanus171** [comment]
What if you tap Read now on these links? Are they loading?

**Comment by ThomasLeigh** [comment]
@yanus171 

In such case they are loaded correctly. But then I deleted those links from *Read it later* and once again choose *Read it later* after tapping - this time it worked. So it's confusing. Maybe it's a case of My phone - it's really in a bad shape now... I have no idea.

**Comment by yanus171** [comment]
That means that you had that article already loaded in another feed. The 
app loads only articles that did not exist yet. If the article (with that 
URL) already exist, and you tap Read it now the app will show it from its 
feed. If you tap Read it later in that case the would do nothing. (Say 
hello to #Remove duplicates issue:)
