### ISSUE TITLE
Some RSS Feeds do not reload correctly

### ISSUE THREAD

**Issue by lulucca12** [yanus171/Handy-News-Reader#317]
- Try adding a feed like [E-IR](https://www.e-ir.info/cetagory/blogs/feed/) that uses  [purl](https://purl.org/rss/1.0/modules/content/) and note thet it works normally.

- Restart your device or stop the application from loading in the background

- Try Reloading

**Comment by lulucca12** [comment]
I think it has something to do with having syndication and slash modules, as other feeds with just content work normally.

**Comment by yanus171** [comment]
Currently this feed contains no entries

**Comment by lulucca12** [comment]
@yanus171 I didn't see that comming as it had content and didn't work.Than we have two issues:
- Add an option for not deleting content if the feed chanes it, if it's not default behavio
- Try with this feed also: https://blogs.plos.org/feed/

**Comment by yanus171** [comment]
The app doesn't delete already loaded articles if they are not old (from app/feed settings)

**Comment by yanus171** [comment]
That feed has loaded 10 articles so I don't understand there problem

**Comment by lulucca12** [comment]
I think this [feed](https://ww.e-ir.info/category/blogs/feed) deletes articles after some time,  the app seems to not maintain them and just responds with a timeout java error when I try updating it.

**Comment by yanus171** [comment]
Yes of cause! If the article web page was removed from server (because if was too old, for example) so the app is unable to reload it. But the loaded articles version remains in the app (if you don't manually tap reload)

**Comment by lulucca12** [comment]
So could there be an option to not deleting them, even if you force reload?

**Comment by yanus171** [comment]
Ok, I can try to restore the old article content in case of an error
