### ISSUE TITLE
Web search integrated

### ISSUE THREAD

**Issue by yanus171** [yanus171/Handy-News-Reader#320]
I have an idea to add a possibility of web search into HNR and open selected web page using app mobiliser (Read now action). It would simplify reading of found web pages, save user time, phone memory and battery when we would have no need to switch between HNR and browser...

 But I cannot find any good free web search API :(

**Comment by Ryuno-Ki** [comment]
Have you tried reaching out to [Algolia](https://www.algolia.com/)?

Or [DuckDuckGo](https://duckduckgo.com/search_box)?

If they aren't good enough, what are your criteria?

**Comment by yanus171** [comment]
Thank you for that. I didn't find the web search window on algoria website. 
But at first glance DuckDuckGo is what I need.

**Comment by Ryuno-Ki** [comment]
Like, I said, you need to [reach out](https://www.algolia.com/solutions/mobile-search/), because it is on negotiating terms. Perhaps you can strike a good deal for an OpenSource Solution.

But then let's go for DuckDuckGo first to get some experience.

**Comment by yanus171** [comment]
Let's go! https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.11.0-beta
