### ISSUE TITLE
[user-request] HNR on (much) older Android devices.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#321]
I've received the following message through *HNR* website:

> Can I hear (again) if me Dummy will be able to receive the bilingual *New  York Times* -HTTPS- (sslException) Feed with an *< Android 5.0 KitKat* mobile  phone?
> 
> OK IC solution for *Android API* <19 seems to be something [like this](https://forums.xamarin.com/discussion/63005/modernhttpclient-tls-1-2-android-api-19).
> 
> Just imagining to use the *HNR* app on older, smaller *Samsung* cellphones  tuned from *2.3* to *Cyanogenmod 4.4* ( e.g. *Galaxy Mini 2*)... reviving them  old phones with your "newspaper" power.
> 
> Regards,   
Sven

**Comment by fanleatherface** [comment]
Thank you, Thomas, for the above quote,  there seems to be a  "<" smaller than, missing before the Android 5.0 part, which is NOT Kitkat, For Your Interest. KitKat ist 4.4 (know-it-all alert!?). this message will delete itself in 42. (zwei-und-pfirsich)

**Comment by ThomasLeigh** [comment]
@fanleatherface  Thank You for pointing this out, just corrected.

**Comment by yanus171** [comment]
I have no problems on KitKat device. Give me an URL if that feed
