### ISSUE TITLE
Dragging an article in article list shouldn't rewrap text

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#324]
When you drag an article in the article list to the side, e.g. to star it, the text in it rewraps to fit the narrower width. This looks messy and can cause the entry to spill over into more rows of text, affecting entries underneath.

![](https://i.imgur.com/qoQQME9.gif)

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1203085115

**Comment by JohnVeness** [comment]
Many thanks, that looks much better now :)

(There is a minor cosmetic issue which this fix has revealed, but I've added that as a new issue #816).
