### ISSUE TITLE
Improve date/time display in article list

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#325]
In an article list, at least on my system the date stamp shows as MMM dd hh:mm. Two problems with that:

1. There is no year displayed. Some feeds, especially when you have just added them, may have articles from a year or more ago, but that isn't obvious
1. Less important, but for example in the UK we usually put the day of the month first, e.g. 3 Sep rather than Sep 3. And other locales do things differently

I haven't checked the code to see if the date format has been hardcoded, or is supposed to be taken from the system locale and is buggy.
![](https://i.imgur.com/oWYaD6R.png)

**Comment by yanus171** [comment]
Here it is https://github.com/yanus171/Handy-News-Reader/blob/master/FlymFork/src/main/java/ru/yanus171/feedexfork/utils/StringUtils.java . Would you like to improve it?
