### ISSUE TITLE
Some in-text links missing in wololo.net

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#327]
Some links within the text of wololo.net articles seem to be missing in HNR.

Compare article in browser:
![](https://i.imgur.com/LSrr5DT.png)

Article in HNR:
![](https://i.imgur.com/qWGQJOF.png)

Feed link: https://wololo.net/feed/

Article link: http://wololo.net/2019/09/05/emulation-news-melonds-0-8-3-released-with-important-input-audio-fixes-jit-builds-coming-soon-mame-updated-to-version-0-213-and-super-mario-64-getting-a-native-pc-port/

**Comment by ThomasLeigh** [comment]
Related to: #124 .
