### ISSUE TITLE
Ability to reassign or disable tap zones

### ISSUE THREAD

**Issue by RMKD** [yanus171/Handy-News-Reader#329]
I often find myself hitting a tap zone by mistake but mostly just want to toggle the 'action bar'. The ability to change tap zone size gives some customization but tends to increase the number of times I hit page down when trying to do something else. For larger phone's it'd be nice to assign the bottom corners to the same function so left thumb can reach the same button as right thumb when using single handed.

**Comment by yanus171** [comment]
So you prefer a setting to remove brightness slider from left side?

**Comment by RMKD** [comment]
Yes, disabling zones seems like the lowest effort fix. 

If someone is thinking about more robust tap zone assignment, it'd be even better to have an ability to assign the share action to both bottom corners. My current workflow is, read article->tap toggle action (bottom right)->stretch to tap share (upper right)->reach back down to select app to share(bottom anchored grid with most recently used mid screen left).

**Comment by xandro0777** [comment]
Setting tap zone size to zero disabled the for me.
