### ISSUE TITLE
v0.10.0 full article text is not automatically loaded.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#335]
I upgraded *HNR* to the  0.10.0 ver., cleared all its data, restored from backup and then all articles show only their title and I need to click *Load full text* each time I want to read an article, even though I have *"Load full text"* checked.

I'm not sure but I have the impression that it refers only to the articles which have been present within the backup.

**Comment by yanus171** [comment]
Try to start Refresh operation

**Comment by ThomasLeigh** [comment]
It seems that after performing *refresh* unread articles are fine again, but *Favorites* - not all of them. Some are still only the titles, and this sometimes trigger **_"Unstar when done"_** feature immediately as they are opened.

**Comment by yanus171** [comment]
Try https://drive.google.com/file/d/1HLfTF1qi1lZBp5uA4clvQRQglhPf-MTD/view?usp=sharing

**Comment by ThomasLeigh** [comment]
Hard to say. Some articles are loaded, some not. Those which are not loaded, do not react to *Load full articles*/*Show original text* buttons. (I did several refresh actions).

Maybe it's something with My phone, currently it doesn't work without a power cable...

**Comment by yanus171** [comment]
https://drive.google.com/file/d/1x7FY2MMmL7ezJ1buCFnTCkeTYUsVGdus/view?usp=drivesdk

**Comment by ThomasLeigh** [comment]
Many articles are still not loaded (only their titles are displayed in full text). *Load full articles* button in full text seems not to react at all. I use *Refresh* action but it takes much time (in fact I don't know how long = it could be great to have some percentage progress indicator).

**Comment by ThomasLeigh** [comment]
After a longer while more articles are loaded, so maybe it need some time...

**Comment by yanus171** [comment]
There were problems with full texts. Seems that this version will solve them https://drive.google.com/file/d/1MqsvNcbSfrK_oimr7Z9zzDKdm-Ok5tM4/view?usp=drivesdk

**Comment by ThomasLeigh** [comment]
There are still some articles which have not been loaded - in this case the button *Show original text*/*Load full articles* doesn't work - but the option *Reload full text* from the menu works.

**Comment by ThomasLeigh** [comment]
Alexey, I'm sorry, I'm browsing articles and now those buttons are working.... it's totally confusing.

**Comment by ThomasLeigh** [comment]
Only *Load full articles* is not working sometimes - but only the button, the option from the menu is working right.

**Comment by ThomasLeigh** [comment]
Still the full article text is not automatically loaded (I need to click the button on the bottom of an article or choose the item from the menu).

**Comment by yanus171** [comment]
Do you have Load full text checkbox checked in these feeds?

**Comment by ThomasLeigh** [comment]
Yes, I have that checked.

It seems that now it's all right - I don't know was it that there were articles which have been loaded partly and I simply read them as they were - or if all the articles "fixed" themselves over the time.

**Comment by yanus171** [comment]
There is a kind of self fixing mechanism. So may be it has done the job.

**Comment by yanus171** [comment]
Can we close it?
