### ISSUE TITLE
The default Data folder setting is cache which is inconsistent with default preference screen

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#337]
I have *HNR* backup storage set to _external_. When I use *Create auto backup* item from the menu, it gives two messages, one after another:

https://drive.google.com/open?id=1M4F--nAJyan6epFL25wmlgZ4DjWxX92o

https://drive.google.com/open?id=1LmZ_GalWKW7Zx2_SnLxII2dqFytePnbI

*v.0.10.1* / *Android 6.0.1*

**Comment by yanus171** [comment]
Give me please a screenshot of Data folder preference dialog

**Comment by ThomasLeigh** [comment]
I don't know why but now it's all right. I haven't performed any particular action...

**Comment by ThomasLeigh** [comment]
@yanus171 

Maybe You are not interested in this issue due to that it is working fine now, but anyway, here You've got the screen:

![Screenshot (Oct 1, 2019 18_31_15)](https://user-images.githubusercontent.com/26142231/66073542-805ced80-e557-11e9-9f8f-3310f568fe70.png)

**Comment by ThomasLeigh** [comment]
I've reopened this thread in order not to multiply issues because this one I find similar enough. My backup settings are the same as before (see the screenshot above), but this time the behavior is as in the video below:
https://drive.google.com/file/d/1MiZnmrs36c_h_Tq53-XSE3fxdplXEsBS/view?usp=sharing

**Comment by ThomasLeigh** [comment]
The video from *Google Drive* is not loaded well at My place, so in case You also encounter this, there are two messages one after another (after I tap *Create auto backup*): the first message starts with *Cannot create dir...* and the second is a message that the backup has been successfully created.

**Comment by ThomasLeigh** [comment]
Oh, I can't find the backup file and folder anywhere - neither on external or internal memory.

**Comment by ThomasLeigh** [comment]
Interesting. I've told You that I have the backup set to "external" as the screenshot illustrates - and it's true. Regardless of that I decided to tap it once again - not changing anything, but tap the same "external" option in the settings (the same screenshot). And it helped (!). Now the backup is created, the folder is there, and so on...

**Comment by ThomasLeigh** [comment]
Maybe after clean installation and restoring from backup the app can't recover "external" settings in practice...?

**Comment by yanus171** [comment]
Yes this is a new setting. It is absent in the old opml file

**Comment by ThomasLeigh** [comment]
But it remembers that I have set the backup (data folder) to the third option. It looks like this:

1. Force *HNR* to stop, clear its data.
2. Install *HNR*.
3. Before launching I put the backup file on internal storage (because without this step the app won't restore, even if the backup is present on the external storage = I mean the 3rd option in settings).
4. Launch *HNR*, let it restore and refresh.
5. Check settings to confirm that it remembers backup set to external storage (the third option).
6. Perform the backup from the menu - it gives two messages: cannot create dir... and the second one on successful backup (even if it's not - I checked and there are no files on external storage).
7. Enter settings and tap on the third option (external backup data storage - which has been checked already anyway).
8. Perform the backup again and this time everything is fine and the backup is truly done.

**Comment by yanus171** [comment]
What is 2? So we need uninstall?

**Comment by yanus171** [comment]
On what step did you select Days folder 3rd option for the first time?

**Comment by ThomasLeigh** [comment]
@yanus171 

> What is 2? So we need uninstall?

I had to uninstall *HNR* and install it again, because only then the issue with *"cannot create dir"* occur.


> On what step did you select Data folder 3rd option for the first time?

I chose it few days ago, without doing any tests - just switched to the 3rd option and keep using *HNR*. The choice has been saved into My backup file, so all the further tests I've done with the backup file remembering My "3rd" choose.

**Comment by yanus171** [comment]
Try this https://drive.google.com/file/d/1jQzTIfZBZCPXlT14RhK12_9H-XyslDqk/view?usp=sharing

**Comment by ThomasLeigh** [comment]
The same as before.

**Comment by yanus171** [comment]
I see the problem: If a user select non default Data folder (not external phone memory) then autobackup.opml is saved there. After clear install or clear data the autobackup would be searched from default folder and would not be found (or would be found an old one). So I think I should save autobackup.opml in all accessible storage spaces, so it would be actual during autorestore

**Comment by yanus171** [comment]
And here is the app https://drive.google.com/file/d/1K61z49xsr0M0fqH-kIDlT2x_OWHM5WRF/view?usp=sharing

**Comment by ThomasLeigh** [comment]
The backup is created also on internal memory, but the issue described above is still present ("cannot create dir...").

**Comment by yanus171** [comment]
Does this message repeat every autobackup?

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.10.6.beta

**Comment by ThomasLeigh** [comment]
Now, just after cleaning the cache, it puts backup file on internal storage. When initiated the second time, it puts the file both on external and internal storage.

Thank You :) .
