### ISSUE TITLE
Unify toast messages.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#339]
Screenshots below illustrate examples of two *HNR* toast messages which look differently. One is vividly rounded and its text has padding applied. The other seems to be without rounded corners and its text seems not to have padding applied.

**Could we have toast messages unified to one form?** I would prefer the rounded one and padding included (exactly as in the example below). It would be also great to have them all displayed in the same place (I would recommend the centered version - as in the brightness example).

![Screenshot_20190929-175137](https://user-images.githubusercontent.com/26142231/66074124-c23a6380-e558-11e9-999b-4f604ecf0004.png)
![Screenshot_20190929-175145](https://user-images.githubusercontent.com/26142231/66074126-c23a6380-e558-11e9-82d5-afb02c4d8196.png)

Besides, I think that it would be nice to have all toast messages' text centered. But the most important thing is to have them unified, i.e. all *HNR* toast messages looking the same way.

**Comment by yanus171** [comment]
Brightness is not the toast message. It's the element of the window gui. It would be hard to guess the toast style in every phone

**Comment by ThomasLeigh** [comment]
Ok, and about toast text being centered - would You mind? I mean both toasts text and brightness "toast" - or just toasts... :) (I like cheese toasts much - and You :) ).

**Comment by yanus171** [comment]
Brightness label is not the toast and it should not be layout accordingly. Toast is a system message that I can customize programmatically

**Comment by ThomasLeigh** [comment]
> Brightness label is not the toast and it should not be layout accordingly. 

Could it look nicer, like (for example) this brightness indicator from *MoonReader*?

![Screenshot (Oct 4, 2019 20_16_06)](https://user-images.githubusercontent.com/26142231/66233872-994ad780-e6ec-11e9-9252-40807aaf331c.png)


> Toast is a system message that I can customize programmatically

Would You mind centering their text?

**Comment by ThomasLeigh** [comment]
@yanus171  I noticed that under _Android 9/MIUI 11_ text within _HNR_ toasts **is already centered**. I don’t know if this is thanks to _MIUI_, _Android_ - or maybe You've centered it?

**Comment by yanus171** [comment]
Say thank to MIUI

**Comment by ThomasLeigh** [comment]
And I’ll tell You that: centered toasts look
### **gorgeous**

`*.*` I’d like other people to have this experience as well!

**Comment by yanus171** [comment]
Show me a screenshot please

**Comment by ThomasLeigh** [comment]
Here You are:

![Screenshot_2019-12-01-22-10-11-354_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/69920419-0e861f00-1488-11ea-8251-5882af6f6440.jpg)
