### ISSUE TITLE
Store article content as sepearate files

### ISSUE THREAD

**Issue by yanus171** [yanus171/Handy-News-Reader#34]
There is sometimes a big time lag when reading sqlite db. I think the source of this problem is the large query result size, because articles content is stored in db. To resolve this issue I have an idea to store articles content to separate files in phone persisntent storage.

May be will comment on some a expediency (or pitfalls) of this idea, before I start to implement it.

**Comment by ThomasLeigh** [comment]
I've also noticed those lags once for a while. I don't know if this idea could help - but **I'd definitely like to have a choice whether to store those (articles) files** in internal or external memory.

Also I was thinking of a feature with which You can export a chosen article (or articles) to a .txt/.rtf/.pdf file - there are situations in which this kind of a feature could be highly welcomed.

**Comment by yanus171** [comment]
Implemented in https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.10.0
