### ISSUE TITLE
Ascribe "Quit the app" to the back button.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#340]
When I want to quit *HNR*, I usually use *Android* back button. But **often I need to tap it more than two-three times**, because it acts like going back through in-app screen history and lead Me over all the steps I took before let Me quit the app.

Sometimes I have several articles on *Android* notification bar. I open one after another and then, when I want to quit the app, I have to go back through all those articles in order to be allowed to quit.

I'd like to ask would it be all right to ascribe "quit without history" action to the back button in *HNR*? In case some users would still preferred the current form of the back button - You could allow them to choose the button action within app's settings. Something like:

* **settings item name:**
Back Button action
* **the item's description:**
Choose preferred Back Button behavior
* **list to choose:**
go back through in-app step history | quit the app after double tap

**What do You think?**

**Comment by yanus171** [comment]
What about tapping Home or Recent instead of Back?

**Comment by ThomasLeigh** [comment]
> What about tapping Home or Recent instead of Back?

I mean the "real close" action which is ascribed to the *Android* back button.

Sometimes I don't want to close the app - then I use the home button, for example. But often I close various apps to make some current task more fluent.

I know that the subject of closing *Android* apps is, let's put it that way, "loaded". With this request I think about Myself and other Users who prefer to close apps via *Android* back button, for whom this may be the expected or desired behavior.
