### ISSUE TITLE
Refresh progress bar.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#341]
It could be fantastic to have a bar indicating visually **_and_** via percentage the progress of the current refresh operation. The animated line which is used currently does not tell anything about how long do I need to wait for the refresh to be done.

I would love to know that :) ! At least to some degree, whether may I drink My coffee without a break, whether could I.... hmmm... take a nap ;) ???? You name it :) .

Oh, if You'd be interested in this (it could be fantastic! :) ) - the progress bar line I propose to be 1px thick and customizable color (reading progress bar rules - it looks beautiful with the red I've picked).

I am very grateful that I can customize *HNR*.

**Comment by yanus171** [comment]
Seems, it's time to turn on Detailed progress technical info ...

**Comment by ThomasLeigh** [comment]
What I mean is a sole visual progress bar and percentage - without anything else, just visual indicator of progress, expressed by horizontal line and percentage.

**Comment by yanus171** [comment]
If you DO turn that pref on, you would see that the current percentage of the whole operation can be hardly calculated. Each step in very unequal to others and depends on many circumstances (cache  state of io, net connection speed, articles to delete count etc)

**Comment by ThomasLeigh** [comment]
Got it. Could it be done approximately - e.g. on the basis of feed number? For example, suppose there are 10 feeds within *HNR*. During the refresh process progress bar could detect that six feeds are done = 60%... Could this kind of approach help - or still too complex and does not change anything important code-wise?

**Comment by yanus171** [comment]
There are several refresh steps: parse RSS, download full texts, download images, delete old articles, delete old images. Before parsing RSS I don't know me article count. Before loading full texts I don't know images count. And I don't know old articles count and images before that step.

**Comment by yanus171** [comment]
The only progress I could do is to decide the whole operation into six stages. But this stages are not equal

**Comment by ThomasLeigh** [comment]
Ok. Could it detect:

1. How many feeds are there to check?
2. When it switched from one feed to the next?
3. To which feed it switched?

If it could, it could be enough to give an approximate percentage base solely on which feed is currently under refresh process.

**Comment by ThomasLeigh** [comment]
I know it could be approximate (a feed may not equal to another feed) - but it could be something.

**Comment by yanus171** [comment]
And let's try to imagine the progress of multi feeds refresh operation ...

**Comment by ThomasLeigh** [comment]
See above.

**Comment by yanus171** [comment]
So we would see the progress of parsing RSS stage, which takes the smallest part of the hike operation. After that we could calculated all new article full texts loads and show progress of that stage. After that we copy calculate the new images downloading (and this is the most heavy step) count and show another progress... and so on

**Comment by ThomasLeigh** [comment]
But it doesn't need to be so detailed as You describe. I mean something that could give an approximate picture of the process. I know that there may be much difference between two feeds, but I'm thinking about an approximate indicator not to trouble the Developer so much :) .

**Comment by ThomasLeigh** [comment]
Just detect which feed is already under the process and on this basis calculate the percentage.

**Comment by yanus171** [comment]
Read my above post again please

**Comment by ThomasLeigh** [comment]
Oh, If I get it right, You mean several progress bars instead of one - depending on what action is taking place at the moment. What I mean is the progress bar which could give an approximate picture of the whole refresh process at one glimpse. When You look at it, You get an approximate impression of what percentage of the whole process has been done so far.

**Comment by ThomasLeigh** [comment]
The simplest mode could be based solely on switching feeds - for example:

1. The app knows that there are 10 feeds (the overall feed number).
2. The app knows when it switches to the next RSS feed during global refresh operation. In that case it checks to which feed it switched. If it swtiched to the sixth feed - it marked the process as being 50% done.

Alternatively it could be more credible if based on stages. Suppose there are five stages for each and every feed to handle during the refresh. Then:

1. The app could first calculate how many stages are for all the feeds (e.g. 10 feeds = 50 stages).
2. Then, each stage shoud be numbered - e.g. the second stage of the second feed should be numbered as "seventh". Starting this stage the app should calculate what percentate out of 50 will be 7. And this could give our percentage for the progress bar.

**Comment by yanus171** [comment]
The first stage (parse RSS) is doing asynchronously for all feeds.

What algorithm should be used if we refreshing a single feed?

**Comment by ThomasLeigh** [comment]
**Good point.** The only reasonable choice seems to be the second one (the one based on stages).

**Comment by yanus171** [comment]
It would not be informative. The stages duration is very different and unexpected

**Comment by ThomasLeigh** [comment]
But it could give an approximate picture of the progress.

It's just a loose idea, I understand that You may not like it due to its very general approach. But since a much more credible approach seems to be too much to handle - I think about anything which could be better than nothing.

**Comment by Ryuno-Ki** [comment]
https://www.xkcd.com/612/ *scnr

How are other applications are handling this?
On GNU/Linux I often see two indicators:
One dealing with the current task and the other with the number of overall operations (current/total - total might change over time).
