### ISSUE TITLE
Javascript displayed in articles on jpost.com/

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#342]
Consider 
https://www.jpost.com/Edition-Francaise/International/Psychodrame-%C3%A0-lUnesco-508077

- when displayed with "full text" some javascript creeps in. This is because for some weird reason the site has the javascript inside a template tag, not script as I would expect.

Now.. the bug - or feature request -  is that even if I reload the article with all tags I don't see a way to hide the javascript because the "template" tag is not displayed.

**Comment by yanus171** [comment]
Why do not to try to set article-2016-main-wrap as full text root class?

**Comment by xandro0777** [comment]
On October 5, 2019 7:50:31 PM GMT+02:00, yanus171 <notifications@github.com> wrote:
>Why do not to try to set article-2016-main-wrap as full text root
>class?

Thanks, works though some JavaScript is left after this article 
https://www.jpost.com/Breaking-News/Turkish-drill-ship-to-start-offshore-operations-south-of-Cyprus-on-Oct-7-603696 - which can be at least blocked.

So it works but I think it would be "nicer" if it were possible to block the "template" with the JavaScript directly. I guess this isn't currently possible because it doesn't have any class associated?

**Comment by xandro0777** [comment]
Tried this article - https://www.jpost.com/breaking-news/article-705523 don't see any way to get rid of the javascript.
