### ISSUE TITLE
Multi-select on "Add a feed" list and 'Edit feeds' option

### ISSUE THREAD

**Issue by stilez** [yanus171/Handy-News-Reader#343]
Adding new feeds, of editing existing ones, always frustrates me, because I have to repeat the same steps for each feed, there's no "multi select" options. In addition the processes have many steps, so I have to repeat all of *those* each time too.  "Add a feed" and "edit feeds" with specific details, as the main culprits:

**'Add a feed' list multi select**

A user interested in a topic, is often interested in multiple feeds on that topic. But at the moment, you have to add them all separately, which is extremely arduous and painful. 

Example: I'm interested in virtualisation related feeds. My current process is:

- Click '+'. 
- Click 'add a custom feed or search'. 
- Type 'virtual'. 
- Enter/click various options. 
- Click 'tick'
- Choose one feed from list.
- Wait for that feed to load before continuing
- **Repeat every step of above, identically, for *each feed* that was listed, that I want to read.**

This is a really painfully long process. Ive just added 6 feeds to populate a group. I could have done this once for all of them, if there had been multi select. I have other groups to add, like that.  

So it would be nice to have an ability to.long-press or equivalent on a feed in the list, to trigger selecting multiple feeds from the same list and then click "tick" to add them all at one time, with the same properties (except name of course!).

**'Edit feeds' multi select**

Often if I edit a feed, its one of multiple feeds I want to edit the same way. I want to group/regroup them all, move or delete them all, change their properties or update settings similarly. But, like "add a feed", there's no way to do that at present. I have to edit **each one separately**. Could multi select ability be added?

**A good example of this** is simply creating+populating a new group. If I want to move 15 feeds into a group of their own, or split 8 feeds out of an existing group, I have to move **each of them one at a time**. There's no way to multiselect and move them all. Incredibly frustrating!

I visualise long-pressing a feed as triggering selection, and allowing multi select, for edit/move/delete feeds purposes. The user can then select multiple feeds and click.a "tick" mark, and then select the action to perform on all of them (at its simplest).

**Afterthought**

There's about 6 steps needed, just to add a feed. That's too many. Can it be cut right down? I've opened a related request for that (#345), as it's not the same issue.

**Comment by yanus171** [comment]
I don't understand why you have to add feeds so frequently?

**Comment by yanus171** [comment]
Multi edit is a valuable suggestion but it demands much time to implement it for all operations. There is a feed edit mode (pencil in left drawer). But it has no multi select yet.

**Comment by stilez** [comment]
> Why you have to add feeds so frequently?

You don't have to add feeds that often, for this to get **really** frustrating. As a person gets an interest in new topics, or rechecks what feeds exist on existing topics, there are often 2, 3 or more to add from the popup list. And of course, its hardly a good experience for a new user, who is setting up feeds over a period of time. For some, I think there is a real chance that this will be so painful as to deter.
