### ISSUE TITLE
0.10.7+ random white screen during full article browsing.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#347]
Even after a complete refresh random articles are displayed as blank white screens. If I choose *"Reload full text"* from the menu, it is loaded properly.

**Comment by afmbsr** [comment]
+1, I noticed this bug starting with version 0.10.7

**Comment by yanus171** [comment]
Is because I needed a white background for svg images to see formulas. But I should set it only for *.svg images

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.10.10-beta

**Comment by afmbsr** [comment]
@yanus171
Is there an update to the translation texts related to moving the layout of the bottom of the entry up, or will the updates be done only by us?

**Comment by yanus171** [comment]
Yes, I forgot to update the text. I will do it in a few days

**Comment by afmbsr** [comment]
@yanus171
If the footer clock is enabled, it appears in normal mode as well

**Comment by yanus171** [comment]
Give a screenshot please

**Comment by afmbsr** [comment]
![Screenshot_20191027_081225](https://user-images.githubusercontent.com/38974362/67630032-d0e31480-f891-11e9-8fce-97d7f935ac70.jpg)

**Comment by yanus171** [comment]
You mean that clock should be hidden in non full screen mode? Only clock, 
not progress bar?

**Comment by afmbsr** [comment]
According to the description[Displays the current time at the top right corner in fullscreen mode]

So the clock should be limited to full-screen mode
