### ISSUE TITLE
A feed stopped properly refreshing.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#348]
I have a feed which worked well for a while and all of a sudden it stopped. *HNR* gives this message while updating the feed:

> EXSite.pl: The feed website is unreachable., java.io.FileNotFoundExcepion: https://exsite24.pl/rss.xml

The thing is the http path listed above seems to be working, while I still can't do the feed refresh.

**Comment by yanus171** [comment]
This RSS has a capture, app should confirm that "I am not a robot" to 
access it . I think this is a site error. May be it would be fixed after time

**Comment by ThomasLeigh** [comment]
So must we rely on the site's creators? Is it possible to circumvent this in *HNR*? It's strange that the feed has worked for some time - now I can't even add it to *HNR* (the app gives an error).
