### ISSUE TITLE
Hierarchical header size.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#352]
Now, when the main article header has been downgraded to smaller ver., there are articles which have in-built their own sub-headers,** which in some cases are of similar size like the main article header** - like here (two screenshots of the same article):

![HNR_headers](https://user-images.githubusercontent.com/26142231/67893271-8d6cfc80-fb56-11e9-97d3-3439ebe9a384.jpg)

I'd suggest to downgrade in-article sub-headers to the form which always be **smaller than the main article header** - to maintain semantic visual chronology.

**Comment by yanus171** [comment]
Try https://drive.google.com/file/d/1Jv1t-EOiEy2CdXp1c9PQfesuAy6cAp3W/view?usp=drivesdk

**Comment by ThomasLeigh** [comment]
Thank You :)
