### ISSUE TITLE
Reorganize “Add a feed” feature.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#353]
Now, given that we have another option within “Add a feed” screen, I'd propose to make the whole feature of adding a new source of content more intuitive. I would propose:

I. Rename “Add a feed” into “Add content”.

**Because**:

1. We've reached much beyond a sole RSS for a longer while now (we can load a given website's links, we can harness Google News, and now we can load a web page).

2. Much more people will understand “content” than “feed”,

II. I'd propose the following items within “Add a feed” window:

1. RSS (add/search).
2. Google News.
3. Web (add/search).

**Comments:**
- **Option 1 (a single text box to enter the RSS address or a phrase to search - no check-boxes)** operates only on RSS, either a direct address or search within RSS feed catalog.
- **Option 2** goes without saying.
- **Option 3 (a single text box to enter the website address or a phrase to search - no check-boxes)**  either grab all links from a given website or search the Web for an article to load.

**Comment by yanus171** [comment]
Word "either" means another checkboxes?

**Comment by ThomasLeigh** [comment]
It refers to a single textbox in which You can enter either a whole www address - or a phrase - and the mechanism will act upon what You've entered.

**Comment by Ryuno-Ki** [comment]
:thinking: Hm, an URL could be detected by „begins with http” or „ends with xml” (since those will be the most likely cases for pasting a RSS link, I guess.
How to differentiate between Google News and Search?

(I don't have the most recent version due to #350)

**Comment by ThomasLeigh** [comment]
@Ryuno-Ki 

> How to differentiate between Google News and Search?

I suppose there is no need to. It would act like that:

I. Tap on "+".
II. There will be three items for You to tap: 

1. RSS (add/search).
2. Google News.
3. Web (add/search).

III. Once You tap the first item, You'll see a text box. If You tap on the third item You'll see a text box, too. Once You tap on the second item, You'll see what is already there.
IV. In the text box You can enter a WWW address or a phrase to search. If You've tapped on the first item, the address should be an RSS feed one - while a phrase should be a phrase to search a RSS feed catalog. If You've tapped on the third item, You can type a WWW address to grab all its links - or a phrase to search and load a chosen one as an article.

**Comment by Ryuno-Ki** [comment]
Thanks for the clarification. I was thinking more in terms of an „omnibar”.

**Comment by yanus171** [comment]
The 3rd point (web) has significant difference.

One case is adding a feed. It has many options. 

Another case is adding a single article. It has no options except search string

**Comment by yanus171** [comment]
And if it was my will I would removed the 2nd point (Google News) completely firm the app

**Comment by ThomasLeigh** [comment]
Remember I mean three separate items on the list, as a result of tapping on them the proper screen should be displayed (so three separate screens).

> The 3rd point (web) has significant difference. One case is adding a feed. It has many options. Another case is adding a single article. It has no options except search string

Is it a problem? The feed screen (the 1st item mentioned above in this thread) can display additional options (I suppose You mean filters, grouping, etc.), while the Web screen (the 3st item mentioned above) can do without it.


> And if it was my will I would removed the 2nd point (Google News) completely firm the app

Then You remove the second item from the list which is displayed after tapping on the *+* icon.

**Comment by yanus171** [comment]
But we can't mix web feed and web search in one item (3rd)

**Comment by ThomasLeigh** [comment]
> we can't mix web feed and web search in one item (3rd)

Can't it be done? It would greatly simplify the intuitiveness of the whole thing: all RSS-related things in one place, while all Web-related things in the other.

**Comment by yanus171** [comment]
So in your variant when 3rd point selected (web) during the user editing of 
the url/search text the feed setup checkboxes should dynamically appear and 
disappear as user enter the text that could be considered as URL or not. 
And so the title text should be changed too dynamically! It would be to 
confusingly

**Comment by ThomasLeigh** [comment]
@yanus171 

> So in your variant when 3rd point selected (web) during the user editing of the url/search text the feed setup checkboxes should dynamically appear and disappear as user enter the text that could be considered as URL or not. 

I suppose checkboxes are not needed anymore if we could split the whole matter into those three items. If You mean, however, a user who'd like - after a while - change the feed address into the one considered not as an RSS - those checkboxes may be always displayed within address editing window - i.e. no need to determine if there is a www address or a phrase (because we are in feed or a web address editing window - which is always a www address).

Regardless of this, if we're about to add a feed or a website (the 1st or 3rd variant), no checkboxes should be displayed because “the textfield will now what to do” (as it already knows: if I add an address, it acts upon it - if I add a phrase, it opens a search results). And it should know on which item a user has tapped - an RSS or a website.

Please bear with Me if I'm not clear enough.
