### ISSUE TITLE
Export/Archive starred articles

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#355]
I would like those exported to some directory on "sdcard" from where I could sync them to my desktop computer - is that somehow possible?

**Comment by yanus171** [comment]
There is only one destination on sdcard that app has access (the path is 
displayed in setting).

What is the purpose of syncing?

**Comment by xandro0777** [comment]
I would like to store/archive some previously fetched articles forever on the big computer.  Easier to find something there with one of the full text search engines, no shortage of storage.

**Comment by yanus171** [comment]
In what format? Each article as separate html file? With images folders?

**Comment by xandro0777** [comment]
Whatever is convenient for you. I would also take plain text.

One thought is that sooner or later people will probably want to import it back when they exchange/sync articles between devices.

**Comment by ThomasLeigh** [comment]
@yanus171 

Do You want the feature of exporting Favorites list back?
