### ISSUE TITLE
Cancel/Ok Buttons can't be activated as they are too low in "Text and background color" dialog

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#357]
The buttons end up between the "Android buttons" (home, back, window list) and can't be hit.

**Comment by yanus171** [comment]
Screenshot please

**Comment by xandro0777** [comment]
![Screenshot_2019-11-04-21-19-15](https://user-images.githubusercontent.com/43711649/68156763-b291ae80-ff4c-11e9-9973-3e72982c0fb6.png)

**Comment by xandro0777** [comment]
Not sure if it is well visible in the picture,  the whole dialog narrowly doesn't fit available screen so vertical scrolling is on.

**Comment by ThomasLeigh** [comment]
It reminds Me of https://github.com/yanus171/Handy-News-Reader/issues/173 , btw.
