### ISSUE TITLE
Schedule refresh for a particular time

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#358]
It would be very nice to have feeds refreshed eg every day at 4am if on charger.

**Comment by Ryuno-Ki** [comment]
Sounds like a case for [Easer](https://f-droid.org/en/packages/ryey.easer/) :-)

**Comment by xandro0777** [comment]
Have you done it? Which intent or activity do you call from Easer?

**Comment by Ryuno-Ki** [comment]
No. I dropped Easer a couple of month ago because it always crashed on startup.
I should give it another try.
What I did with it back then was to turn on WiFi in the morning.
I know, that I could also check for charging status with it.

Regarding intent … Perhaps @ThomasLeigh can provide some info (c.f. #56)

**Comment by xandro0777** [comment]
Having refresh started from a Termux script would be also more than good enough for me.

**Comment by ThomasLeigh** [comment]
I’m not aware of such feed (or group of feeds)-related intents within *HNR*. I don't think there are any.

**Comment by yanus171** [comment]
You can try Easer to start a service:
ru.yanus171.feedexfork.FetcherService

**Comment by xandro0777** [comment]
Tried various things with Easer and Termux but so far nothing works. Unfortunately neither Termux/am nor Easer give me much clue what is wrong.

In Termux tried:
```
$ am startservice  -a ru.yanus171.feedexfork.FetcherService ru.yanus171.feedexfork
Starting service: Intent { act=ru.yanus171.feedexfork.FetcherService pkg=ru.yanus171.feedexfork }
Error: Not found; no service started.
```

```
$ am start  -a ru.yanus171.feedexfork.FetcherService ru.yanus171.feedexfork
Starting: Intent { act=ru.yanus171.feedexfork.FetcherService pkg=ru.yanus171.feedexfork }
Error: Activity not started, unknown error code -1
```

In Easer the event/condition to start fetching work but the "profile" to do the actual fetch has no effect and leaves no trace in /sdcard/logger. FYI, here is my "Do-Fetch" profile in  JSON:
```
{"name":"Do-Fetch","version":14,"operation":[{"spec":"launch_app","data":"{\"package\":\"ru.yanus171.feedexfork\",\"class\":\"ru.yanus171.feedexfork.FetcherService\"}"}]}
```

**Comment by xandro0777** [comment]
I got a reply from the author of Easer, it doesn't implement the functionality yet but the author will try to implement it.

The linked example from Stackoverflow (https://stackoverflow.com/questions/17316232/how-to-start-android-service-from-another-android-app ) showed me how it could be done  from termux - but apparently Handy_News_reader must export some permission for this to work:

```
$ am startservice ru.yanus171.feedexfork/.service.FetcherService 
Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=ru.yanus171.feedexfork/.service.FetcherService }
Error: Requires permission not exported from uid 10049
```

**Comment by xandro0777** [comment]
BTW, would it be somehow possible to pass parameters to the FectherService? it would be nice to be able to explicitly specify which feed(s) to fetch and whether to fetch full articles for example.

**Comment by yanus171** [comment]
In all you can select feeds for auto refresh and wherever load full text or not for each feed. There is no need to pass that info through intent.

**Comment by yanus171** [comment]
I will try to add exported attribute to the manifest. You can also try to use AutoJobService instead of FetcherService. It's already exported

**Comment by yanus171** [comment]
I could also try to make a setting for starting auto refresh in particular time. But this will takes some time.

**Comment by xandro0777** [comment]
There are plenty reasons to pass arguments to the refresh service, I will probably forget some but I will try.

I have good network only at night so I would do a full fetch in the early morning. At other times of the day I may be interested to get some headlines but doing a full fetch would empty the battery at the wrong time.

Some feeds have special schedule, don't want to probe a feed which I know has a 1/mo update every night.

Some feeds I want to read as weekend specials. Also have some seasonal preferences.

When I drive to some place may went to fetch certain feeds relevant for that place.

With Easer or termux I have pretty good control of all circumstances: charging state, time, battery level, battery temperature, location - and my own schedule. No need to reimplement everything of it in HNN.

A number of other bugs/feature requests would probably go away automagically..

https://github.com/yanus171/Handy-News-Reader/issues/135
https://github.com/yanus171/Handy-News-Reader/issues/277
https://github.com/yanus171/Handy-News-Reader/issues/294
https://github.com/yanus171/Handy-News-Reader/issues/295
