### ISSUE TITLE
the new release 0.11.0 full text always shows the full webpage. not mobilized

### ISSUE THREAD

**Issue by Sherman-Yang** [yanus171/Handy-News-Reader#359]

**Comment by Sherman-Yang** [comment]
the new release 0.11.0 full text always shows the full webpage. not mobilized.

if you click "Load full articles" or some RSS is set to get full articles

**Comment by yanus171** [comment]
This is only if you load full text via Read now or Read later (in Read it 
later folder) and if the feed has not been manually set full text root in 
Reload with tags mode.

This was made for web search, so navigation links would be visible by 
default. To view only text you can still Reload full text

**Comment by Sherman-Yang** [comment]
Thank you for your support. I haven't use read it later function yet. right
now for me, all full articles shows it's web page in everywhere. I don't
know which settings can make it show only text.

**Comment by Goran88** [comment]
Same issue here as Sherman-Yang. Please try any of these feeds:

https://martijn.xyz/av/data/rss/

http://www.snopes.com/feed/

https://rss.dw.com/atom/rss-en-all

http://feeds.bbci.co.uk/news/world/rss.xml

http://feeds.washingtonpost.com/rss/politics

http://feeds.feedburner.com/euronews/en/home

http://news.google.com/news?hl=en&output=rss

(probably any of Google News topics)
This is just some examples. Almost all my feeds look like I intentionally did "Reload without Mobilizer" I did not change any settings after update to 0.11.0.
They all worked as expected before 0.11.0. In last version if I do "reload with tags" on any article (to try to find what's wrong) in these feeds it shows Handy_News_Reader_root tag as selected (green)

**Comment by Sherman-Yang** [comment]
I just roll back to the previous version, waiting next version

Thank you

**Comment by yanus171** [comment]
Try https://drive.google.com/file/d/11wC-K4C2IplTkAoGSF-CMhopaTSRU04I/view?usp=drivesdk

**Comment by Sherman-Yang** [comment]
Thank you very much. this version works very well.

Thank you

**Comment by Goran88** [comment]
Works for me also. Thank you.
