### ISSUE TITLE
Inconsistant UI language

### ISSUE THREAD

**Issue by SIRSteiner** [yanus171/Handy-News-Reader#36]
If language is set other than Android default: After changing device orientation from portrait to landscape UI language reverts to Android default.

Here is a screenrecording

[ScreenRecord-2019-01-02-10-53-23.mp4.zip](https://github.com/yanus171/Flym/files/2721449/ScreenRecord-2019-01-02-10-53-23.mp4.zip)

**Comment by yanus171** [comment]
Why did you close it? I see this bug in the current version

**Comment by SIRSteiner** [comment]
Hmm, here this bug is gone, sorry.
