### ISSUE TITLE
Error on eurogamer.es

### ISSUE THREAD

**Issue by layane** [yanus171/Handy-News-Reader#365]
**Describe the bug**
URL: https://www.eurogamer.es/?format=rss

Issue no attached image. 

**To Reproduce**
1. Go to '+'
2. Click on 'Add a custom feed...'
3. Paste URL https://www.eurogamer.es/?format=rss
4. Press back or Save

**Smartphone (please complete the following information):**
 - Device: Xiaomi poco phone 
 - OS: Android 9
 - Browser chrome
 - Version 0.11.1
![Screenshot_2019-11-11-18-49-33-262_ru yanus171 feedexfork](https://user-images.githubusercontent.com/1853429/68608796-0ef84f00-04b4-11ea-8960-5ad58e2e279e.jpg)

**Comment by yanus171** [comment]
Try 
https://drive.google.com/file/d/1Jv1t-EOiEy2CdXp1c9PQfesuAy6cAp3W/view?usp=drivesdk

**Comment by layane** [comment]
Fixed with these version. Thank you! 
![Screenshot_2019-11-12-07-10-12-546_ru yanus171 feedexfork](https://user-images.githubusercontent.com/1853429/68646520-b3fa4280-051b-11ea-84fe-9763bacd46a9.jpg)
