### ISSUE TITLE
Customized Action Bar & In-Article Menu.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#366]
Whenever I need to use some option from the in-article menu, **I need to search for it** (i.e. take a closer look) because the menu is quite long (in My case it takes the whole screen height). Even if I remember the item position -**it's easy to tap on the wrong item**.

**It could make a huge difference if it could be possible to customize both all the in-article menu items and all the Action Bar items.** By “customizing” here I mean to pick and choose at least some items to be placed in those places, and be able to skip the ones which I personally don't need.

This way I could, for example, put the most often used (by Me) options on Action Bar, and all the rest on the in-article menu. I could also skip those ones which I don't need. **As a result I will be able to perform frequent actions in *HNR* much quicker** - because they will be put on the Action Bar and even those on the menu will be much easier to find/tap because **the menu may be shorter then**.

I think not only I would appreciate the ability to customize those things in such a way.

**Comment by ThomasLeigh** [comment]
I am especially concerned about that:

1. **In case of text-based menu it's not so hard to tap on a wrong item.**
2. **It usually harder to find the one You need at the time** - because all of them are pretty similar to each other (small icons do not help much), and there are a lot of them.

Now, even if one could have less items within the menu - I have yet another idea alongside it, which could solve the two points made above:

![New In-Article Menu](https://user-images.githubusercontent.com/26142231/69546047-44606a80-0f93-11ea-8b64-0d732244936a.png)

I think that in such a case:

1. It's much harder to tap on a wrong item.
2. You can much faster figure out where the item You need is placed.

I've tried to make icons as intuitive and simple as I could. **There all could be described** either in a form of *a welcome screen* (when You run the app the very first time) or **within settings** (like screen describing *Tap Zones*).

What do You think?

**Comment by yanus171** [comment]
I like your idea.

But how can we make these icons sense clear for the new users, which were 
never been in settings?

May it can be a non default behaviour, which could be turned on for 
"clever"users.

**Comment by ThomasLeigh** [comment]
> how can we make these icons sense clear for the new users, which were never been in settings?

Maybe some short **introduction screen** at the very first launch of the app (after installation)? And this introduction screen could also be available in a form of help icon somewhere on the sidebar.


> May it can be a non default behaviour, which could be turned on for "clever"users.

Yes, it could be that way. I think it could be better to turn it on by default with the introduction screen put as described above - because I suppose more people could appreciate this approach. If, however, You prefer the other scenario (non-default behavior), it still be a great input to which I will definitely switch as soon as possible :) .


Oh, in case those icons could come in handy, I have them all in .svg, all are free to use (GPL), I can send You if You like.

**Comment by Ryuno-Ki** [comment]
Nah, an introduction screen will likely be skipped over (I want to get into the app ASAP).
It would rather help to show the tips in context.

At least if app user behave somewhat similiar to users of web apps.
Plus, showing it for the first time will likely not skip in user's memory.

**Comment by ThomasLeigh** [comment]
> It would rather help to show the tips in context

Yes, i.e. when a user initiates the menu for the first time? Indeed I share Your opinion that it could be better.

**Comment by Ryuno-Ki** [comment]
The keyword here is „Guided Tour”. It could look like https://introjs.com/ (but would need something for Android).

**Comment by yanus171** [comment]
May be we just need a checkbox at the top of menu to switch between original and icon variants?

**Comment by ThomasLeigh** [comment]
> May be we just need a checkbox at the top of menu to switch between original and icon variants?

If it will remember the choice - yes, sounds good.
