### ISSUE TITLE
Totally confusing behaviour with "Show original article on article list"

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#369]
I have "load full articles" off and some old articles with and without full text fetched.

 After enabling "Show original article on article list" (and not refreshing or asking to fetch a full text)  a number of confusing things happens:

* the article sort order is reversed (newest is shown all the way down)
* the full text symbol is dsiplayed next to all articles even though these were not fully loaded previously
* the view in the article list is jumping up and down

Also.. it would be nice to limit the preview to a fixed number of lines

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.1

**Comment by yanus171** [comment]
If we are reading the articles texts (as a newspaper for example) we read them from top to bottom, so the With text mode should have fixed sorting regardless of Without text mode
