### ISSUE TITLE
Display "I am working" indication when opening articles takes longer time

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#370]
Sometimes on my phone it appears to take a number of seconds to open an article (or preview) after tapping it in the article list.

It would be nice to display some kind of indication that it is just taking a bit longer, because sometimes my finger accidentally does a slight sidewards move when trying to select an article (initiating in an incomplete delete/add to favs gesture) so nothing happens at all and it is not always easy to distinguish.

**Comment by ThomasLeigh** [comment]
...loading... ?

**Comment by ThomasLeigh** [comment]
A cup of coffee icon would also be highly appreciated :)

**Comment by yanus171** [comment]
The icon should not be static. I suppose to use standard Android rounding 
circle

**Comment by xandro0777** [comment]
Yes, the animated circle would be fine. I am still puzzled while it mostly works very quickly and sometimes doesn't seem to react for a few seconds?

**Comment by ThomasLeigh** [comment]
> The icon should not be static. I suppose to use standard Android rounding circle

Floating coffee foam? :) Could have its own style and taste, alongside the *HNR* logo. And it could be nice :) .

**Comment by yanus171** [comment]
Coffee cup is a symbol of calm reading but not of calm waiting :)

**Comment by ThomasLeigh** [comment]
> Coffee cup is a symbol of calm reading but not of calm waiting :)

Hahahaha, **good point** :) . But maybe You remember the time when one would rather prefer to have a coffee that staring at the screen with Windows 95 loading... ;)

**Comment by yanus171** [comment]
Did I resolved it in the last app release?

**Comment by ThomasLeigh** [comment]
I say “yes” :) @xandro0777 how do You like it?

**Comment by xandro0777** [comment]
On Tue, Dec 31, 2019 at 03:00:24AM -0800, yanus171 wrote:
> Did I resolved it in the last app release?

which one is it? I am on 0.11.5 F-droid and did not see an update in a long time. Thinking about it.. it seems I have not seen this very long delays when opening articles for a while.

**Comment by xandro0777** [comment]
The release finally made it into f-droid  and looks like a big improvement.

I still see mysterious behavior:  from the article list I click one article, the spinning wheel starts spinning, disappears in a fraction of second with no apparent action for a noticeable time, then the spinning wheel comes back sooner or later and further action ensues. 

Wondering .. the article selection sends an intent that makes it "out of" HNN through the whole Android intent machinery (I can intercept it with the IntentIntercept app) to finally make it into HNN again.

Is that possibly the reason why this action sometimes causes unpredictable delays? Does it make sense to make the event catchable by other apps?

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.0
