### ISSUE TITLE
Application freeze until "clear data" used.

### ISSUE THREAD

**Issue by vi** [yanus171/Handy-News-Reader#371]
**Describe the bug**
Attempt to open Handy News Reader resulted in empty window being shown.

**To Reproduce**

Don't know, I've already reverted it to working state.

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL
 - OS: Android 9
 - Browser ?
 - Version: Handy News Reader v0.11.5 from F-Droid repository

**Additional context**
No suspicious logcat messages occurred when attempting to start it, except of something like "no touchable window, input event ignored" if I tried to click somewhere. Android showed "App is not responding. Close it?" message after a while if I tried to do something.

Clearing cache for the app or rebooting Android didn't help. Clearing data for the app helped (it automatically restored the backup), and now Handy News Reader works again.

**Comment by ThomasLeigh** [comment]
> Attempt to open Handy News Reader resulted in empty window being shown.

I often encounter a similar issue under *Android 6*. What helps in My case is to kill the app (force quit), no need to clear its data.

**Comment by vi** [comment]
In my case just restarting ("force quit" or "hibernate" in KISS launcher) failed to resolve the issue.

**Comment by yanus171** [comment]
What about the last app release?

**Comment by vi** [comment]
The problem is not a reproducible one, so I don't know how to check if anything's changed with the last release.

**Comment by yanus171** [comment]
So reopen the issues of the problem occurs again
