### ISSUE TITLE
Only export feeds as OPML (not settings as well)

### ISSUE THREAD

**Issue by erazemkokot** [yanus171/Handy-News-Reader#372]
**Is your feature request related to a problem? Please describe.**

The problem is more frustration related.
When first trying out the app I couldn't import my existing OPML file from Flym (the same with Feeder), now when exporting the feed I think I know why.
HNR exports all of its settings in the OPML file, which is ok, but I wanted to only export the feeds, not all the settings as well.

**Describe the solution you'd like**

HNR should have an option to only export the feeds as an OPML, not the settings as well (a separate option of course, so users can still export everything in one file).

**Describe alternatives you've considered**

1. Using other apps to generate the rss feed to back up then manually adding the feeds to HNR - would take way too long
2. Switching to a different reader - none are as feature complete as HNR (the offline support is awesome)

**Comment by yanus171** [comment]
What was the problem? You can't import an opml file into HNR? If so give me this opml so I could fix the bug.
Or
You can't import HNR opml (with settings) to other app?

**Comment by yanus171** [comment]
What was the problem? You can't import an opml file into HNR? If so give me this opml so I could fix the bug.
Or
You can't import HNR opml (with settings) to other app?

**Comment by erazemkokot** [comment]
I can't import a non HNR OPML file (one that only stores rss feeds, not settings as well) and I can actually import the HNR feed to a different reader, but in my case I wanted to reimport the feed into HNR, but without the settings, so that I can change the settings but keep the feed the same without the previous configuration.

Here's an example of a feed only OPML file: https://pastebin.com/nYT0AZGv

**Comment by yanus171** [comment]
I will see why that opml fails to import.

But HNR auto creates opml file with settings periodically, so even if you 
change settings they (in nearby time) will be actual in created auto back 
opml file. So I still see no reasons for your proposed preference to 
include settings in opml.

**Comment by erazemkokot** [comment]
Thanks for checking it out.

I think my use case is fairly unique so I'm taking back the feature request, but still thanks for the interest. If you'd like to keep the issue open to track the OPML import bug then sure, but otherwise you can close the issue.

**Comment by JohnVeness** [comment]
Going back to the subject of this issue, and not the subsequent chat about *importing*, I too would like to see an option to just export the list of feeds as an OPML, not the settings too. This is because I wanted to try out a different RSS reader, and it didn't seem to like the multi-megabyte OPML file created by HNR. I haven't analysed or edited the created OPML file, but my hope is that if it was just the feed details, and just a few kilobytes big, then it might import into the other app OK. At the moment, I feel like I am a little "locked in" to HNR because of this issue.

**Comment by ThomasLeigh** [comment]
@yanus171 Will You consider to include such a feature to export only a feed list?

**Comment by yanus171** [comment]
I think we should decide back up and opml export operations

**Comment by ThomasLeigh** [comment]
What about this:
1. Create auto backup › for the backup.
2. Export to an .opml file (from the feeds edit list) › for sole feed lists.

**Comment by ThomasLeigh** [comment]
Introduced since ver. 0.15.1.
