### ISSUE TITLE
Improve <blockquotes> for readability and aesthetics.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#373]
I often encounter a situation in which part of an article text has different background - I suppose it is a `<blockquote>` element. I use dark theme with black background - and those elements have significantly brighter background, which makes them harder to read in My case.

I’d like to ask would it be possible either to remove this brighter background or to allow to set it by Myself?

Also I’d like to propose a little bit of a touch-up:
1. Decrease font size (of those elements) a little bit.
2. Increase their indent a little bit more.
3. Make their left border more visible.

As a result it could look like this:

![sshot-5](https://user-images.githubusercontent.com/26142231/69890958-54f94380-12f9-11ea-8456-fbeb6d487856.png)

**Comment by Ryuno-Ki** [comment]
Hm, how is it styled anyway?
CSS? Could we allow define custom CSS? 
(Similiar to that HTML feature I never tried).
What about `!important` statements?
Perhaps HNR should strip all CSS? (I observe inline CSS in some feeds).

**Comment by ThomasLeigh** [comment]
> how is it styled anyway? CSS?

I don’t know how it is accomplished in *HNR* - the screenshot presents My preset within *Notepad++ [Markdown Viewer](https://github.com/nea/MarkdownViewerPlusPlus/releases)* plugin, in which I indeed have used CSS.

**Comment by yanus171** [comment]
I try to remove as much html tags and attributes as possible from loaded articles. And after that I apply my own CSS styles. You can see it at the of https://github.com/yanus171/Handy-News-Reader/blob/master/FlymFork/src/main/java/ru/yanus171/feedexfork/view/EntryView.java . Try to propose changes via pull request.

**Comment by Ryuno-Ki** [comment]
That would be a modify of https://github.com/yanus171/Handy-News-Reader/blob/24504969c7df658a4f05d11142a0a1037e771624/FlymFork/src/main/java/ru/yanus171/feedexfork/view/EntryView.java#L162 then.

@ThomasLeigh Could you share the CSS you used for the screenshot?

**Comment by ThomasLeigh** [comment]
Sure:

	blockquote
	{
		padding-left: 14px;
		border-left: 5px solid orange;
		font-size: 20px;
	}

`20px` stands for 62,5% of the article main font size.

**Comment by Ryuno-Ki** [comment]
Hm, @yanus171,
sounds like once you add a way to set the „theme font-size” and a fallback, @ThomasLeigh could adjust what's needed.
(Assuming, that `QUOTE_LEFT_COLOR` and `QUOTE_BACKGROUND_COLOR` are already configurable).

**Comment by ThomasLeigh** [comment]
@Ryuno-Ki Since I’m not a programmer so much I feel confused about how am I supposed to achieve that?

**Comment by Ryuno-Ki** [comment]
He provides a setting and you set the value :-)

**Comment by ThomasLeigh** [comment]
In the place You’ve pointed out here https://github.com/yanus171/Handy-News-Reader/issues/373#issuecomment-560110952 ?

**Comment by yanus171** [comment]
QUOTE_LEFT_COLOR and other color constants are defined in https://github.com/yanus171/Handy-News-Reader/blob/master/FlymFork/src/main/java/ru/yanus171/feedexfork/utils/Theme.java for two themes: black and white. Corresponding text is theme.put(QUOTE_LEFT_COLOR, "#a6a6a6"); for light theme and theme.put(QUOTE_LEFT_COLOR, "#686b6f"); for black.
Some of these colors are  configurable in settings, some are not.

You can ask me to add custom settings for more colors.

Even if you are not a programmer you can try to understand these principles. So we can try to improve article CSS styles

**Comment by ThomasLeigh** [comment]
I’ve done My first attempt :) Modified look for quotes:
1. Black background for dark theme.
2. Orange border for both themes.

What I really would like to achieve is that **quote background will be always the same as article text background**, regardless of theme. But I don’t know how to do that.

If I get it right, there is no setting (within the code) for quote border width (thickness)?

Could colors be defined with alpha (transparency) included?
