### ISSUE TITLE
Reconcile the star icon with a notch.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#374]
When *HNR* takes all the screen (including area around the notch), a star icon (a bigger yellow one, to add or remove from *Favorites*) is partly “eaten” by the notch. Could it be placed a little bit lower on the screen?

**Comment by Ryuno-Ki** [comment]
Do you have a screenshot? Just for us mere mortals without the latest hardware :-D
Perhaps a before/after one could be taken then…

**Comment by ThomasLeigh** [comment]
> Do you have a screenshot? Just for us mere mortals without the latest hardware :-D

I also don’t have the latest one :) (My dream is the Asus Rog II).

Unfortunately it seems there is no way to catch the issue on a screenshot or capture a video - because then the star is 100% visible. It’s all about the hardware notch which partly takes over the space of the star displayed.
