### ISSUE TITLE
Article view broken amidst

### ISSUE THREAD

**Issue by Ryuno-Ki** [yanus171/Handy-News-Reader#375]
Hi,

I have [my own feed](https://jaenis.ch/blog/feed.xml) in HNR as a QA measure.

In [my last article](https://jaenis.ch/blog/2019/node-knockout-2019-postmortem/) the article stops in the middle (screenshot in next comnent).

The HTML view shows the whole content, so something breaks in the article view.

**Comment by Ryuno-Ki** [comment]
![Screenshot_20191130-093603](https://user-images.githubusercontent.com/3097194/69898099-d9c57b00-1354-11ea-8f75-0b03fd53906b.png)

**Comment by yanus171** [comment]
I will see it
