### ISSUE TITLE
Marking items as Read

### ISSUE THREAD

**Issue by dmevis** [yanus171/Handy-News-Reader#377]
If you use the box in the upper bar to hide Read messages, the "Mark all as read" does not function properly.  It does not mark the messages as Read.  If you change the box in the upper bar to display all messages, then the "Mark all as read" functions properly.

**Comment by yanus171** [comment]
I can't reproduce it. Did you use menu item Mark all as read?

**Comment by yanus171** [comment]
Seems I have got it. It doesn't work when you have selected to view a group of feeds

**Comment by dmevis** [comment]
Yes, that is correct.  All of my Feeds are contained within Groups.
