### ISSUE TITLE
Open application to feeds list

### ISSUE THREAD

**Issue by dmevis** [yanus171/Handy-News-Reader#378]
I have several groups of feeds, and read only one of them at a time.  When I open the application, I want an option to be taken directly to the feeds list screen, rather than to the "Unread" screen.  Then I can see how many articles are in each Group, and decide which one I want to read.  Also, you may as well make the feeds list screen cover the entire screen, rather than just a portion of the screen.

**Comment by yanus171** [comment]
I can make an option to open feed list in startup. But I see no sense to make it full width - it would be harder to hide it by swiping

**Comment by dmevis** [comment]
For a small number of articles on a similar subject, your paradigm of going directly to the "Unread" feed, or swiping away the Feeds List to get to the Unread feed makes sense.  However, with a large number of unread messages on a large number of different topics, the Unread feed is useless, and there is reason to swipe away the Feeds List to get to the Unread feed below it.

I suggested having the Feeds List as an entire entry page because it is a more logical starting point for when you open the application, and wish to determine which of the feeds/groups you want to read, rather than just going to the Unread feed.

**Comment by yanus171** [comment]
If settings-notifications and behaviour-remember list article is checked then the selected feed (and reading article) is remembered and restored on next app launch.
