### ISSUE TITLE
Double Tap middle of screen to return to article list

### ISSUE THREAD

**Issue by dmevis** [yanus171/Handy-News-Reader#379]
A feature that some other news readers have that I find very useful, is an option to double-tap the middle area of the screen to return to the Articles List.

**Comment by yanus171** [comment]
What is the problem in swiping from left screen edge?

**Comment by dmevis** [comment]
Example.  You are reading a single Feed/Group that contains 100 articles.  You scroll down to the 10th article and decide to read it.  After you have read that single article you want to return to that same Feed/Group list of articles at the point where you selected the 10th article.  You can hit the Android Return Key, or, I would like to be able to double-tap the center of the screen.

**Comment by yanus171** [comment]
So you mean article list, not feed list - rename the issue. The article list scroll position is restored after return to article list

**Comment by yanus171** [comment]
I also want to add Return to article list button to menu and at the bottom of article text, but that is another issue

**Comment by dmevis** [comment]
Returning to the Article List is something that is done frequently.  I would suggest that it be something than can be done quickly, easily, and without even looking.  That is why I believe that double tapping in the middle of the article currently being read is a very good method.

**Comment by dmevis** [comment]
> 
> 
> So you mean article list, not feed list - rename the issue. The article list scroll position is restored after return to article list

Yes, it is.  But I am suggesting that you scroll the just-read article to near the top of the screen when you return to the Articles List.  That way, when you return to the Articles List, you are always looking at a near full screen of unread articles.
