### ISSUE TITLE
FR: More control over when articles are marked as read

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#382]
I am enjoying HNR very much, but one thing that is awkward for me is the way that an article is marked as read as soon as you enter it. If I get distracted and switch apps and do other things, by the time I re-enter HNR the article has gone from the unread articles list. Yes, I could probably find it by showing unread articles, but I might not even recall what the article was!

At the moment, if I know I'm going to switch away from the app, I will choose Mark as Unread from the menu, but still forget if dealing with a notification or similar. It just "feels" fragile, like I can't trust HNR to look after things properly for me.

I would prefer it if we could have more control over whether an article is marked as read. For example, the user could explicitly press a button to mark it as read (I.e. the opposite of the current Mark as Unread menu item). I realise most people wouldn't like that but that would be most ideal for me.

Alternatively, an article could not be marked as read until the user has explicitly navigated away from it (I.e. pressed back, or swiped to next article).

Thank you for considering this, and for HNR in general.

**Comment by yanus171** [comment]
May be in such a case it worths to star an article?

**Comment by ThomasLeigh** [comment]
Or add a “Disable automatically mark as read” option within settings.

**Comment by JohnVeness** [comment]
That would certainly suit my purposes, although personally I would phrase it as "Automatically mark as read", and ticked by default. If this ever happened, it would be helpful to have a "mark as read" button, maybe in the toolbar at the top, or at the bottom of the article.
