### ISSUE TITLE
Request: add .nomedia to feedex/images folder

### ISSUE THREAD

**Issue by tuchit** [yanus171/Handy-News-Reader#383]
Please add .nomeida file to./feedex/images/  folder
There are so many thumbnail images here, it's not friendly when you pick pic via Twitter and makes the phone manager app in mass.
I tried to add .nomedia manually but it automatically delete it after several hours usage.

**Comment by yanus171** [comment]
Ok.

**Comment by yanus171** [comment]
Try the last app release

**Comment by tuchit** [comment]
THX it works
