### ISSUE TITLE
Allow to remove hyperlinks’ background.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#384]
So far if one doesn’t want to use separate background for hyperlinks, their have to **set manually their background as the same as article text**. It could be great to make this easier, e.g. by adding transparency bar within hyperlinks’ color settings - or a checkbox for removing the background.

**Comment by yanus171** [comment]
Let one correct me, but html colour attribute doesn't support transparency

**Comment by ThomasLeigh** [comment]
I use something like this:

	background-color: rgba(0, 0, 0, 0.70);

where the last value stands for transparency.
