### ISSUE TITLE
Global rejecting filter or the second - rejecting - action within global filter.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#39]
In order to make content-rejecting feature **much more convenient and easier to use** (no need to set it up for each single feed).

I was wondering **which feature could make the biggest difference** in _Handy_ and I came to the conclusion that it could be definitely _"global rejecting filter"_.

The reason is that: although content sources which I subscribe are interesting - there are often articles I am not interested into, so **usually I have many articles to simply skip**, while there are part of them I mark as starred to read later when having more time.

If You, however, imagine **how much time it could save to skip those uninteresting articles automatically**... ??? It would be definitely a great difference, saving much, much time - The result of this feature is very exciting in terms of the app usability (**how an app makes the life easier**).

I was thinking of setting a rejecting filter for each feed but it is quite inconvenient, especially given the **updates of a phrase list** when You need to edit several feeds, delete old set of phrases and paste a new one each time.

Examples of rules would be subjects a user is not interested in - much like 
in case of a current global filter, in My case for example I choose rules 
being applied to articles' headers. I'm not interested in subjects like 
_Tinder_, _Nintendo_... there are many more which could make My **RSS experience 
much cleaner** and - which is even more important - **save much time during 
browsing articles**.

**Comment by crti** [comment]
Just installed the App and searched for this IMHO key feature. Using the App without additional third-party or self-hosted solutions who do such "global filtering" either as a white-list (allowed) or black-list (rejected) is the way to go. 
A first list of useful keywords for the title which usually mean the content is not real news (opinion) and/or contains no really informative info - inspired by https://greatestview.de/die-informationsflut-bewaeltigen-rss-feeds-filtern/: 
> ?
> shall
> wants
> want
> calls
> demand
> plans
> plan
> could
> allegedly
> apparently
> probably
> maybe

I see under Settings > Notifications > Global filter... there is a setting for this (see [News](https://handynewsreader.blogspot.com/2018/11/be-notified-on-important-articles.html)). So the feature is basically implemented for Notifications but not for pre-filtering of feeds as listed in the upcoming features?
> global rejecting filter or rejecting action within global filter
> In order to make content-rejecting feature much more convenient and easier to use (no need to set it up for each single feed).

**Comment by yanus171** [comment]
Yes global Reject filter is in plans. By the way what about global Accept filter? I think it's useless. We can hardly define all keywords do all needed articles.

And I don't think we should have any predefined reject filter. It's very personal specific. And we would have to translate words to all app languages.

**Comment by ThomasLeigh** [comment]
@yanus171 I hope the notification on important articles will remain? (based on custom keywords)

**Comment by yanus171** [comment]
Global star notification will remain of course

**Comment by crti** [comment]
> Yes global Reject filter is in plans. By the way what about global Accept filter? I think it's useless. We can hardly define all keywords do all needed articles.
I agree: global Reject filter should be fine. When a feed has an Accept filter set the question is which has priority: I think the feed filter? Or maybe the priority could be set in the feed filter?

> And I don't think we should have any predefined reject filter.
I just mentioned them as a personal starting point to avoid fake news and journalist opinion pieces. No need to predefine or include them in the App. 

Thanks for providing us which the App. Very nice to have it in F-Droid - I found it there...

**Comment by ThomasLeigh** [comment]
> By the way what about global Accept filter? I think it's useless.

I agree.


> I don't think we should have any predefined reject filter.

I also agree here.

**Comment by ThomasLeigh** [comment]
@yanus171 

> Yes global Reject filter is in plans.

Though this thread has not *"Accepted"* label - does it mean You changed Your mind about this feature's implementation? Or could we label it as *"Accepted"*?

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1484184430
