### ISSUE TITLE
Links disappeared.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#391]
One of articles I receive via *HNR* periodically, is about Google Play temporarily free and on-sale apps. Recently I’ve noticed that those particular articles are not displayed properly, i.e. there are no links. Here is the screen:

![Screenshot_2019-12-20-19-25-42-512_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/71327307-3efd2e00-2507-11ea-8a3f-9eaeedd0a8fb.jpg)

and here how it should look:

https://www.androidpolice.com/2019/12/20/android-apps-games-winter-sale-dec-20-2019/

Unfortunately I can’t point out since which *HNR* ver. the problem occurs.

Interestingly, I’ve found a couple of those articles still within *HNR*, displaying links properly until I’ve reloaded full text, which resulted in links disappearing again.

**Comment by afmbsr** [comment]
I'm using v0.11.5, the links appear normally
![Screenshot_20191223-075454](https://user-images.githubusercontent.com/38974362/71343369-b024fb80-2570-11ea-98dd-a8d49bd7b27c.png)

**Comment by ThomasLeigh** [comment]
@afmbsr Thank You for pointing this out. Did You use “Reload full text” on those articles?

I have already no articles from this series so I can’t do anything now. Once I’ve received such an article again, I’ll experiment with content extract rules and root elements - i.e. I’ll remove all the rules and then I’ll check what will happen...

**Comment by afmbsr** [comment]
Yes, I reloaded the full text because the part containing the links does not appear in the original text

**Comment by ThomasLeigh** [comment]
It indeed has been a case due to Remove Content Rules on My side.
