### ISSUE TITLE
Indication circle sometimes double-blinks.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#394]
This time a little surprise in a form of a video with... oh My: My voice ! :)

https://drive.google.com/open?id=1CAOxljDV1SdcDLyELSV9Lx4YrKu85RJ9

**Comment by yanus171** [comment]
It looks much better with voice! Glad to hear it.

Is the blinking so disturbing? I put much efforts to determine the start 
and finish of CPU/storage intensive processes in the app. And still there 
are some cases when I just wait for 5 seconds and hide the circle 
unconditionally.
The much so works falls in the web view (html parsing) component, which 
runs asynchronously and may separate the process by time...

Try to repeat this video with process info enabled in settings

**Comment by ThomasLeigh** [comment]
> It looks much better with voice! Glad to hear it.

Glad You enjoy it. From time to time I wonder on a *HNR* YouTube channel, with various how-to’s in a similar mold.


> Is the blinking so disturbing?

I find it disturbing to a degree in which it’s not indifferent whether it blinks or not. I could live with it, though. Keep in mind that for some users blinking may be associated with something not perfectly working.


> I put much efforts to determine the start and finish of CPU/storage intensive processes in the app.

Worth admiration, **congratulations on that**.


> Try to repeat this video with process info enabled in settings

Here You are:

https://drive.google.com/open?id=1CCoYVIyhIVzhWlL1AuLmlvaOWBG40L5W
