### ISSUE TITLE
Articles unexpected jump.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#395]
Since the newest ver. articles “jump” unexpectedly (i.e. they jump a little bit up), as it is illustrated in the video below:

https://drive.google.com/open?id=1CE_lqyg6kSuR2Ux2uFtaGGD-n3ZXuNuu

**Comment by yanus171** [comment]
Grant access to video please

**Comment by ThomasLeigh** [comment]
Done. I’m sorry, I was not aware that it requires this.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.0

**Comment by ThomasLeigh** [comment]
It seems it does not occur anymore, I’ll check this out few more times and let You know.
