### ISSUE TITLE
Youtube videos don't work

### ISSUE THREAD

**Issue by afmbsr** [yanus171/Handy-News-Reader#396]
YouTube videos can no longer be played directly from within HNR!
![Screenshot_20191230-174547](https://user-images.githubusercontent.com/38974362/71612969-d07a3900-2bb4-11ea-8d84-100d2304a026.png)

**Comment by yanus171** [comment]
Give a link to problem article. I can watch videos in HNR on my feeds

**Comment by afmbsr** [comment]
All of my feeds have the same problem when an article includes a video from YouTube, I can only watch the video by opening the link.

 Generally you can try this:
http://feedproxy.google.com/~r/WCCFNews/~3/AHfSY7trGYM/

**Comment by yanus171** [comment]
This link shows video inside article. Do you use the last HNR version? Try 
to update webview.

**Comment by afmbsr** [comment]
Yes, I use v0.11.9, I tried it in various ways and on two different phones, but without result.
![20191231_184502](https://user-images.githubusercontent.com/38974362/71629664-c6d1ef00-2c0f-11ea-8d14-35f25d60e543.gif)

**Comment by afmbsr** [comment]
There are discussions on the web about the same issue:

https://stackoverflow.com/questions/58502467/the-embedded-player-shows-please-click-here-to-watch-this-video-on-youtube-to

**The issue may be related to YouTube**

**Comment by yanus171** [comment]
They tell that the problem is on server side

**Comment by afmbsr** [comment]
Yes, it looks like that
 Because today I have tried many apps that have embedded YouTube player, and I found that they have the same problem as well.

 It is up to you to close or keep the case

**Comment by afmbsr** [comment]
Suddenly .. YouTube videos began working again from within the articles a week after stopping. 

![20200105_074004](https://user-images.githubusercontent.com/38974362/71775348-6dabe780-2f90-11ea-84ed-7399255824a4.gif)
