### ISSUE TITLE
Video-related volume buttons action.

### ISSUE THREAD

**Issue by AI-IMED** [yanus171/Handy-News-Reader#397]
- When setting volume buttons whether to move to the next article |  Previous or to scroll the page up |  Down, the buttons become useless (**lose their primary function**) when playing a video clip directly from within _HNR_ **, because the buttons don't work for the volume control of the video!**

- I suggest temporarily disabling any action of the volume buttons except the default setting when playing the video until the video is paused.

**Comment by yanus171** [comment]
I wish I could know when video is playing

**Comment by afmbsr** [comment]
When you click on it ... right?
 I wanted to mention that I mean all of the videos and not only YouTube videos, because YouTube videos do not work from within HNR

**Comment by ThomasLeigh** [comment]
Or maybe we could add an option in settings: *Disable volume buttons action on video* - with the description: “If an article contains a video, disable volume buttons action temporarily”.

**Comment by yanus171** [comment]
I say again: I have no info in the app webview, wherever the user started to play video

**Comment by ThomasLeigh** [comment]
I mean it could be based only on video detection (is there any video within an article) - not on if the video is played or not at the moment.

**Comment by afmbsr** [comment]
@ThomasLeigh 
I do not think that this method is useful, because perhaps the person does not want to play the video sometimes, and this results in the failure of the audio button actions automatically when reviewing an article that contains a video and thus the person will be forced to use the default procedure in this case
