### ISSUE TITLE
Accessing the past archives

### ISSUE THREAD

**Issue by Preformer** [yanus171/Handy-News-Reader#399]
Since downloading all the articles from a blog is kind of complicated (there's an open issue about this), at least getting to access the past archives would be very nice.
 
![This is an example archive of a blogspot blog](https://i.imgur.com/WWuy0TS.png)

Thanks.

**Comment by yanus171** [comment]
Please move this post to #290 and close current issue

**Comment by Preformer** [comment]
@yanus171 Might be a bit related to getting all the articles, but would it be possible to get the archive separately and opening articles through it without saving them?

**Comment by yanus171** [comment]
Yes, just open that web page in Handy news reader (Read now) and browse 
further to any links (again with Read now)

**Comment by Preformer** [comment]
Exactly :P

To open the archive you've to first open the blog in a browser first. I wanted to ask if the archive could have been made available in the app itself.

**Comment by yanus171** [comment]
1. Read now the blog page.
2. Read now one of archive year page
3. Read now one of the article

All actions in app. What do you need else?

**Comment by Preformer** [comment]
Where can I find the action described in the second point?

**Comment by yanus171** [comment]
Tap on the link and select Read now

**Comment by Preformer** [comment]
As I said previously, you've to first open the blog in a browser first... I wanted the archive separately in the app... If its possible.

**Comment by yanus171** [comment]
Open the blog in browser, tap share, choose Read now - the HNR will be 
opened. Then choose in article menu Create shortcut, place it on the home 
screen ...

**Comment by Preformer** [comment]
I couldn't find create shortcut, where is it? Even if I do create shortcut, it'll only lead me into opening the blog in Read Now, right? I don't see the archive in that screen.

**Comment by yanus171** [comment]
Give me a link to that page

**Comment by Preformer** [comment]
I found the create shortcut (was looking from inside the article, it is outside). The shortcut is for HNR's list of downloaded articles. I was looking for an archive like the screenshot in my OP. From where I could open all of the articles of the blog even when they're not downloaded in HNR.

**Comment by yanus171** [comment]
There is a "Add shortcut to home screen" in the article menu. (Scroll menu 
to bottom)

**Comment by yanus171** [comment]
Link! Give me a link!

**Comment by Preformer** [comment]
I found the shortcut option, but it doesn't seem relevant. Here's a link: [Sample blog](http://truthnothingness.blogspot.com/?m=1) This is what you get after opening the shortcut: ![This is what you get after opening the shortcut](https://i.imgur.com/mR85IoJ.jpg) How is this relevant at all? I was originally asking if I could get the list of all the articles of the blog (that is, the archive) which you get after opening a blog, divided by year - month.

**Comment by Preformer** [comment]
The difference in the archive from the blog in a browser and HNR's list is that in the browser you can get the list of all the articles, and in HNR we can only get some of the latest articles that the RSS system allows (mostly 5 in my experience but sometimes more like 10 - 20).
