### ISSUE TITLE
“Test feed” blocked the app.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#400]
This message I’ve received via HNR website:

> I'm new in using the reader and he is really great. I have installed about 15 feeds and today I clicked by mistake on the button "create test feed". Now when I open the app on my Huawei P20lite always the test Feed is opening and the app is blocked and I cannot change the feed or do something in the app. Restarting the app and the phone does not help. Do you have a solution how I can solve this problem? Thanks Stefan

**Comment by yanus171** [comment]
Try to delete app data. For further restore form auto backup

**Comment by ThomasLeigh** [comment]
>“Thanks it worked like described”
