### ISSUE TITLE
Incorrect article (publishing) date displayed

### ISSUE THREAD

**Issue by Preformer** [yanus171/Handy-News-Reader#402]
![original](https://i.imgur.com/8dAyk6L.png)

![In HNR](https://i.imgur.com/ktAs5Nz.png)

Happens many times. Reading through "Read now".

**Comment by afmbsr** [comment]
Correct ... When an article is shared from the browser by (Read now or Read It Later), the article takes the share date and not the date the article was published.

**Comment by yanus171** [comment]
The published date could be acquired only from RSS
