### ISSUE TITLE
Non-intrusive pop up to add clipboard's URL to read later or new feed on launch

### ISSUE THREAD

**Issue by Preformer** [yanus171/Handy-News-Reader#405]
It should be checked if the clipboard's content has any URL, and only if it does should we get a small pop up at the bottom with two options - Read later and Add feed. I think adding Read now is unnecessary, but it can be added too.

**Comment by yanus171** [comment]
Same as #406?

**Comment by Preformer** [comment]
No...

**Comment by yanus171** [comment]
From what source you have to share the text?

**Comment by Preformer** [comment]
If you have a link in clipboard it should ask you to save it after opening HNR, not related to #407.

**Comment by yanus171** [comment]
The Android share our view intent from other app that displays HNR Read now and later don't use the clipboard. I still don't understand you

**Comment by Preformer** [comment]
I was suggesting this issue as a feature request, maybe I should have put
[Feature Request] in the title, my bad.
