### ISSUE TITLE
Tap regions left and right not responding

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#409]
After updating from 0.11.5 to 0.12.2 via f-droid, the tap regions on the left and right edge of the screen no longer respond, to page up/down when viewing an article. The top and bottom and corner regions are still working.

**Comment by yanus171** [comment]
Check Taps enabled article menu item

**Comment by yanus171** [comment]
The left region is used for bridges slider. But the right should work, but it doesn't. I will check it.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.3

**Comment by JohnVeness** [comment]
That seems to work great, thanks :)
