### ISSUE TITLE
Touch-friendly scrollbar in sidebar list of feeds no longer works

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#410]
In 0.12.2, the thick, touchbar-friendly scrollbar in the sidebar list of feeds no longer works. If you try to use it, it immediately changes to a thin, normal, scroll indicator.

**Comment by yanus171** [comment]
What a scrollbar? Add a screenshot please

**Comment by JohnVeness** [comment]
This thing:￼

You used to be able to drag the thumb to quickly scroll up and down the feed list. Now if you try to drag the thumb it turns to:￼

**Comment by JohnVeness** [comment]
This seems to no longer happen in 0.13.1.
