### ISSUE TITLE
Sidebar always reachable.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#416]
The side panel in HNR is highly useful, allowing to switch between various groups of articles during the reading. It could be of a great improvement to allow to pull out the sidebar also while reading a single article.

**Comment by yanus171** [comment]
At first it would conflict with next article swipe. And for the second it 
would be hard to implement while it's not too hard to go back to article 
list (via back device button, choose menu item or back button in the end of 
the article text) and use sidebar from article list

**Comment by ThomasLeigh** [comment]
Ok. I am aware that even if You would implement something like ‘Back Button Action’ (in which one can choose between 1) go to the previous article and 2) pull-out the sidebar)  within article settings, it could still interfere with native Android gestures (newer Androids may have this gesture ascribed as a back button). Or maybe You could still be able to overwrite this Android feature, and therefore it could make sense.

Although it’s not so hard to go back to have the access to the sidebar - **it still could be easier** for those who much more often rely on the sidebar than use a back functionality.
