### ISSUE TITLE
Article Web Search - double-search bug.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#418]
1. Initiate the Article Web Search.
2. Paste an article URL into the field and confirm.
3. The article could be found and placed on the very beginning of the list - tap on it.

![Screenshot_2020-03-05-00-16-32-490_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/75932764-91988600-5e78-11ea-8b99-933cd35a8192.jpg)

4. Then repeat the whole process **with the same article URL** (because maybe You’ve deleted the article by mistake) - this time the article item within the results is displayed differently, as in the following screenshot:

![Screenshot_2020-03-05-00-17-01-679_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/75932772-965d3a00-5e78-11ea-832f-b7ddcc6d11f0.jpg)

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.0

**Comment by ThomasLeigh** [comment]
Fixed, thank You. :)
