### ISSUE TITLE
Article Shortcut may does not work offline.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#419]
1. While offline, choose *Share › Add article shortcut* from the menu.
2. The *Downloading images* shows up (with a working indicator) - nothing else happens, but this message and an animated progress.

If online, the whole thing works with no issues.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.0

**Comment by ThomasLeigh** [comment]
I get the impression that this and a few other issues reported in separated threads are related to that HNR sometimes did not load images during the refresh, (at least in my case) with no apparent reason (nothing to do with images limit or phone free storage space). I’ll observe the off-line behavior for a while, because now it seems to load images and show them offline successfully.

So, although this particular issue also seems to be fixed, I’ll take a closer look, test a little bit longer, and then close the issue, if it wil remain that way.

**Comment by yanus171** [comment]
This issue is related to shortcuts only, not too article images

**Comment by ThomasLeigh** [comment]
> This issue is related to shortcuts only, not too article images

The reason I think it has something to do with images is my first post on the beginning of this thread - when an attempt to create a shortcut resulted in an image-related action.

**Comment by ThomasLeigh** [comment]
Works fine, thank You :)
