### ISSUE TITLE
"Ghostly Unread"

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#42]
Unread articles' count shows a particular number although the list is empty.

I could re-install the app or clear the cache but **I don't want to lose My Favorites** which now it isn't possible to recover (they can be only exported by sharing).

See how it looks - the number of "ghost articles" is displayed both on the sidebar and the widget.

https://drive.google.com/file/d/1cVs4G6_AT3ztDWvu2UAinYRbkFcSIqWg/view?usp=sharing

**Comment by yanus171** [comment]
Try to describe the sequence of action which has led to such situation. I tryed to set all as read from unread section, but I have no your effect

**Comment by ThomasLeigh** [comment]
Unfortunately I can't do that because I don't know when exactly this issue occurred. I just suspect it to have something to do with adding and removing feeds because during this process I've noticed some strange behavior (I add a feed, there are some new items in it, but then after a while they disappear - but this occurred once or twice, and not as a repeatable rule).

**Comment by SIRSteiner** [comment]
Does this problem still exist? If not, please close, because I think that due to the large number of issues it is difficult for @yanus171 to work through everything.
