### ISSUE TITLE
Persistent error display while offline. 

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#421]
Although I have *Detailed progress technical info* disabled, the app still may show some error messages (a tiny red text on the top) from time to time. While working offline, the message is always displayed, i.e. within each and every article, and I need to constantly single-tap on it to hide the message:

![Screenshot_2020-03-04-23-10-15-970_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/75933177-9873c880-5e79-11ea-8119-d19eb5ee96ac.jpg)

I guess there are errors which may be important enough to inform a user even if *Detailed progress technical info* is disabled. Could it be, however, that this particular kind of a message mentioned above, the one which persists while offline, won’t be bothering so much?

**Comment by Ryuno-Ki** [comment]
I noticed, that it disappears once you start scolling down.

**Comment by ThomasLeigh** [comment]
Yes, but in my case often not permanently. I mean it disappears while scrolling, but it often comes back as soon as I stop scrolling.

**Comment by yanus171** [comment]
Ok, this makes sense


Thomas Leigh <notifications@github.com> 5 марта 2020 г. 2:38:36 написал:

**Comment by ThomasLeigh** [comment]
In case of the newly obtained articles (within the “unread”), if I am offline, error messages are displayed on top of each article - which overlap article titles. To see those titles I need to tap on the error message on each article I browse.

Examples of such messages include phrases like: “Java.net ConnectException. Failed to connect to...” or “Java.net UnknownHostException. Unable to resolve host”.

**Comment by yanus171** [comment]
In the latest release https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.0 the error text is hiding by article text scroll. May be that is sufficient?

**Comment by ThomasLeigh** [comment]
@yanus171  Currently I don’t see this error at all while off-line, I’ll perform further tests to find out whether it shows up or not.

**Comment by ThomasLeigh** [comment]
@yanus171 Does this error should be still visible at least for a moment?

**Comment by yanus171** [comment]
What exact criteria should be used to determine whether to show error out not?

**Comment by yanus171** [comment]
May be we just need a preference to not to show an error at all?

**Comment by ThomasLeigh** [comment]
I find it very interesting that **“Page scroll 90%” respects the error message while calculating the distance an article should be scrolled** on tapping the bottom on the screen (where the error message is currently displayed). Only thanks to this the error message does not require any additional action from a user to hide the error: one is able to keep reading, as usually. **Thank You for that.**

Now the only remaining thing is to make this error user friendly, see https://github.com/yanus171/Handy-News-Reader/issues/420 .


> What exact criteria should be used to determine whether to show error out not? May be we just need a preference to not to show an error at all?

**I think that this kind of errors are definitely useful.** One example are images which sometimes cannot be loaded for some reason. A user may expect to see images and it could be a good idea to inform them that something goes wrong with that. The only thing I’d love to see is to **do it in a human way**, i.e., without technical wording (see https://github.com/yanus171/Handy-News-Reader/issues/420 ).
