### ISSUE TITLE
Make ‘Read It Later’ items order fixed.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#422]
Within Favorites I have both read and unread articles. If I open a random unread article out of the middle of the list - it doesn’t affect the items’ order within Favorites in any way - the article just becomes marked as ‘read’.

If I do the same action within ‘Read It Later’, the items’ order has been changed - which may be pretty confusing. I have an impression that the order may be changed also due to other reasons, but I haven’t looked at it so deeply.

Could the ‘Read It Later’ items’ order be similar as in case of Favorites - i.e. with no changes if an article has been opened (read)?

**Comment by yanus171** [comment]
It's a feature. The article in read it later changes its date to current, 
so the last read articles are always at the top of Read it later list

**Comment by ThomasLeigh** [comment]
> It's a feature. The article in read it later changes its date to current,
so the last read articles are always at the top of Read it later list

What is important to me is the order of articles not being disrupted, even if the order is created from scratch on the basis of the time when I add an article to ‘Read It Later’. Everywhere else within Handy I have the oldest articles on the top. Opening an article does not change anything, with the exception of ‘Read It Later’, in which when I tap on the first article on top (which has been already read), it is moved to the very end of the list, which is definitely undesired and confusing.
