### ISSUE TITLE
‘Reading images’ message sometimes persists offline.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#423]
While using the app offline, sometimes the circle indicator is constantly displayed - once I tap on it, it shows ‘Reading images’ message.

**Comment by yanus171** [comment]
I see thit bug for a long time. But I can't understand the source of it still

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.0
