### ISSUE TITLE
‘Mark as Unread’ menu item disappeared

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#424]
Sometimes an article may be accidentally tapped and, therefore, marked as read. In such a case one may find useful to be able to mark it as ‘unread’ to fix the mistake.

**Comment by yanus171** [comment]
There is an article menu item Mark as unread ... Stop. It's disappeared... 
It should be fixed

**Comment by Ryuno-Ki** [comment]
Yes, missed that option as well after my last update. Thanks for bringing it back :-)

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.0

**Comment by ThomasLeigh** [comment]
Thank You.
