### ISSUE TITLE
Move ‘Show html’ from ‘Share’ to ‘Display options’.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#425]
I think it could be a better place for this menu item.

**Comment by yanus171** [comment]
Show html operation also creates a file /storage/feedex/html.html

**Comment by ThomasLeigh** [comment]
Do You consider this a reason to treat it as “an action of a sharing nature”, so to speak? I mean, because the app creates a file behind the scenes, should we consider this more of a sharing action than a display action? I’m not sure if I get this right - but if a file is important, it could be a good idea to rename ‘Show HTML’ into ‘Show (and save as) HTML’.

**Comment by yanus171** [comment]
I would prefer to put it into deeps for it's mostly for developer purposes. (Not for display options). But I don't want to create a new menu item group Additional ... 

May be I will try to rename it into Share HTML and see if there is any app on my phone that is capable for processing such a sharing intent (view html text)

**Comment by ThomasLeigh** [comment]
Let me get this right. If I am a developer, what is more important to me if I have a reason to use this feature? To see a html within Handy - or to have a .html file saved within the device storage and then open it... etc.?

If the latter is more important, then I think “Share” is a good place, let it be renamed to “Save as .html”, and it would be alright.
