### ISSUE TITLE
How to ensure that particular articles never will be deleted?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#426]
@yanus171 answered:

> Favourites are never deleted automatically even during Delete all 
operation in article list screen. Read it later articles auto deleted as in 
other feeds.

**Comment by ThomasLeigh** [comment]
@yanus171 

So if I set the limit for 4 days, articles present within ‘Read It Later’ also will be deleted after that time?

What if an article is placed within ‘Read It Later’ and ‘Favorites’ in the same time?

**Comment by yanus171** [comment]
Then the article would never be deleted until it would be removed form favourites
