### ISSUE TITLE
Open the app within the Last Viewed Article - and more.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#428]
It could save time if the app could open the last viewed article automatically on the app’s launch (remembrering the reading position, as currently it can do). I imagine something like this within HNR’s settings:

Open the app in...
› Unread
› Favorites
› Read It Later
› Last Viewed Article
› Choose the category...

‘Choose the category...’ refers to feed custom categories defined by a user (those which are listed on the HNR sidebar).

I think we could include options which already are present within custom shortcut feature - as a good alternative.

**Comment by yanus171** [comment]
What about existing setting: Article text - Remember the last article ?

**Comment by ThomasLeigh** [comment]
I mean something that makes the app to open the recent article **right away after I tap the app’s icon**. Something that automatically detects which article has been opened most recently and open it right away.

**Comment by yanus171** [comment]
Try that option

**Comment by ThomasLeigh** [comment]
**Could it overwrite custom shortcut feature?** I mean, I have several custom shortcuts to Handy on the desktop: the one which opens the app within “Favorites”, the one which opens the “Unread”, and the one which opens “Read It Later”. It would be great to have the ability to open the last viewed article **regardless of which shortcut I use to open the app**. In other words, it would be great if I don’t need to think which app’s shortcut I need to tap on to read the last viewed article (currently it must be the main shortcut - given that a user doesn’t use back button to exit the app - I suppose, however, that many users quit apps this way, alongside many users which use home button to “quit” apps).

I know I could create a shortcut to the currently read article, but I so much like the idea of automatically remembering the last viewed article :) - it’s so much easier and quicker. Custom article shortcuts are great to read multiple longer articles simultaneously.

**Comment by yanus171** [comment]
Again. It's already implemented. Turn on the corresponding app setting and 
if you start the app from standard app launcher icon you will get the last 
read article

**Comment by ThomasLeigh** [comment]
> if you start the app from standard app launcher icon you will get the last
read article

Could it work the same way, however, if I tap on a shortcut to Favorites, or any other custom shortcut to HNR?
