### ISSUE TITLE
Cross-shortcut “Article Web Search” action.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#430]
The ability to run the Article Web Search straight through the app’s shortcut on the desktop is fantastic, I didn’t realize that it is so easily accessible (!).

Currently it is available only through the main shortcut to the app (which I don’t use). It would be great to have it available regardless of what a shortcut is - a shortcut to display “Favorites”, the “Unread”, “Read It Later”, etc.

**Comment by yanus171** [comment]
You can create an original shortcut for app one which can be moved to any 
place on the home screen. To do so just drag the app shortcut to the home 
screen

**Comment by ThomasLeigh** [comment]
I know, but it would be easier if I don’t need to tap only on one special shortcut for the app to open the Article Web Search.

**Comment by yanus171** [comment]
Seems I can't get your mind. May be video would help?

**Comment by ThomasLeigh** [comment]
Here You are:

https://drive.google.com/open?id=1_LJCZp8E6BWxh6gb8LDaph1WgI7DE-HD

On the video You see that “Article Web Search” action is present only within the app’s main shortcut. I don’t use that shortcut at all, I have only three custom shortcuts: one which opens “Favorites”,  another one opens “Unread”, and another one opens “Without a feed”. I’d love to be able to perform “Article Web Search” directly by holding on those shortcuts.

**Comment by yanus171** [comment]
Long tap shortcut actions are available only from main app icon in Android. 
May be we need only one (main app) icon with several long tap menu items: 
Favourites, Unread, Web search?

**Comment by ThomasLeigh** [comment]
> Long tap shortcut actions are available only from main app icon in Android

Do You mean that it cannot be attached to custom shortcuts, like the one to Favorites, for example?


> May be we need only one (main app) icon with several long tap menu items:
Favourites, Unread, Web search?

No, no - it is **insanely fantastic** that now I can open “Favorites” with one single tap, **please leave this feature in place :)**

**Comment by yanus171** [comment]
You understood me right. It can't be attached to custom shortcuts.
