### ISSUE TITLE
Report issues into GitHub directly from the app.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#434]
Recently I encountered an issue with a music player I use (Vinyl Music Player - https://github.com/AdrienPoupa/VinylMusicPlayer/releases). I found out that it has an in-built GitHub reporting system, which even can attach a bunch of technical information about a user’s device and OS. Once I’ve reported the issue, a GitHub thread has been automatically created on my behalf.

![Screenshot_2020-02-21-01-45-49-718_com poupa vinylmusicplayer](https://user-images.githubusercontent.com/26142231/76035214-37afc300-5f41-11ea-9a32-9dd019103069.png)

I wonder would You be interested in implementing a similar feature within HNR?

**Comment by yanus171** [comment]
Do you remember your GitHub password to enter it every time you have to 
create an issue? I think the link to browser is more practical. May be we 
should move it from the app about section to some more noticeable place

**Comment by ThomasLeigh** [comment]
The bottom of the sidebar?

**Comment by yanus171** [comment]
The main problem here is that the much post of users dinner has GitHub 
account and are lazy to create one to open issue. May be create a special 
account for them ?...

The bottom of the sidebar in never reachable for my feed list :)

**Comment by Ryuno-Ki** [comment]
Well, you could ask for a one-time [Personal Access Token and offer a form](https://gist.github.com/bmcbride/62600e48274961819084).

**Comment by ThomasLeigh** [comment]
Maybe within settings, create a visually distinguished area above all the settings’ categories, with a ‘Report Bugs and Ideas’ link?
