### ISSUE TITLE
Cannot bring back the in-article menu. 

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#436]
1. Within an article disable Tap Actions. 
2. In settings disable auto full screen mode. 
3. The question is how to bring back the in-article menu, because it's still full screen and I cannot enable Tap Zones again.

**Comment by ThomasLeigh** [comment]
Oh, fortunately the context menu action of disabling Tap Zones is correlated to a corresponding setting within the app’s settings, so I’ve been able to turn it on again.

It was traumatic experience not to be able to preserve articles by adding to Favorites ;) .

**Comment by ThomasLeigh** [comment]
Do You think it should be considered as a bug? I’m not sure...

**Comment by yanus171** [comment]
Use should show the action bar by tap on the right bottom corner. In action 
bar press menu button (...) and check Tap zones enable.

By the way how did you opened the menu in screen mode before it was 
implemented show menu by tap?

**Comment by ThomasLeigh** [comment]
> Use should show the action bar by tap on the right bottom corner.

Once I disabled Tap Actions, the right bottom corner hasn’t reacted.

**Comment by yanus171** [comment]
The source of problems that I have a rooted phone with a hardware menu button.
The tap action enabled menu item was designed to ease video operations in 
article text. And it should be easily turned on and off. Any ideas how to 
achieve it?

**Comment by ThomasLeigh** [comment]
> By the way how did you opened the menu in screen mode before it was
implemented show menu by tap?

I tapped on the bottom right.

Interestingly, on my phone I don’t have the equivalent of a physical menu button at all. It is possible, but I would need to use virtual Android buttons which I don’t want to.


> And it should be easily turned on and off. Any ideas how to achieve it?

Perhaps by introducing custom swipe action or more Tap Zones. For example, swipe down on the HNR full-screen would show the menu. Or instead of one there could be two biggest zones: the upper part of the screen and the bottom one. For convenience I’d recommend to make one of them 75% of the whole height of the screen, and the second  one 25%. And this 25% would be always active (it would be omitted during Tap Zones Disabling).

**Comment by yanus171** [comment]
This will cause the problems with video operations

**Comment by ThomasLeigh** [comment]
Then the only thing which comes to me is, again, the sidebar reachable from a single article. Maybe there is a way for it to not interfere with slide to the next./prev. article: those gestures could be accepted by the app if they haven’t been performed from the edge of the screen. While the slide right from the edge of the screen could show the sidebar, on top of which You could put three-dots or something else to tap and show the menu.
