### ISSUE TITLE
Aesthetic & elegant swipe left/right.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#44]
I strongly believe in the power of details so I'd like to share with You **a way of swiping left/right** which I find absolutely amazing and I'm sure it can make Our app significantly better looking. Something like this one presented in the screen recording below - or something similar. Fingers crossed that You'll love it too :) !

https://drive.google.com/file/d/1OFPdgP2fO3OQPZ-oPgjPldQZFvp3eM52/view?usp=sharing

**Comment by yanus171** [comment]
Please describe the concrect differences from current swipe
С уважением, Алексей

Thomas Leigh <notifications@github.com> 6 января 2019 г. 4:54:09 написал:

**Comment by ThomasLeigh** [comment]
1. The item area doesn't change the height during the swipe (now it changes because of the text adjusting to decreasing space - it doesn't look well and it bothers the overall experience because the height change moves other items as well).

2. Now there is almost no animation, for example the icon accompanying swiping shows itself right away - i.e. without smooth animation from 0 to 100% visibility. Another thing there are no colors which may show up gradually while swiping (see the previous video).
