### ISSUE TITLE
" open link " options should be on the first page!!!

### ISSUE THREAD

**Issue by tuchit** [yanus171/Handy-News-Reader#441]
I guess "open link" options is the most-used button.
Why don't you just add it to the preview page? As a button on the bottom or in three dots options directly.(now in the three dots options -- share -- open link.
No tap tap then tap for the most useful button plz!

**Comment by yanus171** [comment]
No need for tap tap. Just tap on the article title

**Comment by tuchit** [comment]
Thx for the tip.😀

**Comment by JStyle21** [comment]
Wanted to ask about this feature but then i found this issue, thanks for the tip @yanus171 but it wasn't obvious at all, maybe color the title as a link or style as button, somehow making it appear clickable?
