### ISSUE TITLE
Make it easier to reach articles at top of list

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#442]
With modern large-screen phones, when operated by thumb in the hand that is holding the phone, it can be hard to reach articles at the top of the screen in the article list. It would be great if HNR had some features to help with this. I can suggest some ideas if wanted.

**Comment by yanus171** [comment]
What ideas?

**Comment by JohnVeness** [comment]
I have a few, which can be divided into two broad categories: having entries still at the top of the screen/list but making them easier to reach, and having entries at the bottom of the screen/list.

- Add a banner/information section above the article list when first entering a feed, taking up the top quarter or third of the screen, making the top article easier to reach. As the user scrolls up, the banner would scroll up too, so you would still be able to view the same number of articles per screen.

DoggCatcher, a podcast app, does this.

Before scrolling:
![](https://i.imgur.com/iaSO6Od.png)

After scrolling:
![](https://i.imgur.com/LKXLeh1.png)

- Display the article list as usual, but allow the user to pull down the article list beyond where it would normally allow you, without it springing back up to the top. A void would be revealed above the top of the list.

- In addition to the existing "Display oldest articles first" setting, add a setting to scroll the list to the bottom by default when entering a feed. That way, the newest articles would be immediately viewable at the bottom. This wouldn't make much difference with feeds that don't have many entries, though.

- Populate the article list starting at the bottom of the screen rather than the top.

I realise some of these ideas are more radical than others. The banner idea is probably the one that would seem the least odd to an end user. In any case, I think many apps (ones that use lists a lot, such as email apps) will be facing this problem, and it would be nice if HNR could innovate here.

**Comment by yanus171** [comment]
This problem is actual. Especially after next app update where I will 
introduce full screen mode in article list too.
From you proposions I like variant with scroll article list down when older 
articles come first (at the bottom of the list). But why we need a separate 
preference for it? I think this should be the only mode when older articles 
first setting is checked

**Comment by JohnVeness** [comment]
Thanks for considering this. I agree that probably doesn't need to be a separate option. Thunderbird (the desktop mail client) automatically scrolls the message list to the bottom when the sort order is such that latest messages are at the bottom, so it's already a UX pattern that exists.

**Comment by JohnVeness** [comment]
Just for your interest, another app that has chosen the "large banner at top" approach is the next version of Firefox, on its tab screen. At first it looks like wasted self-promotional space, but it makes sense after some thought.

 ![](https://i.imgur.com/ixMw1Yq.png)

After scrolling:
![](https://i.imgur.com/p9qbtkV.png)

**Comment by yanus171** [comment]
In the latest release https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.0 the action bar is auto hiding by list scrolling down (when it is show by tap on right bottom edge). Try it
