### ISSUE TITLE
HNR inconsistent star indicator.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#445]
1. Browse unread articles one by one (i.e., displaying their text).
2. Add the currently viewed article to Favorites (“star it”).
3. Swipe to the next article.
4. Swipe back to the previous article, i.e., the one which You’ve just marked as starred.
5. View the Action Bar and see that the star indicator is disabled, as if the article hasn’t been added to Favorites.

**Comment by ThomasLeigh** [comment]
Thank You, it works fine now. :)

**Comment by yanus171** [comment]
I don't see it's fine

**Comment by ThomasLeigh** [comment]
Oh, this is a surprise.

**Comment by ThomasLeigh** [comment]
It does not work on my HNR again.

This issue is related to the previous one: https://github.com/yanus171/Handy-News-Reader/issues/301
