### ISSUE TITLE
HNR may lose content while switching between apps.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#446]
It looks as follows:
1. An article has been loaded/displayed - I see its text and image.
2. I switch to the other recent app and go back to the HNR.
3. Now the article looks exactly like before being fully-loaded, i.e., no text, no image. And the loading indicator sticks to “Reading images”, although it’s still online.

See this video:
https://drive.google.com/file/d/1ViQwem7qbGCbisC9sqjp25-uyDfezNIa/view?usp=sharing

**Comment by yanus171** [comment]
Can't reproduce it. Try to find the detail circumstances of that bug

**Comment by yanus171** [comment]
What about latest release?

**Comment by ThomasLeigh** [comment]
@yanus171 
It seems it does not occur anymore, I’ll check this out few more times and let You know.

**Comment by ThomasLeigh** [comment]
The issue still occurs.
