### ISSUE TITLE
Load all images in Without images mode

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#447]
1. Disable “Display images” within the app’s settings.
2. View any article which should have images (like [this one](https://blog.documentfoundation.org/blog/2020/03/02/our-new-extensions-and-templates-page-is-getting-ready/), for example).
3. Go to *Reload › Load all images* from the context menu, to display images within this article.

I’ve tried with various articles from different feeds - with the same result, i.e., **nothing happens** (images haven’t been loaded).

If I have “Display images” enabled in the settings, images are displayed.

**Comment by yanus171** [comment]
This is the meaning of display images setting

**Comment by ThomasLeigh** [comment]
What is the intended action for *Reload › Load all images* from the context menu then?

**Comment by ThomasLeigh** [comment]
And could it be available to display images on demand, i.e., having the option disabled within the app’s settings, but being able to load images within a currently viewed article on demand?

The reason I ask for this is that I generally don’t need images, but there are exceptions of the rule. Unfortunately those may be articles from different feeds, so I can’t set a separate rule to load images per particular feed because this is not the case.

Now in order to see images I need to change the app’s settings each and every time, however rare - it would be much of a help to be able to do it on demand via a context menu, i.e., temporarily per a currently displayed article.

**Comment by yanus171** [comment]
The Load all images menu item  works only when display images setting is checked and it loads images that were not auto loaded due to the max images per article setting.

**Comment by yanus171** [comment]
I think I can make this menu item work also in without images mode, so this command will load all current article images

**Comment by ThomasLeigh** [comment]
**Fantastic, thank You so much :) !!!**

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.1

**Comment by ThomasLeigh** [comment]
Wow, thank You, it’s fantastic :) !
