### ISSUE TITLE
Content divided into articles.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#450]
Could You please describe the following description in more details - how it works?

> “the url content is devided into articles by root class name, also there should set classname for article title, date and image”

**Comment by yanus171** [comment]
There should be long explanation ... In a few words I am developing a new 
feed load type suited for forum web pages with no RSS. So each post should 
be parsed as separate article. To setup a feed with such a load type a user 
would need to set class names for article html element, for date, for 
avatar (article image), for URL and others ... To ease that I have added a 
Copy class name context menu item to Reload with tags mode
