### ISSUE TITLE
Do we really need “Read it later”?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#452]
The more I’m thinking about it the more confusing it becomes. What do You think about this idea: let’s remove ‘Read it later’ and replace it with ‘Favorites’ which already exists.

In my opinion there is too much of a potential semantic confusion regarding all the functions ‘Favorites’ may act upon - and the existence of ‘Read it later’ in the same time. I mean that, for example, many users may use ‘Favorites’ for this very purpose: to mark articles to read them later. So it seems unnecessary to double this feature in a form of a separate ‘Read it later’ category.

**Comment by yanus171** [comment]
But don't forget about another purpose of Read it later: it contains all 
articles loaded with Read now and later operations which could be just 
temporary articles, not favourites

**Comment by ThomasLeigh** [comment]
> But don't forget about another purpose of Read it later: it contains all
articles loaded with Read now and later operations which could be just
temporary articles, not favourites

Should articles viewed via ‘Read now’ really be stored? Wouldn’t be better to do this like that:

• if a user chooses ‘Read now’’, HNR will open an article, but without storing/remembering it in any place,

• if a user chooses ‘Read it later’, HNR could add the article to Favorites? (in such a case the feature could be called ‘Read it later in Favorites’)?

**Comment by yanus171** [comment]
May be rename Read it later in Loaded from web? Or Without a feed?

**Comment by ThomasLeigh** [comment]
> May be rename Read it later in Loaded from web? Or Without a feed?

What do You think about “Passed On” or “Handed Down”?

**Comment by yanus171** [comment]
I can't find meaningful translation of these text to Russian. And may be even to English :(

**Comment by ThomasLeigh** [comment]
I was wondering what is the essence of this feature and concluded that it serves mainly for opening articles via Android Share action, from external web browsers. I was wondering what words could describe this, but in a non-technical manner. When a user wants to open an article in HNR, from external web browser, via Android Share feature, You could say that this article is handed down or passed on from a web browser to HNR.

**Comment by yanus171** [comment]
It is not only by from sharing form external browsers. It is also from Read 
now (later) operation from HNR

**Comment by yanus171** [comment]
May be "Without a feed"

**Comment by ThomasLeigh** [comment]
My concern is that “feed” is not the only possible source of content in HNR...

**Comment by yanus171** [comment]
And what? Whatr about "Without a feed" ?

**Comment by ThomasLeigh** [comment]
“Without a feed” suggests that this is the only place when one can use non-RSS sources, which is not true.

**Comment by yanus171** [comment]
Feed is not only RSS. It's an item in left menu which can be of three 
types: RSS, Web links and One page.

**Comment by ThomasLeigh** [comment]
> Feed is not only RSS. It's an item in left menu which can be of three
types: RSS, Web links and One page.

Oh... good point, I’ve been so into the RSS that I forgot about the broader meaning of a “feed”... Maybe my spirit is still much into the glory of the 90’ies, when RSS and Usenet, and FTP, and other stuff had ruled... :)

So, back to “WIthout a feed” - what do You think about “Off the Feeds”? Although some online translators do it wrong, it means “apart from feeds”, something like that. Sounds pretty modern imho. :)

**Comment by ThomasLeigh** [comment]
@yanus171  What about “Off the Feeds”?

If You don’t like it, let’s use “Without a Feed” instead of “Without a news feed” because the latter sounds like RSS-related. But I really curious of Your take on “Off the Feeds”.

**Comment by yanus171** [comment]
Without a feed translates like without a food :) And Of the feed translates 
to food too. That's why is added weird news


Thomas Leigh <notifications@github.com> 12 апреля 2020 г. 15:33:12 написал:

**Comment by ThomasLeigh** [comment]
@yanus171 

Not “of the feed” but “off the feed” - which really means “besides the feeds”. Like “off the Earth” means “out of the Earth”. 

“News feed” suggests that there are only news feeds within HNR, which is not true.

I think that food association wouldn’t be an issue since HNR users should know that this is not a food-related app. But in case it bothers You anyway, maybe at least “without a content source”? Or simply “without a source”?

**Comment by yanus171** [comment]
Can we close it?
