### ISSUE TITLE
This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled

### ISSUE THREAD

**Issue by relan** [yanus171/Handy-News-Reader#453]
**Describe the bug**
0.13.0 compilation fails.

**To Reproduce**
1. Run gradle assembleRelease.
2. It fails with:
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.

**Expected behavior**
Compilation should succeed.

**Additional context**
Full log: https://f-droid.org/wiki/page/ru.yanus171.feedexfork/lastbuild_202.

**Comment by yanus171** [comment]
I have added gradle.properties file with android.useAndroidX to github

**Comment by relan** [comment]
Thanks!
