### ISSUE TITLE
Control data usage

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#454]
I wonder if this idea worth sharing, due to Android has already its own native feature for that. If, however, we could have such a data counter clearly visible within the app - it could be helpful, especially if the app would have its own notifications on reaching a particular data cap.

I’m not sure, though, could this feature be a desired one...?

**Comment by Ryuno-Ki** [comment]
Hm, if there were options to load media only via WiFi, that would be sufficient (haven't checked).
Text is compressed well, i.e. should not hurt the data cap that much.

**Comment by ThomasLeigh** [comment]
@yanus171  What do You think?
