### ISSUE TITLE
What are the differences between various HNR versions?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#455]
Regarding **when and how often** new releases are published - and **what** exactly is published: what are the differences between HNR published on Google Play vs F-Droid vs GitHub?

**Comment by yanus171** [comment]
GitHub releases are most often. After fdroid robot find and compile new 
one, it generates and publishes APK file for fdroid.
Google play releases are published in rate cases when I think that last 
GitHub release is stable enough

**Comment by ThomasLeigh** [comment]
> After fdroid robot find and compile new one

Where does F-Droid robot find HNR? On GitHub? If so, how does it know that this specific version should be considered as another stable release?

**Comment by yanus171** [comment]
All releases are ment to be stable for fdroid

**Comment by ThomasLeigh** [comment]
Does F-Droid robot check HNR on Google Play - or GitHub?

**Comment by yanus171** [comment]
No. Fdroid robot knows nothing about For play

**Comment by ThomasLeigh** [comment]
So F-Droid receives more HNR releases than Google Play?

**Comment by yanus171** [comment]
Yes, but Fdroid had a big time delay (up to several weeks) from a moment of 
the GitHub release.
