### ISSUE TITLE
What is the approach about ads?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#456]
I remember Alexey speaking about wanting HNR to be completely ad-free. @yanus171 
 Could You please address this matter for our public FAQ for HNR website? Meaning: what is Your approach toward ads in HNR?

**Comment by yanus171** [comment]
The html web page article consist of hierarchical elements with content. 
Must every element has its identified by its class name. Among them are 
those which contain useful content and those that contains useless parts 
such as ads, menu buttons etc.

While loading web page article the HNR tries to automatically find the best 
web page element with an article text and to show only that content. Also 
the user can specify such an element manually.

Another feature is that the user can specify black list elements, which 
would be excluded from text.

To simplify this actions there is an article Edit mode where elements 
classes with web page content are displayed and user can tap on any of them 
to show, hide or specify as full text root element.

**Comment by ThomasLeigh** [comment]
**I’m so sorry that I haven’t specified my question well enough.** What I mean is Your take on ads within the app - since HNR is free, many free apps have ads, and in order to have an ad-free app, one must pay.

The topic which You’ve addressed, however, I’ll also use on the website.

**Comment by Ryuno-Ki** [comment]
Like: Are there any plans to show ads to help finance the app?
Or do you commit on will-always-be-adfree?
What about begging for donations? etc.

I think, that's what was on @ThomasLeigh mind.

**Comment by yanus171** [comment]
So I still can't understand the question

**Comment by yanus171** [comment]
How can open source app include the app? Any developer in that case can cut the ads from the app and release ads free version

**Comment by yanus171** [comment]
I can commit that app would never include ads. This is my point of view, especially because it's one of the main feature: read content without useless content - ads.

On the other hand the app is open source, so in case the ads would appear in the app, any person with near developer skills can cut the ads from the app and compile and release an ads free app version
