### ISSUE TITLE
Visual Picker (instead of Content Edit Mode = for non-HTML-users).

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#458]
IMO CEM is one of the most powerful HNR’s features. I’m constantly telling people about the HNR beating all the web-browsers out there, regarding a content-cleaning mechanism. I’ve never seen any better solution before - web browsers with their in-built ad-blocking mechanisms or ad-blocking plug-ins are still far away from what HNR is capable of - because HNR allows to pick even non-advertisement elements to hide (!). Some web browser plug-ins allow this, too - but it’s definitely a rarity.

There is one serious downside, though. In order to benefit from this HNR feature one need to know HTML. I’d love to see all the rest users be able to take advantage of this fantastic thing.

Therefore, I’d like to ask could be possible to allow at least some actions to be performed without a need to enter the code view (Content Edit Mode)? I mean that a user could tap & hold on various article parts and then chooses one of those:

- hide,
- show,
- set as article root,
- set as article title,
- set as article date,
- set as article image;

**Comment by yanus171** [comment]
Where is html in Editor mode? It just shows the borders of elements user can operate with. Each element is identified by its class name: in the beginning and in the end.

**Comment by ThomasLeigh** [comment]
> Where is html in Editor mode? It just shows the borders of elements user can operate with. Each element is identified by its class name: in the beginning and in the end.

All right, I mean those borders of elements. Don’t You think that users could have this easier without any visual changes/additions to the text? Just tap and hold and choose... :) It could be much less confusing - in fact, no confusing at all.

**Comment by Ryuno-Ki** [comment]
With what algorithm would you determine the selector for that element? :thinking:

**Comment by yanus171** [comment]
In the case of high level hierarchy of page elements the current solution seems to me optimal. 

There are more problems with URL key part of generated string (storm in the edit mode operation dialog title) which is added to corresponding preference. By default it is the page URL, but often it's useful to use only page domain, to apply rules to all that site articles...

**Comment by yanus171** [comment]
Another problem is that instead of set full text root, show hide operation are specified without URL, applying class name to All web pages, which causes  ambiguity when hidden element in one web page domain should be show on the other...

**Comment by ThomasLeigh** [comment]
>  In the case of high level hierarchy of page elements the current solution seems to me optimal. If you have more concrete ideas, tell them.

My idea is to allow the same functionality which is currently allowed by Content Edit Mode - without Content Edit Mode - which could be much more intuitive for non-technical users.

I don’t know how it looks “under the hood”. Do You mean that it is too difficult to implement?

**Comment by yanus171** [comment]
I still don't understand how it should look like in your view?

**Comment by ThomasLeigh** [comment]
> I still don't understand how it should look like in your view?

Edit Content View as is currently, is all right.

What I mean is its easier mode, so to speak:

Now when I want to mark an element as article root, or I want to hide or show an element within an article - I have to enter Content Edit View. Once I finish, I should “reload full text”.

What I mean is to allow the same actions or at least some of them (e.g., mark an element as article root, hide or show an element, etc.) **without a need to enter Content Edit View**. So, suppose I read an article, and I see an advertisement within it. I could tap and hold on that and then choose from the context menu “Hide”, text would reload itself automatically and there is no advertisement :) . All of that without a storm of tags within square brackets ;)
