### ISSUE TITLE
Move “Vibrate on swipe” from “Advanced” to “Behavior”.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#459]
It could be a better place for this option.

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.2

**Comment by ThomasLeigh** [comment]
Cannot find it there.

**Comment by yanus171** [comment]
It's in article text section. Notification now lacks behaviour. It was 
distributed among other sections. We should remove word behaviour

**Comment by ThomasLeigh** [comment]
> It's in article text section. 

I don’t find it there...

> Notification now lacks behaviour. It was distributed among other sections. We should remove word behaviour

I agree. Besides I guess that You’ve changed “Behaviour” into “Operation”?

**Comment by yanus171** [comment]
It was not my "operation" but your are right in meaning.
