### ISSUE TITLE
Allow Content Extract Rules to operate on domain addresses instead of particular web pages.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#461]
As Alexey has pointed out [here](https://github.com/yanus171/Handy-News-Reader/issues/458#issuecomment-611068145):

> There are more problems with URL key part of generated string (shown in the set full 5ext root operation dialog title) which is added to corresponding preference. By default it is the page URL, but often it's useful to use only page domain, to apply rules to all that site articles...

This is why I needed to correct Content Extract Rules entries to be applied on multiple articles instead of one particular article. It could be great for it to write only website domains, instead of particular web page addresses.

**Comment by yanus171** [comment]
But in common case the web domain can includes several sub domains, which 
can demand different extract content rules for each one. Even more: there 
is no universal algorithm to extract web domain from web page url

**Comment by Ryuno-Ki** [comment]
Well, I can tell from Python and JavaScript, that there are ways to pass an URL to a function and let it parse it into its different parts (e.g. hostname, path, anchor etc).

**Comment by yanus171** [comment]
Example two URLs:
www.news.com/sports/daily/54321.html
and
www.news.com/forum/thread/12345.html

Try to parse it and definitely extract the URL key for full text root. Take 
in mind that each of them has different class names for full text root.

**Comment by ThomasLeigh** [comment]
What about a mechanism which could just remove the last part from “/” to “html”? This could help, to some degree.

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.14.2

**Comment by ThomasLeigh** [comment]
Thank You.
