### ISSUE TITLE
Make “Article reading notification” better looking.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#464]
Now on my phone it seems to display nothing- which may be confusing:

![HNR Article reading notification](https://user-images.githubusercontent.com/26142231/79082334-57e35680-7d25-11ea-86d5-5c6b15958fc8.jpg)

Could it contain some text, like “Keeping HNR up-and-running...” :) ?

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.2
