### ISSUE TITLE
Correct “nullCurrent setting:” into “Current setting:”.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#466]
“Time that the entries will be kept” is now described as: “nullCurrent setting: [here the setting which has been chosen]”, whatever setting I choose.

**Comment by afmbsr** [comment]
In addition, there is a repetition of the (%%) symbol in the "Min. Battery level" option in the "Article refresh" setting

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.2
