### ISSUE TITLE
Fixed scroll distance.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#467]
Whenever I tap the bottom Tap Zone to scroll an article, **I am naturally used to expect its bottom line (the line currently displayed approximately on the bottom of the screen) to end up on the top of the screen.** Unfortunately it won’t be always that way, due to articles of various length. **As a result my reading is often disturbed while I’m close to the end of an article** - because at this point the article is not scrolled over the regular distance, but only till it reaches its end. Therefore I need to pay an extra attention to find out where I should continue reading, where my last line lays.

Although it’s not so big deal, it bothers me. I can imagine a feature which could ensure that every time I tap on the bottom Tap Zone, the article will be scrolled the same distance, even on its end, when it could be filled with empty space to fill the regular scrolling distance. As a result my reading could be 100% seamless, i.e., without a confusion on the end, which happens pretty often.

Settings-wise, the feature could be called “Fixed scroll distance” and described as “Scroll article text always over the same distance.”

**Comment by yanus171** [comment]
I definitely agree with you, but I don't know how to implement it

**Comment by ThomasLeigh** [comment]
Fingers crossed, I’m extremely happy that You share this need.

**Comment by Ryuno-Ki** [comment]
Hm … is it possible to add a HTML tag with a style attribute at the end? Does WebView understand `display: block; min-height: 100vh` on it? (`vh` is a new unit for `viewport height`)

This way, you would create space.

**Comment by yanus171** [comment]
@Ryuno-Ki it works! Thank you much!

**Comment by yanus171** [comment]
Ideally we need: screen height - button section height, which is hard to calculate, but I suppose 90% wil be sufficient.

**Comment by Ryuno-Ki** [comment]
`min-width: calc(100vh - 100%)` *shoot in the blue

The `100%` should be calculated by CSS from the element it is affecting.

**Comment by yanus171** [comment]
What do you mean by shoot in the blue? May be you can give me concrete 
text? You can see article resulting html via menu, share, show html

**Comment by Ryuno-Ki** [comment]
Shoot in the blue as in: I've not tested it, but it could work.

I'm too lazy to wire up my Android phone to my laptop to test it.
I write it with a Web Dev hat on.
