### ISSUE TITLE
Wrong ‘read’ indicator within “Without a feed”.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#469]
While there is the unchecked square icon indicating that only unread articles should be displayed, there are still read articles on the list.

The list is properly displayed once I check the icon and unchecked it again, but it still acts wrong if I switch to “Favorites” and back to “Without a feed”.

**Comment by ThomasLeigh** [comment]
It would be great if this indicator could be remembered per a single feed. Would it be possible?

**Comment by yanus171** [comment]
What do you mean by indicator? Give me a screenshot please

**Comment by ThomasLeigh** [comment]
I mean that it would be great if such a situation could be possible:

1. Open any feed and make the list showing only the unread articles (via the button on the top bar).

2. Open another feed and make the list showing the read articles also (via the button on the top bar).

3. Go back to the previous feed » having its list remembering that it should display only the unread articles.

Still want to have a screenshot?

**Comment by yanus171** [comment]
Ok. I think I could make it. Everyday it in the separate issue please
