### ISSUE TITLE
Change of language setting ignored

### ISSUE THREAD

**Issue by franconian** [yanus171/Handy-News-Reader#470]
**Describe the bug**
Changing language setting from 'System default' (de_DE in my case) to 'English' doesn't show any effect. Neither at once nor after restarting the app.

**To Reproduce**
1. Go to 'gear icon (settings).'
2. Click on 'language'
3. Scroll down to 'English' and choose
4. Go back, close app in recent screen and restart HNR from launcher. App language remains German.

**Expected behavior**
App should appear in English.

**Smartphone (please complete the following information):**
 - Device: Peregrine
 - OS: Android (LOS)
 - Version 7 (14)

**Additional context**
HNR version 0.13.1 

Edit: Change works on a second device (LOS 16) as expected

**Comment by yanus171** [comment]
Can't reproduce it. May be someone else can?

**Comment by SIRSteiner** [comment]
Maybe this is the same as #351
I can't reproduce it because all my devices have newer Android versions.

**Comment by franconian** [comment]
Not only "maybe", it is the same issue and apparently associated with elder Android versions. 

Am 20. April 2020 16:28:52 MESZ schrieb SIRSteiner <notifications@github.com>:
>Maybe this is the same as #351
>I can't reproduce it because all my devices have newer Android versions.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/yanus171/Handy-News-Reader/issues/470#issuecomment-616590371
-- 
Gesendet mit K-9 für Android.

**Comment by yanus171** [comment]
Why then create a new issue?

**Comment by franconian** [comment]
Sorry, my fault, I didn't do a careful search before posting. Is it possible to merge them? Otherwise just close the issue.

Am April 20, 2020 3:06:52 PM UTC schrieb yanus171 <notifications@github.com>:
>Why then create a new issue?
>
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/yanus171/Handy-News-Reader/issues/470#issuecomment-616613927
-- 
Diese Nachricht wurde von meinem Android-Gerät mit Librem Mail gesendet.
