### ISSUE TITLE
What is the difference between “Web Page Links” and “One Page” load types?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#471]
Plus: does “One Page” obtain content from a single page (i.e., always without loading articles from links on this page)?

**Comment by yanus171** [comment]
Yes, from a single page. But if you set next page class then the other pages content will be added too.

**Comment by ThomasLeigh** [comment]
What is a next page class?

**Comment by yanus171** [comment]
Often large page content is divided into several parts with corresponding 
links ( Prev, .., 6, 7, 8,... Next) So the Next class name is the class 
name for the"Next" link (or the "Prev" one)- the link that can be used to 
iterate over all pages.

**Comment by yanus171** [comment]
Can we merge it with #450?

**Comment by ThomasLeigh** [comment]
Yes, how could I do that?

**Comment by ThomasLeigh** [comment]
@yanus171 , could such an explanation be correct?

> **“Web Page - Divide”** is meant for pages which content is already organized into logical separate blocks, like single posts within a forum thread.

> **“Web Page - Links”** simply follows and loads all the links present on a given page (You can further adjust which links in particular should be loaded and which omitted).

**Comment by yanus171** [comment]
Yes you are right. One correction:
Web page divide website should already contains the articles content.
But web page links website contains articles content in other pages, 
accessible by links from main webpage.
