### ISSUE TITLE
Source error

### ISSUE THREAD

**Issue by RAMAR-RAR** [yanus171/Handy-News-Reader#474]
When the app refresh the sources, a lot of them load the xml source text, instead of load the new articles published.

Android version: 9
HNR version: 0.13.1
Ex.
![Screenshot_20200422-163934_Handy News Reader](https://user-images.githubusercontent.com/47423745/79995789-eee3a780-84b7-11ea-903a-d7e13afe6b9f.jpg)

![Screenshot_20200422-163931_Handy News Reader](https://user-images.githubusercontent.com/47423745/79995880-10449380-84b8-11ea-9bbd-e25d6ea96240.jpg)

**Comment by yanus171** [comment]
Give me a link to feed

**Comment by RAMAR-RAR** [comment]
http://rss.cnn.com/rss/edition.rss

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.3

**Comment by RAMAR-RAR** [comment]
App doesn't work.  When i refresh it blocks on third  link feed and the few link feeds that load has the prevoius problem

**Comment by RAMAR-RAR** [comment]
I tried to load CNN link feed but without success

**Comment by yanus171** [comment]
Send me a crash.txt file from feedex folder

**Comment by RAMAR-RAR** [comment]
[crash.txt](https://github.com/yanus171/Handy-News-Reader/files/4535309/crash.txt)

**Comment by yanus171** [comment]
Did you tried the latest so version (0.13.3)?

**Comment by RAMAR-RAR** [comment]
Yeah I installed the version that you pass, when you told me to take the crash.txt there was this one with refeer to  1.13.1 version

**Comment by yanus171** [comment]
I can't reproduce it. Try to clear app data and restore firm autobackup.opml

**Comment by RAMAR-RAR** [comment]
I cleared app data, deleted autobackup.opml, import the feeds then the CNN was readen with XML error and the app continue in refresh to stop in third link feed

**Comment by yanus171** [comment]
What does it mean there's third link feed?

**Comment by RAMAR-RAR** [comment]
I mean when HNR refresh it look like in list of feed it blocks on third feed.

Ex.--------
(HNR update notification)
(2.36 MB) 3/38 *name of a feed* *name of a feed*
...
----

**Comment by yanus171** [comment]
So the problem is in CNN feed?What it the result of this feed refresh only?

**Comment by RAMAR-RAR** [comment]
CNN  feed(like other feeds) updated show the xml and when I refresh the feeds HNR  remain in loop on third feed

**Comment by yanus171** [comment]
What is that third feed? What URL?

**Comment by RAMAR-RAR** [comment]
In the moment I'm writing this HNR doesn't seem blocks on third feed (if "Convert xml symbols before parsing" is off), this rss=https://www.agi.it/cronaca/rss works but the same site with other category has the xml problem.
CNN's problem persist.

**Comment by RAMAR-RAR** [comment]
> What is that third feed? What URL?

I can't identify when refresh the feeds
