### ISSUE TITLE
No “button layout” within strings.xml.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#475]
I can’t find “Button layout” feature within [strings.xml](https://github.com/yanus171/Handy-News-Reader/blob/master/FlymFork/src/main/res/values/strings.xml), therefore neither on Crowdin to translate.

**Comment by yanus171** [comment]
It's in arrays.xml file, not in strings.xml

**Comment by ThomasLeigh** [comment]
Although there is an “arrays” file on Crowdin, there is still no such string in there...

**Comment by yanus171** [comment]
Fixed it.

**Comment by ThomasLeigh** [comment]
Thank You. What about “To keep app in memory”... this also I cannot find anywhere, regarding the arrays and strings files.

**Comment by ThomasLeigh** [comment]
Oh, and there is only “Horizontal”, “Vertical”, and “Do not show buttons” - but there is no “Buttons layout”.

**Comment by yanus171** [comment]
Search the end of strings.XML again
