### ISSUE TITLE
How to load articles based on link pattern?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#482]
I’d like to add a non-_RSS_ website to _HNR_. It has many links, the actual articles are equipped with links

`https://sitename.com.us/US/3001/...........`

and

`https://sitename.com.us/US/1000/...........`

Is there any way to load (also while auto-refresh) only such articles, without all the rest links from the same domain, but with different numbers than 3001 and 1000 within the address?

**Comment by yanus171** [comment]
Give me an URL to a webpage with links

**Comment by yanus171** [comment]
Try to use regex filter on article title or URL: /\d+/
Don't forget to delete all non starred articles from context menu to reset 
feed articles (I always forget to rename this menu item to something more 
sensable)


Thomas Leigh <notifications@github.com> 24 апреля 2020 г. 22:55:03 написал:
