### ISSUE TITLE
Tap Zones Preview.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#486]
1. What do You mean by “End editing”?
2. What about the red “error” on the bottom left corner?

![Screenshot_2020-04-27-01-10-03-100_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/80323312-f219c300-882a-11ea-890c-6227f8af2ee6.jpg)

**Comment by yanus171** [comment]
They should be hidden

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.4
