### ISSUE TITLE
Entries kept time in relation to Delete old articles interval.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#487]
If I have entries kept time set to “forever” - what about “delete old articles interval”?

**Comment by yanus171** [comment]
The Delete old internal determines how often the app will find the old 
articles (according with keep time settings) and delete them. Also during 
this operation the images sizes are calculated (updated)

**Comment by ThomasLeigh** [comment]
If I have entries kept time set to “Forever”, but I set Delete old to “One day” - what will happen?

**Comment by ThomasLeigh** [comment]
@yanus171 

“Delete read articles” is described as “Regardless of the articles keep time” - so I thought that if I have “Delete read articles” set to 1 day, it will be deleting 1-day-old articles regardless of that I have “Time that entries will be kept” set to “Forever”. But it seems that it does not work this way because I have 9829 All Articles, while 703 Unread, 1124 Starred and 63 Without a feed.

Please help to solve this mystery. :)

**Comment by ThomasLeigh** [comment]
And one more question: what is the difference (I don’t mean calculating feed and images size on sd-card) between “Time the entries will be kept” and “Delete old articles time”? It sounds like those two have the same function...

**Comment by yanus171** [comment]
Forever kept time + 1day delete period = delete no articles

**Comment by yanus171** [comment]
Delete read articles setting is not a list but a checkbox - you can't set 1 day there

**Comment by yanus171** [comment]
Read the setting more carefully: Delete old article interval - how often the old articles check would be performed

**Comment by ThomasLeigh** [comment]
I am sorry but I still cannot understand this fully. Does “Delete old article interval” not serve to delete articles - but only to check which articles are old?

**Comment by yanus171** [comment]
Yes, it is

**Comment by ThomasLeigh** [comment]
Please confirm to make me sure: the reason that I have so many All Articles is that I have entries kept time set to forever, regardless of Delete Old Articles set to one day?

**Comment by ThomasLeigh** [comment]
**But I have checked Delete Read Articles....**

**Comment by yanus171** [comment]
Congratulations, Thomas! It seemed that I have found the big with Delete read checkbox

**Comment by yanus171** [comment]
By the way that checkbox has more priority over forever kept setting

**Comment by ThomasLeigh** [comment]
>  It seemed that I have found the bug with Delete read articles setting

So may this be a reason why I have so many articles in “All Arcticles”?

**Comment by yanus171** [comment]
Yes, because of it. I will make a new app version soon

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.4

**Comment by ThomasLeigh** [comment]
I’ve set Delete Old Interval to 1 minute and I have still over 10 000 All Articles.

**Comment by yanus171** [comment]
Do you have any feed custom article keep time?
And also you should execute delete old operation manually from article list 
menu to have effect immediately

**Comment by ThomasLeigh** [comment]
> Do you have any feed custom article keep time?

No. Just one kept time for all: set to “Forever”.


> you should execute delete old operation manually from article list menu to have effect immediately

I’ve done that - nothing has changed.

**Comment by yanus171** [comment]
Check again please that you have Delete read articles setting checked

**Comment by ThomasLeigh** [comment]
Yes, I have.

**Comment by yanus171** [comment]
Can you send me autobackup.ompl ?

**Comment by ThomasLeigh** [comment]
Yes. I’m not sure if [this link](https://trailofthelight.xyz/filerun/wl/?id=cOz7Txq9yx4WEEyqrXe01b5zk4VgCGnN) will be all right because I’m testing a new sharing service...:

**Comment by yanus171** [comment]
Try such an experiment: Make some article read, then tap menu item Delete 
old articles, wait until operation finished, check if that article exists.

Check that app version is 0.13.4 in settings

**Comment by ThomasLeigh** [comment]
0.13.4. After the experiment the article is still there (within All Articles).

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.5

**Comment by ThomasLeigh** [comment]
I’ve double-checked and now (0.13.5) it works, but only if the app is online. If it is offline, nothing happens.
