### ISSUE TITLE
“Theme & appearance”.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#488]
I’d suggest to dedicate one place within the app’s settings to its appearance. It could be renamed from “Theme” into “Theme & appearance”. It could consist of:

1. **Theme.**
2. **Custom colors.**
3. **Text and background color.**
4. **Read articles on lists.** (currently within Articles’ list)
5. **Show clock.** (currently within Page header)
6. **Show battery level.** (currently within Page header)
7. **Text size of the clock.** (currently within Page header)
8. **Clock color and background.** (currently within Page header)
9. **Reading progress bar.** (currently within Page header)
10. **Progress bar height.** (currently within Page header)
11. **Progress color.** (currently within Page header)
12. **Toolbar & buttons color.**

**Comment by yanus171** [comment]
I don't like this idea. This category would be to big and would break the 
settings logical hierarchy
