### ISSUE TITLE
“Convert xml symbols before parsing”.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#490]
Could You please describe this feature...?

**Comment by yanus171** [comment]
Its some kind of temporary crutch to remove XML from article text. It 
should be unchecked if you want to see XML in text (Mostly for developers). 
When I find universal solution I would remove this preference

**Comment by ThomasLeigh** [comment]
I can’t find this string (“convert xml...”) to translate [here](https://github.com/yanus171/Handy-News-Reader/blob/master/FlymFork/src/main/res/values/strings.xml) ....
