### ISSUE TITLE
Black-themed settings.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#491]
Currently there is dark mode which makes app’s settings dark thanks to dark-gray background. Could You, however, add another theme which could make app’s settings background black, i.e., much more contrast between text and background within settings itself?

**Comment by SIRSteiner** [comment]
Like this?

![Screenshot_1589679853](https://user-images.githubusercontent.com/3488638/82133912-a935a880-97f1-11ea-9158-391c2d525358.png)

**Comment by ThomasLeigh** [comment]
Yes.
