### ISSUE TITLE
String location request and question.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#497]
I can’t find the following string both within strings and arrays files:

`“You will receive Long operation notifications from Handy News Reader”`

Where can I find it? Could it be available on Crowdin?

2. The message mentioned above shows up once I long tap on a HNR notification on Android notification shade. **By “long operation” do You mean only article refresh?**

**Comment by SIRSteiner** [comment]
The string is named "long_operation" and source string  is "Long operation"

**Comment by SIRSteiner** [comment]
I think "Long operation" should be changed to "Updating" because it appears while updating HNR

**Comment by ThomasLeigh** [comment]
To what “long operation” is referring? Is it only about notifications on article refresh? Or any possible HNR notification?

**Comment by SIRSteiner** [comment]
I saw it only when updating articles

**Comment by ThomasLeigh** [comment]
All right, I will do the experiment, wait a moment.

**Comment by ThomasLeigh** [comment]
It affects not only article refresh notification but also notification on deleting old articles and maybe other situations. (I mean that if You uncheck this notification from the “Long operations” group, it disables not only notifications on article refresh)

Therefore I suppose “long operation” is meant to cover various HNR activities.

Now, it should nicely fit the sentence “You will receive xxxxxx notifications from Handy News Reader”, due to Android itself is constructing this.

@yanus171 
I would replace “Long operation” with one word: “various”, if it could be all right code-wise?

**Comment by SIRSteiner** [comment]
What do think about "state" or "status"?

**Comment by ThomasLeigh** [comment]
“Status” is all right. “Various”, however, sounds more human (“status” sounds more IT-like, more official, if You will).

**Comment by yanus171** [comment]
Where do you see that text in app?

**Comment by SIRSteiner** [comment]
In notification when swiping down. But it seems to be a device specific issue. In Android Studio emulator it looks different.
![Screenshot_2020-05-03-09-55-12-650_com miui home~(1)](https://user-images.githubusercontent.com/3488638/80908990-b304d980-8d24-11ea-9db4-dfdf17b1a0b7.jpg)
