### ISSUE TITLE
When “Duplicate current feed” feature may come in handy?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#498]
...

**Comment by yanus171** [comment]
I need that for web page devide load type, when I parsed in HNR various 
sections from the same forum, which had the same class settings for each 
feed. And setup them manually is difficult due to it's big count( class 
name for text, for icon, for date, etc).

**Comment by ThomasLeigh** [comment]
Do You mean that when You want to subscribe another forum thread with similar classes, You use “Duplicate”, thanks to which You (almost) don’t need to fill all the classes from scratch?

**Comment by yanus171** [comment]
Yes, excactly

  
>Суббота, 2 мая 2020, 14:22 +03:00 от Thomas Leigh <notifications@github.com>:
> 
> 
>Do You mean that when You want to subscribe another forum thread with similar classes, You use “Duplicate”, thanks to which You (almost) don’t need to fill all the classes from scratch?
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением, Алексей
