### ISSUE TITLE
Cannot install v0.14.0.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#501]
I can’t install HNR v0.14.0 because it shows “App not installed” screen. In such cases often helps to uninstall the previous version of the app, but I don’t want to loose the unread article list. :(

If there is no chance to workaround this, I’ll browse all the unread...

Will “Without a feed” be included in the backup?

**Comment by yanus171** [comment]
Was such a problem in previous releases?

**Comment by ThomasLeigh** [comment]
No.

**Comment by ThomasLeigh** [comment]
I’ll try bravely to browse all the unread... :) Will Without a feed be included in the backup?

**Comment by yanus171** [comment]
Do not do that. I suppose the APK has a problem. I will make a new one

**Comment by ThomasLeigh** [comment]
Oh, I guess I am too much of a hothead when it comes to new features in Handy :) :) :)

**Comment by yanus171** [comment]
No we can't test it :(
