### ISSUE TITLE
Where “Auto set as read when title was visible” should work?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#514]
Will this feature work regardless of on which list the article is displayed? I mean, it can be displayed within several lists, such as “Unread”, “Favorites”, “All articles”, “Without a feed”, and so on.

Will this feature should work everywhere, or only on a single feed list?

**Comment by yanus171** [comment]
Due to the per feed setting this feature will work only in single feeds

**Comment by ThomasLeigh** [comment]
So even if I enable it, articles from this feed won’t be marked as read if browsed through other lists, like “Unread” or “Favorites”?

**Comment by yanus171** [comment]
You are right
