### ISSUE TITLE
Make space around “Read more”.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#516]
Please make “Read more” links on article lists more separated both from article text and next article title - currently it’s easy to click on the next article instead of “Read more”, and “Read more” would be easier to notice when separated both from top and bottom.

**Comment by SIRSteiner** [comment]
As a first step what about moving full text indicator to article image like the new indicator at the left bottom edge?

**Comment by SIRSteiner** [comment]
Another suggestion: moving all indicators to the article image, then we have more space on the right side:

![Screenshot_1589151102](https://user-images.githubusercontent.com/3488638/81512587-dbdb2f00-9321-11ea-8cb6-2cf12b18f5f5.png)
