### ISSUE TITLE
No clock while fullscreen.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#517]
The clock is displayed whether Action Bar is visible or not. But if I switch to full screen, it kind of disappears. Like this:

https://cloud.trailofthelight.xyz/wl/?id=OicS139VHheoR3XIKc5YEbYFXw9yFu1G

**Comment by franconian** [comment]
I think we see a correct behaviour in the video. 
First 4 seconds in full screen, status bar hidden, action bar hidden > clock visible. 
Next 4 seconds full screen with action bar, status bar hidden > clock visible. 
The both following sequences are in normal mode with and without action bar, status bar now visible > clock disappears. 

I cannot recognize a bug

**Comment by ThomasLeigh** [comment]
1. Clock on status bar can be disabled on some Android devices.

2. If the clock shouldn’t be visible, there is still a part of its background visible, which shouldn’t be visible at all.

**Comment by franconian** [comment]
Neither 1. nor 2. match the current issue heading.

**Comment by SIRSteiner** [comment]
Please look at the old issue #141 
But I agree there is a part of the background visible.

**Comment by yanus171** [comment]
It's a feature. There is no need for clock when status bar with system 
clock is visible

**Comment by yanus171** [comment]
And don't forget about the progress bar. It should we always visible. So you see it's background

**Comment by SIRSteiner** [comment]
If you disable and enable status bar there you can see a small part of the clock background. But if you open a new article this part is gone

![IMG_20200505_072636](https://user-images.githubusercontent.com/3488638/81037095-d608c800-8ea1-11ea-804e-c2d295919bff.jpg)

**Comment by franconian** [comment]
> It's a feature. There is no need for clock when status bar with system clock is visible

I agree. But possibly it should be mentioned in page header settings that you'll see the clock and the battery level only in full screen view i.e. when status bar is hidden.

**Comment by SIRSteiner** [comment]
![IMG_20200505_115913](https://user-images.githubusercontent.com/3488638/81054902-f0ee3300-8ec7-11ea-882f-9af9c3f1cb80.jpg)
It is written in summary

**Comment by franconian** [comment]
> It is written in summary

You are right, badly read by me. Only battery level lacks the hint.
