### ISSUE TITLE
crash report generated

### ISSUE THREAD

**Issue by smallwanderings** [yanus171/Handy-News-Reader#519]
When the app is open, if I turn my phone from portrait to landscape the app generates a crash report.

Also when I tried to email the cradh to the contact email I get a message that the email address is invalid.

**Comment by SIRSteiner** [comment]
More informations needed please (device, os version...)
I recommend a clean installation. Did you try it?

**Comment by yanus171** [comment]
Did you use the latest so version 0.14.0? Where in the app screen rotation 
results in crash?

**Comment by smallwanderings** [comment]
I have 0.13.1 from F-Droid, where 0.14.0 is not available.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by smallwanderings** [comment]
BLU Vivo XL4. Android 8.1.0

**Comment by smallwanderings** [comment]
It crashes when I am looking at the list of articles in the app. It does not crash when I'm reading an article, or when I am in settings.

**Comment by smallwanderings** [comment]
I downloaded 0.13.4 fromthe F-Droid website and that does not crash like 0.13.1.
