### ISSUE TITLE
Could settings font size respect the system font size?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#52]
It would be great to give users such a flexibility: **everyone could have a user experience of their choice**: people for whom current settings font-size is all right - could be still satisfied, and people for whom a bigger settings font size makes a difference, also could feel well, knowing that using _Handy News Reader_ will also be comfortable to them.

**Comment by yanus171** [comment]
I suppose you mean Standard (default) item in font size settings.

**Comment by yanus171** [comment]
The article list font size = 18dp + settings. But the article text font size prefs is not a font size, but a zoom of webview = 100 + setting * 20. So these settings are different. May it will be better to rename article text font size pref to zoom?

**Comment by ThomasLeigh** [comment]
In this thread I mean the font-size of each text on this screen (which is only the beginning of a scrollable list of items):

https://drive.google.com/file/d/1ZqWAjpd6tsCWGkx3f5D6pWrXY5fj8oaH/view?usp=sharing

**Comment by yanus171** [comment]
So do you mean the size of the text in preference window? I still don't understand :(

**Comment by ThomasLeigh** [comment]
@yanus171 Alternatively it could be great to allow to resize settings font size to make it bigger (200%, 300%, maybe also 400% - I'm not sure how it could look like).
