### ISSUE TITLE
How to remove particular blocks with regex?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#521]
[Here is the article](https://antyweb.pl/bing-google-wyszukiwarki/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Antyweb+%28AntyWeb%29#).

I’d like to remove blocks beginning with “Zobacz też:” and containing links (there are two within this article).

I’ve tried the following regex:

	/(?:\<p)(?:.*)>(?:.*)(?:Zobacz\ te\ż)(?:.*)<\/p>/g
	
It works on the website to examine regex’es, but it does not remove those blocks from the article within HNR after reloading the full text.

Could someone help with that, please?

**Comment by yanus171** [comment]
Do you need check link presence? Maybe just any block starring with that 
text? For example <p>Zoba itcz też(.)+?</p>

**Comment by ThomasLeigh** [comment]
Any block is all right. I thought that because there is a link inside, I need to do it that way.

**Comment by ThomasLeigh** [comment]
But in case of

   /(?:\<p)(?:.*)>(?:.*)(?:Zobacz\ te\ż)(?:.*)<\/p>/g

I haven’t included links anyway.

**Comment by ThomasLeigh** [comment]
The original code is something like that: <p style="......."> ...

**Comment by yanus171** [comment]
Past here original html part, that you want to remove

**Comment by ThomasLeigh** [comment]
It may differ, but it should always contain “Zobacz też:”

	<p style="text-align: center;"><strong>Zobacz też:</strong> <a href="https://antyweb.pl/windows-10x-surface-duo-emulator/">Już dzisiaj można sprawdzić Surface Duo. Wkrótce Windows 10X. Jest tylko jeden haczyk</a></p>

**Comment by yanus171** [comment]
Try <p.style(.*?)Zobacz też(.*?)</a></p>

**Comment by ThomasLeigh** [comment]
Doesn’t work.

**Comment by yanus171** [comment]
<p(.*?)Zobacz też(.*?)</a></p>

**Comment by yanus171** [comment]
Remove word style

**Comment by yanus171** [comment]
Try <p(.*?)Zobacz też(.*?)</a></p>

**Comment by ThomasLeigh** [comment]
No effect.

**Comment by yanus171** [comment]
Try <p(.*?)Zobacz też(.*?)</a></p>

**Comment by yanus171** [comment]
Did you reloaded full text?

**Comment by ThomasLeigh** [comment]
Yes, I’ve done that.

**Comment by yanus171** [comment]
Now go to the feed filter setting and change Apply to Title to Apply to content (it is a bug)

**Comment by ThomasLeigh** [comment]
A have apply to content checked from the beginning.

**Comment by yanus171** [comment]
Check it again. There is a bug

**Comment by ThomasLeigh** [comment]
Still nothing. :(

**Comment by yanus171** [comment]
Give me a screenshot of your feed filters

**Comment by ThomasLeigh** [comment]
![Screenshot_2020-05-10-16-20-14-017_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/81501833-b1b24e80-92da-11ea-9580-df6c0e3c6408.jpg)

**Comment by yanus171** [comment]
Try <p((.|\n)*?)Zobacz też((.|\n)*?)</p>

**Comment by ThomasLeigh** [comment]
Unfortunately I don’t have this article anymore. And the code has been changed to:

	<p><strong>Zobacz również:</strong> <a href="https://antyweb.pl/komputer-kwantowy-opis-zastosowania-ocena/">Największa rewolucja tego stulecia? Komputer kwantowy kontra rzeczywistość</a></p>

How to adapt

	<p((.|\n)*?)Zobacz również((.|\n)*?)</p>

to this new code?

**Comment by yanus171** [comment]
It should be ok for new html too

**Comment by ThomasLeigh** [comment]
:( :( :( :(

**Comment by yanus171** [comment]
I have just opened the editor with regex search, pasted html from your post and found it with regex from my post... Did you reloaded full text of that article after filter edit?

**Comment by ThomasLeigh** [comment]
Could You check this one?

https://antyweb.pl/komputery-kwantowe-jaki-wplyw-beda-mialy-na-nasze-zycie/
