### ISSUE TITLE
Random (?) past articles from time to time.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#523]
I have (at least) two feeds about which I’m sure that from time to time some past articles are loaded as new ones. I am not sure are those articles random. The feeds are:

https://www.spreaker.com/show/2771049/episodes/feed

and

http://legacy.theunexplained.tv/feed.xml

If You want, I will note the exact articles - which and when have been showed up.

**Comment by Ryuno-Ki** [comment]
I had a similiar experience and found the published data in an invalid format.
As far as I can tell, this isn't the case here (format looks fine to me).

**Comment by yanus171** [comment]
May be the problem is with particular trees channels?

**Comment by ThomasLeigh** [comment]
What trees channels are?

**Comment by ThomasLeigh** [comment]
This issue is related to the previous one: https://github.com/yanus171/Handy-News-Reader/issues/274

**Comment by yanus171** [comment]
Fixed typo

**Comment by Peterspapan** [comment]
I have the issue with feeds from sz.de
