### ISSUE TITLE
“Reset feed and delete all unstarred articles”

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#525]
What does this option do:

1. Delete all unstarred articles.
2. Does it do anything else?

**Comment by SIRSteiner** [comment]
@yanus171 This string is too long for the menu!

**Comment by ThomasLeigh** [comment]
Wrap menu items would be a good idea.

**Comment by afmbsr** [comment]
This option makes the feed as if it had just been added, so when a refresh is made for the feed, a new, clean upload of the articles will be made
