### ISSUE TITLE
“Category extract rules”

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#526]
Could You please describe this a little bit further (for translation sake)?

**Comment by yanus171** [comment]
Wait for the next app release please

**Comment by ThomasLeigh** [comment]
I’ve read the release description, but I still cannot understand what for categories may be useful in practice?

**Comment by yanus171** [comment]
Did you installed the new app version?

**Comment by ThomasLeigh** [comment]
Yes

**Comment by yanus171** [comment]
Try to toggle article list menu item Show category

**Comment by yanus171** [comment]
Do you see article categories in the list?

**Comment by ThomasLeigh** [comment]
I have this enabled. Furthermore, something has happened and now it looks like this:

![Screenshot_2020-05-09-20-31-31-370_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/81482081-bae8e000-9234-11ea-8e35-ee0dd1b3962e.png)

**Comment by yanus171** [comment]
There are still no category displayed. Try different RSS feeds

**Comment by ThomasLeigh** [comment]
Why one article is displayed differently on the list on the picture above?

Could You please show me how categories should look like? I still cannot find them. Or share a feed which supports them.

**Comment by yanus171** [comment]
![Screenshot_20200510-130553](https://user-images.githubusercontent.com/18382136/81496480-976b7700-92c0-11ea-924d-97899b2ea4e6.jpg)

**Comment by ThomasLeigh** [comment]
“Show article category” - checked.

![Screenshot_2020-05-10-16-32-42-212_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/81502088-220d9f80-92dc-11ea-8eaf-ad0f6df37383.jpg)

**Comment by yanus171** [comment]
Reset the feed and reload

**Comment by ThomasLeigh** [comment]
Still nothing. Here You are how it looks with “show categories” enabled and disabled:

**disabled:**
![Screenshot_2020-05-10-21-21-25-002_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/81508619-6497a200-9305-11ea-8df0-d405e12bca21.jpg)

**enabled:**
![Screenshot_2020-05-10-21-21-00-699_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/81508617-63667500-9305-11ea-9970-ee48a9dcc9b4.jpg)

**Comment by yanus171** [comment]
Open any article in that feed and screenshot the beginning of it

**Comment by ThomasLeigh** [comment]
![Screenshot_2020-05-11-15-10-21-577_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/81565504-bbe75200-9399-11ea-958a-2afa57c6d2ad.jpg)

**Comment by yanus171** [comment]
Gine me a link to feed

**Comment by ThomasLeigh** [comment]
`http://feeds.feedburner.com/Antyweb`

**Comment by yanus171** [comment]
Try feed https://antyweb.pl/feed/

**Comment by ThomasLeigh** [comment]
I wanted to duplicate the feed to change its address (not to loose the current articles of this feed) and I’ve stumbled upon a problem, which I describe here: https://github.com/yanus171/Handy-News-Reader/issues/547 .

**Comment by yanus171** [comment]
Can just add a feed with URL https://antyweb.pl/feed/ refresh and check 
categories?

**Comment by ThomasLeigh** [comment]
Now I see categories of this channel, but I have many channels still without them and I don’t know whether they do not have categories or I should reset all those feeds...?

**Comment by ThomasLeigh** [comment]
And what can I do with those categories?

**Comment by yanus171** [comment]
Hooray. You saw the categories at last. If the channel has categories. You 
should see them in newly loaded articles.

**Comment by yanus171** [comment]
No need to reset feeds. But if you reset feed and refresh it. You will see 
the categories in all loaded articles

**Comment by yanus171** [comment]
The categories also known as #tags. But word tag is occupied in Edit 
content view mode.

**Comment by ThomasLeigh** [comment]
> No need to reset feeds. But if you reset feed and refresh it. You will see
the categories in all loaded articles

What about Favorites?


> The categories also known as #tags. But word tag is occupied in Edit
content view mode.

What can I do with categories? When they may come in handy?

**Comment by yanus171** [comment]
To get the categories in starred article you should reload it's full text.

**Comment by yanus171** [comment]
You can filter articles by category

**Comment by Ryuno-Ki** [comment]
`tag` and `category` are common terms with respect to ontology.
You can find them on WordPress, for example. I wouldn't open another issue regarding its naming.

**Comment by ThomasLeigh** [comment]
@yanus171 

> To get the categories in starred article you should reload it's full text.

Is there a way to reload full text of all the Favorites at once?


> You can filter articles by category

How can I do that?

**Comment by yanus171** [comment]
There is a apply to category checkbox in feed filter settings.

**Comment by yanus171** [comment]
If we say about filter, there is a few need to reload the categories of 
existing articles because the filter is applied to me articles only.
