### ISSUE TITLE
Some RSS feeds can't be added in Android 4

### ISSUE THREAD

**Issue by GHEagle** [yanus171/Handy-News-Reader#529]
Hello. Some rss feeds can't be added to HNR in devices with Android 4.x.x. When I try to add them, a
message with the word "Error" pops up with no other explanation. For example, the following feed:

https://plazajuarez.mx/index.php/category/orbe/feed/

That feed can be added without a problem in Android 9 but not in Android 4.

**Comment by yanus171** [comment]
This is because for Android 5+ the app uses the fresh okhttp lib, but for 
Android 4- the original Android connection is used. I think the issue would 
be hard to resolve
