### ISSUE TITLE
Disable headers hyperlinks in article text.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#53]
It is not a rare occurrence that during browsing articles (in full text mode) **I accidentally tap on their headers**, which results in opening an external web-browser. Since I prefer to read articles in _Handy_, I go back to the app.

It could be of a great help to disable articles headers' links (in settings?) in order for them not to be tapable (which won't result in such a case described above any more - **so it won't disrupt reading**).

**Comment by yanus171** [comment]
It might make sense...

**Comment by yanus171** [comment]
By why only in full text mode?

**Comment by ThomasLeigh** [comment]
_"why only in full text mode?"_

I didn't know how to name this other way - I mean the view You see after opening an article from article list, which can take two variants: full article text and an excerpt.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Flym/releases/tag/v0.8.4

**Comment by ThomasLeigh** [comment]
Oh, really? Did You really remove it? It looks like You did.

**Comment by ThomasLeigh** [comment]
Could You please confirm that You've removed those headers links? Because since My phone acts often pretty strangely, I can't trust it.

**Comment by yanus171** [comment]
I confirm on my phone, but if you opened the issue you'd better to confirm and close it

**Comment by ThomasLeigh** [comment]
It remains closed.

**Comment by ThomasLeigh** [comment]
Currently it acts like it is disabled - so article headers are clickable again.

**Comment by yanus171** [comment]
A user (on Russian forum 4pda) asked me much to return that feature. It 
could be useful. But I removed link color from it.

**Comment by ThomasLeigh** [comment]
Could You please restore this feature in a form of a checkbox in settings? I often tap on titles by accident and this is very annoying because it' constantly opens an external web browser window.

**Comment by yanus171** [comment]
Ok

**Comment by yanus171** [comment]
Try it https://drive.google.com/file/d/11SpmsE-gGEDbrPDLkgeOuapgF0YNpuEk/view?usp=drivesdk

**Comment by ThomasLeigh** [comment]
Thank You :)

**Comment by ThomasLeigh** [comment]
My device - if disconnected from the charging cable - often acts like this: if I'm reading (*HNR* or some e-book), it works - but if I open some other app (a web browser, for example) - it suddenly turned off and doesn't want to reboot as if it could be 100% discharged. This thing happened also when I accidentally tap on article header :) . So now You know even an additional reason why this "small" feature like non-linked headers could be of significant importance ;) :) .

Thank You.
