### ISSUE TITLE
Cannot extract full images and texts from some articles with <div class="item_slide_show clearfix>

### ISSUE THREAD

**Issue by hoan-cosmos** [yanus171/Handy-News-Reader#530]
**Bug symptom**
Cannot get full images and texts from some articles.

**To Reproduce**
1. Add "https://vnexpress.net/rss/du-lich.rss" as feed source in Handy New Reader
2. Press refresh to download news.
3. Just some articles which have "div class="item_slide_show clearfix"" will have this symptom.

**Screenshots**
This article is uploaded on website vnexpress.net on May 6th, 2020.
Original article link: https://vnexpress.net/ve-dep-lang-que-quang-nam-4092701.html
![image](https://user-images.githubusercontent.com/29880544/81247719-edcc8180-9044-11ea-92e5-8dbbc1e0e652.png)

**Comment by hoan-cosmos** [comment]
@yanus171

**Comment by yanus171** [comment]
What is your Android version?

**Comment by hoan-cosmos** [comment]
I've encountered this sympton in android 5.1 and android 10. I believe this is not specific to OS version, but rather belongs to something wrong in the way you parse html.
Flym News Reader newest version by FredJul (in kotlin) does not have this error.

**Comment by hoan-cosmos** [comment]
@yanus171

**Comment by yanus171** [comment]
A cant reproduce it. Give me an URL of problem article

**Comment by hoan-cosmos** [comment]
I placed the article URL in the uppermost comment:  [https://vnexpress.net/ve-dep-lang-que-quang-nam-4092701.html](url)

**Comment by hoan-cosmos** [comment]
@yanus171

**Comment by yanus171** [comment]
I have much text and images in all these links loaded via Read now in HNR. Try to tap Edit content view and setup the full text root

**Comment by hoan-cosmos** [comment]
I've just tried another article with "div class=item_slide_show": [https://vnexpress.net/cac-tac-pham-khong-lo-hut-khach-4108714.html](url). I'm sure  the previous article link, this new article link and every other links with div tag item_slide_show will have this bug. The previous article is old so It's hard for me to record video demo loading it on HNR now.
Video demo the bug with new article: [https://drive.google.com/file/d/1Ga8eK1J2teIgTxPDW6Iiv9GkD2GANZp0/view?usp=sharing](url)
@yanus171

**Comment by hoan-cosmos** [comment]
@yanus171

**Comment by yanus171** [comment]
Please read carefully my previous post. You should go to edit mode and setup full text root

**Comment by hoan-cosmos** [comment]
Oh sorry sir, now I get it! But I think maybe users will not want to configure this manually, maybe in the future HNR can auto detect the scenario for which load type to use.
