### ISSUE TITLE
"Undo" after "Mark all as read" doesn't work

### ISSUE THREAD

**Issue by franconian** [yanus171/Handy-News-Reader#536]
Mark all articles as read via in-articles list menu or floating button >
Tap "Undo" in shown pop-up > 
all articles are still marked as read

**Expected behavior**
List with unread articles

 - HNR version 0.13.5

**Comment by yanus171** [comment]
Can't reproduce it with 0.14.1

**Comment by franconian** [comment]
Indeed, update to 0.14.1 is helping. 

Sadly, now "Undo" disappears behind the floating button on my device. 
Caused by screen size? (4.5 inch)
