### ISSUE TITLE
Reversed sort order after changing article list view

### ISSUE THREAD

**Issue by franconian** [yanus171/Handy-News-Reader#537]
Different sort order in article list with vs. without article text in article list

**To Reproduce**
1. App settings > article list > articles order unchecked
2. On edit screen of a feed "Show original text on article list" unchecked
3. In article list latest article on top matching with app setting
4. Check "Show original text on article list" and return to the list
5. Latest article at the bottom, oldest at the top

**Expected behavior**
No sort order change

 - HNR version 0.13.5

**Comment by yanus171** [comment]
When article text is displayed the only sensable order is when the newest 
are at bottom. Because in our world we read from to to bottom

**Comment by franconian** [comment]
I agree that we are reading from top to bottom. But I have no problem to read the paper of today before reading the one of yesterday. 
The sort order should remain by date descending like it is described in settings.

Am 9. Mai 2020 05:24:50 MESZ schrieb yanus171 <notifications@github.com>:
>When article text is displayed the only sensable order is when the newest 
>are at bottom. Because in our world we read from to to bottom
>
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/yanus171/Handy-News-Reader/issues/537#issuecomment-626097675
-- 
Gesendet mit K-9 für Android.
