### ISSUE TITLE
Suggestion for menu

### ISSUE THREAD

**Issue by SIRSteiner** [yanus171/Handy-News-Reader#539]
I suggest moving the export/import from feed edit menu to the top feed menu and remove the auto backup option from article list menu.

It could looks like this:

![screenshot_topmenu](https://user-images.githubusercontent.com/3488638/81458490-e8814b00-919a-11ea-90c4-23161b47881a.png)

**Comment by yanus171** [comment]
This operations are very rare. Should we occupy place for them? May be 
better to move export import to article list menu?

**Comment by yanus171** [comment]
The auto backup operation is more rare but sometimes is useful. When the auto backup period is large and for some purposes we want to initiate auto backup emmidiatelly

**Comment by SIRSteiner** [comment]
I don't agree. Because as I started with HNR I searched around to import my opml file from another rss reader. It was not intuitive.
In article list menu should be only operations to the opened feed not related to the whole app.
Is there any difference between auto backup and opml export (except filename)?

Or what about moving export/import to settings menu?

**Comment by franconian** [comment]
I absolutely agree with @SIRSteiner for the same reasons. 
It takes some time to find the restore feature after a clean re-install, like I did it just now, and I think it is a good idea to move the backup/restore button to the sidebar for it concerns the entire app. 
 
I think nothing of @yanus171 's suggestion to move it to the in-article menu which is by now very crowded and confusing. 

Furthermore I'd suggest to remove the "detailed tech information" from the menu as well. It is an "Advanced" setting and imho has no business to be there. 

Finally a direct link to the article list submenu might be really useful on the list menu. Then also the items "Show URL" and "Show category" could be removed and the menu becomes shorter. 
(Btw, what's an "article category"? I cannot see any difference wether checked or unchecked.)

**Comment by yanus171** [comment]
Ok. I agree for import button in feeds action bar. But are you sure such an icon with be recognizable by all users? May be we should organise additional (...) menu section and put import item there with text. And I think export icon should not occupy place there. It's very rare operation (in case we make HNR user friendly sometime:)

**Comment by yanus171** [comment]
Other toggle menu items (info, URL, category) are very useful for my development purposes, but may be useless for other users. I propose to move these items in Additional sub menu. And I think we should not limit the menu item set. Within the app development the menu will only grow. And the solution here is to organize an hierarchy.

**Comment by yanus171** [comment]
For category welcome to #526

**Comment by SIRSteiner** [comment]
Thank you @yanus171 
Let me think about an icon this evening

**Comment by SIRSteiner** [comment]
Maybe something like this?

![opml](https://user-images.githubusercontent.com/3488638/81482182-70b42e80-9235-11ea-98fa-f92bc3d8fd7e.jpg)

**Comment by yanus171** [comment]
Looks great. But may we place the opml above the arrow?

**Comment by ThomasLeigh** [comment]
> I suggest moving the export/import from feed edit menu to the top feed menu and remove the auto backup option from article list menu.

I don’t agree, if someone is interested in my opinion. The reason I don’t agree is that I consider export/import as rarely used features, in general. The only good scenario is the one in which a user themselves can decide what to put on top of the sidebar. See https://github.com/yanus171/Handy-News-Reader/issues/366 .


> I searched around to import my opml file from another rss reader. It was not intuitive.

I agree with that. In my opinion, however, an option to import a backup should be placed in two locations:

1. On the start screen which shows only one time once the app is launched the very first time after installation.

2. Within the settings (not to occupy additional place within the menu, or anywhere else).


> Is there any difference between auto backup and opml export (except filename)?

Different file names.


> It takes some time to find the restore feature 

Oh. Just put the backup file into the feedex folder (internal memory) and then run the app. No additional action required, because the app will restore itself automatically once launched (given the file is placed into the location mentioned above).

But, again, I’ve addressed the topic earlier on above and agree that it should be more intuitive.


> Furthermore I'd suggest to remove the "detailed tech information" from the menu as well.

Agree.


> Ok. I agree for import button in feeds action bar.

Please don’t do that :)


> Other toggle menu items (info, URL, category) are very useful for my development purposes, but may be useless for other users.

Again, customized menu and Action Bar would be perfect. With such a feature each of You could compose Your Own optimized menu and Action Bar.

**Comment by SIRSteiner** [comment]
Okay, we have to find a consensus. Another suggestion:

Many other apps run an introduction at their first start. There we can show where export/import is located. Additionally we can add two separate intuitive icons for export and import at the top of the feed edit instead a submenu. It seems there is enought space.

>I agree with that. In my opinion, however, an option to import a backup should be placed in two locations:
>1. On the start screen which shows only one time once the app is launched the very first time after installation.
>2. Within the settings (not to occupy additional place within the menu, or anywhere else).

1. I don't agree because as I started with HNR I played around to find out if this app is good for me or not. And later I searched the export/import feature. Therefore showing this feature at the first start is in my opinion not a good idea.
2. I don't agree 100% because export/import is a feature not a setting.

>Again, customized menu and Action Bar would be perfect. With such a feature each of You could compose Your Own optimized menu and Action Bar.

That doesn't solve this problem because a new user should find export/import quickly and not after customisation.

**Comment by ThomasLeigh** [comment]
> we have to find a consensus

In this case there is no place for this, as far as I am concerned. But I am not a developer.


> There we can show where export/import is located. 

Can’t an additional (“import feeds”) item be added to the welcome dialog, which already is shown after the first launch?


> as I started with HNR I played around to find out if this app is good for me or not. And later I searched the export/import feature. Therefore showing this feature at the first start is in my opinion not a good idea.

You don’t have to use it. Even if You won’t use this feature from the start screen, You are still able to use it from settings. I think more users will notice this feature this way - than if put within some description.


> I don't agree 100% because export/import is a feature not a setting

Many apps have backup feature placed within settings. But regardless of that it’s a better place than the app UI.


> That doesn't solve this problem because a new user should find export/import quickly

1. Welcome dialog, again.
2. Users should look into settings, really :) .

**Comment by SIRSteiner** [comment]
Okay, as a first step we could move all menu items (article list, feed edit, settings-advanced) about (auto)backup and export/import to a new preferences category "Backup and export/import"?

**Comment by ThomasLeigh** [comment]
I'm sorry, could You please point out more clearly which menu items You'd like to move into settings?

**Comment by SIRSteiner** [comment]
1. Article list "Create auto backup" (maybe completely remove)
2. Feeds edit "Import from/Export to an .opml file
3. Settings-Advanced "Enable automatic backup" and "Auto backup interval"

**Comment by ThomasLeigh** [comment]
Thank You for clarifying, Ronny, I am in worse condition therefore I may have trouble with various things.

> Article list "Create auto backup" (maybe completely remove)

I’ve pull-requested to rename this into “Backup now”. I don’t mind to remove this from menu.

> Feeds edit "Import from/Export to an .opml file

I think that the feed edit screen is a place when it may be natural to look for an option to import/export feeds. Although currently this option does not operate solely on feeds, I still think that it is a good idea for this option to stay here. I would only recommend to rename it into “export/import”.


Then we would have at least four backup-related items within settings (enable..., interval..., export/import...), and You’d like to have a separate category for those, called “Backup and export/import”. I would like to recommend to name it “Backup & Restore” - what do You think?

**Comment by yanus171** [comment]
1. Current place for opml import is bad. I confirm it with several users mailed me with question, where to find it. For some reason Feed edit screen is a some kind of mystery room which users often look for long time.

2. The better visible and more logical place for opml import is a feed list action bar (I agree with @SIRSteiner). I like an icon with word opml, but with word at the top and arrow at the bottom.

3. I have nothing against duplicate some actions in settings.

4. Export to opml operation should be separated from backup, for it should not write article content in file. And it should be somewhere deep: in feed edit screen menu or in settings or both.

**Comment by yanus171** [comment]
@SIRSteiner, can you implement something form above?

**Comment by SIRSteiner** [comment]
@yanus171 Yes, I think. Will start this evening
