### ISSUE TITLE
check box for load full article just when user open an article from a feed 

### ISSUE THREAD

**Issue by Monirzadeh** [yanus171/Handy-News-Reader#543]
**Is your feature request related to a problem? Please describe.**
Handy news reader has an option for each feed to load full article from an specific feed.
it is good but take time to refresh (or can be unnecessary to load all of them). 
**Describe the solution you'd like**
add an option user load feed in normal mode (fast refresh) but if user open article from that specific feed will load full article automatically
add a new check box in `Edit a Feed` with this title `load full article if user open` (disable `load full article` automatically )

**Comment by yanus171** [comment]
Is it hard press load full article button when needed?

**Comment by Monirzadeh** [comment]
1. if i active full screen it can't see that button load full article
2. some website don't have access to content by default so i should do that so many times for website.( i explained why i prefer this option over active `load full article` )
