### ISSUE TITLE
imported opml not refresh

### ISSUE THREAD

**Issue by Monirzadeh** [yanus171/Handy-News-Reader#545]
**Describe the bug**
if you import opml file (inoreader in my case) your list of feed import but you can't refresh them to see article of each feed.
even refresh bottom from `all article` or individual feed can't get article

**To Reproduce**
1. open menu with swap left to right
2. Click on 'pencil'
3. click 3 dot on up right
4. select `import from an opml file`
5. back to application main home
6. open menu with swap left to right
7.  select `All article` or `one of your feed`
8. press refresh icon 

handy news reader show a notification that try to refresh feed but article not show up after that 

**Expected behavior**
1. after i press refresh icon get new article from imported feed (if select `all article` download from all feed if individual feed just get article from that link)
2. it can be automatically refresh after new feed import ( or ask user to start refresh)

**Smartphone (please complete the following information):**
 - Device: poco
 - OS: Android 10
 - Version 0.13.5

**Additional context**
if you follow this steps you can get article for specific feed
1. open menu with swap left to right
2. long press one of feed to open  `Edit a Feed` menu
3. in `Feed` tab > `Load type` change from `RSS` to any other option (`Web Page - Links` or `Web Page - Divide` )
4.  select again `RSS`
5. press back and come back to application main home
6. select that feed. now refresh button  can get article

it can't possible to do for each feed in high number of feed

**Comment by jacobrosenthal** [comment]
I have the same issue. Confirmed that toggling rss off and on 'fixes' it but I cant do that for hundreds of feeds
