### ISSUE TITLE
App crash once “duplicate feed” action.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#547]
1. I’ve opened Antyweb feed (http://feeds.feedburner.com/Antyweb).
2. I’ve chosen Duplicate feed.
3. The app now constantly crashes once scrolled down whether on sidebar feed list from the group in which Antyweb is put or within the edit feed screen (the same group).
4. I’ve sent the crash report via email.

[This is how it looks...](https://cloud.trailofthelight.xyz/wl/?id=obb7RVfNKAc7F9wvdrREOqmlWsPIrGe1)

**Comment by yanus171** [comment]
What's in crash.txt?

**Comment by yanus171** [comment]
I fixed the problem. Can you open Feed edit screen and delete copied feed?

**Comment by ThomasLeigh** [comment]
Thank You. Yes, I’ve done that.

**Comment by yanus171** [comment]
Did you check that bug is fixes with new version?

**Comment by ThomasLeigh** [comment]
Yes, it is fixed.
