### ISSUE TITLE
"Remove from the Favorites when done" doesn't work on original text mode.  

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#55]
It seems it only works in full text mode.

**Comment by ThomasLeigh** [comment]
Yeah, but there are cases which display full text in a form of "original text" in app - and an excerpt in a form of "full text" in app.

**Comment by yanus171** [comment]
Is such a case a Load fulltext checkbox would be unchecked in feed settings 
and remove when done will be activated

**Comment by ThomasLeigh** [comment]
Could we care about users who won't come up with the solution You've mentioned, by making "mark as favorite when done" works universal in both cases (full and original text)? Or is it too much hassle work-wise?

**Comment by yanus171** [comment]
Why should we remove star when user didn't read full article text yet?

**Comment by ThomasLeigh** [comment]
I mean cases in which full article texts are displayed as "original text" (which most of the times display only an excerpt).

**Comment by yanus171** [comment]
Please answer my previous question : Why should we remove star when user didn't read full article text yet?

**Comment by ThomasLeigh** [comment]
Because I mean those cases in which it displays a full article text, although labelled as "original" (shorter one).

**Comment by yanus171** [comment]
In such a case the Load full text checkbox in that feed settings should be 
unchecked and the article star would be removed when bottom is reached.

**Comment by ThomasLeigh** [comment]
How an average user would know that this is what (s)he should do?
