### ISSUE TITLE
Tap on in-article category.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#558]
What do You think about the idea to allow users to tap on in-article categories? Once tapped, it could show the menu:

- Block.
- Allow.

(it could create or update the existing ACCEPT or REJECT filter)

**Comment by yanus171** [comment]
It's not an often operation to create such a menu for it

**Comment by yanus171** [comment]
And did you manage to use categories in filter of your feeds?

**Comment by ThomasLeigh** [comment]
I’ve begun to add categories to the filter, I am not sure whether it works or not yet.
