### ISSUE TITLE
Run the app with... custom shortcut actions and settings.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#56]
When I want to use _Handy_, most of the time I want to open either _Favorites_ or _The Unread_. Either cases **first I need to pay attention in which of those categories I've opened the app last time** - in order to switch to the desired one, if necessary. I think here is the opportunity to make life easier:

1. Introduce _"Open the app in..."_ in settings: a user could choose _"Favorites"_ or _"The Unread"_, or maybe something else either (I'm not sure, but those two are My main concern).
2. Introduce _"actions"_ (I'm not sure if this is the proper name for what I'm thinking about - see further below) which can be used to make a custom shortcut to run the app on the desktop: one action to run it directly in _Favorites_, another one to run it directly in _The Unread_.

**Why not only the first point?** Because I'm sure there are a lot of people who use the app as I am: often launching it in one or the other of the two categories. There are, however, users with other proportions, so that I propose the two points above to satisfy both groups.

Ad.2:
By _"actions"_ I mean something like that: for example, using _Nova Launcher_ I can create a shortcut not only to a particular app, but to one of its functions (like a shortcut to set the alarm instead of a shortcut to the _"Clock"_ app). Various apps provide various so-called _"actions"_ to use by launchers which allow users to create action-based shortcuts.

**Comment by ThomasLeigh** [comment]
_"Why only not only second? I suppose there is no need in new settings."_

It is probable that there are users who rarely use _"Favorites"_ - and there are users who rarely use _"The unread"_ (they could browse new articles once for a longer while, adding chosen ones to _Favorites_).


_"I also thought about launcher shortcuts (actions) , but not only Unread or Favorites - just any feed or group."_

**It could be definitely great** to have those actions available. I Myself would then create shortcuts to _Favorites_ and _The Unread_.

**Comment by yanus171** [comment]
By Second I mean to implement launcher shortcuts only
С уважением, Алексей

Thomas Leigh <notifications@github.com> 7 февраля 2019 г. 12:06:40 написал:

**Comment by ThomasLeigh** [comment]
Ah, all right, if You'd like to implement settings as well, it would be even better, because it will meet more users' needs. But launcher actions I think are the most important because with the help of it we will be able to run Handy directly where we want.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.9.3

**Comment by ThomasLeigh** [comment]
Great. Here You are My update on this matter.

## Fail to create a working shortcut to a single feed.
I tried to create a shortcut to *Favorites* and a shortcut to a particular feed. The first worked well, while the latter did not: although a shortcut has been placed on the desktop, it leads to *the Unread* instead of the feed I've pointed out.

## Besides...
Could feed-related shortcuts have feed name as their title? What about icons?

## Could we have dedicated actions?
As I've described it before:
> "By "actions" I mean something like that: for example, using *Nova Launcher* I can create a shortcut not only to a particular app, but to one of its functions (like a shortcut to set the alarm instead of a shortcut to the *"Clock"* app). Various apps provide various so-called "actions" to use by launchers which allow users to create action-based shortcuts."

There are apps which allow to create shortcuts to all available actions, here You are a screenshot from one of those apps, in which You can see what actions *Handy NR* currently provides:

![Screenshot (Jun 23, 2019 12_30_07)](https://user-images.githubusercontent.com/26142231/59976910-1e413380-95cb-11e9-8663-1b0320a329b8.png)

And now, there is no action for opening *Favorites*. You might ask why we should have such an action if we already are able to put the *Favorites* shortcut? There may be various reasons for that, considering users playing with apps which can harness those actions. I mean things like device automation apps (*Tasker*, *MacroDroid*) or custom Android layout apps (*Kustom Live Wallpaper*). For example in the latter - instead ordinary icons - You can create totally customized (visual-wise) desktop or lockscreen shortcuts, which will lead to various apps or - more directly - to their actions. This way I have a shortcut which - after I tap on it - checks My carrier account. Similarly I could have a shortcut to open *Handy's Favorites* without even a need to place an icon on the desktop.

Here You are a screenshot of My several custom shortcuts on the left and right edge of the screen. No icons at all :) :

![Screenshot_20190623-151501](https://user-images.githubusercontent.com/26142231/59976914-27320500-95cb-11e9-8753-4fec67f9c851.png)

## What about *"Open the app in..."* in settings?
Still it could be a great idea and an alternative for putting additional icons on the desktop:

> "Introduce "Open the app in..." in settings: a user could choose "Favorites" or "The Unread", or maybe something else either (I'm not sure, but those two are My main concern)."

**Comment by yanus171** [comment]
Give a screenshot of HNR feed shortcut please

**Comment by ThomasLeigh** [comment]
Here You are:

![Screenshot (Jun 24, 2019 13_35_17)](https://user-images.githubusercontent.com/26142231/60016056-5f961980-9685-11e9-8b8c-4ab25a099a58.png)

**Comment by yanus171** [comment]
Give me a video of shortcut creating process please

**Comment by ThomasLeigh** [comment]
I tried to repeat all the steps and now it's all right... strange.
