### ISSUE TITLE
Some URLs do not work in HNR (Android 4.4.2).

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#563]
A message from a user via HNR website:

> some URLs do not work in Handy News Reader, in Android 4.4.2.
For example :
https://www.rtl.fr/podcast/la-curiosite-est-un-vilain-defaut.xml
Message: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl = 0x559f3248: Failure in SSL library, usually a protocol error error: 1407742E: SSL routines: SSL23_GET_SERVER_HELLO: tlsv1 alert protocol version (external /openssl/ssl/s23_clnt.c:744 0x53aa1cfc: 0x00000000)

**Comment by yanus171** [comment]
This is because of Android 4. The correct loading of that webpages 
guaranteed only on Android 5+


Thomas Leigh <notifications@github.com> 25 мая 2020 г. 17:09:51 написал:

**Comment by ThomasLeigh** [comment]
The user has replied:

> In Android 6 it works. 
> There must however be a workaround for Android 4.4.2, because on this 
version of Android, Chrome and Firefox can access the example URL 
without problem.

What do You think, @yanus171  ?

**Comment by yanus171** [comment]
To make it work on Android 4 I should use the old okhttp library version. 
The new okhttp version support only Android 5+. So for Android 4 I use 
native system connection which does not support all web pages

**Comment by franconian** [comment]
An interesting post from the maintainer of AntennaPod on F-Droid highlighting this issue of apps with old Android versions and why it works with browsers: 
https://staging.f-droid.org/en/2020/05/29/android-updates-and-tls-connections.html
