### ISSUE TITLE
RSS Feed Widget

### ISSUE THREAD

**Issue by fleurc** [yanus171/Handy-News-Reader#564]
Hi, first time i do a request of a developer.
I have been searchibg far and wide for a decent widget implementation for RSS widgets in android. So far the closest was Feedly and Posidon Launcher, both of which were clunky at best. Feedly took away any customization for the widget, and the launcher was slow, taking at least 2 minutes to actually show feeds, wich wouldn't have been a problem if they stayed after i went to homescreen. None of these worked as I'd hoped, but Handy News Reader seems different, more concise and precise.
The only feature i would like for it is if it could give me a widget to see headlines from my homescreen. Thank you very much for the attention and thank you for all the time put into this app.

**Comment by yanus171** [comment]
I can't understand why do you need a widget on the home screen. Can't you 
just open the app and read new articles?


chrystian4 <notifications@github.com> 26 мая 2020 г. 5:49:53 написал:
