### ISSUE TITLE
How to avoid labels repeating themselves?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#565]
In case of part of the feeds I needed to choose CSS class for labels. As a result, part of those feeds show **labels which are repeating themselves**. One example is [this feed](http://feeds.feedburner.com/dobreprogramy/Wszystkie). Here You are the code responsible for labels:

	<div class="tags">
		<a rel="tag" href="https://www.dobreprogramy.pl/Aktualnosci,Oprogramowanie,7.html" class="label big">Oprogramowanie</a> 
	</div>
	
I chose ‘tag’ as the class for labels. The result is as follows:

![fsdfdgdfg](https://user-images.githubusercontent.com/26142231/83333103-2d326a80-a29f-11ea-9e8b-28620e4ffbe9.jpg)

The article You’ll find [here](https://www.dobreprogramy.pl/Ciemny-motyw-aplikacji-Google-dostepny-dla-kazdego-z-Androidem.-Wystarczy-pobrac-bete,News,106386.html).

**Comment by yanus171** [comment]
Try to set "label" as class for categories in this domain. But anyway I 
will fix that bug

**Comment by ThomasLeigh** [comment]
Thank You very much, it’s better now. Should I close this issue?

**Comment by yanus171** [comment]
No
