### ISSUE TITLE
Category filters.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#566]
If a category filter is not a regex:

1. Is it case-sensitive?
2. What should I enter to construct a filter referring to categories containing a particular word? Does it have to be a regex filter in such a case? If so, could You give an example of such a filter for categories containing a particular word?

**Comment by yanus171** [comment]
The non regex filter is NOT case sensitive. You can give a word that should 
be contained in the category list. For example: the word "sport" would be 
triggered for category list "big Sport, tennis, football". Anyway check it 
please

**Comment by ThomasLeigh** [comment]
> The non regex filter is NOT case sensitive

Are You sure? Because in case of “Remove text” filter a non-regex filter is case-sensitive (I’ve double-checked that).
