### ISSUE TITLE
Improve F-Droid update time.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#567]
Recently I’ve stumbled upon a way which may help provide F-Droid users with quick HNR updates. It has been implemented within NewPipe Android app. Here is the quote describing this improvement:

> “If you use the F-Droid app, it notifies you as well about an update for NewPipe - please keep in mind that it can take F-Droid a while to update their repository. A new alternative to this is adding https://archive.newpipe.net/fdroid/repo?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501 as a new repository in your F-Droid client then updating. You will get updates quickly and within the F-Droid app. These builds are the same as the ones released on GitHub, so if you currently have the official F-Droid version, you will need to uninstall that to use a GitHub/NewPipe repository build (make sure to back up data).”

What do You think?

**Comment by yanus171** [comment]
What should I do?

**Comment by licaon-kter** [comment]
"reproducible build" :)

**Comment by ThomasLeigh** [comment]
I’m not sure, but maybe it’s about self-hosting Your Own custom repo, [like this](https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/). Looks pretty complicated.
