### ISSUE TITLE
one feed doesn't work, error message too quick

### ISSUE THREAD

**Issue by fuckyourdumbshit** [yanus171/Handy-News-Reader#570]
**Describe the bug**
The feed at http://harpers.org/rss fails to load unlike the 30 feeds that work fine. This feed also works fine in Flym but not in handy. There is a red error message that goes away too quickly for me to read.

**To Reproduce**
Add the feed linked above and try to refresh it.

**Expected behavior**
It should load like it does in Flym and like all other feeds do in handy.

**Smartphone (please complete the following information):**
 - Device: lg stylus
 - OS: android 8.2

**Comment by yanus171** [comment]
Try https://drive.google.com/file/d/1aRGCQ-O-NjibH3gAF33-F0APENMvlm-u/view?usp=drivesdk
