### ISSUE TITLE
Crash on opening a shortcut to the “Without a Feed”.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#571]
A few days ago I created a desktop shortcut to HNR’s “Without a Feed” group. Now, given the app is not present within RAM, tapping on the shortcut results in the app crash (I’ve sent the crash report via email). The crash does not happen if the app is already present within the RAM. The issue does not occur in case of other shortcuts (e.g., to “Favorites”).

**Comment by yanus171** [comment]
Try 
https://drive.google.com/file/d/1aRGCQ-O-NjibH3gAF33-F0APENMvlm-u/view?usp=drivesdk

**Comment by ThomasLeigh** [comment]
Thanks, it works. This ver. does not display article icons, even if re-enabled in settings.

**Comment by ThomasLeigh** [comment]
Should I create another threat for that?
