### ISSUE TITLE
Custom font?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#572]
1. There is no “custom font” string in Crowdin.
2. Can this feature be used to set a custom font for whole article text? How to do that?

**Comment by yanus171** [comment]
Copy custom font ttf file in the feedex/fonts/ folder and select it in 
Theme - Font setting

**Comment by ThomasLeigh** [comment]
Thank You.

I created “feedex” and then “fonts” folder on sd-card, then put .ttf file into it, stopped HNR and relaunched it. Unfortunately it does not see the font. I did the same on internal memory.

Here You are [the font](https://cloud.trailofthelight.xyz/wl/?id=smeekXBs6ZEdjfBUy3dluo2j5WtXSDhX) - it should be called “Lato” or “Lato Light”..

**Comment by yanus171** [comment]
You should not create the folder by yourself. It should be created 
automatically. You should copy the ttf file in another folder (see storage 
settings in additional section)

**Comment by ThomasLeigh** [comment]
Oh. I thought that the “feedex” folder should be present directly within root storage. Once I’ve put .ttf file into this path:

	/storage/75F7-14F9/Android/data/ru.yanus171.feedexfork/files/feedex/fonts

it works.
