### ISSUE TITLE
“Show article icon” does not work.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#573]
Since the two recent updates there is no article icon displayed on article list anymore. I tried to disable and enable it again - to no avail.

**Comment by yanus171** [comment]
Try to set Settings-Article Refresh-Preload images to Always

**Comment by ThomasLeigh** [comment]
It helped partially, meaning: now there are article icons, but only those made out of article images. Earlier on there were also squares of various colors with a letter inside (I guess the first letter of a feed name).

**Comment by yanus171** [comment]
I have removed these squares for the sake of article title space

**Comment by nikhilCad** [comment]
Same issue, but for me Setting preload images to always don't help
