### ISSUE TITLE
OPML import broken

### ISSUE THREAD

**Issue by SIRSteiner** [yanus171/Handy-News-Reader#574]
You cannot import opml file in v15.0 neither at startup a fresh installation nor via menu.

I sent the crash data to you.

**Comment by yanus171** [comment]
Do you have settings-advanced-use standard file manager enabled?

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.15.1

**Comment by SIRSteiner** [comment]
With v0.15.1 it is fixed. Thanks
