### ISSUE TITLE
Larger article text size.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#575]
Could it be a big trouble to allow to enlarge article font size by two-three additional levels (so 10-11 instead of 8)...? If it wouldn’t be so much trouble, please make it happen...

**Comment by yanus171** [comment]
OK

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.15.1

**Comment by ThomasLeigh** [comment]
**Thank You very very much.**
