### ISSUE TITLE
Which load type would fit this scenario?

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#578]
I’d like to ask You on the following scenario:

There is a non-RSS website on which **links** to articles I am interested into have “read-more” class. I’d like HNR to scan the main domain for links with “read-more” class and load their destination as separate articles.

1. What load type should I use?
2. Do I understand correctly that “Web Page - Divide” does not fit this scenario?
3. If I should use “Web Page - Links”, what can I do to load only links with “read-more” class?

**Comment by yanus171** [comment]
You should use Web page links type with URL feed settings set to web page 
content with read more links.
You have two possible scenarios:

1. You should get the web page content with read more links only. So in HNR 
Read now your web site page with read more links, go to Edit content mode 
and set the full text root to class that correspond to one of the read more 
links. (There can be many full text root points in article with the same class)
or
2. Use the web page with read more links as it's own and setup filters to 
remove unnecessary links.

**Comment by ThomasLeigh** [comment]
In case of the second scenario:

1. Does the filter should be applied to content or links?
2.  Is it possible to create a filter (“ACCEPT”)_allowing only links with “read-more” class?

**Comment by yanus171** [comment]
The filter should be applied to links.
You can create accept filter, but not for class but for URL.

But the first scenario is more simple. Give me a link to your web page and 
I will try to find a class name for you.
