### ISSUE TITLE
Data Units Clarification.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#580]
There are several places within HNR where data units may be displayed (e.g., the sidebar, the notification...). Could we clarify those units, choosing between decimal (e.g., megabyte › MB) and binary (e.g., mebibyte › MiB) system?

See [this](https://en.wikipedia.org/wiki/Mebibyte) for example.

**Comment by yanus171** [comment]
The image size is always displayed in Megabytes. The article text size is 
always displayed in Kilobytes

**Comment by ThomasLeigh** [comment]
Could we therefore change “M ”into “MB” and “k” into “kB”?

**Comment by yanus171** [comment]
I will try, but it seems to occupy more space

**Comment by ThomasLeigh** [comment]
I personally do not care so much about units, but recently I discovered that there is also this binary system of which I haven’t heard before. Earlier on I was totally convinced that 1MB = 1024kB. Now, You could guess that there might be users for whom this matter is important, and the sole “M” letter would confuse them. For me it’s very strange case, though. And “MiB” always reminds me of “Man in Black” ;) .
