### ISSUE TITLE
Images are not available off-line.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#582]
Here You are how it looks in my case: if I am on-line, images are loaded on-the-fly, but while off-line there are no images. I’ve checked this behavior even after full refresh (a couple of times).

On this [video](https://cloud.trailofthelight.xyz/wl/?id=apeJpNVOl4mLfWhX6cvDZxFIsWDfjGfi) I initially am off-line, then I switch on-line and then off-line again.

**Comment by yanus171** [comment]
I can't understand the problem. The images can't load offline.

**Comment by ThomasLeigh** [comment]
I thought that HNR allows to read **whole** articles off-line (images included), once they are obtained via the refresh process.

**Comment by yanus171** [comment]
From your video I don't see that you have loaded (refreshed) the articles 
with images before

**Comment by ThomasLeigh** [comment]
[Here](https://cloud.trailofthelight.xyz/wl/?id=apeJpNVOl4mLfWhX6cvDZxFIsWDfjGfi) You are.

**Comment by yanus171** [comment]
Again. You are scrolling only be articles. If you swipe back to articles 
with already loaded images (from right to left) you will see the article 
images even in offline phone mode

**Comment by ThomasLeigh** [comment]
Yes, but I thought that images are obtained during the refresh. It seems they don’t. Could they be obtained via the refresh, instead of the very moment I’m opening the article?

**Comment by yanus171** [comment]
So, go to this feed settings and check Auto images load

**Comment by yanus171** [comment]
And refresh

**Comment by ThomasLeigh** [comment]
It works, thank You; I haven’t known that this option should be enabled to include images within the refresh.
