### ISSUE TITLE
Font proposition.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#587]
I’d recommend the Lato fonts to be included within pre-installed fonts in HNR. 

> “The Lato font family is available as a free download under the SIL Open Font License 1.1. The fonts can be used without any limitations for commercial and non-commercial purposes. They can be also freely modified if the terms of the license are observed.”

[more information and download](http://www.latofonts.com/lato-free-fonts/)

**Comment by yanus171** [comment]
Pull request ttf file in fonts folder please
