### ISSUE TITLE
Old articles spam on every triggered update

### ISSUE THREAD

**Issue by hontogit** [yanus171/Handy-News-Reader#588]
**Describe the bug**
With the last update of HNR (0.15.1), it loads for most of my feeds lots of old and dated articles per feed, like if I would add them the first time. And it does this on every update of articles, even if I delete all of them.

**To Reproduce**
Seems obvious.

**Expected behavior**
HNR fetches the newest published articles after last read, and deletes those older than days set in preferences.

**Smartphone (please complete the following information):**
 - Device: HTC One
 - OS: Android 7.1.2
 - Browser: Fennec F-Droid
 - Version: 0.15.1

**Additional context**
Like I said, it happens with most, not all feeds. One exception I noticed are feeds from github.

And I also observed this behaviour in the past month with a few feeds like https://blog.joinmastodon.org/index.xml or https://signal.org/blog/rss.xml - but not on every update or with listing more than five articles.

**Comment by ThomasLeigh** [comment]
Me too.

I have the impression that my HNR does not remember what I’ve read: during the refresh HNR loads articles which I’ve already read. Sometimes a few of them, sometimes many more (maybe it loads the whole content of an RSS feed).

**Comment by spaetz** [comment]
Same here, not all feeds though. It loads all items as new despite having been read. AND it marks the date of the posts as.the.date and time when it fetches these again,.so somehow it fails to parse the date of the posts in the feed. Not all feeds though. Failing feeds for me are: https://aspaeth.de/feed
https://www.economist.com/europe/rss.xml
Many other feeds work fine.

**Comment by yanus171** [comment]
Try this https://drive.google.com/file/d/17zGywigjSfSRz0x0FDYkKRQEibMeaWHW/view?usp=sharing

**Comment by yanus171** [comment]
Try https://drive.google.com/file/d/17zGywigjSfSRz0x0FDYkKRQEibMeaWHW/view?usp=sharing

**Comment by spaetz** [comment]
Yes! The articles show their real date, now rather than the datevwhen they were fetched!

**Comment by spaetz** [comment]
Akthough, I do get some old articles occasionally thrown in, that *appear* to have the fetch date, but are in reality old articles from a subscribed wordpress feed.

**Comment by yanus171** [comment]
Is this a feed problem?

**Comment by spaetz** [comment]
I don't think so. The feed looks OK and I have old articles popping up from eg https://www.pro-linux.de/rss/index1.xml and https://aspaeth.de/feed. Which both look just fine as RSS.

**Comment by hontogit** [comment]
With the new version from f-droid I can't reproduce the issue now. Looks solved for me. 🙂 Thank you!

**Comment by newissuemaker** [comment]
I am still having this problem, it males getting to the actual new stuff difficult as I can't always remember what I read or dismissed (marked a read) before.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1079762063

**Comment by touwys** [comment]
With the assumption that when "Delete all read articles" is enabled, old articles previously deleted will return, is there a solution in the offing that will eventually prevent these from returning? Is it even possible to prevent it from recurring?

**Comment by yanus171** [comment]
Do you observe this behavior in the last beta?

**Comment by newissuemaker** [comment]
> With the assumption that when "Delete all read articles" is enabled, old articles previously deleted will return, is there a solution in the offing that will eventually prevent these from returning? Is it even possible to prevent it from recurring?

I actually tried to check that a while ago but I couldn't find it in the UI at the time and forgot about it. I'll retry, thanks.

**Comment by touwys** [comment]
> Do you observe this behavior in the last beta?

If this question was addressed to me — and if the beta version is Release 0.16.22 — then yes. Loads and of old articles returning.

**Comment by touwys** [comment]
With release v0.16.23: this issue persists.

**Comment by nikhilCad** [comment]
For me this issue regularly happens on Github, Youtube and this feed https://old.reddit.com/r/twoxindia/search.rss?q=onex+wednesdays&restrict_sr=on&sort=relevance&t=all

I think main issue is that dates aren't being parsed correctly.

**Comment by yanus171** [comment]
@nikhilCad, thank you. I have fixed some date parse errors. Wait for the next beta

**Comment by touwys** [comment]
Anybody else care to comment if this issue is largely resolved for them too? With the release of v0.16.28? I notice a huge gain. Thank you @yanus171

**Comment by touwys** [comment]
@ Thank you ThomasLeigh, I concur.

**Comment by ThomasLeigh** [comment]
Unfortunately yesterday I received one year old post from one YouTube channel, another old post from yet another YouTube channel :( .

**Comment by ThomasLeigh** [comment]
In one YouTube channel I’ve just received a one-month-old article, another channel gave six-month-old article :(

**Comment by yanus171** [comment]
Can you give an url of this post and channel?

**Comment by ThomasLeigh** [comment]
@yanus171 I don’t have those posts even within the already read articles, I’ve just installed the newest beta ver. - if I encounter this behavior again, I share direct links to those posts and channels.

**Comment by ThomasLeigh** [comment]
@yanus171 

Ok, I’ve already have some examples:

[channel 1](https://www.youtube.com/feeds/videos.xml?channel_id=UCSc73ZLW4BGSsP2yJWOJRFQ) : [the article link (video) - one year ago](https://www.youtube.com/watch?v=kSojY55xoqE)


[channel 2](https://www.youtube.com/feeds/videos.xml?channel_id=UCt_rozszkv0IYrM8U-rkN1g) : [article - 8 months ago](https://www.youtube.com/watch?v=NoxrfBsWU5k)


[channel 3](https://www.youtube.com/feeds/videos.xml?channel_id=UCgo2BrI5xkXduYvYv6lskkg) : [article 1 - one month ago](https://www.youtube.com/watch?v=xbXyqSRO9Jk) ; [article 2 - one month ago](https://www.youtube.com/watch?v=h8O7PgAHC8A)

**Comment by touwys** [comment]
Release v0.17.1

This is also a troublesome feed that reloads old articles upon refresh:

[**Old articles spam**
](https://www.gunafrica.co.za/rss-feed/category/342/)

**Comment by yanus171** [comment]
Give a link to channel and post please

**Comment by nikhilCad** [comment]
Does this still happens to anyone? For me its more or lss fixed.

**Comment by ThomasLeigh** [comment]
For me it's still happen, regarding YouTube channels, although not every time. It could be great to fix that somehow, because it would save confusion or even irritation for the users who experience that behavior.
