### ISSUE TITLE
The “Holy Grail” of RSS readers’ users.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#589]
I become more and more concerned about browsing various content sources via an RSS reader. The reason is that I’m usually skip most of the new articles (!!!). Although HNR is equipped with a pretty nice set of advanced ways to tailor Your favorite set of content, I’m still having serious trouble with this, it’s a big challenge, not due to the app itself, though.

I tried to confine feeds to particular labels (categories), but it is still doesn’t help much, I guess due to those categories being not precise enough (which unfortunately is not up to HNR itself).

My “Holy Grail” is the situation in which the majority of new articles are interesting for me. But currently I can’t manage to achieve such a perfection.

I’d like to ask You, since You are probably subscribe many sources - **what percentage of newly arrived articles are in fact interesting for You, usually?** And, perhaps, how You improve the overall stream of content to be much more interesting?

I feel more and more concerned about it because on one hand it’s a waste of time to browse articles only to skip 80-90% of them - on the other hand, however, those 10-20% are interesting enough. But if I can’t distinguish them by a category or anything else... I don’t know what to do.

**Comment by Ryuno-Ki** [comment]
Actually, I'm skipping all news for months now just to catch up with the 250+ I starred for later reading (down to about 150 now).
