### ISSUE TITLE
Web  Page (Links) - help request.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#590]
I’d like to ask for help with the following scenario:

There is a single page with a lot of links: an e-zin archive from 1 to at least 250 issues. Links to all those 250+ issues are present on [that single page](http://www.realityshifters.com/pages/news.html). They have no HTML class, but they all have “archives” within their address.

Now, I’d like to add this particular single page to *HNR* to load all the archive links. I’ve added the page (the address linked above), set load type as “Web Page - Links”, added an ACCEPT filter (regex checked) applied to URL:

	/(?:archives\/)(?:.*)/
	
Alternatively I tried:

	/(?:.*)(?:archives\/)(?:.*)/
	
Of course I’ve reset the feed before all the next attempts. Unfortunately I still end up with a single article (“Reality Shifters - News”) instead of all the 250+ links loaded as separate articles.

Could You please help me with the proper setup?

**Comment by ThomasLeigh** [comment]
I also tried a non-regex filter applied to title - with a word “RealityShifters”. It also does not help. All the links are loaded when I don’t use filters.

**Comment by yanus171** [comment]
You should you accept non regex filter with word archive

**Comment by ThomasLeigh** [comment]
Indeed, thank You.
