### ISSUE TITLE
Deleted Articles Downloaded Again and Again (Web Site - Links)

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#596]
I’ve labelled this as “bug” although I am not sure whether it is supposed to be viewed this way. One way or another, it would be much better to fix it. Here is what I mean:

I subscribe a website via “Web Site - Links” load type. I’ve marked all its articles as read because I don’t want them to interfere with the “Unread” list. I’ve starred them manually (a couple of hundreds articles..........) in order not to have lost them, because although I have articles kept forever, read articles are deleted, so I had to ensure that those articles won’t be removed. Unfortunately they therefore interfere with my “Favorite/Starred” list.

**The thing is I’d like to have a clean article list** (meaning: consisting only of articles I’d like to read). I could display only unread articles, but then they’re interfere with the main “Unread” list - which I don’t want. Therefore I’ve marked them all as read and I delete articles which I’ve done reading. But **they come back via another refresh**, they are haunting me ;) .

**Comment by yanus171** [comment]
You want to say that we need Delete read article checkbox in feed edit 
dialog (per feed)?

**Comment by ThomasLeigh** [comment]
No. I mean this:

Imagine a web page with 300 links. You add that page to *HNR* with “Web Page - Links” load type. Suppose You end up therefore with 300 unread articles. You read them and they are read now. If You toggle *HNR* to show read articles, You still see 300 articles - now read. **To this point everything is fine as should be.**

What I’d like to ask for is:

**could it be possible for those 300 articles not to be downloaded again during the next refresh, even if they’ve been deleted via “Delete Read Articles”?**

**Currently in such a case the 300 articles are downloaded again, so I handle this scenario a little bit differently:**

1. You have the feed “X” with 300 unread articles.
2. You don’t want those articles to be displayed within the main Unread list, so You mark all the 300 articles as read on the get-go.
3. But You still want the “X” feed list displaying only articles which You don’t yet read, therefore 1) You delete those articles which You really have read and 2) You mark all the 300 articles as starred to preserve them (otherwise they may be deleted automatically).

Unfortunately in that scenario the 300 articles still interfere with the main Favorites list, but I don’t know a better way.

**Comment by yanus171** [comment]
The solution is not to delete read articles.

**Comment by ThomasLeigh** [comment]
But then my list will display both articles I’ve read and those which I haven’t.

**Comment by yanus171** [comment]
That why you asked for #599.

**Comment by ThomasLeigh** [comment]
If You subscribe an RSS feed, You don’t want the articles You’ve read to be downloaded again. I’d like to have the same behavior in case of “Web Page - Links”. But it seems deleting read articles is an obstacle here, because it makes read articles to be downloaded again (once they’ve been deleted).

Deleting read articles seems not to be an obstacle in case of RSS feeds - meaning: *HNR* still somehow remembers which articles You’ve read, even if they’ve already been deleted. Those articles usually do not show up again once the next refresh.

In case of “Web Page - Links” it seems not to work that way, meaning: every article which has been deleted, will be downloaded again during the next refresh.

My point is that I’d like to receive only new articles via “Web Page - Links” - as in case of ordinary RSS feeds.

**Comment by ThomasLeigh** [comment]
#599 refers to the matter of article list remembering its “mode” (whether to display only the unread articles or not) - **per a single feed**. So that You could switch between feeds and its lists could display articles in various ways, e.g., You open a feed nr 1 and You see only the unread articles, You open a feed nr 2 and You see not only the unread articles. And so on.

**Comment by yanus171** [comment]
You had no need to delete read articles in Web links feed. Just enable 
unread filter checkbox to hide them

**Comment by yanus171** [comment]
The RSS feed has exact publication time for every article. So the app 
remembers the date time of last refresh and l in the next refresh operation 
it loads only articles that are newer than that date.
In case of Web page links feed the app doesn't know the article publication 
time so it can't distinguish the new articles from old (in case you have 
deleted them).
In the next all release I try to determine the publication date of Webpage 
listed articles (via time html tag and event html code extract rules 
preference), but it doesn't work for all web pages.

**Comment by ThomasLeigh** [comment]
> You had no need to delete read articles in Web links feed. Just enable unread filter checkbox to hide them

But I use automatic deletion of read articles to optimize the app.


> In case of Web page links feed the app doesn't know the article publication time

What do You think therefore about the refresh time as the article time? E.g., if *HNR* obtained articles (I mean only “Web Page - Links” here) on July 1, 13:01, it sets their date as July 1, 13:01 and it will remember both article titles and their time even if they’ve been deleted. It would clear this information once the feed has been reset.

**Comment by Peterspapan** [comment]
I have a similar problem. Automatically deleted old articles reappear as new even if the are years old but not in all feeds. I can live with that butvit is sometimes misguiding.
