### ISSUE TITLE
Tap on notification on starred article results in endless loading.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#598]
I use “Mark as Starred” filter, therefore I sometimes have Android notification that an article has been marked as starred. I can tap the notification and should then see the article. Unfortunately when I tap on it, it opens a blank page with endless loading. If I, however, open the same article from the article list in *HNR*, it works fine.

[The video](https://cloud.trailofthelight.xyz/wl/?id=1d3ZzNnWpvDmwuQW9lNh5Yxa4f77wB7j).

**Comment by yanus171** [comment]
I cant reproduce it
