### ISSUE TITLE
Pictures not preloading if feed from OPML import

### ISSUE THREAD

**Issue by Closer2U** [yanus171/Handy-News-Reader#601]
**Describe the bug**
I imported an existing OPML which I created with Flym. Pictures from the feed were shown there but are not in the Handy-News-Reader. I would have to tick the "load pictures" separately  on every feed (but I have over 150).
If the feed is added directly ( "+" --> url to rss or atom feed pasted --> tick preload pictures) then everything works fine. 

**To Reproduce**
1. Go to '(import) OPML'
2. Add the existing feed with everything ticked correctly and pre configured in menu

**Expected behavior**
I would expect the pictures to be shown next to the headlines in my feed. 

**Smartphone:**
 - Device: Xiaomi Redmi Note 7
 - OS: MIUI 11.0.8 (MIUI optimization turned off)
 - Version of the app: v0.15.1

**Comment by yanus171** [comment]
Are there only headline images are not shown or all article images?

**Comment by Closer2U** [comment]
Only the headline ones while scrolling through the feed. 
If one clicks on the headline to load the article the pictures load just fine.

**Comment by p-roman** [comment]
I have this same issue, having just imported OPML that I exported from Feedly. On latest Handy version, 0.16.15.

**Comment by yanus171** [comment]
Check feed auto load images setting
