### ISSUE TITLE
Include line-height within allowed CSS commands.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#606]
Please allow to use `line-height` within font-related CSS commands.

**Comment by yanus171** [comment]
I don't contrast CSS command set. Use Show Html to find the source of problem

**Comment by ThomasLeigh** [comment]
What do You mean by that You don’t contrast CSS command set?

There is no problem. I thought just it would be good to be able to adjust the text also with line-height (meaning: the space between each text line). Like currently we have letter-spacing and it works perfectly.

**Comment by yanus171** [comment]
Try to insert line-height text into Main font CSS text setting

**Comment by ThomasLeigh** [comment]
I’ve tried, to no avail. It reacts to letter-spacing but not to line-height.

**Comment by tasmo** [comment]
> I’ve tried, to no avail. It reacts to letter-spacing but not to line-height.

Also tried it without success.

**Comment by salim-b** [comment]
Seems related to https://github.com/yanus171/Handy-News-Reader/issues/322.
