### ISSUE TITLE
Fix the suggest link (open the mail app but doesn't set the address mail)

### ISSUE THREAD

**Issue by RAMAR-RAR** [yanus171/Handy-News-Reader#61]
-Fix the suggest link (open the mail app but doesn't set the address mail)

**Comment by ThomasLeigh** [comment]
Could You please tell a little bit more on what this request is about?

**Comment by SIRSteiner** [comment]
I think @RAMAR-RAR means the suggest link at help page. But I can't find this problem. There is nothing to fix...

**Comment by SIRSteiner** [comment]
I think this issue could be closed
