### ISSUE TITLE
Image hover text accessibility, AKA: XKCD fix

### ISSUE THREAD

**Issue by NicholasConrad** [yanus171/Handy-News-Reader#611]
Ability to view hover text on images in articles would be helpful for a growing number of web comics, most famously: XKCD.

**Comment by yanus171** [comment]
Illustrate the example please

**Comment by Ryuno-Ki** [comment]
XKCD has an m-dot site as I learned recently. You can have an adjusted feed: http://m.xkcd.com/rss.xml
