### ISSUE TITLE
Refresh almost often while launching the app.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#625]
I’ve observed that if I’m not using HNR for a while and then launching it, it often performs the refresh once it is launched. Is there a way to avoid that? (I have the refresh set to 6 hours).

**Comment by yanus171** [comment]
Check Auto refresh on app start setting

**Comment by ThomasLeigh** [comment]
“Refresh feeds on open” - I have this unchecked and I think it’s good because I don’t want the refresh being performed after each HNR launch.

**Comment by amit3s** [comment]
I see a similar behavior. I've noticed this happens of the previous feed refresh was interrupted - for example by a crash. If it runs to completion, or if I hit "cancel refresh", the next launch doesn't cause refresh.

**Comment by yanus171** [comment]
If the scheduled refresh operation is too long the system may interrupt it. So it would be scheduled again by the system and it would often start during next refresh. I could make a wake lock during refresh, but it would consume battery
