### ISSUE TITLE
Latex support?

### ISSUE THREAD

**Issue by cgoliver** [yanus171/Handy-News-Reader#626]
Love the app, wondering if it is possible or if there are plans to render latex?

EDIT: this is useful when reading math/cs blogs which often have inline latex. for example: https://www.offconvex.org/2020/06/24/equilibrium-min-max/

**Comment by yanus171** [comment]
Please describe a user case where it's suitable to read latex files on phone.

**Comment by cgoliver** [comment]
> Please describe a user case where it's suitable to read latex files on phone.

Sorry for the ambiguity, I imade a clarification in the original issue. Thanks!
