### ISSUE TITLE
Re add read later to share link options

### ISSUE THREAD

**Issue by Vormgear** [yanus171/Handy-News-Reader#627]
I used the share to read later action as the primary means of saving articles that I diden't want an ongoing subscription to or that did not have a rss feed. 

In the version 0.15.8 of handy news reader this feature was removed.

Please add it back.

**Comment by yanus171** [comment]
To reach this feature from other apps use share command

**Comment by Vormgear** [comment]
Im sorry. I meant the open with command. The share command is usauly not avalable for non selectable urls.

**Comment by yanus171** [comment]
For example in Chrome I can do a long tap on a link and select Share the link

**Comment by Vormgear** [comment]
My phone does not have that option when I long press on a link. It only shows the read now option.

**Comment by yanus171** [comment]
Show a screenshot please

**Comment by Vormgear** [comment]
When I was running handy news reader version 0.15.6 and all the versions before the open with dialogue looked like this.
![before update open with dialogue](https://user-images.githubusercontent.com/19961546/93507278-71e41f00-f8eb-11ea-8668-f966c9721c3f.png)

When I update to version 0.15.7 the read later icon is gone.
![after update open with dialogue](https://user-images.githubusercontent.com/19961546/93507277-714b8880-f8eb-11ea-9c5b-9cd25ba548a3.png)

**Comment by yanus171** [comment]
I need a video of the whole process (since browser app)
