### ISSUE TITLE
An Option to change User Agent

### ISSUE THREAD

**Issue by dorrisowens** [yanus171/Handy-News-Reader#628]
**Is your feature request related to a problem? Please describe.**

Usually when we connect to a site we share our IP address as well as useragent. While IP address can be hidden with VPN but the webview uses the User Agent which specify device model and can reveal a lot about a user.

**Describe the solution you'd like**

I Request you to add a feature to change user agent to a custom or some pre added user agents. This will not only protect privacy but will even help users to stay anonymous too as today even RSS links have implemented analytics which collects info like IP, location and Device model by useragent.

Thanks

**Comment by yanus171** [comment]
What user agent value should be sent?

**Comment by ThomasLeigh** [comment]
“Handy News Reader”?

**Comment by Ryuno-Ki** [comment]
Note, that it is [common to include the version](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) in the User Agent string.

I'd even go so far and add a comment with the library you use for making the connections (also with version).
