### ISSUE TITLE
Font cannot be changed.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#630]
One user has reported, as follows:

> “Loving your app. I have a Xiaomi Phone and I am unable to select any font from the list and even after adding my custom font in the folder I cant see it there in the options. Can you help me out?

> All the fonts appear on the list, even my custom font, but I cant select any of them. When I click on default font, only it highlights (I can post a gif if needed). So name is not changed”

Android 7.1.2 / MIUI 11.0.2, no SD-card, “Data folder” set up as “External Memory (/storage/emulated/0)”

**Comment by yanus171** [comment]
Yes, screenshot is needed

**Comment by Sarmadkh** [comment]
I have reported it. Available if more info needed.

![dannnnn](https://user-images.githubusercontent.com/29545475/95653806-d83c1600-0b14-11eb-9d98-ab6754b06544.gif)

**Comment by yanus171** [comment]
Thank you for the info. Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.15.10

**Comment by Sarmadkh** [comment]
Working like a charm. Thanks for your quick response
