### ISSUE TITLE
StringIndexOutOfBoundsException Error on Android 4.2.2

### ISSUE THREAD

**Issue by glocalglocal** [yanus171/Handy-News-Reader#631]
Handy News reader 0.15.7 on Android 4.2.2.

When updating I am getting this error:

![1a](https://user-images.githubusercontent.com/16408198/95657308-58f21680-0b03-11eb-9393-5b17c1c98600.png)

The feed is here: 
Communication Research
http://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=crxa&type=etoc&feed=rss

This works fine on my Android 6 phone.

**Comment by ThomasLeigh** [comment]
@yanus171  Could it be related to [this one](https://github.com/yanus171/Handy-News-Reader/issues/632)?
