### ISSUE TITLE
Syntax error on Android 4.2.2

### ISSUE THREAD

**Issue by glocalglocal** [yanus171/Handy-News-Reader#632]
Handy News reader 0.15.7 on Android 4.2.2.

When updating I am getting this error:

![3a](https://user-images.githubusercontent.com/16408198/95657387-d61d8b80-0b03-11eb-9134-1b35b6f9b768.png)

The feed is here: 
International Journal of Communication 
http://ijoc.org/index.php/ijoc/gateway/plugin/WebFeedGatewayPlugin/atom 

It works fine on my Android 6 phone.

**Comment by yanus171** [comment]
I know about this problem and I see no solution to it. To list such a feed 
I should to l use okhttp lib. But the latest okhttp release demands Android 5+

**Comment by glocalglocal** [comment]
In that case, in addition to the error messages, could HNR explain nothing can be done about this and #563 so that users don't think they are bugs?

**Comment by ThomasLeigh** [comment]
I think it’s a great idea, related to [this one](https://github.com/yanus171/Handy-News-Reader/issues/420).
