### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [yanus171/Handy-News-Reader#634]
https://f-droid.org/wiki/index.php?title=ru.yanus171.feedexfork/lastbuild_220&oldid=280175

**Comment by yanus171** [comment]
Can you help me with understanding the source of the problem? I have no problems with complie on my desktop.
How could the new release https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.15.13 be checked ?

**Comment by yanus171** [comment]
The error is described as
e: /home/vagrant/build/ru.yanus171.feedexfork/FlymFork/src/main/java/ru/yanus171/feedexfork/parser/HTMLParser.kt: (99, 9): 'run(T.() -> R): R' is only available since Kotlin 1.3.50 and cannot be used in Kotlin 1.3

**Comment by relan** [comment]
0.15.3 fails with the same error: 'run(T.() -> R): R' is only available since Kotlin 1.3.50 and cannot be used in Kotlin 1.3

Full log: https://f-droid.org/wiki/page/ru.yanus171.feedexfork/lastbuild_223

**Comment by yanus171** [comment]
May be it worths to update Kotlin in virtual machine?

**Comment by licaon-kter** [comment]
Where does Kotlin come from exactly?

**Comment by yanus171** [comment]
Try a new release https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.15.14 please

**Comment by licaon-kter** [comment]
Better, thanks

**Comment by yanus171** [comment]
Does it compile successfully now?

**Comment by licaon-kter** [comment]
Yes, will be picked up next cycle.
