### ISSUE TITLE
Inquiries and suggestions regarding article title

### ISSUE THREAD

**Issue by AI-IMED** [yanus171/Handy-News-Reader#635]
Hi Alexey
 I adore HNR;  Because it allows me great control to customize the reading experience according to what I want, but I want more :-)

 Is there a way at the moment that enables me to control the alignment of article titles for any feed, either towards the right or the left, instead of center alignment?  If there is no way to do so, what do you think about applying centering of the article title only when the "Justified text" option is activated.

 - Creating an option to show or hide the top click areas might be better than having the top click areas visible permanently and not being taken advantage of, some people might need it, but for me I didn't find it any benefit

 - I suggest that if the "Title link" option is enabled, the article title text takes the color of the links, that would be great

**Comment by ThomasLeigh** [comment]
@afmbsr  We collect our users’ impressions on Handy News Reader to share on [our website](https://handynewsreader.blogspot.com/) (“about” section). Would You be willing to share Your Own thoughts? If so, I invite You to take a closer look [here](https://github.com/yanus171/Handy-News-Reader/issues/147).

**Comment by afmbsr** [comment]
@ThomasLeigh Sure, I would be happy with that
