### ISSUE TITLE
“Scroll to top” within lists.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#636]
Since to my sadness [HNR does not remember individual lists positions](https://github.com/yanus171/Handy-News-Reader/issues/533), I often need to loooong scroll to reach the first article. It would be great to have “a ball button” in the bottom right (next to “mark as read”) to go directly to the top, either within article list or an article itself. We could then remove “Scroll to top” from the menu.

The reason I think “the ball button” would be better than a menu item is that this particular action (scroll to top) may be especially useful and desired to reach quickly, to have it always at hand (meaning: one tap needed instead of two taps).

**Comment by touwys** [comment]
I second this motion of Thomas Leigh. 

Why though, a ball-button with which to scroll to the top instantly, instead of the usual, instantly recognisable, upwards-pointing arrow?

**Comment by ThomasLeigh** [comment]
For the sake of UI’s consistency - of course it could be also an upwards pointing arrow within the ball :) . It would be great :)

**Comment by touwys** [comment]
:))

**Comment by yanus171** [comment]
I could add a tap zones for it. To the top right and left edges of the screen (as in article view screen) one for scroll to the top, other one to the bottom.

**Comment by touwys** [comment]
If others agree with this, is it feasible for you to adjoin the Scroll-to-Top and Scroll-to-Bottom buttons — in their natural top-bottom configuration — and place them both at the centre of the top edge? 

Thanks.

**Comment by ThomasLeigh** [comment]
> I could add a tap zones for it. To the top right and left edges of the screen (as in article view screen) one for scroll to the top, other one to the bottom.

I think it would be much more intuitive if placed on the bottom. It would be great great great to have that ball... :) :) :) Tap Areas are ok, I just much like the look of the ball and even if a user doesn’t know about Tap Zones, per will definitely notice the ball :)

Peace! :)

**Comment by yanus171** [comment]
The bottom edges are already occupied by next page, status and action bar visibility toggle tap zones.

**Comment by yanus171** [comment]
That is the ball button? (Image)

**Comment by ThomasLeigh** [comment]
@ya\ There is no image.

**Comment by Ryuno-Ki** [comment]
I'd assume a [FAB](https://material.io/components/buttons-floating-action-button) was meant here.

**Comment by ThomasLeigh** [comment]
@Ryuno-Ki  Yes.

**Comment by kisccz** [comment]
Hey guys did get a solution to this?

**Comment by yanus171** [comment]
May be long tap on the top/bottom area

**Comment by ThomasLeigh** [comment]
**Fantastic**, thank You so so much @yanus171  !!! :)

**Comment by touwys** [comment]
Большое спасибо, спасибо! @ yanus171

Much appreciated, thank you! @yanus171
