### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by Sarmadkh** [yanus171/Handy-News-Reader#637]
I like the way you people are making the app better every day. Here are few suggestions. Please consider.

1. Scroll to top button in the article list and within the article. (Already requested now)
2. Option to remove duplicate articles. The ones having the same title. Flym has this option.
3. Option to export the article extraction rules.
4. Option to re-apply the extraction rules on articles that match the criteria. Currently, once I have created an extraction rule, I have to open each article and refresh it for the rules to be applied.
5. Justified text option is not working for my language. (Urdu - It is read right to left)

**Comment by yanus171** [comment]
1. So post about it to that issue (not this)
3. You can copy and paste settings from Advanced - Content extract rules 
section. Also you can export HandyNewsReader_auto.backup file, which 
cantons settings info
4. This option is already exists and is named Reload all texts in Visible 
articles section of the article list menu.

Things would much be easier if you'd separate your suggestions in the 
separate issues

**Comment by ThomasLeigh** [comment]
@Sarmadkh We collect our users’ impressions on Handy News Reader to share on [our website](https://handynewsreader.blogspot.com/) (“about” section). Would You be willing to share Your Own thoughts? If so, I invite You to take a closer look [here](https://github.com/yanus171/Handy-News-Reader/issues/147).
