### ISSUE TITLE
Remove duplicate articles.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#638]
(a separate issue extracted from [here](https://github.com/yanus171/Handy-News-Reader/issues/637#issue-722428427))

> Option to remove duplicate articles. The ones having the same title. Flym has this option.

**Comment by yanus171** [comment]
Should this option work during the refresh or new articles or should it be 
an operation applied to all existing articles?

**Comment by ThomasLeigh** [comment]
@Sarmadkh What do You think?

**Comment by Sarmadkh** [comment]
I think it should work while fetching the articles. I mean there will be no duplicate articles anymore in the list if it is implemented during the sync. I am not a developer but since Flym has this option and it works flawlessly, you can check how they are doing it.

**Comment by ThomasLeigh** [comment]
@yanus171  What do You think?

**Comment by kisccz** [comment]
Duplicate articles are still appearing in my feeds :(
