### ISSUE TITLE
Refresh the group refreshes also feeds from outside the group.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#641]
This issue shows up when You have feeds arranged within several groups. It looks like that:

1. On the sidebar tap on a feed group name to display all the articles from the group.
2. Tap on the refresh icon on top » I think it should refresh only feeds which belong to the group, but I am 100% sure that it also refreshes other feeds (I’m not sure if all HNR feeds are refreshed or just a few more from other groups).

> Android 10 / HNR 0.15.12

**Comment by yanus171** [comment]
How do you understand that over feeds are refreshing?

**Comment by ThomasLeigh** [comment]
Suppose You have 100 feeds all together, organized into several groups. Suppose one group has three feeds. Now, if You tap on that group name on the sidebar, and then on the refresh icon - it won’t refresh only those three feeds, but also other (I think all the rest 97).

**Comment by yanus171** [comment]
How do you understand that over feeds are refreshing

**Comment by ThomasLeigh** [comment]
I see new articles from other feeds than ones from the group within which I tapped the refresh icon. Those articles have never been seen before.
