### ISSUE TITLE
Github code snippets not visible.

### ISSUE THREAD

**Issue by PrithirajN** [yanus171/Handy-News-Reader#644]
**Describe the bug**
The Github code snippets are not shown in the app.

**To Reproduce**
1. View this article- “Announcing Flutter Windows Alpha” by Chris Sells https://link.medium.com/TBKZQXjvTab
2. Scroll down a bit you will see a big gap in the, there should be the snippet.
3. This can be confirmed by going to the original article in Medium

**Expected behavior**
There should have been a code snippet.

**Screenshots**
This is how it is shown in the app:
![Screenshot_2020_1026_144530](https://user-images.githubusercontent.com/60390549/97154598-16366c80-179a-11eb-9fd3-b55afc3c55b3.jpg)

This is how the original article looks:
![Screenshot_2020_1026_144617](https://user-images.githubusercontent.com/60390549/97154730-42ea8400-179a-11eb-84b8-85c31af776b6.jpg)

**Smartphone (please complete the following information):**
 - Device: Vivo Y98
 - OS: Android 8
 - Browser: Chrome

**Additional context**
Hope the problem is solved, due to this many a time I face difficulties as I love to use this app to learn web development and mobile development and the code snippets are very important.

**Comment by yanus171** [comment]
Try to turn on settings, advanced, convert do symbols before parsing

**Comment by PrithirajN** [comment]
> Try to turn on settings, advanced, convert do symbols before parsing
> 
> 
> 

Nothing happens, I tried.

**Comment by Ryuno-Ki** [comment]
If you check the source code of https://medium.com/feed/flutter, you'll notice, that the code snippet gets loaded as iFrame. (Ctrl-F „win32 plugin”).

On the website, Medium is loading its content asynchronously. Could that be a reason?
