### ISSUE TITLE
Parsing error on a RSS feed

### ISSUE THREAD

**Issue by GFNIAE** [yanus171/Handy-News-Reader#645]
I am a grateful user of Handy News Reader. I downloaded the app from f-droid repo and it is updated (0.15.7). Android 9, Samsung A20e.

I met an issue when trying to load this rss channel : www.jeuneafrique.com/feed. I have no problem with it when using other apps like Feeder (but does not load the full articles, I have to display them with web app) or Flym (works and load the full articles and pictures).

The following error is displayed in Handy News Reader :
org.apache.harmony.xml.ExpatParser$ParseException:
At line 13, column 4: mismatched tag

Is there something you or I can do to use this rss feed on Handy News Reader ?

**Comment by Rochey** [comment]
I've got a similar issue with
http://www.androidpolice.com/feed/
Same parse exception error just a different line and column, line 6 column 14 not well formed (invalid token)
I also see the error in the left side menu under AndroidPolice which has the correct icon but under it it says Line 6 Column 14.

The feed works fine on other RSS apps, I've tried spaRSS reader and Flym from Fdroid.
If you need anything from me to help resolve the issue please let me knw.

**Comment by yanus171** [comment]
The loaded content of http://www.androidpolice.com/feed/ in HNR is:
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.19.8</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"6582152c08d5169d","token":"a8ce4878c95b4c46a3e337c0a39e65c9","version":"2021.5.2","si":10}'></script>
</body>
</html>

But in desktop Chrome I see normal feed output

**Comment by ThomasLeigh** [comment]
Similar error message with [this RSS](https://fileland.pl/rss.xml) - could anything be done to be able to read it in HNR again?

![Screenshot_2021-08-18-17-42-50-867_ru yanus171 feedexfork](https://user-images.githubusercontent.com/26142231/129963240-440f9c3f-ccf1-4b08-9561-0a2575457223.jpg)

**Comment by yanus171** [comment]
This site needs registration

**Comment by ThomasLeigh** [comment]
Is it possible to log in within HRN? I tried to "read now" fileland.pl and it does not help because the log-in form does not work.

**Comment by yanus171** [comment]
Currently it's impossible to log within HNR. Try to log in via browser before using HNR

**Comment by ThomasLeigh** [comment]
@yanus171  I’ve logged in within Chrome, MI Browser, Brave... nothing helped, unfortunately.

**Comment by evoke322** [comment]
I meet the same issue, for example, [1](https://feeds.feedburner.com/ruanyifeng) , [2](http://diygod.me/feed) . HNR can load the icon but show nothing in the articles list.

**Comment by yanus171** [comment]
The first feed has loaded correctly in the latest release. For the second please make a separate issue named JSON RSS feed
