### ISSUE TITLE
Automatic Sorting of Groups, Sub-Groups, Feeds and Labels by Name

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#647]
When adding a new Label or Feed to a huge, fast-growing list of sources, it calls for a method much quicker and less tedious than having to manually move the newly added feed or label from the bottom up into its desired alphabetical position in the list. 

Could you please provide a step (e.g. add a group context menu entry?) that allows for the instant automatic sorting of these?

Thank you.

**Comment by touwys** [comment]
ABC sorting of Labels was added to Handy News Reader version 0.16.22. Thank you. Can you please do likewise by adding under Advanced Settings the ABC sorting of the Feeds within the Feed Groups?

Thank you

—

![Screenshot_20220327_050711](https://user-images.githubusercontent.com/65730626/160265259-6853fe44-018a-494e-806c-c996674b28e0.png)

**Comment by yanus171** [comment]
Do we need auto sorting of feeds within groups only or group auto sorting too?

**Comment by touwys** [comment]
Alexey

Both, please. Thank you!

If you can have a look at the HNR-backup that I emailed to you, you can see how many feeds are located under the ALTERNATIVE GROUP. Initially they were sorted manually, but later on I just gave up on it, because the feeds mix changes quite frequently.

Pierre





-----Original Message-----

**Comment by touwys** [comment]
A BIG thank you out to the author! Release v0.16.28_257 took care of this enhancement very suavely, and I am most happy to be able to close this thread.
