### ISSUE TITLE
Add option to remove duplicate articles(By Title)

### ISSUE THREAD

**Issue by nikhilCad** [yanus171/Handy-News-Reader#649]
**Is your feature request related to a problem? Please describe.**
I have subscribed to two news feeds by the same media house and some of their articles are duplicates, not all. I want to removerhose duplicates

**Describe the solution you'd like**
Check the Title of feeds to see whether they already exist before adding them, this should be available in settings

**Describe alternatives you've considered**
Original Flym app jas this option. You might want to check it out.

**Additional context**
-

**Comment by yanus171** [comment]
The same as #638
