### ISSUE TITLE
Separate unread section for each folder of feeds

### ISSUE THREAD

**Issue by nikhilCad** [yanus171/Handy-News-Reader#650]
**Is your feature request related to a problem? Please describe.**
My schedule : first news, then opinion pieces,  then a little stuff from reddit rss feeds

**Describe the solution you'd like**
I want separate unread tab for each folder

**Describe alternatives you've considered**
Couldn't. find alternative tbh

**Additional context**
None

**Comment by yanus171** [comment]
You can select a group of feeds and uncheck read filter checkbox
