### ISSUE TITLE
Starred Articles • Open Multiple Links Directly in Browser

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#651]
1. Daily, I accumulate several hundreds of classified Starred Articles for the sole purpose of research archiving, as well as news group distribution. Invariably, I end up using an internet browser during the process to open these batches of Starred Articles. To do this, I use an eloborate roundabout method to get **multiple starred articles** to open in a browser.

2. As a solution, please consider to include a Share-option that allows for multiple Starred Articles to be opened in a browser directly, instead of just one-by-one? "Multiple" in this instance meaning **all of, or any number of, user-selected** Starred Articles. Such a feature should also come in very "handy" when extended to any open articles list.

3. As a subset of options to (2) above, it may include user-entries such a time delay to be set, in seconds, between the opening the tabs of the selected Starred Articles in the browser, and to open the tabs in order of preference such as, for example, date, alphabetical or reverse order.

Thank you.

**Comment by yanus171** [comment]
What do you do in a browser with these articles?

**Comment by touwys** [comment]
Thank you for posing the question.

They are all opened in the local (android tablet) browser first, for further reading, classsification and for some preliminary distribution/sharing. Ultimately, a select number of them end up getting transferred to the PC browser directly, where the process of classifying them for distribution to news groups and other interested parties are completed. Once completed, they are archived into scrapbook-libraries on the PC, for later retrieval, and reference.
