### ISSUE TITLE
Mark All Unread

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#654]
Too often, I will hit the "Mark as read" button (or use the "Mark all as read" menu entry) by mistake. By the time I realize the mistake, the "Undo" option is no longer available. Although this does not pose that much of a problem when only a few articles are at stake, it means real trouble when thousands of them are. 

The way I view it, there are two ways to approach the solution:

1. A more immediate one could be to increase the "Undo" delay-time from the approximately two seconds it is now, to something more realistic — if only by a few seconds. By how much it should be increased, however, is the question, because of different user requirements. 

2. Provide a "Mark All Unread" option as a menu entry, as well as by extending the functionality of the "Mark all as read" button. The latter, for instance, could change its colour instance, to show the current status as read or unread.

Thank you.

**Comment by yanus171** [comment]
3. Hide Mark all as read button in app settings and use a menu item for 
that action

**Comment by touwys** [comment]
@yanus171 

```
3. Hide Mark all as read button in app settings and use a menu item for
that action
```

I may have expressed myself badly in the opening post: I did not mean that I _accidentally_ hit the Mark All button. What I meant was that I do use the button _deliberately_ to Mark All  read, and then I realize too late that I made a mistake by doing so. By then, the two-second undo-window is gone. Hence, it does not matter whether the Mark All button or the menu entry is used to execute mark all as read. The original post indicated that both methods are used interchangeably. 

If the two solutions that were offered here are not acceptable, please at least consider adding a double-confirmation dialogue for Mark All As Read, which is similar to the one currently in use for the Unstar Articles dialogue.

Thanks.
