### ISSUE TITLE
Add support for furigana

### ISSUE THREAD

**Issue by 21241** [yanus171/Handy-News-Reader#655]
Hi devs I really like this app thank you thank you I use it everyday :D
It would be even better if the app supports furigana (small Japanese letters on top of Chinese characters). They are now displayed as normal characters after the Chinese characters. Here is a correct example:
https://www3.nhk.or.jp/news/easy/k10012745171000/k10012745171000.html
They are called "ruby text" in Libreoffice, maybe that helps.
The issue is reproducible by reading any article from this RSS link:
https://rsshub.app/nhk/news_web_easy

**Comment by 21241** [comment]
Hi devs I really like this app thank you thank you I use it everyday :D
It would be even better if the app supports furigana (small Japanese letters on top of Chinese characters). They are new displayed as normal characters after the Chinese characters. Here is an example:
https://www3.nhk.or.jp/news/easy/k10012745171000/k10012745171000.html
They are called "ruby text" in Libreoffice, maybe that helps.
The issue is reproducible by reading any article from this RSS link:
https://rsshub.app/nhk/news_web_easy

**Comment by Ryuno-Ki** [comment]
Ah, finally it clicks, what is meant with https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby in HTML!

(Likely not applicable in the app, though, since Android is a different platform than the web)

**Comment by yanus171** [comment]
Try https://drive.google.com/file/d/1sx8gN_-DxXmHjrdcjQP0oGk59dDcHXO0/view?usp=sharing

**Comment by 21241** [comment]
Hi again thanks for the quick response! I downloaded the apk and it displays the furiganas correctly only when I click on "edit content".

**Comment by yanus171** [comment]
The correct text would be displayed only after reloading the article or for 
new loading ones. So press Reload Full text menu item

**Comment by 21241** [comment]
Wow it works now thank you so much! Is this feature going to be added to the f-droid version in the future?

**Comment by yanus171** [comment]
@Ryuno-Ki, thank you for explanation

**Comment by yanus171** [comment]
@21241, yes

**Comment by Ryuno-Ki** [comment]
@yanus171 A well, the other day I browsed all HTML elements (something screenreader-related research IIRC) and wondered, what `<ruby>` was about, since it didn't appeared in the little Japanese I learned. So thanks is to @21241 for bringing up an example :-)
