### ISSUE TITLE
Porting on Ubuntu touch

### ISSUE THREAD

**Issue by MoonDragon-MD** [yanus171/Handy-News-Reader#657]
Have you ever thought of making a porting for Ubuntu touch to put on open store? The current rss readers are not good, yours would be the best!!

**Comment by yanus171** [comment]
It would take to much work for me now

**Comment by MoonDragon-MD** [comment]
I understand it's hard enough just for android, I if I knew how to do it I would help you, I hope seeing this post someone will. I renew my compliments on your app thank you
