### ISSUE TITLE
Add Multiple Links to Read Later

### ISSUE THREAD

**Issue by Sarmadkh** [yanus171/Handy-News-Reader#662]
After Pocket and Instapaper app failed to fetch the full content of the articles on multiple sources, I have realized that Handy News Reader can also be used for this purpose. Currently I have to share links one by one with this app to save them for later. Is there a way to bulk add links to save for later? Unable to grasp the **_Web Page - Divide_** option.

**Comment by yanus171** [comment]
Web page divide extract several articles from one Web page (for example 
posts in a forum).
There is no currently an ability to share several articles. And I can't 
understand from what source are these article links.
And how do you fetch articles from different sources?


Sarmadkh <notifications@github.com> 16 февраля 2021 г. 18:41:51 написал:

**Comment by Sarmadkh** [comment]
By sources I mean to say different sites. Pocket app won't work on multiple sites I use and simply returns "there is no content here" What I am doing right now is creating a folder within Handy app and then adding links to read later. Please consider adding bulk link options, or a separate read later folder where links won't get deleted. Full text extraction works extremely well here

**Comment by yanus171** [comment]
Explain it more concrete please

**Comment by Sarmadkh** [comment]
You know how Pocket and Instapaper works, we add links there to read full text later and its works offline. Similar thing is possible with Handy app by sharing links with it and then selecting **Read Later** option. What I am suggesting is to consider having an option where can add/paste multiple links (or even single link for that matter) and every item in there will be saved in a separate read later folder. Currently items are added in a **Without a Feed** tab. I was suggesting it because your full text extraction rules are so efficient that even Pocket fails to fetch the full content on multiple sites. Please consider or guide

**Comment by yanus171** [comment]
How can you add/paste multiple links?

**Comment by Sarmadkh** [comment]
If you are asking from a developer point of view, I am sorry i wont be of much help. There is a [chrome extension](https://chrome.google.com/webstore/detail/batch-save-pocket/ihhiomekhplpdojbcaniaglcfopckaef) that lets you add multiple links to pocket at once. Again I am suggesting this because of the excellent text extraction feature of Handy app.

![unnamed](https://user-images.githubusercontent.com/29545475/108588860-3b6c6d80-737d-11eb-8f41-4a1e54bddcdc.jpg)

**Comment by yanus171** [comment]
It would be simpler instead of pre collecting the links just share each of 
them and select Read later
