### ISSUE TITLE
Text surrounded by double < hidden

### ISSUE THREAD

**Issue by mcholiday** [yanus171/Handy-News-Reader#666]
If there is a text in the article like this:

```
<<Some text surrounded by those html brackets.>>
```

It will be hidden in the Handy News Reader, but it is visible in my browser. 
I can see it if I select view html. Example:

```
<p>
<b>
<
<Some Text.>>
</b>
</p> 
```
The News Reader will display
<>
Then I have to check it in my browser to see what it says.

**Comment by yanus171** [comment]
Try to check unchecke settings, additional, convert XML symbols before parsing
