### ISSUE TITLE
Button to go directly to top of feed, Setting to always open to top of feed

### ISSUE THREAD

**Issue by kisccz** [yanus171/Handy-News-Reader#667]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open a feed and it takes me to the very end of the feed. I have to scroll so much to reach the top. 

**Describe the solution you'd like**
option to always to be taken directly to the top at all times or/and a button to scroll to the top like the one that already exists for articles.

oh I saw you already talked about this before, how can I scroll to the top? Was it changed?

**Comment by kisccz** [comment]
oh I saw you already talked about this before,  how can I scroll to the top? Was it changed?

**Comment by yanus171** [comment]
In what issue?

**Comment by kisccz** [comment]
https://github.com/yanus171/Handy-News-Reader/issues/636

Issue 636

**Comment by yanus171** [comment]
Use that issue please
