### ISSUE TITLE
After loading some articles, article goes to bottom of feed

### ISSUE THREAD

**Issue by kisccz** [yanus171/Handy-News-Reader#668]
**Describe the bug**
After opening some articles, not all, and pressing "load full article" the date and time of the article is changed and the article is sent to the end of the feed because it becomes the oldest one. 
**To Reproduce**
1. Go to article
2. Click on 'load full article'
3. go back to feed
4. article is at the end of the feed with changed date and time (oldest article)

**Expected behavior**
to remain in the same place in the feed after loading the article
**Screenshots**
how can I attach a screenshot? 

**Smartphone (please complete the following information):**
 - Device: moto g7 power 
 - OS: Android 10
 - Version Handy News Reader 0.15.15

**Additional context**
This happens for some articles not all. But it happens nearly every time I use the app for some articles

**Comment by yanus171** [comment]
Can't reproduce it. Try to find exact conditions when this occurs

**Comment by kisccz** [comment]
https://www.economist.com/international/rss.xml

Use this feed and load an article. For me it always goes to the bottom
