### ISSUE TITLE
Help with regex...

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#670]
Maybe it could be a good idea to gather all regex-related help requests in this thread.

My current issue is that I’d like to accept only posts starting with “Edition 5xx” (I mean any three-digit number beginning with “5”). I tried the following regexes (ACCEPT filter, regex checkbox checked):

	^Episode 5[0-9]+[0-9]+$

and this one:

	^Episode 5[0-9]+[0-9]+[a-zA-Z]+$
	
Nothing seems to work, but I’m not sure what is the source of the problem. The RSS is here: http://legacy.theunexplained.tv/feed.xml .

Could someone help with that?

**Comment by ThomasLeigh** [comment]
Each time I reset the feed, btw, and refresh.

**Comment by yanus171** [comment]
Edition or Episode?
Try Edition\s5\d\d

**Comment by ThomasLeigh** [comment]
Thank You for correcting me.

I tried

`Edition\s5\d\d`

and

`^Edition\s5\d\d$`

Doesn’t work.

**Comment by yanus171** [comment]
Edition\s5\d\d works for me. Did you request the feed and refresh after further edit?

**Comment by ThomasLeigh** [comment]
Oh, I see. When I unchecked "Load full articles" it works. Could it be done to work also when "Load full articles" is checked?

**Comment by yanus171** [comment]
It works fine on my phone which Load full articles checked. Again did you 
forget to reset the feed?

**Comment by ThomasLeigh** [comment]
[See for Yourself](https://cloud.trailofthelight.xyz/wl/?id=vvPjHfSf2ARgw9SBfPqUwW4BbhcUcKJu), now it doesn’t work at all:

**Comment by ThomasLeigh** [comment]
I’ve done the feed reset each and every time.

**Comment by ThomasLeigh** [comment]
I removed the filter and it still didn’t work. I’ve double-checked the RSS address and found that there is a new one, so I’ve replaced

`http://legacy.theunexplained.tv/feed.xml` with `http://theunexplained.tv/feed.xml`  - it still didn’t help.

Each and every time I reset the feed. But it works again after x-nth attempt to change anything, delete the filter, add a filter, load full articles checked or unchecked, and so on. No clear indication that anything of those solves the issue. It looks like it may be an issue related to the feed itself, not the Handy News Reader. But it’s beyond the scope of my knowledge. I only can tell that this particular feed behaves strangely, providing seemingly random **old** articles every now and then (we’ve discussed this matter some time ago on this forum - it is related to several feeds, including YouTube channels).

**Comment by ThomasLeigh** [comment]
Maybe a log of everything what HNR is doing would be helpful but  we have not such a feature yet.

**Comment by yanus171** [comment]
Did you try to delete the feed and add it again?

**Comment by raniesantos** [comment]
Have you figured out how to make regex filters work?
