### ISSUE TITLE
Scroll to top jumping.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#672]
1. On an article list hold on top to initiate “scroll to top” (first time on the list).
2. Once it is scrolled to the top it unwillingly reverts to other position.
3. Repeat the first step and this time everything works fine.

It looks [like this »](https://cloud.trailofthelight.xyz/wl/?id=tu9sUIVUPi7gBbhRUQzWqptpspfJtoEl)

**Comment by touwys** [comment]
Same experience here. Reported by email direct to developer.
