### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by yant0** [yanus171/Handy-News-Reader#676]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would like a widget redirects to webview or browser

**Describe alternatives you've considered**
Notification feed

**Comment by moshpirit** [comment]
Yes, please

**Comment by yanus171** [comment]
The app already has home screen shortcuts which can be added to any feed, feed group or article.

**Comment by moshpirit** [comment]
Yes but screen shortcuts are not the same, a widget shows the actual news and can be used as a foot in the door to make us read the whole thing and use the app

**Comment by ArtexJay** [comment]
would be useful, can also sync the articles without needing to fully open the app and can be done in the background.

**Comment by yanus171** [comment]
It's already implemented via feeds auto refresh
