### ISSUE TITLE
A trigger to show only short/medium/in-depth articles.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#677]
I am nicely surprised by the idea of text size indicator You’ve recently introduced. It reminds of a very useful feature, i.e., **filtering articles by their length**. It would be great to be able to make any displayed article list to **show only items of particular length** (I would propose “short”, “medium” and “in-depth”). Such a trigger would be placed on top on the sidebar (below buttons, above the “Unread” group) and **allow to switch any currently displayed list to display only articles of chosen length** (one of three modes mentioned above).

What do You think?

**Comment by ItsIgnacioPortal** [comment]
I was thinking more along the lines of adding _length_ as a **filter** option. I think it should allow filtering with a specific number of characters, instead of "short", "medium", etc, because those are subjective.

**Comment by yanus171** [comment]
Describe a use case of such a feature please

**Comment by ItsIgnacioPortal** [comment]
@yanus171 This infosec writeups RSS feed: https://infosecwriteups.com/feed

Lots of newbies post very short writeups that simply aren't worth reading (about 30% of them). being able to filter them out from the get go would save me quite some time

**Comment by yanus171** [comment]
So  in this case we don't need a trigger but a new feed filter type: by size

**Comment by ThomasLeigh** [comment]
It would be great to have the feature I’ve described in the first post - it would be set up within the app’s settings to adjust boundaries for each level of article length. **This would be much more available and friendly for an average user to benefit.** And in the same time it allows to set up Your Own prefferred limits.

**Comment by yanus171** [comment]
Why is the new type of filter not suitable?

**Comment by ThomasLeigh** [comment]
The feature I’ve described would be **easily available at hand** on the sidebar, therefore it would receive many average users’ attention and be widely appreciated.

Another filter is ok for more advanced users who are accustomed to dive into the app’s settings and experiment.

**Comment by ItsIgnacioPortal** [comment]
I mean, we could implement both features. But I'm pretty sure that my proposal is easier to code.

**Comment by yanus171** [comment]
@ThomasLeigh please describe the use case of this feature which couldn't be resolved by feed filter by text size
