### ISSUE TITLE
app crashs reopens and brings up sharing tray ramdomly

### ISSUE THREAD

**Issue by E1K4M41** [yanus171/Handy-News-Reader#698]
**Describe the bug**
App crashes and the sharing apps tray is opened

**To Reproduce**
1. Go to ' the app'
2. Click on 'click on any article, and start reading normally'
3. After few minutes the app will crash and  the tray for sharing to other people opens'

**Expected behavior**
The app not crashing

**Screenshots**
![Screenshot_20210809-171439_1](https://user-images.githubusercontent.com/61159258/128739672-2f51e40e-ad5a-4392-afdb-6b152c59f8fc.png)

**Smartphone**
 - Device: Nokia 7 Plus
 - OS: android 10
 - Browser: firefox
 - Version 0.16.3

**Comment by yanus171** [comment]
Try this https://drive.google.com/file/d/1h7kA2AkpFi_XnxxqdEY-R--SxNkCeqHM/view?usp=sharing

**Comment by Animyos** [comment]
> Try this https://drive.google.com/file/d/1h7kA2AkpFi_XnxxqdEY-R--SxNkCeqHM/view?usp=sharing

Hey there,
I have the same issue when I try to open the app. When I try to download the apk by @yanus171, it says Application not downloaded, after I said yes to install an update for Android News Reader

Device: Nokia 3.4
Android version: 10
App version: 0.16.1

**Comment by Mrnofish** [comment]
Experiencing the exact same issue under LineageOS 18.1 (Android 11). I haven't tried the APK, but I hope a fix can be found and dispersed quickly, Reader is almost unusable right now.

**Comment by yanus171** [comment]
The app version 0.16.4 should work

**Comment by Ryuno-Ki** [comment]
I can confirm that the last version fixes the crashes.
