### ISSUE TITLE
Disable fetching rss when sync is disabled

### ISSUE THREAD

**Issue by ReleaseStandard** [yanus171/Handy-News-Reader#699]
Handy News Reader fit perfectly my needs thank you so much !
<br />
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I disable sync (from the tile) and see that handy news reader continue fetching rss feed.
<br />
**Describe the solution you'd like**
It would be great that handy news ready follow user preference isSyncActive ex:
https://stackoverflow.com/questions/11252876/check-if-sync-is-enabled-within-android-app/20098676
<br />
**Additional context**
AccountManager compat API 5
AccountManager.get compat API 5
AccountManager.getAccountsByType API 5
ContentResolver.isSyncActive API 5
Const.ACCOUNT_TYPE API 5
Account API 5
ContentResolver API 1
Need peemissions:
Manifest.permission.GET_ACCOUNTS
Manifest.permission.READ_SYNC_STATS

**Comment by yanus171** [comment]
Only rss fetching should be disabled when sync is off? What about Autobackup and Old articles deletion processes?

**Comment by yanus171** [comment]
Test it https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-901340678

**Comment by ReleaseStandard** [comment]
- There is a master auto sync setting that applies to all accounts/provider (the one that you can toggle from a tile)
 - auto sync setting used in the framework [AbstractThreadedSyncAdapter](https://developer.android.com/reference/android/content/AbstractThreadedSyncAdapter)
 - From [this](https://developer.android.com/training/sync-adapters/creating-sync-adapter) a sync adaptater is used when there is a data exchange between client and server, eg: fetching rss over network, backup applications with on google
 - From [this](https://ostoday.org/android/frequent-question-what-is-auto-sync-on-an-android-phone.html) it seem that backup from phone to computer could considered also as a form of sync that is regulated by the master setting
 - So a local backup on phone should not take care of master auto sync setting
 - Old articles is also a local process so it does not follow master auto sync setting
 
I've tested 059ace608a46e68a50d9baf5c35dc4228bde73a7 it solve effectively the initial issue.
You'r pro sir
