### ISSUE TITLE
HNR v0.16.7 Add Menu Entry "Labels" to Live Article Links

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#701]
Live links are commonly displayed in the content while resding an article. Clicking on any live link, presents a menu such as the one shown below. Absent in the menu, is a direct link to the "Labels" feature, which necessitates several more steps before the particular article can be put to "Labels"

Please, provide a menu entry in the article live link menu, which entry will provide direct access to "Labels".

Thank you for your consideration.

**Additional context**
![Screenshot_20210831_155233](https://user-images.githubusercontent.com/65730626/131518177-a3014b15-c938-4744-a72a-3ff885ec2013.png)

**Comment by yanus171** [comment]
For what article? Viewed or linked?

**Comment by touwys** [comment]
The subject refers to live article links in an article being **Viewed**.

**Comment by yanus171** [comment]
An article Label setup is accessible from the article menu (by tap on article text) without need for link menu

**Comment by yanus171** [comment]
I don't understand how articles labels concerned with links to OTHER articles.

**Comment by touwys** [comment]
One should be able to attach a Label to another article i.e. one that is linked from within the text of the article currently being read — without having to open the linked article first. At the moment, the user has to open an article linked from within the one being read to open it for reading, and then only can he set the Label for it

**Comment by touwys** [comment]
`But this action should only be activated with Read later in favourites item.`

Looking at the screenshot of the link menu in the original post (OP), do you mean that the Label setup window gets activated when the user clicks on the "Read later" menu entry? I presume that it is impossible to gain direct access to Labels from the menu shown in the OP due to app coding constraints? If direct access is not available, activating Labels via another menu entry is still very good. Thanks!

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-919212176
