### ISSUE TITLE
Text to speech

### ISSUE THREAD

**Issue by RAMAR-RAR** [yanus171/Handy-News-Reader#704]
I would like a text to speech button where you can select a piece of text or all text, so I could listen the news in background(with a play, pause and stop button).

**Comment by nikhilCad** [comment]
You can use Evie TTS engine. Click share and then select Evie app.

**Comment by moshpirit** [comment]
Evie is not available on F-droid and it would be nice to have a native integration, especially now that [SherpaTTS](https://github.com/woheller69/ttsEngine) exists.
