### ISSUE TITLE
Data Access problems

### ISSUE THREAD

**Issue by Andreas-ddl** [yanus171/Handy-News-Reader#706]
V. 0.16.7
For me it seems to be a general bug of data access:
Android 10 AOSP: no feedex folder created (first installation)
Android 11 (Samsung, Xiaomi, AOSP): export of opml fails due to data access failure (Android 9 - HTC - works seems not to be linked to data to be saved)

**Comment by yanus171** [comment]
Setup storage location in additional settings

**Comment by Andreas-ddl** [comment]
Reported senseful setting actually not active,
possible selection not senseful and when selected under "/config..."
![Screenshot_2021-09-06-10-53-47-712_ru yanus171 feedexfork](https://user-images.githubusercontent.com/53121472/132189721-ad88a181-a8c5-4152-a842-5bd23f595dc2.jpg)

**Comment by yanus171** [comment]
Is the price for the Google play update. The app should only had access to accepted storage. But why it's not sencefull?

**Comment by yanus171** [comment]
You can you this directory for data storage

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-919212176
