### ISSUE TITLE
where do I put my custom font

### ISSUE THREAD

**Issue by Rially** [yanus171/Handy-News-Reader#707]
I tried this https://github.com/yanus171/Handy-News-Reader/issues/572
but did not work either.
What directory do I have to put my ttf file in?

**Comment by yanus171** [comment]
See storage settings in advanced section + fonts subdir

**Comment by yanus171** [comment]
Or wait for the new beta where I will make a button Add custom font

**Comment by Rially** [comment]
Thank you! That worked.
Can you give me an example for adding custom font per url?  I tried this:
mysite.org:entry-header=CustomFont-Name.ttf
And then I reloaded an article from mysite.org, but it did not change the font.

**Comment by yanus171** [comment]
site.ru:header=a_RussDecor.ttf=font-weight: 400; font-size:18; 
letter-spacing: 0.01em

**Comment by yanus171** [comment]
Give me the real suite URL and required class name to apply font and I send 
you corresponding string

**Comment by Rially** [comment]
I tried creating a string like this and it did change font weight and size, but the font did not change.
site:
dj.sina.com.cn
class:
artibody

**Comment by yanus171** [comment]
May be your font doesn't support your language?
