### ISSUE TITLE
Jerky scrolling article list

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#708]
**Describe the bug**
Sometimes scrolling upwards in the article list is jerky.

**To Reproduce**
1. Unsure if relevant, but I have Articles order set to Display old articles first
2. Open an article list that contains many articles
3. Scroll upwards (i.e. swipe downwards on the screen)
4. Notice that scrolling is sometimes jerky

**Expected behavior**
Smooth scrolling!

**Screenshots**
![MP4_20210911_155713_2](https://user-images.githubusercontent.com/2512915/132953335-37d36b22-afe6-459f-b155-9e1ac033520b.gif)

I'm scrolling slowly here to emphasise the problem, but it happens with fast scrolling too. Notice that the scrolling seems to sometimes jump and overtake where my finger is touching the screen.

Version 0.16.7

**Comment by yanus171** [comment]
Does it occurs in every feed? May be article icons have huge size?

**Comment by JohnVeness** [comment]
It does it on every feed. If I scroll very slowly, it seems the sudden jump occurs just when the bar that shows the length of the article comes into view. Indeed, as far as I remember, this jerkiness has only started recently, possibly at the same time as that bar was introduced.

**Comment by yanus171** [comment]
So try to turn the bar off, by set max text size to 0

**Comment by JohnVeness** [comment]
I have just tried that, but scrolling still has the periodic sudden jerk/jump unfortunately.

**Comment by yanus171** [comment]
Try to change list view scrolling cache setting in system developers options

**Comment by JohnVeness** [comment]
I don't seem to have such a setting (and yes, I have tapped the Android build number sufficient times to enable the "Developer options").

**Comment by yanus171** [comment]
Sorry, I have mistaken it with my custom ROM setting
