### ISSUE TITLE
Increasing padding with font size in article list

### ISSUE THREAD

**Issue by tasmo** [yanus171/Handy-News-Reader#709]
When increasing the text size for the article list, the font becomes bigger but the heading area remains in its size.

That causes that the headings are very close to the separator line on top and the description text at bottom.

**Expected behavior**
The padding should be increased with the custom article text size.

**Screenshots**
With text size +3:
![Screenshot_20210911-213240_Handy_News_Reader_1](https://user-images.githubusercontent.com/102685/132961558-2e0d2f30-1bd4-462e-be99-5b4c3740ee8a.png)

**Smartphone (please complete the following information):**
 - Device: Oneplus3t
 - OS: LineageOS 18.1
 - Handy News Reader version: 0.16.7

**Comment by yanus171** [comment]
Can't reproduce it
