### ISSUE TITLE
Action tap button still present when the option to hide them is active..

### ISSUE THREAD

**Issue by moshpirit** [yanus171/Handy-News-Reader#711]
I like clear screens: less buttons and bar visible as possible. Having 4 floating buttons stress me and this is why I disable the buttons, but one still persist: one that enables them. There is already an option in the menu to activate/deactivate them already so: shouldn't it be hidden too?

**Comment by afmbsr** [comment]
I'm using the latest beta version, and I don't have the problem you mentioned

https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-922365500

**Comment by moshpirit** [comment]
I'm using 0.16.7 (F-droid) ([screenshot here](https://i.imgur.com/Yukzdz3.jpg))

**Comment by yanus171** [comment]
See https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.16.15
