### ISSUE TITLE
Option to automatically hide the top bar when reading an article when scrolling down.

### ISSUE THREAD

**Issue by moshpirit** [yanus171/Handy-News-Reader#712]
This allow us to enjoy of a clear experience with the option to use the bar (and its menu) by just scrolling up.

The less objects in the screen, the better IMO.

**Comment by yanus171** [comment]
I tried, but it was too hard due to complicated layout (WebView inside Pager) :(

**Comment by yanus171** [comment]
The problem is that webview is inside the pager (horizontal list) that 
provides the article left right swipe. And the action bar is over the pager...
