### ISSUE TITLE
F-Droid build failed: GMS

### ISSUE THREAD

**Issue by linsui** [yanus171/Handy-News-Reader#713]
https://github.com/yanus171/Handy-News-Reader/commit/d92ea9115fd5bbdea2b45cd0b53602c27cbd4dd1 added gms which is not FOSS. Could you provide a flavor without it or remove it? Thanks!

**Comment by Jaloou** [comment]
> [d92ea91] added gms which is not FOSS.

It is not a purpose of Handy News Reader app to be complaint with the FOSS, mentioned by you.


> [d92ea91] Could you provide a flavor without it or remove it?

For what? For Handy News Reader app becomes worser: without a support of many modern https connections and vulnerable to security treats?
Please, explain for what you want it. Factually, are you suggesting to get the app worser only for a specific possibility to obtain the app builds via F-Droid web-site? The main purpose of Handy News Reader app is in providing RSS feeds to people and the app is doing it better now. But the purpose is not a complaince with the specific build requirements of side web-site like F-Droid.
There are many ways to get builds without F-Droid web-site and yet download ready Handy News Reader apk file from many other web-sites like ApkPure, ApkMirror and etc, etc.

**Comment by linsui** [comment]
Neither you nor ma are the developer of Handy News Reader so I won't discuss the purpose of it. But if you didn't notice that please allow me quote the readme:

> no ads/free software under GNU GPL license

> Users of Handy News Reader have NOT to have a Google account even. They just need only to upgrade Google Play Services app and nothing more.

It's not that easy. There are many users doesn't use Google Play Services for many reasons. Now Handy News Reader is not available to them any more. If you want security, why do you still use the old Android 4.4 which is vulnerable to security treats?

**Comment by yanus171** [comment]
Why HNR became unavailable for users without Google play installed? I can't tests it without Google play, but I tried to make it run in that case.

I think I can make a special flavour but that would make harder a release production.

**Comment by linsui** [comment]
There is no apk in the github release so I didn't test. Looks like it's pretty easy to remove GMS. I can apply a patch on our side.

**Comment by yanus171** [comment]
@linsui, I have commited fdroid flavor without gms. Is it enough?

**Comment by linsui** [comment]
That's great! Thanks!

**Comment by Jaloou** [comment]
> [d92ea91](https://github.com/yanus171/Handy-News-Reader/commit/d92ea9115fd5bbdea2b45cd0b53602c27cbd4dd1) added gms which is not FOSS. Could you provide a flavor without it or remove it?

> [d92ea91](https://github.com/yanus171/Handy-News-Reader/commit/d92ea9115fd5bbdea2b45cd0b53602c27cbd4dd1) added gms which is not FOSS. Could you provide a flavor without it or remove it?

Many various apps (include and RSS readers) with demanding Google Play services are available today for download from F-Droid.
For instance, the modern TTRSS-Reader app is hosted on F-Droid having an option enabled as default for using Google Play services.
I had attached the screenshots for proofing it.
![Screenshot_2021-09-25-22-04-21](https://user-images.githubusercontent.com/87898844/134783679-e54d566e-ca24-4177-bc51-228472b6ed61.png)
![Screenshot_2021-09-25-06-50-59](https://user-images.githubusercontent.com/87898844/134783696-3b00e343-a39d-499a-b48c-5307ce51f6e7.png)

So, other app developers do not have the problem described by you here in this topic at its beginning. The reason in your initial post here is fully wrong and misleading people only.

May you need ask support at F-Droid with your problem but not here at GitHub. Your issue here is offtopic.

**Comment by Jaloou** [comment]
> It's not that easy.
Why? You did not explained the reason.
Probably you are wrong again because it is very easy for Android users and almost all Android users around the World are using Google Play services being happy with it.

> There are many users doesn't use Google Play Services for many reasons.
For what reasons? You did not explained it again.
Reasons can be wrong. And I was already proofing 2 times here in this topic your arguments for the reasons was wrong.
> Now Handy News Reader is not available to them any more.
Available. Just forget wrong reasons, install Google Play services and be happy with it.

> If you want security, why do you still use old Android 4.4 which is vulnerable to security treats?

Because my very old device is still reliable and safe with the uptodate version of Google Play services! ;-)

**Comment by linsui** [comment]
China users can't use google at all. And it's non free. Some users does not want to install it on there phone. By the way, you can install Android 11 on your old Samsung Galaxy S2.

TTRSS-reader also provides a fdroid flavor. The SSL setting is just a dummy UI in fdroid flavor. See https://github.com/nilsbraden/ttrss-reader-fork/blob/master/ttrssreader/src/fdroid/java/org/ttrssreader/gui/MenuFlavorActivity.java.

**Comment by Jaloou** [comment]
> China users can't use google at all.
They denied to use Google Play Store app.
But they allowed to use Google Play Services app. It is 2 different apps.
So, you are wrong again.

> And it's non free.
Google Play Services app is free.
Thus, you are wrong yet more.

> Some users does not want to install it on there phone.
Usually, Google Play Services app is going preinstalled with Android. If not (rare cases) then it is easy to download and install or update for free.
Please, stop to decide instead another users. You do not have such rights. People are able to make their own choice by their self.
You was never answered to my question why you are propagating (even effortly) to do not use Google Play Services app?
You want devices be vulnerable to hacker attacks? You are propagating in favour of criminals?
You want millions of people with some devices was unable to use Handy News Reader with many web-sites?

> By the way, you can install Android 11 on your old Samsung Galaxy S2.
It is not a firmware from Samsung but from another developers and their firmware is full of issues.

> TTRSS-reader also provides a fdroid flavor. The SSL setting is just a dummy UI in fdroid flavor.

But TTRSS-Reader is available on F-Droid already with the enabled option to use Google Play Services app! Exactly.
The developer of Handy News Reader app can do it similar.

**Comment by linsui** [comment]
> They denied to use Google Play Store app.
> But they allowed to use Google Play Services app. It is 2 different apps.
> So, you are wrong again.

They can't. Many roms in China can't install GMS. And Google is blocked in China.

> Google Play Services app is free.
> Thus, you are wrong yet more.

No, it's not free as in freedom.

> Usually, Google Play Services app is going preinstalled with Android. Users should not to do at all. If Google Play Services app is not preinstalled (rare cases) then it is easy to download and install or update for free.
Please, stop to decide instead another users what they allegedly want what they allegedly do not want. You do not have such rights. People are able to make their own choice by their self.
Most Android users around the World use Google Play Services app.

As I said, many users do not want to install GMS. They don't want to use non free software. They decide that themselves. Why fid you say I decide it for them? How can I??? There are many custom roms and they can be installed without GMS.

> But TTRSS-Reader is available on F-Droid already with the enabled option to use Google Play Services app! Exactly.

Please stop if you can't understand English and code. As I said, it's a dummy UI and does nothing. Switch the button won't use GMS.

> You was never answered to my question why you are propagating (even effortly) to do not use Google Play Services app?
> You want devices be vulnerable to hacker attacks? You are propagating in favour of criminals?

Why are you propagating Google service? Are you recieving money from Google? Some users don't want to use software that they can't read the code and check what they do under the hood. Why must they use GMS?

> It is not a firmware from Samsung but from another developers and their firmware is full of issues.

Sansung only support their device for 3 years while you phone is published 10 years ago. How can it be safe? Even Doogle will stop supporting 4.1. https://olhardigital.com.br/en/2021/07/09/reviews/google-vai-encerrar-suporte-ao-play-services-android-4-1-e-4-3/

**Comment by yanus171** [comment]
@Jaloou, what the problem? I can still release at GitHub and Google play gms apk, but froid will build the FOSS version.

**Comment by yanus171** [comment]
What should I do more to close the issue?

**Comment by linsui** [comment]
I'm just waiting for a new tag. This issue can be closed. Thanks!
