### ISSUE TITLE
Starred entries not visible.

### ISSUE THREAD

**Issue by wombatch** [yanus171/Handy-News-Reader#715]
For a week (maybe a bit longer) the "starred" entries have disappeared from my view.
In the main panel there is still an entry "Starred" with a count of 43 but if I select it nothing is visible. 
I can add an entry to the "Starred" entries and the count on the panel is incremented but still nothing is visible. This seems to be some change in the way favourites are managed? If i add an "unread" entry to "Starred" then it is visible but anything read, disappears. 
Has there been a recent change in operation, is there some configuration option I am missing, will I ever be able to see these "starred" entries again?
Sorry for reporting this as a bug (maybe it is, maybe not) but I really can't find an answer to the question anywhere. 

**Smartphone (please complete the following information):**
 - Device: [Sony E5823]
 - OS: [Lineage 14.1 (Android 7.1,2)]
 - Browser [Firefox, Brave, Lightning, default]
 - Version [0.16.7]

**Comment by yanus171** [comment]
As a temporary solution you can select in menu Visible articles Filter by labels and set All

**Comment by yanus171** [comment]
And I cant reproduce it afetr that action

**Comment by wombatch** [comment]
Thank you for the suggestion, sadly the options to change the visibility is not displayed on my phone (not sure if it ever was, perhaps not).
Here an example
![photo_2021-10-07_11-40-112](https://user-images.githubusercontent.com/10166804/136360855-d6738eda-1679-4349-bb11-bb128c51d7ac.jpg)

Clearly at this point the best action would be to uninstall and re-install but I don't want to lose the data. Are the some folders/files I can copy to keep the data while i reinstall the app?

**Comment by wombatch** [comment]
Assuming I am following this correctly and I think I am because I installed the APP on a tablet to check operation, then I have NO menu options shown on my Article list.

**Comment by wombatch** [comment]
Well I have a screen copy from before and after i changed the preferences.xml I have a backup of the old preferences file so can put it back and see what happens. I think in the old prefences i had the app set to "Auto-backup" i seem to have not got that working this time.
![photo_2021-10-11_11-21-09](https://user-images.githubusercontent.com/10166804/136766523-a8886f99-7e47-4f0f-862d-aff59fba389f.jpg)
![photo_2021-10-11_11-20-30](https://user-images.githubusercontent.com/10166804/136766518-f2e3d817-6924-421a-aa5c-e65f70f2ba2f.jpg)
