### ISSUE TITLE
Option to put Next and Previous article buttons at bottom

### ISSUE THREAD

**Issue by nikhilCad** [yanus171/Handy-News-Reader#716]
**Is your feature request related to a problem? Please describe.**
My phone is long and reaching on top for Next Article button is little uncomfortable

**Describe the solution you'd like**
Add option in Settings> Operations which will bring both Next/Prev Article buttons at top/buttom of article view

**Describe alternatives you've considered**
It's just a minor inconvenience

**Additional context**
None

**Comment by yanus171** [comment]
See https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.16.15
