### ISSUE TITLE
Custom Refresh interval setting per feed

### ISSUE THREAD

**Issue by moshpirit** [yanus171/Handy-News-Reader#717]
I'd like to be able to read the articles from websites like [The Economist](https://www.economist.com/espresso) or [Democracy Now (Spanish)](https://www.democracynow.org/es/categories/el_resumen_semanal) that change their content every day within HNR, but I'm not sure of how to configure the feeds, so I can get it. I'm not even sure if this is possible, but if not, it would be a great feature (an option to set a source as a periodic source of information to be updated every X hours/days).

**Comment by yanus171** [comment]
What about setting the refresh internal in settings?

**Comment by moshpirit** [comment]
I don't know what do you mean by that, sorry

**Comment by yanus171** [comment]
That should be a separate issue
