### ISSUE TITLE
Find In Article Content

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#720]
**AIM**
Find the desired word(s) in the content of an article which is currently open for reading in HNR Reader.

**REASON**
The need to quickly search for something instead of having to read through the complete article to try and find it. 

**EXECUTION**
Add a menu-entry for "Find" to the appropriate HNR menu — or any other method required to call the Find-action. If possible, the new "Find" should have similar features to the "Find" action found in external internet browsers: These are, for example:

1. Highlight found words
2. Move up and down the article content to view found words. 

Thank you.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1484184430
