### ISSUE TITLE
Access External Browser Direct from Article Subject in Article List

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#721]
**AIM**
To open an article, straight from an article-headline in the feed list to the default external browser. 

**REASON**
To access the extra utilities/operations that are often offered by the external browser. Also, very useful for multitasking.

**EXECUTION**
Long-press on the article-headline in the feed list to call up the current context-menu, to which the menu-entry "Open in External Browser" is added. Click on it to open the article in the external browser. 

Thank you,

**Comment by touwys** [comment]
Please consider expanding this enhancement by making it possible to select not only one, but **multiple** articles in the articles list, whic are to be opened in the default external browser.

**Comment by yanus171** [comment]
I dont think it is possible in Chrome

**Comment by yanus171** [comment]
I suppose it's impossible by external browser
