### ISSUE TITLE
Improved Mark item as read

### ISSUE THREAD

**Issue by JStyle21** [yanus171/Handy-News-Reader#726]
**Is your feature request related to a problem? Please describe.**
Currently the only way i found to mark an single item as read without reading it is to manually swipe right, that works but it's a bit annoying since it requires an exact movement to the right and when going over several items pretty fast it doesn't connect most of the the time and even if it does it requires the full movement which is a bit tedious over hundred of items to repeat.

**Describe the solution you'd like**
Either another option to manually mark an item as read such as tap or a more snappy swipe so it will work easier and require less accuracy to hit exactly right

**Describe alternatives you've considered**
I didn't find any

**Additional context**
I don't think it's needed but can provide otherwise

**Comment by yanus171** [comment]
What is your proposal?

**Comment by JStyle21** [comment]
I think maybe, having a separate mode one can enter and in that mode you could swipe right or left on an item or maybe tap and that would mark them as read.

OR

Making the current swipe right easier and more responsive, i've used [feeder](https://f-droid.org/en/packages/com.nononsenseapps.feeder/) before HNR and it was snappy and fast when you did that, not sure what's causing the delay here

Alternatively another option i could use right now is to mark the interesting ones as fav's and then mark everything as read and go through the fav's but honestly i find it satisfying remove items one by one, it's like crossing items of a list.

**Comment by JStyle21** [comment]
I just discovered tap actions and it allows me to quickly browse and mark items so i guess that solves this problem but i really wanted something that fast for the article list, swiping isn't working fast and requires exact swipe direction and angle...

@yanus171 
Should i close the issue like this or do you wish to attempt another solution?

**Comment by yanus171** [comment]
May you post a video where you fail to swipe articles in list?

**Comment by JStyle21** [comment]
Sure, here you go:
https://easyupload.io/lg3n8r

I've had touch points and data enable so you could see that too
