### ISSUE TITLE
Allow an OPML export option in internal storage.

### ISSUE THREAD

**Issue by kentiongson** [yanus171/Handy-News-Reader#731]
I cannot export an opml file as a backup in any folder of my choosing inside my internal storage. How come that this option (exporting an opml file) only available if there is an extarnal storage (sd card) present?

I can't even access the autobackup file from the default location because I'm not using a rooted phone. That's why exporting an opml file in the internal storage is my only option of having a backup for my rss feeds since I don't have an external storage as well.

**Comment by yanus171** [comment]
The recent app version should place auto backup file in the Downloads folder

**Comment by davidbishop** [comment]
It still doesn't.

After 4 fresh setups, left for Feedly again.

Shame, otherwise good.

**Comment by yanus171** [comment]
The app can't overwrite the auto backup file in Downloads folder after reinstall. So you should delete it manually

**Comment by davidbishop** [comment]
Sorry, can't say.

Moved to Feeder because of the issue.


31 Mar 2022 20:40:09 Damien Cassou ***@***.***>:
