### ISSUE TITLE
Bring back/improve side tap zones for page up/down

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#732]
**Is your feature request related to a problem? Please describe.**
Personally, I am not liking the recent change where we can no longer tap on the right edge of the screen to page down. I have tried to give it a few days to avoid a knee-jerk reaction, but I still find it was better/easier to tap on the right edge with my thumb (when holding my phone in my right hand) than at the bottom. Tapping at the bottom I find my thumb gets in the way of the text I'm reading (with tapping on the side I could more easily "hover" my thumb out of the way), and it's also a bit too easy to accidentally tap in the corners, or on the Android navigation buttons.

**Describe the solution you'd like**
I realise it's hard to keep everyone happy, and I know that too many options can be overwhelming, but (as someone who never changes the brightness or who uses any of the corner tap zones), personally I'd love to have four tap zones:

- Top half of the left edge - page up
- Bottom half of the left edge - page down
- Top half of the right edge - page up
- Bottom half of the right edge - page down

This would leave the middle free for tapping on links and images. This would also improve left-handed/left-thumbed usage.

Possibly the split should be top 30% or 40% of the edges for page up with the other 60% or 70% for page down, given that page down is the more common action.

Several Kindles had this kind of layout, see e.g. the side buttons on ![the Kindle Keyboard](https://upload.wikimedia.org/wikipedia/commons/0/00/Amazon_Kindle_3.JPG)

Obviously this would inconvenience other users who like the existing tap zones, so maybe a fully-customizable tap-zone feature is needed?

**Comment by yanus171** [comment]
You propose leaves no place for brightness slider (on both sides). I agree 
that the fully customizable team zones is the best solution... But it takes 
much time to implement it. And even it doesn't resolve all problems .

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1087072730

**Comment by JohnVeness** [comment]
Thanks, it's great to be able to page down with side taps again, especially as I can now do it on the left edge as well as the right (I think it was right edge only, previously?).

One annoyance is that the side taps only work if I enable the brightness gesture - I don't want to change brightness using that gesture! I'm pretty sure that it used to be the case that the right edge page down tap would work even if the brightness gesture was disabled.

**Comment by yanus171** [comment]
Ok, I will try to fix it

**Comment by JohnVeness** [comment]
Hi, I've just upgraded from that test version you linked me to, to 0.17.0. I'm glad to see that I can now tap the sides to page down, without requiring the brightness feature to be enabled. So thanks for doing that :heart: 

One more thing would make this perfect: In those side zones I can tape, but I cannot drag scroll. I have to move my thumb a few millimetres towards the centre of the screen to drag! Obviously not a major hardship, but it would be great to be able to drag the page up and down in the left and right margins too. That way I can basically keep my thumb in the same place for most interactions I want to do on a page.

**Comment by yanus171** [comment]
It's impossible to drag on tap zones

**Comment by JohnVeness** [comment]
Oh. When I had 0.16.23 running, I could tap in the margins to page down, orr drag in the margins to change the brightness, so I assumed it would be possible to tap to page down and drag to scroll the page. That'd be a shame if not possible.
