### ISSUE TITLE
"Current article" does not persist

### ISSUE THREAD

**Issue by amit3s** [yanus171/Handy-News-Reader#733]
**Describe the bug**
While I'm on the article view, and then I switch to other apps, or if I return to the phone after a while, the article that was displayed is "lost", and a new article is shown in its place.  Marking an article as "read" as soon as it is opened causes this behaviour.

I do not know what series of steps are required for HNR to get into the state where the previous article is replaced by a newer one - it could be background feed updates happening in the meantime, or it could be due to the app not opened for a long time, and suspended by Android, or it could be a combination of both.

This behaviour has always existed, so it's not a regression. I'm currently on v0.16.15 via fdroid.

**Comment by yanus171** [comment]
Cant' reproduce it
