### ISSUE TITLE
PDF raw text is shown when 'load complete article' selected and article link points to .pdf

### ISSUE THREAD

**Issue by amit3s** [yanus171/Handy-News-Reader#734]
Frequently, the hackernews feed links to pdfs.  In the case of loading the complete article text, this results in downloading the pdf, and then attempting to render that pdf as an html file, resulting in a text dump of the pdf.  This of course causes the memory usage to spike and the app to become very slow, but is also pointless.

In case the article link refers to a non-html or non-text file, HNR should default to not loading the entire source.

**Comment by yanus171** [comment]
Give me a link to feed

**Comment by amit3s** [comment]
Link to HN feed

https://news.ycombinator.com/rss

I've not seen a PDF recently, will post a link when that happens

**Comment by amit3s** [comment]
This article loaded the PDF raw text for me today.

https://news.ycombinator.com/item?id=29561325

But there were several linked PDF docs via the HN feed in recent days, and the raw text was not dumped for all. So while the behavior recently has improved, it's not 100% yet, like this case shows.

**Comment by yanus171** [comment]
This link doesn't contains weird PDF. So I can't prevent  loading it

**Comment by amit3s** [comment]
I suppose if the text starts with `<PDF`, it could be ignored?
