### ISSUE TITLE
read article doesn't disappear

### ISSUE THREAD

**Issue by Pada0** [yanus171/Handy-News-Reader#736]
When you slide an article from the list to the left to mark it as read the article doens't disappear automatically from the list. Instead you have to go inside an article and go back to refresh the list.
And if you click on one of the remained article marked as read, it is the first article of the list which appear instead the article you click.

Android 9

**Comment by yanus171** [comment]
Can't reproduce it

**Comment by Pada0** [comment]
I could reproduce it on a android 10 Xiaomi.
Here is a screenshot of the unread tab from the android 9 blackview in case of misunderstanding :
![Screenshot_20211120-191319](https://user-images.githubusercontent.com/73777780/142737147-0d020003-75a9-4f72-b2ea-6c8012643a90.png)

**Comment by Pada0** [comment]
After that, if i click of one of this remain read articles (in grey), Handy show me the content of the first unread article (older than  remain read articles). If I quit the content of this first unread article, I have a crash with this message :



UNCAUGHT EXCEPTION
> Stacktrace:
> java.lang.IllegalArgumentException: Illegal update. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/unread_entries/-1
> at ru.yanus171.feedexfork.provider.FeedDataContentProvider.update(FeedDataContentProvider.java:657)
> at android.content.ContentProvider$Transport.update(ContentProvider.java:359)
> at android.content.ContentResolver.update(ContentResolver.java:1720)
> at ru.yanus171.feedexfork.fragment.EntryFragment$3.run(EntryFragment.java:688)Version : 0.16.15
> Version Code: 246
> Package : ru.yanus171.feedexfork
> FilePath : /data/user/0/ru.yanus171.feedexfork/files
> Phone Model: BV9900Pro
> Android Version : 9
> User : release
> Total Internal memory : 119575760896
> Available Internal memory : 50607087616
