### ISSUE TITLE
Please bring back the old way to share all starred articles to gmail.

### ISSUE THREAD

**Issue by Goran474** [yanus171/Handy-News-Reader#737]
What was great the old way:
- HNR put starred articles (headlines and hyperlinks i could tap on) right in the email body. 
- HNR automatically entered the email subject:  "Handy News Reader: starred entries" for me.
- One could easily organize these emails in folders or some other preferred ways, search for articles, tap on hyperlink and open it in desired browser or even in HNR again.

For me it was a great functionality that I used a lot for many years, since HNR forerunner FeedEx. 

What's confusing now:
- There is nothing in the email body, it's empty. No article headlines, no hyperlinks to tap on.
- No email subject entered, just empty field.
- Not really useful text file attached (shared_article_links.txt) with no starred articles in it, just a list of labels and only a few articles that I put labels on  earlier.
- Again, no all starred articles there. I could not find a way to share all starred articles any more in any useful way. 
- Now I have to go through tedious task to put some label on all of  them, one by one, only to find them shared in not very useful text file attachment. And since it's a .txt, there is no  hyperlinks to tap on to easily access old articles. And since it's an attachment... 
- Not easily searchable any more

Please bring back the old  functionality to share all starred articles (not just with labels) in the email body with email subject entered automatically. It was one of the reasons why HNR was so handy. 
To add labels to headlines and hyperlinks in the "share starred  entries" email body while still keeping just starred (no label) articles would be great new functionality.

**Comment by yanus171** [comment]
I put the content in attachment because sharing all started articles cookie 
easelly exceed maximum sharing text limit.

I will fix the mail subject and add articles without labels.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1751806447

**Comment by Goran474** [comment]
Thank you!
Still there is missing mail subject (Handy Reader Shared or something like that) but the old functionality is now a choice which is great.
