### ISSUE TITLE
Share Article Links by Single Label

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#739]
It is currently impossible to export the shared article links by single label. It is only possible to export the content of the entire label-tree for sharing.

Please, consider adding the desired action by which the shared article links of a single label can get exported as well?

Thank you.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1751806447

**Comment by touwys** [comment]
> Try [#683 (comment)](https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1751806447)

Release v0.19.3: Well done, thank you!
