### ISSUE TITLE
Text Anomaly in the Shared Articles Links List

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#740]
The Shared Article Links List contains repeating text type anomalies. The original (before) and the resultant text (after) are shown in the following examples:

**LABEL-TEXT TYPE BEFORE EXPORT:**
SARS-COV2 — ORIGIN: 
SARS-COV2 — PANDEMIC: 
SARS-COV2 — STATS: 

**LABEL-TEXT TYPE AFTER EXPORT:**
SARS-COV2 â€” ORIGIN: 
SARS-COV2 â€” PANDEMIC: 
SARS-COV2 â€” STATS: 

Can this be fixed, please?

Thank you,

**Comment by yanus171** [comment]
Can't reproduce it. Send me a example file with it
