### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Salixj** [yanus171/Handy-News-Reader#744]
My Handy News Reader crashes when I try and Reset Feed and Delete Non-Starred Articles when it is in the All Articles folder.

**To Reproduce**
1. Go to 'menu" when in All Articles Tab
2. Click on 'Visible Articles'
3. Scroll down to 'Reset Feed and Delete Non-Starred Articles'
4. Crashes

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/issues/683
