### ISSUE TITLE
Adding Label Anomaly

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#745]
*Describe the bug*

Creating a new label which to allocate to an article while in read mode, will disable all labels previously allocated to this article.

*To Reproduce*
1. Enter Label Setup while reading an article.
2. Allocate one or more labels for the article.
3. While still reading it, enter Label Setup once more to create another, NEW label for the article — in addition to the previous ones.
4. Return to the article, and enter Label Setup again to allocate the New Label. Nor that the previously allocated labels for this article is now Disabled.

*Expected behavior*

All labels previously allocated to an article should remain enforced when a new label is added for it until they are disabled by the user. 

*Device: HUAWEI MediaPad M5 Lite*
Model: BAH2-L09
Operating System: Android 8.0.0
Browser: Firefox 68.11

Thank you for attending to this issue.

**Comment by yanus171** [comment]
Can't reproduce it

**Comment by touwys** [comment]
I made a mistake in the steps given, for which I am sorry. Here is a short video which should explain it better than I can. The label setup is actually entered by clicking on a _link_ inside the article being read. Look out for the existing label "Energy" to be allocated, as well as the new label "test" that is added in Label Setup for this _linked_ article.

In the second video, the label setup proceeds normally, but notice the "two null" and "null" label tags below the headline date. This is the article that contains the link that was used to enter the label setup which produced the error shown in the first video.


https://user-images.githubusercontent.com/65730626/147177674-4a4a49ed-8c11-4441-aad3-fae2fd7949a2.mp4


https://user-images.githubusercontent.com/65730626/147177711-eb0961d7-a15d-436b-89ff-84984acdef65.mp4
