### ISSUE TITLE
Add "Edit feed" Link to Feed Menu

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#747]
Please view the scrrenshot below for context.

Thank you.

![20211225_132955_temp](https://user-images.githubusercontent.com/65730626/147384224-a7ffa4b9-0c5f-4427-b9df-6787c911d9e9.png)

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1079762063

**Comment by touwys** [comment]
Excellent! Thank you.
