### ISSUE TITLE
Feature request: add an option to remove the arrow, favorite icon, time, source from article screen

### ISSUE THREAD

**Issue by adguardgirl** [yanus171/Handy-News-Reader#750]
**Is your feature request related to a problem? Please describe.**
Feature request: I like the app but I would like it more if the article screen had less info 

**Describe the solution you'd like**
Add the option to remove the arrow next ti each article in the article list.
Add the option to remove any other info (favorite icon, time, source) from
article screen. So only the titles of the articles are seen!

**Describe alternatives you've considered**
As far as I know the only alternative is to use another app but I really like this one :) 

**Additional context**
I hope that the description is clear enough.

**Comment by yanus171** [comment]
If we remove the favorite icon, how can we see favorite articles?

**Comment by adguardgirl** [comment]
Hi yanus!

As removing the favorite icon would hopefully be an optional feature, it
should be used by those who don't use the favorite articles feature. I
personally read news through the app and never add any favorite articles.
All favorite articles are shown in a menu where the rest of items are. It
should already be possible. Swipe from left screen side to right and there
is "starred" sect ion that (as far as I know) displays all favorite
articles.

Cheers :)

**Comment by yanus171** [comment]
So we need no switch to hide start if you don't use favorites.
We have settings to hide full text indicators, category, icon, read 
indicators. What do you need also to hide?

**Comment by RusselNash10121** [comment]
I have wanted these features for a long time.
I don't use favorites so I would appreciate the ability to disable them on the feed list.
Also would like the ability to disable the arrow, time and source.
A cleaner feed list would this a perfect app for me!

**Comment by yanus171** [comment]
> So we need no switch to hide star if you don't use favorites.
> We have settings to hide full text indicators, category, icon, read
> indicators. What do you need also to hide?

**Comment by RusselNash10121** [comment]
> > So we need no switch to hide star if you don't use favorites.
> > We have settings to hide full text indicators, category, icon, read
> > indicators. What do you need also to hide?

I don't mean this to sound rude but I answered your question, or did I not?

**Comment by yanus171** [comment]
Do you know about Article text expanding setting in Sticker list section?

**Comment by yanus171** [comment]
What is the source?

**Comment by RusselNash10121** [comment]
> Do you know about Article text expanding setting in Article list section?

Yes, but that is disabled so that doesn't apply to this request.

Here is an edited screenshot showing what I would like it to look like.

[https://drive.proton.me/urls/GQ6Y4J4ME4#1HwPEd8s5Qzp](url)

**Comment by yanus171** [comment]
I can't load the screenshot

**Comment by RusselNash10121** [comment]
Hmm, I double checked and it works just fine for me on multiple devices.

Anyway, here's an alternate link.

https://www.imagebam.com/view/MEIE9WO

**Comment by yanus171** [comment]
The time is there. So I can't still understand what should I remove. Show 
the original screenshot and mark on it the elements you wish to remove

And I can't compound article title and other (grey) info so compact, to be 
sure these sections are not overlapping

**Comment by RusselNash10121** [comment]
Of course you asked after I deleted the original screenshot, lol. Had to make a new one.
(The date / time is fine on the article list.)

https://www.imagebam.com/view/MEIESO2

**Comment by RusselNash10121** [comment]
If you compare the two, you can see I removed the star and the character below the star (comma or apostrophe?).
I understand about it not being so compact.

**Comment by yanus171** [comment]
To get rid of comma you can set settings, article list, text Max size to 0


RusselNash10121 ***@***.***> 29 января 2023 г. 20:58:10 написал:

**Comment by RusselNash10121** [comment]
> To get rid of comma you can set settings, article list, text max size to 0

Very nice! I did not notice that setting could be turned off by setting it to 0. Thank you.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1416828674
