### ISSUE TITLE
Auto Backup as well as export OPML fails

### ISSUE THREAD

**Issue by billie80** [yanus171/Handy-News-Reader#754]
**Describe the bug**
When enabling auto backup a popup appears to the set time saying it is saved to the download folder. When taking a look there no backup file is created. The same happens when trying to export the opml, however there is an error message "Export failed. Make sure you have writeable SD-card mounted". In the german translation it does not mention SD-card but "Speicher" meaning storage.
When first starting HNR it asks for the storage permission which I have granted. Then the Android File Manager opens and asks me to select a file. Maybe this is causing the problem. It should ask to select a folder where HNR is allowed to write the backup instead of a file. As I can only abort this action probably the required permission is not granted.

**To Reproduce**
1. Enable auto backup
2. Popup says it is created but no backup is saved
3. Try to export opml
4. Error as above is shown and no backup is saved

**Expected behavior**
The backup is exported to storage and opml export works.

**Screenshots**
Grant storage permission:
![01_-_grant_storage_permission](https://user-images.githubusercontent.com/9938306/157478267-6f688437-6a20-45ab-9e27-7bc6c6a0d8e8.png)
Then file manager wants me to select a file which I cancel, it is not possible to select a diretory:
![02_-_file_manager](https://user-images.githubusercontent.com/9938306/157478287-b7a0c2fa-5105-49a2-b71f-6223af9e152c.png)
Error when trying to export opml:
![03_-_export_error](https://user-images.githubusercontent.com/9938306/157478305-c24332bc-5a73-486c-979c-4ecd806f2593.png)

**Smartphone:**
 - Device: Shift6mq
 - OS: Android 10
 - Browser: Firefox
 - Version: HNR 0.16.15

**Comment by yanus171** [comment]
Try to manually (via file manager) delete the file, which the app fails to 
write

**Comment by billie80** [comment]
Sorry, but there is no file to delete. It is never created and there are no previous backups or exports.

**Comment by yanus171** [comment]
Try the least beta https://github.com/yanus171/Handy-News-Reader/issues/683 please

**Comment by billie80** [comment]
I will but as it is the Google release I am not sure it works as I don't use GMS.

**Comment by billie80** [comment]
Tested the Beta 0.6.19_249. Unfortunately it shows the same behaviour!

**Comment by yanus171** [comment]
Cant confirm that on Android 10 emulator... Anyway during backup file export where shilud be no call for standard file manager ... Show me a video please

**Comment by billie80** [comment]
The file manager is not called when I try to export. This happens after I grant the storage permission. Maybe an issue with the new storage access framework.
I think although storage permission is given the App is not allowed to write to the Download directory.
In other Apps when giving the permission the stock file manager is also involved. Here one has to select the directory and it is possible to confirm the selection by clicking  "Allow access to Download". This confirmation is not possible with the selection dialog showing when giving the permission for HNR.
Log also says:
java.io.FileNotFoundException: /storage/emulated/0/Download/HandyNewsReader_20220313_124817.opml: open failed: EACCES (Permission denied)

**Comment by DamienCassou** [comment]
I face exactly the same issue. I thought I had backups of my opml file but the app hasn't backed up anything for a year. Exporting manually also doesn't work and shows the same message as described in this issue.

**Comment by billie80** [comment]
Unfortunately this does not work for me independent of which of the paths I choose.

**Comment by yanus171** [comment]
@moshpirit give me more info or send a video

**Comment by billie80** [comment]
Please find attached a video and the relevant logs.

https://user-images.githubusercontent.com/9938306/179897907-e467bfd7-88e3-4e0b-9734-f0d830242f89.mp4

[log.txt](https://github.com/yanus171/Handy-News-Reader/files/9146558/log.txt)

**Comment by moshpirit** [comment]
@yanus171 I don't know how to access the log, but here's a video: 

https://user-images.githubusercontent.com/7888062/180039754-04c4bbb0-20c7-4eb8-9e8f-b07600048c88.mp4

 I think it's the same thing @billie80 posted

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683

**Comment by moshpirit** [comment]
I've installed it on my tablet (Samsung Tab S4, official ROM, Android 10, in Spanish). 

It seems like I can now export OPML files, but not saving them. I can only share them. 

Also, backups are not being saved on Downloads/HandyNewsReader for me. The folder exists, but it's empty even after changing the backup time to 1 minute (from default 1 day. BTW, is it any button we can press to manually create a backup?)

I used a clipboard app to save the links and then get them back to configure HNR again faster. I saw I got this message pasted every now and then when configuring the HNR again:

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/ru.yanus171.feedexfork/files/feedex/HandyNewsReader_20220731_182450.opml
	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:800)
	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:442)
	at ru.yanus171.feedexfork.utils.FileUtils.copyFileToDownload(FileUtils.kt:79)
	at ru.yanus171.feedexfork.utils.FileUtils.copyFileToDownload(FileUtils.kt:67)
	at ru.yanus171.feedexfork.parser.OPML.lambda$exportToOpml$1(OPML.java:718)
	at ru.yanus171.feedexfork.parser.-$$Lambda$OPML$8NRcon40hLbXkhhhbnEKquiADW0.run(Unknown Source:4)
	at ru.yanus171.feedexfork.utils.WaitDialog.doInBackground(WaitDialog.java:25)
	at ru.yanus171.feedexfork.utils.WaitDialog.doInBackground(WaitDialog.java:7)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

-------------------
Version : 0.17.9
Version Code: 267
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: SM-T830
Android Version : 10
User : dpi
Total Internal memory : 56557961216
Available Internal memory : 10081247232
-------------------
```


PS: wouldn't it a better idea calling the beta versions differently (eg: HandyNewsReader Beta) when there's issues with backups? Because if I have many sources and filters, it's not an incentive for users to uninstall the app, then install the beta and configure all over again until the next version is released and repeat the process.

**Comment by yanus171** [comment]
Thank you for report 
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1200486005 
- Lets finally fix backup issue and theer will be no problem :)
- To manually activate backup got to article list menu & select More options -> Create separate backup file or Create autobackup file

**Comment by moshpirit** [comment]
It worked!!! 😍😍 thanks a lot!!

**Comment by yanus171** [comment]
Hooray.

**Comment by billie80** [comment]
Great! Unfortunately I can not test this at the moment as I don't have a working phone right now. Will do so as soon as possible.

**Comment by sbadux** [comment]
Hello @yanus171, I have the same problem. I've installed the last version from F-Droid (17.7) then I found this thread and tried to upgrade to 17.11 from your Drive link. When I try to install it, Android says "App not installed".
I thought I have to install the previous beta (17.9) before the .11, but Android doesn't let me install it. It says that an error occurred. I've rebooted my phone and tried to download the app again, but I still can't install it...

**Comment by billie80** [comment]
I guess you have to uninstall the App first. Downgrades are not supported by Android. Also the drive version might have a different signature which also prevents the upgrade.
@yanus171 could you tag the new version. You know F-Droid :-)

**Comment by sbadux** [comment]
> I guess you have to uninstall the App first. Downgrades are not supported by Android. Also the GDrive version might have a different signature which also prevents the upgrade. @yanus171 could you tag the new version. You know F-Droid :-)

Thank you very much. I didn't want to lose the settings, but if it's needed I'll uninstall the app. In the new version is it possible to select a custom folder where to save the backup? I'm thinking to set a folder synced with my PC via Syncthing, so I would like to save the backup in that folder. I can open a new issue if this is offtopic

**Comment by billie80** [comment]
You just have to wait a few days more. If @yanus171 tags the new version it will be picked up by F-Droid eventually. Then you can update as usual.

**Comment by sbadux** [comment]
> You just have to wait a few days more. If @yanus171 tags the new version it will be picked up by F-Droid eventually. Then you can update as usual without losing your settings.

Thanks!

**Comment by yanus171** [comment]
You will not lose your settings after uninstall if you have a backup file. 
To create it select Run auto backup now menu item in More options menu of 
article list window. Check that you have   HandyNewsReader_auto.backup file 
in Downloads. You can uninstall after that.

**Comment by yanus171** [comment]
For now I want to add some minor improvements before fdroid release. So it 
could be longer than few days

**Comment by billie80** [comment]
> You will not lose your settings after uninstall if you have a backup file.
But this is currently not possible as auto-backup and manual backup fails. I guess it is the same for @sbadux.

**Comment by yanus171** [comment]
I have made a release https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.17.12 
You may start counting few days

**Comment by sbadux** [comment]
> I have made a release https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.17.12 You may start counting few days

Thanks!!

**Comment by billie80** [comment]
Got the update from F-Droid today. Now export and auto-backup work fine. Thank you very much!

**Comment by yanus171** [comment]
Ok, I will try to hurry up with new release :)
