### ISSUE TITLE
F-Droid Updates behind Play Store

### ISSUE THREAD

**Issue by billie80** [yanus171/Handy-News-Reader#755]
I don't know if it is a real feature request as it is related to F-Droid packaging only. So I hope it is okay to skip the template.

There were related requests but this topic never came up explicitly. I hope I did not miss anything during my search.

I don't think you are directly involved in F-Droid packaging. There is one thing however which would help to bring new releases there earlier.

Currently F-Droid detects new versions of HNR by Git tags. Recently I noticed that the most recent version is 0.6.18. This version is already available at the play store. In F-Droid it is not picked up by the auto update process because the tag is not available.

So it would be really great to have a tag associated to each release for updates to get picked up earlier. What do you think?

**Comment by yanus171** [comment]
There is a beta issue 
https://github.com/yanus171/Handy-News-Reader/issues/683 where I put app 
versions for testing. But I have got no feedback. So I am still waiting for 
last beta to be tested ...

**Comment by billie80** [comment]
Understood! Play Store users are beta testers 😃
Will close this then!

**Comment by yanus171** [comment]
I can release a big fix to Google play during several hours. And fdroid one would takes several weeks

**Comment by billie80** [comment]
I think several weeks is a bit exaggerated. It is slower true, but this is mainly due to F-Droid is building from source.

If the auto update function can be used (which is true for HNR) F-Droid will scan everyday for a new release. In the case of HNR it checks for new tags. Then it will be compiled in the next build cycle which takes at max. two days. Afterwards it deployed!
So max one day to get picked up, two days to build (depends on the number of new releases for other Apps) and deployment. So it should be around 4 days.

If there is a build failure it has to be fixed manually first and then go into another build cycle. Only then it can take longer depending on how quick the issue will be fixed.
