### ISSUE TITLE
Preselect its Location when adding a new label

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#756]
**Is your feature request related to a problem? Please describe.**

I use labels extensively in order to categorise my news articles for redistribution. The list of labels is long and growing, and when adding a new label, these are added right at the bottom of the current list of labels. If the user wants to maintain an alphabetically-sorted list, like I do, it means that any newly added label has to be manually dragged into position. An option for an automatically-sorted list would be the ultimate convenience, but since that is not yet available, I hope that the following proposal will be favourably considered for implementation when you see it fit to do so.

**Describe the solution you'd like**

In order to add a new label in your favourite location, please follow these steps:

1) Open the Label setup dialogue.

2) Select a current Label in the list of labels, e.g. "Food", above which you want your new Label, e.g. "Family", to later appear in your labels list. This can be in alphabetical order, or any other order of your choosing.

3) Select Setup to add the new Label "Family" and click OK to close the Label setup dialogue.

**Describe alternatives you've considered**

Proposed an HNR-option through which the labels can be sorted automatically into alphanumerical order.

**Additional context**

**Please see image provided herewith:**

![labels setup screenshot 20220316_edit](https://user-images.githubusercontent.com/65730626/158589070-b00d4a8d-0a36-4f8c-b248-1000ff802f58.gif)

**Comment by yanus171** [comment]
Seems that a last I would have to implement alphabetical sorting ...

**Comment by touwys** [comment]
> Seems that a last I would have to implement alphabetical sorting ...

Your work is always greatly appreciated, thank you.

**Comment by yanus171** [comment]
try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1079373727

**Comment by touwys** [comment]
Thank you very for adding this feature. Please take another look at #647 ?
