### ISSUE TITLE
Screen brightness do not adjust

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#759]
Swiping up and down the left edge of the screen will not adjust the screen brightness, even having enabled the Software Overlay setting under Operations.

—

![Screenshot_20220321_075524](https://user-images.githubusercontent.com/65730626/159212847-f8753a42-1d53-414e-bffc-c1bb8f7537ef.png)

**Comment by touwys** [comment]
This issue appears to have resolved itself by pure chance during a Theme>Font reset.

**Comment by yanus171** [comment]
So does the issues reproduce if you disable tap actions in settings?

**Comment by touwys** [comment]
Sorted, thank you. Issue due to user error. "Tap zones" should have been enabled.

**Comment by yanus171** [comment]
Did you enable tap actions in settings?
