### ISSUE TITLE
App not registered in "Complete Action Using" dialogue to add Custom Fonts & More

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#763]
**Describe the bug**

The user wants to add custom fonts, but using the default method does not open an app with which to complete the desired action, i.e. he does not gain access to the fonts he wants to install. The screenshot that follows does not display a file manager or a similar means to enable access to the fonts to be installed. (The desired user fonts, however, can still be copied directly into the font-folder located in the default app data directory).

**To Reproduce**

Steps to reproduce the behaviour:

1. Open programme "Settings"
2. Tap on "Theme"
3. Tap on "Font"
4. Tap to open the Font drop-down menu
5. Scroll down to and tap on "Add custom font..."
6. The interface dialogue opens. It displays various applications _[screenshot]_ — none of which provides the means with which to complete the add font action. There is no file manager listed that gives access to the files on the device.

**Expected behaviour**

At Step 6 above, the user would expect to see a File Manager of some description to open through which they can gain access to the files on the device.

**Screenshots**
![HNR — SCREENSHOT APPS LOADED ADDING NEW FONTS photo_2022-03-28_11-10-20  resized](https://user-images.githubusercontent.com/65730626/160367141-c76dcfe3-71a0-441e-a801-0d95a5f4274b.jpg)

**Mobile Device — Tablet:**

• Huawei Mediapad M5 Lite Model: BAH2-L09
• Android Version : 8.0.0
• Device Total Internal memory : 24958189568
• Android Browser Firefox 68.1.1
• Android File Manager X-plore 4.28.32
• Handy News Reader Release 0.16.22_252

**Comment by touwys** [comment]
Please take a look at this issue again, because it also affects the backup restore process. It is impossible to restore a backup when the dialogue does not offer a path to access to the  *.backup files. 

Meanwhile, is there an alternative way to restore a backup? Tappng on the backup-file itself, does not restore it, and neither does it invoke HNR to do so.

**Comment by touwys** [comment]
Could this perhaps offer the solution?

<a title="[Register an app to show in 'complete action using dialog in Android - Genera Codice](https://www.generacodice.com/en/articolo/3005019/Register-an-app-to-show-in-'complete-action-using-dialog-in-Android)" href="https://www.generacodice.com/en/articolo/3005019/Register-an-app-to-show-in-'complete-action-using-dialog-in-Android">Register an app to show in 'complete action using dialog in Android</a>

**Comment by yanus171** [comment]
Did you try to install Total commander?

**Comment by yanus171** [comment]
Try to uncheck Use standard file manager in advanced settings

**Comment by yanus171** [comment]
Try to uncheck Use standard file manager in advanced settings

**Comment by yanus171** [comment]
And it's another issue. Move your last post to a new one please

**Comment by touwys** [comment]
> Try to uncheck Use standard file manager in advanced settings

Did that, but if a backup is restored using the internal dialogue, the app crashes every time. Consequently,  so it is impossible to continue.

**Comment by yanus171** [comment]
> And it's another issue. Move your last post to a new one please
