### ISSUE TITLE
"Share whole text" prepends leading garbage

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#766]
When sharing articles with "Share whole text" there is some style sheet prepended, then comes the article text.

```
@font-face { font-family:"MainFont"; src: url("");} @font-face { font-family:"CustomFont"; src: url("file:///data/user/0/ru.yanus171.feedexfork/files/feedex/fonts/");}
```

**Comment by yanus171** [comment]
Отключите блокировку неизвестных источников, установите присланную мной 
версию и включите обратно


xandro0777 ***@***.***> 29 марта 2022 г. 23:42:42 написал:

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1751806447
