### ISSUE TITLE
Topmost Article in Feed List is Unresponsive to Tap/Swipe Actions

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#768]
**Describe the bug**
 
1. Tap, or swipe, on the topmost article in any feed list.
2. There is null reaction to the aforesaid input.
3. This unresponsive behaviour is not observed for all group feed lists — only some.

**To Reproduce**

Steps to reproduce the behaviour:

1. Tap, or swipe, on the topmost header in a feed list.
2. Error: zero response.

**Expected behaviour**

1. Tapping on the article headline should open it in the reader.
2. Tapping on the article date line should open the Label Setup dialogue.
3. Swipe left should mark the article as Favourite (Star).
4. Swipe right should mark/dim the article as read  — or unread if it's been read already. 

**Screenshots**

https://user-images.githubusercontent.com/65730626/161041564-d147d8f1-1197-4a5d-997a-df90865302d9.mp4

**Device — Tablet:**

• Huawei Mediapad M5 Lite Model: BAH2-L09
• Android Version : 8.0.0
• Device Total Internal memory : 24958189568
• Android Browser Firefox 68.1.1
• Android File Manager X-plore 4.28.32
• Handy News Reader Release 0.16.22_252

—

**Comment by DamienCassou** [comment]
I have exactly the same issue.

**Comment by yanus171** [comment]
Still can't reproduce it

**Comment by yanus171** [comment]
Will the issue appear when you disable tap actions in app settings.

**Comment by touwys** [comment]
> Will the issue appear when you disable tap actions in app settings.

Yes.

**Comment by forstran58** [comment]
I am also facing the issue (Pixel 5, hnr version 0.16.21 from f-droid).
After scolling the feed list up a little bit, though, topmost article becomes responsive, again.

**Comment by touwys** [comment]
> I am also facing the issue (Pixel 5, hnr version 0.16.21 from f-droid). After scolling the feed list up a little bit, though, topmost article becomes responsive, again.

I really think you are onto something here. I was able to repeat your actions, and as can be seen from the screen video, moving the list up and down and header to hide and reappear, made the topmost article responsive again:

—

https://user-images.githubusercontent.com/65730626/161391118-5839d2df-a339-4003-9cd7-512ab676f68e.mp4

**Comment by yanus171** [comment]
I got it!!! This happens only when the list of articles fits on one screen and scrolling is not required (temporary ignoring of the upper tap zone in the program is performed by scrolling event). I'll fix it.

**Comment by touwys** [comment]
Excellent! Glad you tracked down the culprit so quickly.

**Comment by yanus171** [comment]
try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1087072730

**Comment by touwys** [comment]
> try [#683 (comment)](https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1087072730)

Referring to release 0.16.23:  The topmost article in a list of articles is sometimes still unresponsive to finger-tap/swiping actions. Moving or scrolling  the page slightly, will then have it respond to input again.

**Comment by yanus171** [comment]
What about the latest API release?

**Comment by touwys** [comment]
> What about the latest app release?

All good here, thank you.
