### ISSUE TITLE
 The Articles of the Incorrect Feed Group are Getting Set as "All Read" 

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#769]
**Describe the bug**
 
 1. When tapping on the "Mark All As Read" button in one group of feeds, the articles in the next group opened get set as all read instead of those in the relevant group.
 2. _Notably, this behaviour is inconsistent as it happens randomly_.
 
**To Reproduce**

Steps to reproduce the behaviour:

1. Open the feeds of a group.
2. Tap on the "Mark All As Read" button in that group.
4. Exit the 1st group, and tap to open another feed group quickly thereafter.
5. Error: All the articles in the 2nd group get set as having been read, instead of those in the preceding group that were supposed to be marked as read. 

**Expected behaviour**

Tapping on the "Mark All As Read" button in a group of articles, should only set the articles for the relevant group as read.

**Device — Tablet:**

• Huawei Mediapad M5 Lite Model: BAH2-L09
• Android Version : 8.0.0
• Device Total Internal memory : 24958189568
• Android Browser Firefox 68.1.1
• Android File Manager X-plore 4.28.32
• Handy News Reader Release 0.16.22_252

—

**Comment by yanus171** [comment]
Does this issue occur only in feed groups? What about single feeds and labels?

**Comment by touwys** [comment]
It appears so, yes. Strange thing happened though, initially the overall Label category and Favorites displayed the same behaviour in that the first article was unresponsive. I then started to test a number of the sub-labels of which the first article did respond to taps & swipes. Then, returning to the overall Labels and Favourites, they responded as well.

I have only three feeds outside of groups. They were all tested and the first articles all responded to the taps & swipes. They were all read articles when I started the test.

**Comment by yanus171** [comment]
Seems your post refers to another issue

**Comment by touwys** [comment]
Yes, it does. Thank you for pointing it out. I think it refers to issue #768, which appears to be resolved in v0.16.23. This issue, #769, remains valid, though.

**Comment by yanus171** [comment]
So please delete two your previous posts in the current issue and answer to my question

**Comment by touwys** [comment]
I have observed this behaviour in nothing else but the feed groups due to my usage pattern. 

Only 3 feeds are not classified into a group, and the label content are never **individually** "unstarred" (marked as read?) due to its effectual relationship with Starred/Favourite.
