### ISSUE TITLE
In Feeds: Moving a feed by hand instead adjusts the screen brightness

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#770]
**Describe the bug**

With "Operation" >> "Brightness gesture change" setting enabled , it is impossible to move a feed into another position. Instead, the screen brightness is getting adjusted when swiping up or down.

**To Reproduce**

1. Go to "Feeds".
2. Click & hold on a feed in a group and move it up or down into a new position.
3. See error: feed does not move, instead screen brightness is getting adjusted.

**Expected behavior**

Holding & moving a feed up or down, upon release should put it to its desired new location.

**Screenshots**

https://user-images.githubusercontent.com/65730626/161380327-78a258a3-a22d-4885-afa8-834dba214750.mp4

**Device**

• Device: Huawei Mediapad M5 Lite
• OS: Android 8.0.0
• HNR 0.16.22
• Browser: Firefox 68.11

**Additional context**

Disabling the "Brightness gesture change" setting is required before a feed can be moved into another position.

—

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1112449720

**Comment by touwys** [comment]
Thank you, issue resolved.
