### ISSUE TITLE
Separating universal & local group actions

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#773]
With more than 500 feeds in all, all but 3 are categorised into many different groups. One expects that certain HNR operations are confined or restricted to local execution only, for example, apply to groups alone. However, we find a mix of local and universal application of some actions that can be applied either locally or universally. This can be quite confusing, and can lead to unforeseen, startling results. 

An example of the aforesaid, happens when long-pressing at the top of an article feed list. This evokes the dialogue exhibited in the screenshot below. Since I do not know what to call this dialogue, I henceforth name it the "yellow box dialogue" (or "YBD" for short).

Looking at the YBD, it is apparent that four different actions can be evoked by tapping on each of the items presented on the menu. Whereas the 1st and the 4th item shown on the YBD menu call for the **localised** action to be performed,  unless I am wholly mistaken, numbers 2 and 3 evoke the **universal** action that affects **all** feed groups. 

I propose that the actions (and their descriptions, too, where applicable) on the YBD-menu are changed to apply to the **local** group only, and that those actions that call for universal results, are moved elsewhere more fitting.

![Screenshot_20220404_104037](https://user-images.githubusercontent.com/65730626/161520640-710f7d7a-aaf6-4ae1-b2f8-426354390362.png)

**Comment by yanus171** [comment]
All four actions are related to long tapped article

**Comment by touwys** [comment]
Yes, but the results of the actions are not? What result is to be expected when the "Mark upper are read" is tapped? I do not understand this command properly. Previously, what happened is that **all** articles were marked as read — not only the long-tapped one.

**Comment by touwys** [comment]
If the "Mark all as read" button in the bottom right corner is tapped, the desired action is **locally** executed. Long-pressing a read article, and then tapping "Mark all as unread" in the dialogue calls the action alright — only this time it is **universally** executed.

**Comment by yanus171** [comment]
Try #683

**Comment by touwys** [comment]
Thank you, release v17.2 fixes this issue very nicely.
