### ISSUE TITLE
 Two repeated feed errors

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#774]
**Describe the bug**

Once the sidebar is opened, and it presents a list of feeds by groups, or otherwise,  errors are visible directly underneath numerous feed names, namely:

1. "Error: Socket already closed"

2. "Error: Unexpected end of str..."

**To Reproduce**

1. Start auto refresh. When finished,
2. Go to the Sidebar to view the feeds.
3. Click on a feed group to open it (do this if the feeds are grouped, as in this case).
4. Scroll down the presented feeds list.
4. See error directly beneath the feed names.

**Expected behavior**

No errors of the kind.

**Screenshots**

![Screenshot_20220404_142104](https://user-images.githubusercontent.com/65730626/161547622-3d93c01e-19a2-48cb-afe4-c0ad31ec8821.png)

**Device**

 - Device: Huawei Mediapad M5 Lite
 - OS: Android 8.0.0
 - Browser: Firefox
 - Version: 68.11

**Additional context**

The reported errors are applicable to release version 0.16.23, although it previously occurred in other releases, too. It appears to be a problem related
to the device and its internet connection. If so, what is the solution, and how can it be prevented from reoccurring?

**Comment by yanus171** [comment]
The solution is to refresh these feeds when the internet connection will be 
back

**Comment by touwys** [comment]
Thank you. I did exactly that, several times, before I posted this as an issue. The internet connection, at the time, was indeed functional, and only the reboot of the device followed by an article refresh appears to have solved it.

**Comment by yanus171** [comment]
So the problem is in these two feeds? Give me their urls so.

**Comment by touwys** [comment]
No, there were more than two feeds. Too numerous to have logged here. See screenshot. When next this issue occurs, I will try to improve my observation of the circumstances around it to post it here.

Here are 3 example feed URL's

http://off-guardian.org/feed/

https://newspunch.com/feed/

https://naturalnews.com/rss.xml

**Comment by ArtexJay** [comment]
> No, there were more than two feeds. Too numerous to have logged here. See screenshot. When next this issue occurs, I will try to improve my observation of the circumstances around it to post it here.
> 
> Here are 3 example feed URL's
> 
> http://off-guardian.org/feed/
> 
> https://newspunch.com/feed/
> 
> https://naturalnews.com/rss.xml

I've tried all the feeds shown in your screenshot, I cannot appear to reproduce it in v0.17.17 beta. Reloading and "start autoreload" appears to fetch correctly the articles without socket errors. 
Do you still have the same socket error on v0.17? or the beta mentioned?

**Comment by touwys** [comment]
It is fixed, thank you. Could it have been ascribed to an internet connection stability issue?

----------------------------------------

01 Oct 2022 08:01:04 Emperor ***@***.***>:
