### ISSUE TITLE
Undue long pause inbetween assigning article labels

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#777]
**Describe the bug**

When labels are assigned to articles , there is an undue long pause inbetween.

**To Reproduce**

1. Go to article list.
2. Click on subhead i.e. the date/timeline to open label setup dialogue.
3. Scroll down the applicable label and select/enable it.
4. Click "OK" to close the label setup dialogue.
5. Issue: user is faced by a blank screen for an unproductively long time, before the articles list becomes accessible again.

**Expected behavior**

A quick label saving processing time.

**Screenshots**

https://user-images.githubusercontent.com/65730626/162559590-dee48803-4488-4ccb-a749-9ec38573de08.mp4

**Device**

 - Device: Huawei Mediapad M5 Lite
 - OS: Android 8.0.0
 - Browser: Firefox
 - Version: 68.11

**Additional context**

The pause between assigning a second label and returning to the list of articles again is,  relatively speaking, much shorter, as per screenshot:

https://user-images.githubusercontent.com/65730626/162565173-5f580d5f-ba1b-4129-84a5-f6bbe6b84f4c.mp4

**Comment by touwys** [comment]
**Additional context**

**Comment by touwys** [comment]
Release v0.16.28_257 resolved this issue. Thank you, it's a huge productivity improvement.

**Comment by yanus171** [comment]
I hand done nothing about it :)
