### ISSUE TITLE
App stopped working after Lineage OS update

### ISSUE THREAD

**Issue by linuxissuper** [yanus171/Handy-News-Reader#781]
I've updated Linage OS 18 (android 11)  
    Security string 2022-04-05
    System Webview 100.0.4896.58

Since then I'm getting:  
```
UNCAUGHT EXCEPTION
Stacktrace:
java.lang.NullPointerException: Attempt to get length of null array
at ru.yanus171.feedexfork.utils.FileVocinit12.run(FileVoc.kt:69)
at java.lang.Thread.run(Thread.java:923)

Version : 0.16.21
Version Code: 251
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Xperia Z1 Compact
Android Version : 11
User : android
Total Internal memory : 12688826368
Available Internal memory : 2292629504
```

**Comment by yanus171** [comment]
Seems that this is IO error. Check app permissions to phone memory

**Comment by linuxissuper** [comment]
Ok, it seems there is a problem with the feeds or my db.  
When I reinstall the app, it works.  
But when I import the backup db, I get the same error  
   
Maybe the Lineage OS update was just a coincidence

**Comment by yanus171** [comment]
The solution is to go to advanced settings and set Data folder
