### ISSUE TITLE
Reader View: Garbled text is displayed in article content 

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#784]
As per subject. This unusual text, as shown in the screenshot, occurs in the articles from one source. Three page links are given below as examples:

[Example 1](https://m.jpost.com/science/article-704927)

[Example 2](https://m.jpost.com/science/article-702961)

[Example 3](https://m.jpost.com/science/article-704921)

The original webpages do not display the same anomaly.

![Screenshot_20220425_080713](https://user-images.githubusercontent.com/65730626/165031861-62e418bd-a358-4729-820e-760b65b403fc.png)

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1159666253

**Comment by touwys** [comment]
@yanus171

**Thank you for release v17.2**. At first glance, the issue appears to prevail. Herewith some new screenshots, with their respective source links:

https://www.jpost.com/breaking-news/article-709752

![Screenshot_20220619_123600 _ Garbled text](https://user-images.githubusercontent.com/65730626/174477613-bc79f7bd-ceef-41ae-9282-dab1c5cd4e64.png)

•
•
•
https://allnewspipeline.com/The_Future_Is_MUCH_Closer_Than_We_May_Think.php

![Screenshot_20220619_123657 _ Garbled text](https://user-images.githubusercontent.com/65730626/174477657-1cc15e72-cf7f-4fbf-a6f3-0c63ab15d46d.png)

**Comment by yanus171** [comment]
Cant reproduce it on https://www.jpost.com/breaking-news/article-709752 . @touwys, Did you try to reload the article

**Comment by yanus171** [comment]
https://allnewspipeline.com/The_Future_Is_MUCH_Closer_Than_We_May_Think.php is subject to separate issue reasoned by web page encoding (UTF_32)

**Comment by touwys** [comment]
Thank you for pointing out the webpage encoding for this site is causing the issue in the Reader. Can it be fixed?

----------------------------------------

28 Jun 2022 12:45:41 yanus171 ***@***.***>:

**Comment by yanus171** [comment]
> Can it be fixed?
As a separate issue

**Comment by touwys** [comment]
I cannot remember whether I tried to reload the page, or not. However, with release v17.3, having now tested many pages from the same site, I am also unable to reproduce the issue. I think it can be put to rest.

----------------------------------------

28 Jun 2022 12:41:15 yanus171 ***@***.***>:
