### ISSUE TITLE
Restoring from a backup crashes the app every time

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#786]
**Describe the bug**

After uninstalling and then doing a fresh install of the app, it crashes every time while restoring either one of several backups. Therefore, the user is left completely unable to restore the various programme configurations, which means for instance, that umpteen **Labels** have to be laboriously recreated.

**To Reproduce**

1. Uninstall **version 0.16.23** of the app.
2. Reinstall **version 0.16.23** of the app.
3. Go to default download folder on device.
4. Select app auto backup file or suitable alternative.
5. Tap to restore the selected backup.
6. App crashes immediately.

**Expected behavior**

App should restore the backup without crashing.

**Device**
 - Huawei Mediapad M5 Lite
 - OS: Android 8
 - Browser: Firefox 68.11

**Additional context**

1. Backup file size 43Mb+
2. If, instead of lumping all the programme configurations together as it is presently getting done, some of them, such as the "Labels" could be backed up **separately**  just like the feeds OPML-file.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1112449720

**Comment by touwys** [comment]
Thank you, issue resolved.
