### ISSUE TITLE
Can't reach part of the menu while Landscape orientation is on.

### ISSUE THREAD

**Issue by ThomasLeigh** [yanus171/Handy-News-Reader#79]
If I check _"Landscape orientation"_ in the menu and the article turns into it - **part of the menu is not visible** any more and it is not scrollable - so, for example, there is no way to switch back to the portrait mode.

**Comment by SIRSteiner** [comment]
I cannot reproduce this issue. Any news with v0.9.0? A video could be helpful for @yanus171

**Comment by ThomasLeigh** [comment]
I've just checked and the issue doesn't occur anymore (i.e. the context menu is scrollable again). Thank You :) .
