### ISSUE TITLE
Changes to filters are saved to the incorrect filter

### ISSUE THREAD

**Issue by snowweb** [yanus171/Handy-News-Reader#792]
**Describe the bug**
When the rule type of one filter is changed, another filter in the list of filters is affected, changing it's rule type to the rule type intended for the one you just edited.

**To Reproduce**

1. Create some filters for a feed (in my testing I have 11 filters, all of which are regex and of the "Mark as starred" Type.
2. Select and open the 3rd filter from the bottom of the list
3. Select the "Accept" rule type option
4. Click "OK"
5. Click the filter you just created **Note that it is now "Mark as starred" type again!**
6. Click "OK"
7. Check the filter at the top of the list. **Note that it has magically become an "ACCEPT" filter!**

**Smartphone**
Cherry Mobile Flare S8 Max
OS: Android 9; Build/PPR1.180610.011
Browser: Brave 1.37.116, Chromium 100.0.4896.127
HNR Version:  0.16.21

**Other remarks**
- I have not tried it with other numbers of filters created, this may still occur with only 2 filters created.
- If you repeat the operation, editing the same 3rd rule from the bottom again, setting it to "Accept", the same occurs, except this time the 2nd filter from the top is changed instead of the one you edited.
- If you changed anything else when you edited the rule at the same time as changing the rule type, that change will also be saved the incorrect rule.

**Comment by yanus171** [comment]
Try the last beta 
https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1087072730

**Comment by snowweb** [comment]
I just tried again to download but on my laptop and it seems I was able to circumvent the permissions, by clicking the download link instantly before the page finishes loading!

So I got the file, but when I transferred it to my phone and tried to launch it, after pressing the "Install" button, it goes through the process but a few seconds later says, "file not installed". Tried several times.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1112449720

**Comment by snowweb** [comment]
Ver 16.28 seems to have fixed this issue. Good job!

Thank you!
