### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by inspector71** [yanus171/Handy-News-Reader#793]
**Describe the bug**
Run the app, what was working now is not. Cannot get any meaningful response.

**To Reproduce**
1. Open the app
2. Wait about 5 seconds

**Expected behavior**
If it's freezing trying to parse a badly formatted feed, an error would be handy. Then that feed would be ignored whilst the rest of the app would remain usable.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Motorola G6
 - OS: Android 9

**Comment by yanus171** [comment]
It's #765 issue. Please close this one
