### ISSUE TITLE
Labels Separator

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#796]
**Is your feature request related to a problem? Please describe.**

When numerous labels are assigned to an article, they are difficult to read afterwards. Please view the attached screenshots for an example.

**Describe the solution you'd like**

Please provide a separator such as a comma or pipe between labels to easily distinguish between them.

![Screenshot_20220505_075423](https://user-images.githubusercontent.com/65730626/166871087-e7c0ab38-3464-4caf-a202-ba4cc19127ae.png)

![Screenshot_20220505_080135](https://user-images.githubusercontent.com/65730626/166871112-9d7cdcea-ea11-4294-b506-f3f315171476.png)

**Comment by ArtexJay** [comment]
They are separated now

**Comment by yanus171** [comment]
Give me a link to feed

**Comment by touwys** [comment]
This is only one link I have chosen randomly — none of the links show the label separator.

https://www.activistpost.com/feed

----------------------------------------

01 Oct 2022 15:01:13 yanus171 ***@***.***>:

**Comment by yanus171** [comment]
This is what I see


touwys ***@***.***> 1 октября 2022 г. 16:11:40 написал:

**Comment by ArtexJay** [comment]
just tried activistpost on v0.17.17, the tags are correctly separated...

![Screenshot_20221001-170232_Handy News Reader](https://user-images.githubusercontent.com/32932497/193428358-7390e101-2f17-4533-9db9-82bcafa60e51.jpg)

**Comment by ArtexJay** [comment]
Sorry, confused labels with tags in the screenshot somehow

**Comment by yanus171** [comment]
Me too :)

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1264614844

**Comment by touwys** [comment]
Fixed! 😁

Thank you @yanus171

----------------------------------------

02 Oct 2022 14:37:30 yanus171 ***@***.***>:
