### ISSUE TITLE
Often doesn't show counts in left-hand menu since 0.17

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#800]
Since 0.17 (and still present in 0.17.1), very often, when I open the left-hand list of feeds, all the counts are missing.

One way to reproduce this is as follows:

1. Open HNR
2. Open the left-hand menu
3. Observe there are counts (numbers) in the menu
4. Rotate the device to landscape
5. Observe that the counts have disappeared

I'm pretty sure I've seen this happen without having to rotate, too.

**Comment by yanus171** [comment]
This is because of counters lazy loading. Just wait until they would have 
loaded. There is a progress indicator at bottom

**Comment by JohnVeness** [comment]
No, it's not that. I'm aware of that new feature. In this case there is no spinner and the numbers never appear.

**Comment by JohnVeness** [comment]
To clarify, I do think it's related to the new lazy loading feature, especially given that it started in 0.17. It's just that sometimes the app seems to get into a state where the lazy loading doesn't get triggered and no amount of waiting will make it happen (well, other than maybe a scheduled refresh of the feeds occurring while you're waiting).

Annoyingly, the procedure in the first post doesn't seems to consistently trigger it, but I have managed to record the problem happening, seemingly triggered by pressing Back twice, as follows:

https://user-images.githubusercontent.com/2512915/169992726-0ab2e34e-548e-4d62-b9c6-1710ccdc72dd.mp4
