### ISSUE TITLE
App Crashes while importing feed.rss file upon installatiin

### ISSUE THREAD

**Issue by fenix011** [yanus171/Handy-News-Reader#804]
Just send you the traces
**Describe the bug**

As said, app Crashes in 'my phone ' while importing feed.rss file upon installatiin

**To Reproduce**

Install app via F- Droid

Choose feed.rss upon file picker

(See trace | error log  , sent via e-mail )

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Redmi 9A NFC
 - OS: MIUI 12 - ANDROID LINUX variant
 

**Additional context**

**Comment by yanus171** [comment]
The app has no ability to import single feed as a file

**Comment by yanus171** [comment]
Send me please backup file too via email
