### ISSUE TITLE
Sharing an article from reader view does not include article title 

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#805]
_With reference to version 17.2:_

Previously, if I'm not mistaken, it was possible to share both the article title and the article link from the menu called up in the article reader view. Now, the link only, gets shared.

**Comment by touwys** [comment]
Since it is already possible to share a text fragment from an article — which gets done without any referential information applicable to it — please consider adding the article title and the source URL for it as well?

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1170312141

**Comment by touwys** [comment]
Issue solved with release v17.3. Thank you.

----------------------------------------

29 Jun 2022 19:59:50 yanus171 ***@***.***>:
