### ISSUE TITLE
Cannot add custom font

### ISSUE THREAD

**Issue by afmbsr** [yanus171/Handy-News-Reader#806]
https://user-images.githubusercontent.com/38974362/175285911-30afa9e4-ace3-4245-9fe8-b1b810a07797.mp4

**Comment by yanus171** [comment]
Try to press back buttons on file select dialog and then choose a file from 
downloads folder

**Comment by touwys** [comment]
Adding custom fonts is an issue for me in release v17.2 as well — and it has been like that in certain previous releases. The workaround was to locate the fonts folder, and copy the desired new fonts directly to it. The newly added fonts should then be visible to select in Settings\Themes\Fonts.
 
OS is Android 8.
Device is Huawei MediaPad M5 Lite.

•

![Screenshot_20220624_124831](https://user-images.githubusercontent.com/65730626/175807592-55cb4e4d-20d3-413f-93e3-eab30565f414.png)

**Comment by afmbsr** [comment]
The mentioned methods will not work in solving the problem, so I had to go back to version 0.17.0 which supports adding custom fonts without problems.

**Comment by yanus171** [comment]
try this https://drive.google.com/file/d/15T8fQIXNHvNBK1iwKViSqzD2mEwPZjjT/view?usp=sharing

**Comment by afmbsr** [comment]
> try this https://drive.google.com/file/d/15T8fQIXNHvNBK1iwKViSqzD2mEwPZjjT/view?usp=sharing

it's working! Thanks a lot for the fix.
