### ISSUE TITLE
Article dates sometimes incorrect

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#813]
**Describe the bug**
Sometimes, article dates are not correctly displayed, which can also mess up sort orders.

**To Reproduce**
1. Add feed https://godotengine.org/rss.xml
2. Find article "First public release"
3. Compare date with that of same article in RSS feed text or https://godotengine.org/article/first-public-release

**Observed behavior**
Article date is today, 12 AM.

**Expected behavior**
Article date should be 14 Jan 2014.

**Screenshots**
Raw RSS:
![Screenshot_20220801-195722](https://user-images.githubusercontent.com/2512915/182233801-18265657-09fd-4718-9f61-1162fd2587d9.png)

Article on web:
![Screenshot_20220801-195752](https://user-images.githubusercontent.com/2512915/182233854-7ddb9abc-2e39-43df-9be3-6f39b920578c.png)

Article in HNR:
![Screenshot_20220801-195807](https://user-images.githubusercontent.com/2512915/182233883-4601212a-b292-4ff6-af6e-049cf4754835.png)

Version 0.17.7 from F-Droid.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1203085115

**Comment by JohnVeness** [comment]
Thank you, that seems to work great!

Incidentally, I see the fix was to change the year "border" from 5 years to 20 years. I suspect it will be a while before the 20 year thing will be a problem, but I was wondering what the point of that border was anyway. Can you explain, for interest?

**Comment by yanus171** [comment]
The date parse errors (which often occurs for dates time formats which are 
not already implemented in the app) makes the articles date to be set to 
01.01.2000 +- which makes articles invisible (due to default keep date 
settings). To make it visible I check the result date and if it's earlier 
than date border I set it to today
