### ISSUE TITLE
Chinese character 

### ISSUE THREAD

**Issue by nokturna1** [yanus171/Handy-News-Reader#814]
Chinese page bernama.com font encoding issue 
![Screenshot_20220802-204813](https://user-images.githubusercontent.com/80862894/182379060-68bea4c4-4140-4d56-b6ac-77b749f7872a.png)

**Comment by yanus171** [comment]
Give me a link to rss

**Comment by nokturna1** [comment]
Here: 
https://www.bernama.com/man/rssfeed.php

**Comment by yanus171** [comment]
Please your post to https://github.com/yanus171/Handy-News-Reader/issues/807
