### ISSUE TITLE
Screen brightness adjustment is inaccessible in Article Reader View

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#817]
As per subject: Screen brightness adjustment is inaccessible in Article Reader View.

Release v0.17.11

**Comment by yanus171** [comment]
May be an app had found a video in an article text and disabled all tap actions?

**Comment by touwys** [comment]
@yanus171 — yes, thank you.

**Comment by yanus171** [comment]
Are you sure?
