### ISSUE TITLE
Fixed position for the drop-down text-view arrow in article list

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#818]
The new staggered view of the expanded 
text arrow, is really inconvenient in that it
causes many accidental, or unintended 
actions, such as invoking the drop-down
text view instead of the label setup menu.
One would expect the arrows to be in the 
same vertical plane i.e. in a fixed position,
 rather than a variable that gets determined 
by the preceding text length. In older 
releases,the drop-down text arrows were 
in a fixed position in a vertical plane on 
the far right of the article list screen, where 
it did not pose any such problem.

(Sorry, unable to post screenshots).

**Comment by yanus171** [comment]
The problem is that this arrow is too small, so I made the collapse/expand action to be activates by tap on all article item swiping space (except article title - open article , date & size - label setup)

**Comment by JohnVeness** [comment]
> Much worse. The problem is that this arrow is too small, so I made the collapse/expand action to be activates by tap on all article item swiping space (except article title - open article , date & size - label setup)

Ah, that explains why I keep getting the expand action happening accidentally when I'm trying to open articles - I prefer never to use expand (and never use labels for that matter), so for me it would be great if I could click anywhere n the article swiping space to open the article.

**Comment by touwys** [comment]
Is the expanded text view an absolute necessity, or can it be done away with completely?
