### ISSUE TITLE
Some dates in article list missing month and day?

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#819]
**Describe the bug**
Sometimes when I view the article list, some articles have just a year and a time, but no month or day of the month.

**Screenshots**
![Screenshot_20220804-133454](https://user-images.githubusercontent.com/2512915/182852926-1d18ed90-31ec-45a0-8d5d-41b7d3a025f4.png)
![Screenshot_20220804-133504](https://user-images.githubusercontent.com/2512915/182852930-9188eadf-3c5b-4f70-9425-a7cf6475d668.png)
![Screenshot_20220804-133515](https://user-images.githubusercontent.com/2512915/182852936-9ed15bfc-eef0-44de-a0ba-0d19f841b561.png)

**Additional context**
Feed is https://godotengine.org/rss.xml . I'm running 0.17.11 because of issue #813 (that issue now fixed). I'm not sure if this problem is new or has been present for a while - it may be that I've only just noticed it because I've been paying special attention to dates recently. As far as I can tell the affected articles *are* being sorted correctly, so I'm thinking this is just a cosmetic issue.

**Comment by JohnVeness** [comment]
I should add that if I click on one of the affected articles, the full and correct date is shown, so it's just a problem in the article list.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1484184430
