### ISSUE TITLE
clipboard filled with exception & stacktrace

### ISSUE THREAD

**Issue by emdete** [yanus171/Handy-News-Reader#820]
**Describe the bug**

When i pasted from my clipboard into an SMS a stacktrace was pasted.

**To Reproduce**

I have no clue why, when or where that happened.

**Expected behavior**

The app should not change the clipboard without notifying the user.

The npe should not happen

**Screenshots**

This was the content of the clipboard:

```
Stacktrace:java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.database.Cursor.getString(int)' on a null object reference
at ru.yanus171.feedexfork.fragment.EntryFragment$15.run(EntryFragment.java:1353)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7664)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$ MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit. java:947)
-------------------
Version : 0.17.7
Version Code: 265
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
```

**Smartphone (please complete the following information):**

 - Device: teracube 2e
 - OS: Android Version : 11

**Additional context**

This really is a wonderful app. :) Thank you!

**Comment by yanus171** [comment]
The toast message 'Error text was copied to clipboard' will resolve the issue?

**Comment by emdete** [comment]
like "Some error occured, i pasted tracing information about it into your clipboard, please send it to the developer."? :D yes, why not?

**Comment by emdete** [comment]
yes there is a new dialog asking me what do do with an exception - great, thank you! (maybe the message is a bit brief for the average user, i would use "error" insyead of exception cause a non-developer  may be confused?)
