### ISSUE TITLE
Feed no longer working (davespace)

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#822]
The following feed works in 0.17.1 and earlier, but no longer works in 0.17.7 or 0.17.11. Error is "at line 1, column 0, no element found".

http://www.davespace.co.uk/blog-all.atom

**Comment by ArtexJay** [comment]
> The following feed works in 0.17.1 and earlier, but no longer works in 0.17.7 or 0.17.11. Error is "at line 1, column 0, no element found".
> 
> http://www.davespace.co.uk/blog-all.atom

Tested your feed in the latest v0.17.17 it works fine
https://www.davespace.co.uk/blog-all.atom

**Comment by JohnVeness** [comment]
Thanks. What was the problem (or the commit that fixed), out of interest?

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/commit/96a37d965051784672a691c312baa96c7a7751ca
