### ISSUE TITLE
Filter out old articles when refreshing feed

### ISSUE THREAD

**Issue by Liorst4** [yanus171/Handy-News-Reader#823]
**Is your feature request related to a problem? Please describe.**
The amount of storage that app was taking on my device was getting really big, so I tried to use the "delete old articles feature".
I set it up to 3 months, lots of old articles were deleted and all was good... until the next day, when I refreshed the my feed and got 700 new articles.

RSS Feeds like the LLVM blog, contains all of the articles since 2009 (https://blog.llvm.org/index.xml).
Since these old articles weren't in storage, the app treated them as new articles.

**Describe the solution you'd like**
RSS has an optional `pubDate` tag (https://www.rssboard.org/rss-specification#optionalChannelElements)
Atom has has the `updated` tag (https://www.rfc-editor.org/rfc/rfc4287)
Cross reference the setting from "delete old articles" and discard articles that are older than the maximum value.

(Make the discard optional when first fetching the articles)

**Describe alternatives you've considered**
Keeping hash of old articles and comparing new ones against them

**Comment by yanus171** [comment]
After first RSS feed refresh an app saves update time and in subsequent 
refreshes treats articles as new only if their date is after saved one.

Also you can reset the feed as if it was just created by Reset feed and 
delete all unstarred ... item in the article list window menu
