### ISSUE TITLE
Option to export OPML file and autobackup to a particular folder

### ISSUE THREAD

**Issue by openwick** [yanus171/Handy-News-Reader#825]
Right now when opml  and autobackup is exported it only exports to Downloads folder. I have a folder which I kept it in sync with my cloud so if I can export opml to that folder I can sync and keep my feeds online as well. 

I dont want download folder to be in sync cause my cloud storage will sync random files along with opml if I keep sync for downloads folder hence the need.

**Comment by yanus171** [comment]
What is your Android version?
