### ISSUE TITLE
Auto-Sync Not Working

### ISSUE THREAD

**Issue by ArtexJay** [yanus171/Handy-News-Reader#827]
**Describe the bug**
 This might be a me issue, but Handy News Reader is not auto-syncing at all. It doesn't auto-sync while I'm using the app, have it closed or in the background.
I also do not get the notification telling me whether or not it has auto-synced. When I check the app I find it has not synced since the last manual sync I did. This issue persists when I'm using Wifi or Data.

I made sure to enable auto-sync (every 30mins) in the app's settings of the app as well as to exclude it from battery-saving restrictions that my phone may impose on it when it's not open or in the background.

The last build of Flym correctly syncs in the background for me however without changing any settings. And other RSS readers I've tried, like the one I'm switching from auto-sync as expected too.

**Expected behavior**
I expect HNR to auto sync in the background, while the app is open or when it's closed. And to provide the notification telling me it has.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T Pro
 - OS: Android 11
 - Version of Handy News Reader 0.17.1

**Comment by yanus171** [comment]
Try to start auto refresh manually from article list menu. Do you see 
process notification?

**Comment by ArtexJay** [comment]
> Try to start auto refresh manually from article list menu. Do you see process notification?

Yes I do, however, it acts only as a manual refresh/sync. Afterwards it does not auto-sync on it's own.

**Comment by ArtexJay** [comment]
My issue could be the same as this issue which I just found out was reported a year ago https://github.com/yanus171/Handy-News-Reader/issues/727

**Comment by yanus171** [comment]
No, it's more like #831

**Comment by ArtexJay** [comment]
This was a Xiaomi issue, it looks like Xiaomi updated some system application, Im unfortunately not sure what it was, but auto-sync now correctly automatically retrieves articles.
