### ISSUE TITLE
Error Reading a Link in certain RSS Feeds

### ISSUE THREAD

**Issue by ArtexJay** [yanus171/Handy-News-Reader#830]
**Describe the bug**
Unable to fetch the body/contents or recognize the url link in certain cases and when you attempt to reload full text an error was given. Using the same link provided in Flym and Freeder the articles load correctly. This i seem to affect World section as the Politics section does not receive this same error.

**To Reproduce**
1. Add (without quotes) "https://moxie.foxnews.com/google-publisher/world.xml"
2. Load the rss feed
3. Open one of the articles
4. You will see that the article is not loaded at all, only the title is loaded.
5. Click on "Reload Full Text" 
6. HNR will give an error ": java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found." (As show in the screenshot)

**Expected behavior**
Expected that the articles contents will load properly.

**Screenshots**
![Screenshot_2022-09-23-00-02-34-351_ru yanus171 feedexfork](https://user-images.githubusercontent.com/32932497/191891266-f90889da-21f5-4ad0-b324-8d299248f396.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9t Pro
 - OS: Android 11
 - Version HNR 0.17.1

**Additional context**

**Comment by yanus171** [comment]
Even more. This feed had article content inside it (no need for losing full text) and HNR is not showing it. I will try to fix it

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1236133593

**Comment by ArtexJay** [comment]
> Try [#683 (comment)](https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1236133593)

This totally fixes it! 
However, it appears that in v0.17.16 a rss feed is broken/not fetching content properly.
An error is presented as seen in the screenshot below when you refresh the feed, this issue was not present in  v0.17.1 (Stable build) :


![Screenshot_2022-09-28-04-03-57-132_ru yanus171 feedexfork1](https://user-images.githubusercontent.com/32932497/192725031-b2fb4406-5619-452c-91f1-d8db14e9f05e.jpg)

New Feed erroring: https://tass.com/rss/v2.xml

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1261320390

**Comment by ArtexJay** [comment]
You're gonna kill me I know, but this is the last feed error I was able to find. I recently added another feed to HNR and was receiving a similar error. 

HNR correctly fetches the article but when you click on "Load full article" or "reload full text" it gives this error:
![1664525282999](https://user-images.githubusercontent.com/32932497/193223202-a43cdeb9-faae-423b-a9ce-94f47bce8feb.jpg)

New feed is: https://feeds.feedburner.com/engpravda/news

**Comment by yanus171** [comment]
Cant reproduce it in last v0.17.17. Try to select Reset feed and delete non starred articles from article list menu. And refresh feed

**Comment by ArtexJay** [comment]
> Cant reproduce it in v0.17.17. Try to select Reset feed and delete non starred articles from article list menu. And refresh feed

The issue is present in v0.17.17, and I have managed to do it on 2 devices that I own that support run android.
The suggestion didn't change anything. As i have said before clicking on "load full article" or reload "full text" gives the error shown in the screenshot above "no scheme was found for 35"

**Comment by yanus171** [comment]
Go to article and select menu Reload, Edit URL. And show me screenshot

**Comment by ArtexJay** [comment]
![image](https://user-images.githubusercontent.com/32932497/193532815-e023cbfe-e960-43a9-9bdf-e0c27181880e.png)
