### ISSUE TITLE
Tags are excluded from article texts

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#833]
**Describe the bug**
When reading the particular article below, some content viewable in the web version doesn't appear in HNR.

**To Reproduce**

1. Subscribe to feed https://www.signal.org/blog/rss.xml
2. Open article "Help people in Iran reconnect to Signal – a request to our community" (currently the latest article)
3. Scroll down and compare with the web version of same article (see screenshots)

**Screenshots**
HNR:
![Screenshot_20220926-183453](https://user-images.githubusercontent.com/2512915/192353296-224f7edc-8deb-43b8-8d3e-02f5b7065745.png)
Web:
![Screenshot_20220926-183720](https://user-images.githubusercontent.com/2512915/192353343-978e6349-9ea8-4e0a-bd6f-683c1423718e.png)
HNR:
![Screenshot_20220926-183625](https://user-images.githubusercontent.com/2512915/192353189-7f4492b6-d70c-43cb-884f-ea4e52e59ec8.png)
Web:
![Screenshot_20220926-183831](https://user-images.githubusercontent.com/2512915/192353220-387e3031-d9fc-454f-b81b-650b4eed548d.png)
HNR:
![Screenshot_20220926-191958](https://user-images.githubusercontent.com/2512915/192353365-61ac9cac-383f-47c3-a818-101bea457a46.png)
Web:
![Screenshot_20220926-183842](https://user-images.githubusercontent.com/2512915/192353391-e2679a5b-7457-4b18-b161-a1d74679ba2c.png)

Version 0.17.14

**Comment by yanus171** [comment]
Try to (un)check in advanced settings Convert XML symbols before parsing

**Comment by JohnVeness** [comment]
Thanks. That setting was ticked previously. Unticking it fixes the first screenshot (see below), but not the others, sadly:

![Screenshot_20221001-182308](https://user-images.githubusercontent.com/2512915/193421117-dde19342-131c-4d73-88a4-6c3754b9c480.png)

**Comment by yanus171** [comment]
This is because I exact the articles tags starting from #

**Comment by JohnVeness** [comment]
Aha, I see. Personally I don't use categories in HNR, but now I've turned it on in the "Article list" settings, I see that "#IRanASignalProxy" is now displayed underneath the article date in the list.

Any chance for turning this hashtag extraction off completely?

**Comment by yanus171** [comment]
I will make a setting

**Comment by JohnVeness** [comment]
Thanks. Although, thinking about it, would it work if (without needing a setting) you copied the hashtags into categories, but kept them within the body of the article too? I realise that might look a

**Comment by yanus171** [comment]
The main purpose for me in it was to remove tags as a rubbish from article text

**Comment by JohnVeness** [comment]
Hello, I appreciate everything you do for this app, but I just wondered if you had a chance to visit this? I came across an article that viewed in HR that included:

> ```Basically, after registering it on PS5, then registering it on PS5, TronicsFix (and most of the audience, myself included) were expecting PS5 to be “unregistered” from the disc drive, and ask to register it again when the drive gets brought back from PS5 to PS5.```

instead of the intended (from the website):

> ```Basically, after registering it on PS5 #1, then registering it on PS5 #2, TronicsFix (and most of the audience, myself included) were expecting PS5 #1 to be “unregistered” from the disc drive, and ask to register it again when the drive gets brought back from PS5 #2 to PS5 #1.```

As you can imagine, I was scratching my head for a while when first reading the article in Handy Reading!

**Comment by yanus171** [comment]
Ok, I will make a setting to exclude or not the tags from article text

**Comment by yanus171** [comment]
Try v0.19.9 https://disk.yandex.ru/d/vYgKLsMY6SMIOA
