### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [yanus171/Handy-News-Reader#838]
https://monitor.f-droid.org/builds/log/ru.yanus171.feedexfork/278#site-footer

https://issuetracker.google.com/issues/184872412 This is an issue of AGP 4.1. Updating AGP to 4.2 or above should fix it. Could you please upgrade the AGP? Thanks!

**Comment by yanus171** [comment]
@linsui how to update it?

**Comment by linsui** [comment]
I bumped

https://github.com/yanus171/Handy-News-Reader/blob/40f31b7ab61f6b60713be870690272270c4bfcb8/build.gradle#L11

to 7.3.1,

https://github.com/yanus171/Handy-News-Reader/blob/40f31b7ab61f6b60713be870690272270c4bfcb8/build.gradle#L4

to 1.7.20 and

https://github.com/yanus171/Handy-News-Reader/blob/40f31b7ab61f6b60713be870690272270c4bfcb8/gradle/wrapper/gradle-wrapper.properties#L6

to 7.4.

**Comment by yanus171** [comment]
Done it. Try again please

**Comment by linsui** [comment]
Thanks!

**Comment by yanus171** [comment]
Should I make a new release to fix it?

**Comment by linsui** [comment]
I updated the commit directly.

**Comment by linsui** [comment]
https://monitor.f-droid.org/builds/log/ru.yanus171.feedexfork/280#site-footer
