### ISSUE TITLE
Article view too dark

### ISSUE THREAD

**Issue by testcocoon** [yanus171/Handy-News-Reader#84]
In both mode (dark and light), the article is darker as the list of articles.
The result is that in light mode, the background is not white but grey in the article view and it is necessary to play with the backlight intensity to make it readable in a sunny environment.

There should be an option to have the same intensity in the acticle view and the list view.

**Comment by yanus171** [comment]
Just swipe down to up in left edge of screen in article view to restore 
brightness

**Comment by testcocoon** [comment]
Thanks.
I did not know this. Certainly, there should be a menu item to restore the brightness.
If you don't know that swiping  on this area permits to restore it, you can search a lot of time until you find a way to find a solution.

**Comment by yanus171** [comment]
Its better to make a setting to enable brightness swipe turned off by default
