### ISSUE TITLE
"share stared article" creates zero byte attachment in email-client

### ISSUE THREAD

**Issue by cmdtstof** [yanus171/Handy-News-Reader#847]
**Describe the bug**
when using "visible article > share stared article" and choosing an email-client (k-9), the attachment "shared_article_links.txt" created has a size of 0 (zero) bytes.

**To Reproduce**
1. mark rss articles with star
2. go "visible article > share stared article"
3. choose email-client (k-9)
4.  attachment "shared_article_links.txt" size = 0 bytes

**Expected behavior**
would be greath if there would be a list of stared article with all the infos (title, date, url, ..., except the text (as option???)) exported.

android
latest version of handy-news-reader 0.17.14 (272)

thanks

**Comment by yanus171** [comment]
This option is context to selected feed. So try to select starred articles 
section before activation it.

And you are using very old app version


stof999 ***@***.***> 2 февраля 2023 г. 08:43:21 написал:

**Comment by cmdtstof** [comment]
thanks for answering.

i use the latest version from f-droid.
not the the latest? update needed? :)

and i choose "stared" for seeing only the stared articles.
then 
- "visible article > share stared article"
- choose email-client (k-9)
- attachment "shared_article_links.txt" still size = 0 bytes
???
thanks

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1416828674

**Comment by cmdtstof** [comment]
i tryied to understand but ... ???
thanks

**Comment by yanus171** [comment]
Install the last beta app version

**Comment by cmdtstof** [comment]
thanks a lot.
