### ISSUE TITLE
Clipboard is spammed (eg with stacktraces: ForegroundServiceStartNotAllowedException)

### ISSUE THREAD

**Issue by paphko** [yanus171/Handy-News-Reader#848]
Quite often I get a toast that something has been copied to the clipboard, even though the app is not in foreground.

Example:

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service ru.yanus171.feedexfork/.service.FetcherService
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:109)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service ru.yanus171.feedexfork/.service.FetcherService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4787)
	at android.os.Parcel.readParcelable(Parcel.java:4755)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3018)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6201)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1967)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1933)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
	at ru.yanus171.feedexfork.service.FetcherService.StartService(FetcherService.java:1930)
	at ru.yanus171.feedexfork.service.AutoJobService.onStartJob(AutoJobService.java:224)
	at android.app.job.JobService$1.onStartJob(JobService.java:68)
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:105)
	... 7 more

-------------------
Version : 0.17.22
Version Code: 280
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: SM-G991B
Android Version : 13
User : dpi
Total Internal memory : 242017611776
Available Internal memory : 47047778304
-------------------
```

Further values in clipboard are plain numbers like "7" or "23".

![image](https://user-images.githubusercontent.com/6435623/216969766-fc0692c6-1ac0-40f0-b747-9fc27c84c1e7.png)

This is quite annoying. How can I switch this off?

**Comment by xUltra-xx** [comment]
Same problem and still no solution found.

**Comment by yanus171** [comment]
This is the same as #831

**Comment by paphko** [comment]
I checked the sources and I found that the string that is copied to clipboard is constructed in [DebugApp.java](https://github.com/yanus171/Handy-News-Reader/blob/master/FlymFork/src/main/java/ru/yanus171/feedexfork/utils/DebugApp.java) in function `SendException(..)`.
Maybe we could add an option to disable such Debug-SendExceptions entirely?

Further analysis revealed that my particular exception is caused in [FetcherService.java#L2043](https://github.com/yanus171/Handy-News-Reader/blob/master/FlymFork/src/main/java/ru/yanus171/feedexfork/service/FetcherService.java#L2043), which is apparently only executed when variable `foreground` is `true`, but the exception is thrown when a totally different app is running in foreground.
Could it be that the negation is wrong in the definition of the `foreground` variable? So that it should rather be:
```
        final boolean foreground = ACTION_MOBILIZE_FEEDS.equals(intent.getAction());
```
I'm a Java developer, but not an Android developer, so my guess might be wrong because I don't know too much about intents, maybe @yanus171 can comment on that?

**Comment by paphko** [comment]
Btw, [this](https://github.com/yanus171/Handy-News-Reader/blob/master/FlymFork/src/main/java/ru/yanus171/feedexfork/utils/DebugApp.java#L235) is the exact line where the error is copied to clipboard, right after the string is sent to some russian e-mail address (without asking twhether it should really do so!):
![image](https://user-images.githubusercontent.com/6435623/219971068-58a28e7d-9254-4b6a-bc0e-85ee7eaad870.png)

@yanus171 please be so kind and either disable this code entirely or at least add an option to the app so that the user may opt-out of sending some information to russia.

**Comment by yanus171** [comment]
The app is NOT automatically sending any mail to anybody. In the case of 
critical error the app just makes an intent to send a mail with debug info 
to my personal address (I am Russian). In this case the standard android 
dialog appears giving a user a choose of sending the info or not. And via 
what app.

**Comment by yanus171** [comment]
If you are so concerned about clipboard, I can make a setting to disable 
coping debug info to it.

**Comment by paphko** [comment]
> The app is NOT automatically sending any mail to anybody. In the case of critical error the app just makes an intent to send a mail with debug info to my personal address (I am Russian). In this case the standard android dialog appears giving a user a choose of sending the info or not. And via what app.

Thank you for clarifying that 😃 
(as I said, I'm not an Android dev, so I don't exactly know how intents work)

At least for  me the use case that you describe does not really work. I've never seen a dialog asking whether or not to send some information.

An option for disabling the clipboard filling would be great 👍 (yes, it's very annoying that my clipboard is filled automatically).

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1441898564

**Comment by paphko** [comment]
Thank you @yanus171, I really appreciate your effort for fixing this so quickly 😃 

The clipboard-messages are gone, after I disabled the new option.

Unfortunately, there are still plenty of exceptions that are thrown. There was even a notification from the device (Samsung) saying (translated to english):

> Handy News Reader crashes frequently. Put the app in deep standby to keep the phone running smoothly.

I would really like to continue using the app, so I am willing to analyze the thrown exceptions. But I've never seen a dialog or error log that I could report, except for the stacktrace in this very issue.
Any Idea what I could do?

**Comment by yanus171** [comment]
Enable debug options :) and send me an info


paphko ***@***.***> 27 февраля 2023 г. 11:27:48 написал:

**Comment by paphko** [comment]
I still don't get any dialog for sending the exception info.

But I get the clipboard filled very often (with enabled debug option) which is probably the reason for the device notification.
I checked the stacktraces from the clipboard and it's the same stacktrace every time: the one from my first post...
So I guess I cannot provide more information to you.

**Comment by paphko** [comment]
![Screenshot_20230301_195827_Nova7](https://user-images.githubusercontent.com/6435623/222238234-fc7aec22-eba7-412c-82b3-07cdc51aa210.jpg)

App is frequently reported to crash, most likely due to the error from the first post... Is it just me, or does it also happen for others?
