### ISSUE TITLE
"Run Auto Backup Now" Produces 4 Backup Copies

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#849]
**Describe the bug**
"Run Auto Backup Now" Produces 4 Backup Copies

**Expected behavior**
"Run Auto Backup Now" Produces 1 Backup Copy

**Screenshots**
[Auto Backup](https://user-images.githubusercontent.com/65730626/217290424-769ab6fd-e77f-486e-8b0a-fb37025a2b62.png)

**Device:**
 - Huawei M5 Lite Tablet OS
 - Android 8
 - Handy v18.8_google

**Comment by yanus171** [comment]
This is not a bug. It's a feature. These are 4 DIFFERENT last auto backup file copies

**Comment by touwys** [comment]
Attaching the backup date to the name to each individual auto-backup file, instead of using a sequential number, would have cleared that up very nicely, thank you.

**Comment by yanus171** [comment]
Numbers are much simpler to implement

**Comment by touwys** [comment]
> Numbers are much simpler to implement

If less relevant to the job at hand? 🤔
