### ISSUE TITLE
Webpage Links Set Date Not Respected

### ISSUE THREAD

**Issue by ArtexJay** [yanus171/Handy-News-Reader#851]
**Describe the bug**
When loading links from a webpage, it will typically load the date as the time that it synced and fetched the links. However when the links for example articles have a date in the link and that date is set the date doesn't change to the set date that has been selected. change.

Set date categorization seems to only affect RSS feeds and not Webpage Link Feeds.

For example, you fetch the link at 11:07 am on tuesday however the article was created on monday at 5pm, when date field is set, it still shows 11:07am Tuesday rather than the correct article's set date of 5pm Monday.

**To Reproduce**
1. Load articles using Webpage links feed
2. Click on one of the articles and click on "edit contents"
3. Find the date and set it as the date
4. Reload the article

**Expected behavior**
It is expected that the date will change to the new date that you have set. But the date doesn't change

**Smartphone (please complete the following information):**
 - Device: Xiaomi 9T Pro
 - OS: android 11
 - Browser: stock
 - Version v0.18.2

**Comment by yanus171** [comment]
Give me a link to that web page

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1445433229
