### ISSUE TITLE
Mark above as read not working

### ISSUE THREAD

**Issue by sbadux** [yanus171/Handy-News-Reader#852]
**Describe the bug**
Hello,
I scroll the "unread" list and starring the items I want to read later. If I can't scroll the whole list, I usually use the "set above as read" feature and continue to scroll in a second time.
Unfortunately I have big problems with the "set above as read" feature. Most of the times:
- The first time i clikc the "set above as read" it does nothing
- If i use "set above as read" on any other article it works
- If i use "set above as read" again without closing the app, it marks a (random?) of articles as read.

Few minutes ago this happened:
- I had a long list of articles. I scrolled down and set the first 20/30 articles as read the first time it didn't work 
- I tried "set above as read" on a random article below and it worked (It set the above article as read as expected)
- 78 unread unread articles remained
- I scrolled down 5/10 articles and used the "set above as read" feature
- All the 78 articles have been marked as read and I lost all the unread list

**To Reproduce**
It's really hard to find a single way to reproduce, I've tried to describe it above in a detailed way.
the bug is so obvious that I think it only affects me..

**Desktop (please complete the following information):**
 - OS: Lineage OS (Android 12)
 - Version 0.18.10
 - Device: Motorola Moto G 8 Plus
 - OS: Lineage 19

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1444217732

**Comment by sbadux** [comment]
When I try to install it, Android says that this package conflicts with an existing package. Should I remove the old version and reinstall this one?

**Comment by yanus171** [comment]
Yes, you should. But check that you have an auto backup file 
HandyNewsReader_auto.backup in handy_news_reader subfolder of downloads.


sbadux ***@***.***> 24 февраля 2023 г. 22:04:26 написал:

**Comment by sbadux** [comment]
I've updated the app. I'll check how it's working and let you know in the next few days

**Comment by sbadux** [comment]
At the moment all seems fixed! Thank you very much. I'll report if any strange behavioru will appear
