### ISSUE TITLE
Feed Error "Mismatch Tag"

### ISSUE THREAD

**Issue by ArtexJay** [yanus171/Handy-News-Reader#853]
**Describe the bug**
Unable to fetch the news articles/links properly for this feed specifically.

**To Reproduce**
1. Add the following feed "https://nationalpost.com/category/news/feed.xml"
2. Attempt to fetch the news articles
3. Error will be presented instead.

**Expected behavior**
It should be able to fetch the news articles, for whatever reason it stopped doing so and now presents with the error. I've tried it on other devices like my tablet with the same issue being experienced.
I've tried it on other RSS readers like Freeder and it's able to fetch the links/articles properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/32932497/221224665-9e9d79cb-1d52-4855-bdb0-a875bf8866db.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi 9T Pro (affects all devices i've tried)
 - OS: Android 11
 - Version v0.18.2

**Comment by sbadux** [comment]
Similar error on this feed: 
https://www.pambianconews.com/feed

Feeder correctly adds it, but Handy News does not. 0.18.13 beta

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1445433229

**Comment by sbadux** [comment]
It seems to work. Just after the installation, all the articles of the missing feed appeared. I will check in the next few days before confirming
