### ISSUE TITLE
Unlock italian translation

### ISSUE THREAD

**Issue by sbadux** [yanus171/Handy-News-Reader#855]
Hello,
I did a review on the italian translation which was a mess. 

Can you please un-approve the following sentence which is incorrect:
Automatic refresh will only be done if Wi-Fi connection is available

You approved the english sentence and nobody can change it. You can approve SIRSteiner's translation which is the best IMHO.

EDIT: I forgot to ask: the next version will include the reviewed translation?

**Comment by yanus171** [comment]
Unapproved it. Can you now edit it?

**Comment by sbadux** [comment]
Yes, now it's fine. Thanks!
I've finished the translation
