### ISSUE TITLE
Very old articles appear on the feed as just published

### ISSUE THREAD

**Issue by sbadux** [yanus171/Handy-News-Reader#856]
Hello,
sorry to bother you with another issue, but since you are so kind to listen all the reports I want to point it out.

I found that on some feeds, the old articles are marked as just published and unread. I mean *very* old articles from 2021/2022. Also if I mark all as read, the articles may come out as unread again in the following days. Not always the same articles, but old articles are mixed with the new.

For example, I can receive a new article and then an article from 2021 from the same feed. They are usually low-frequency feeds and the strange thing, is that Handy reports them as just published while they are not.

E.g.
1) In the https://pointieststick.com/feed/ I see the "Highlists from 2022" article as published on Feb 27th, 2023 (2:34PM) on Handy.  If I open the article on a browser, the real date of that article is Dec 31st, 2022.
2) The "2.0.0 Release" of the AntennaPod feed, is reported as published today in my HNR app while the real publish date is [Sept, 8 2020]

Feeds where I experience this "bug":
https://antennapod.org/rss.xml
https://pointieststick.com/feed/
https://www.lffl.org/feed

**Comment by yanus171** [comment]
Cant reproduce it. Did you setup any date tags in Edit content mode?

**Comment by sbadux** [comment]
Hello,
this happened just after the install. I've not changed anything in the options.
I also found this bug on all my previous installations of HNR (i've installed it many times on different phones in the last 2 years).

Can you please try to keep the subscriptions above for few days? The old articles are not shown everytime I refresh the feeds, just after some time (every 2-3 days). Moreover, HNR doesn't show all the old articles as unread, only a random one.

I tried to understand which is the trigger, but can't understand why they are shown

**Comment by yanus171** [comment]
What is your feed custom keep time?


sbadux ***@***.***> 5 марта 2023 г. 20:38:17 написал:

**Comment by sbadux** [comment]
It's set on 1 day

If I open AntennaPod feed, I only see this. 
![photo_2023-03-05_20-05-28](https://user-images.githubusercontent.com/28478027/222980566-89a4d999-e789-4903-9447-3549bd14dfbb.jpg)

As you can see, it shows only 1 article while for normal feeds (the ones that work fine) all the articles starting from 1st March are shown.
Another question rises: it's expected that I see all the articles from March 1st if the "keep time" is set at "1 day"?

**Comment by yanus171** [comment]
That's strange. I can see any article of I set custom keep time to forever 
(the first is 4 mouth ago). What is your app version?

**Comment by yanus171** [comment]
By the way. Old articles are removed only during Deleting old articles 
operation, which frequency is set in settings, or can be launched manually 
from menu

**Comment by sbadux** [comment]
I'm now using 0.18.14 beta but I had this problem also with the original F-droid version

My "delete old articles" interval is set to 1 day, I try to change this value to 2 days and see what happens. Anyway, as you can see in the image, it seems that old articles appear with a much newer date. I don't know if it's an app or feed problem, but I didn't had this problem with other RSS apps. Maybe the old artilces are managed in a different way

**Comment by hak814** [comment]
This seems similar to a problem I am experiencing with version 0.18.18 (fresh installation without adjusting default parameters).

I import an opml file with the following contents: 

```
<?xml version='1.0' encoding='utf-8'?>
<opml version='1.1'>
<head>
<title>Handy Reading export</title>
<dateCreated>1681484699110</dateCreated>
</head>
<body>
		<outline title='Bruzz - mobiliteit' type='rss' xmlUrl='https://www.bruzz.be/topic/mobiliteit/rss.xml'>
	</outline>
		<outline title='Bruzz - milieu' type='rss' xmlUrl='https://www.bruzz.be/topic/milieu/rss.xml'>
	</outline>
</body>
</opml>
```

Then I go to the 'Unread' folder and press the 'Refresh' button. The first time it seems to load correctly the recent articles, but with repeated presses, old articles appear (after up to 3 presses) with an incorrect recent date, again and again.

**Comment by AI-IMED** [comment]
Yes, I can confirm the problem, I noticed that the in-app publication date is incorrect for articles fetched through blogger blog feeds, as well as atom feeds.

http://www.blogger.com/feeds/1053392259941718227/posts/default


https://github.com/yanus171/Handy-News-Reader/releases.atom

**Comment by yanus171** [comment]
Try https://disk.yandex.ru/d/HTkVEdqYvE6qXA

**Comment by hak814** [comment]
v0.19.8 doesn't solve my issue

**Comment by AI-IMED** [comment]
v0.19.8 doesn't solve the problem: 

 https://github.com/moneytoo/Player/releases.atom

https://raqamitv.com/feed/

**Comment by yanus171** [comment]
@AI-IMED did you try to reset the feed before refresh? Give me a concrete examples of articles with the wrong date

**Comment by yanus171** [comment]
@hak814 did you try just to create an RSS feed with url https://www.bruzz.be/topic/mobiliteit/rss.xml

**Comment by AI-IMED** [comment]
I did a clean reinstall of the application and all the settings were default. I tried several feeds and got an incorrect publication date within the application with the previous two feeds. You can notice that in the first article of each feed.

**Comment by hak814** [comment]
Same here: clean install with default settings. 
For yesterday's attempt, I imported an OPML export.
Today, I tried again and added the feed(s) manually. 

When adding only one feed (https://www.bruzz.be/topic/mobiliteit/rss.xml OR https://www.bruzz.be/topic/milieu/rss.xml), there doesn't seem to be a problem. 
The problem persists however when adding both those feeds.

**Comment by yanus171** [comment]
@AI-IMED, Try again please v0.19.9 https://disk.yandex.ru/d/vYgKLsMY6SMIOA

**Comment by yanus171** [comment]
And you don't need free install. Just reset feed and refresh it

**Comment by AI-IMED** [comment]
Now it looks good to me, except for the article dates that are fetched by loading web page links, they take the Refresh date and not the publish date, is that how it works?

**Comment by yanus171** [comment]
Yes it is. The article date make sense only in feed to organize sort
