### ISSUE TITLE
Some feeds problem and useful enhancements

### ISSUE THREAD

**Issue by Nick-1231** [yanus171/Handy-News-Reader#859]
Hello.

**1)** Some of the feeds doesn't work correctly. For example (Double Commander feed):
https://doublecmd.sourceforge.io/snapshots/rss.php?os=win
(This RSS feed doesn't work in Handy Reading…)

And it would be very helpful to make the following changes:
**2)**	Filters for folders (not only for one feed)
**3)**	Notification option for new feeds with star only (not for all feeds)
**4)**	New rule: ACCEPT + Mark as starred (for important articles)
**5)**	Global filter for all feeds with whitelist/blacklist mode (as this realized in separated feed filter)
(For example, it will be very useful for those, who have very many feeds, but need to download only articles with chosen words/regular expressions).

**P.S.** Thanks for this useful app as RSS/ATOM/JSON feed reader (and for GPL v3 License). Very hope that it will continue to develop actively in the future.
(Because at the moment there are practically no open source applications that can filter and notify only the necessary articles in the feeds and folders).

**P.P.S.** Android 13; Handy Reading v0.18.10 (last stable (from F-Droid)).

Screenshots with information about enhancements:
[![](https://i.ibb.co/sgYFmSS/thumb-f23b963ab29c501298d63722f869c8a5.png)](https://i.ibb.co/5xmzqgw/Image-01.png) [![](https://i.ibb.co/zJK6KTx/thumb-39013c3b9c8e148ece24b06ef7c78cf1.png)](https://i.ibb.co/VWRkgmK/Image-02.png) [![](https://i.ibb.co/DkMD51w/thumb-801a29195bd062a77f6b587932a5a426.png)](https://i.ibb.co/fHT4p25/Image-03.png) [![](https://i.ibb.co/1vDTzqc/thumb-544c96ab0cc9606fbf61b5061c4cdbfa.png)](https://i.ibb.co/JyV2966/Image-04.png) [![](https://i.ibb.co/MsPrzRb/thumb-0a702f534439657553f9c542cdf14519.png)](https://i.ibb.co/pPz17VW/Image-05.png)

**Comment by yanus171** [comment]
Can you devide this into separate issues, so we could discuss them separately?
