### ISSUE TITLE
Bugs with parsing some RSS feeds

### ISSUE THREAD

**Issue by Nick-1231** [yanus171/Handy-News-Reader#860]
**Describe the bug**
App can't parse some RSS feed

**To Reproduce**
1. Add new RSS feed (Official RSS of Double Commander snapshots):
https://doublecmd.sourceforge.io/snapshots/rss.php?os=win
2. Error of parsing it

**To Reproduce**
Steps to reproduce the behavior: (other feed example)
1. Add new RSS feed (Official RSS of QuiteRSS program):
http://quiterss.org/ru/rss.xml
2. Empty (without any errors)

**Expected behavior**
Normal parsing this RSS feeds

**Screenshots**
[![](https://i.ibb.co/FBqTnNf/thumb-562550952096c5d51cb411e883275eaf.png)](https://i.ibb.co/RhbJvkg/Image-01-error.png) [![](https://i.ibb.co/gy2NKVG/thumb-11234638d428bb5b11062c4765fd397d.png)](https://i.ibb.co/3R1CC2p/Image-02-empty.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera
 - Version: 96

**Smartphone (please complete the following information):**
 - Device: Redmi Note 9 pro
 - OS: Android 13
 - Browser: Opera
 - Version: 73

**Additional context**
None

**Comment by yanus171** [comment]
Try the last beta 
https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1445433229
