### ISSUE TITLE
Global and folder filtering and starred notifications only

### ISSUE THREAD

**Issue by Nick-1231** [yanus171/Handy-News-Reader#861]
**Is your feature request related to a problem? Please describe.**
App don't have folder filter (and global filter too); and also don't have notification only starred articles... (It's very useful if you have so many, many RSS feeds in multiple folders...)

**Describe the solution you'd like**
1)	Filters for folders (not only for one feed)
2)	Notification option for new feeds with star only (not for all feeds)
3)	New rule: ACCEPT + Mark as starred (for important feeds)
4)	Global filter for all feeds with whitelist/blacklist mode (as this realized in separated feed filter)
(For example, it will be very useful for those, who have very many feeds, but need to download only articles with chosen words/regular expressions).

**Describe alternatives you've considered**
I tried another apps with global filtering options and starred notifications only. :)) (But they are not open source!)

**Additional context**
Screenshots with information about enhancements
[![](https://i.ibb.co/sgYFmSS/thumb-f23b963ab29c501298d63722f869c8a5.png)](https://i.ibb.co/5xmzqgw/Image-01.png) [![](https://i.ibb.co/zJK6KTx/thumb-39013c3b9c8e148ece24b06ef7c78cf1.png)](https://i.ibb.co/VWRkgmK/Image-02.png) [![](https://i.ibb.co/DkMD51w/thumb-801a29195bd062a77f6b587932a5a426.png)](https://i.ibb.co/fHT4p25/Image-03.png) [![](https://i.ibb.co/1vDTzqc/thumb-544c96ab0cc9606fbf61b5061c4cdbfa.png)](https://i.ibb.co/JyV2966/Image-04.png) [![](https://i.ibb.co/MsPrzRb/thumb-0a702f534439657553f9c542cdf14519.png)](https://i.ibb.co/pPz17VW/Image-05.png)

P.S. I'm very hope, that this filtering and notifying will be realized in near versions of Handy Reading!..
P.P.S. And of course, thanks for the app (under GPL v3 License) to all developers!

**Comment by yanus171** [comment]
Filter for filters and Global are discussed in #326 or #39
Notification for starred articles by filter is already implemented
Can't you make two filter with Accept and Mark as starred?
