### ISSUE TITLE
Feed Parsing Error

### ISSUE THREAD

**Issue by tchamade61** [yanus171/Handy-News-Reader#865]
**Describe the bug**
Unable to read certain feeds. No articles are displayed and a ParseException error message is given.

**To Reproduce**
1. Add feed: "https://www.makeuseof.com/feed/category/linux/"
2. Load the rss feed
3. HNR gives error: "org.apache.harmony.xml.ExpatParser$ParseException:At line 1, column 0: no element found". No articles displayed.

**Expected behavior**
Expected feed to be loaded correctly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42547020/228578440-dde1e84e-ae60-4a5a-a5fd-51bc0451fa98.png)

**Smartphone**
 - Device: Galaxy S21
 - OS: Android 13
 - Version HNR 0.18.16 (beta from #683)
 
**Additional context**
Above feed is read correctly by other RSS readers on Android and PC. Issue affects all feeds on makeuseof.com.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.19.7
