### ISSUE TITLE
Android 4 page loading problem

### ISSUE THREAD

**Issue by riomccloud** [yanus171/Handy-News-Reader#868]
**Describe the bug**
When I try to load any RSS feed, the mentioned error appears.

**To Reproduce**
1. Android 4.4.2
2. Add an RSS URL
3. Try to load it

**Expected behavior**
Load the RSS feed.

**Screenshots**
![Screenshot_2023-04-09-20-11-00](https://user-images.githubusercontent.com/32412883/230800930-2fc3ff79-66f2-4f4d-8acd-672be4d189c3.png)

**Smartphone (please complete the following information):**
 - Device: Multilaser M7S NB196
 - OS: Android 4.4.2
 - Browser: Chrome, Via
 - Version 81, 4.6.0

**Comment by yanus171** [comment]
Unfortunately current square lib used for loading web pages supports only 
Android 5+, so in your case the app uses native connection mechanism which 
doesn't correctly loading many web pages
