### ISSUE TITLE
Problem displaying Google feeds

### ISSUE THREAD

**Issue by Peterspapan** [yanus171/Handy-News-Reader#869]
The behaviour changed a couple of months ago. When updating a feed , recent articles are loaded and the title displayed.  However, after a couple of seconds the title is replaced by 
![Screenshot_20230414-120522_Handy Reading](https://user-images.githubusercontent.com/25079585/232125657-99310d6c-6879-46bf-95c9-6f348edfc57e.jpg)
the mention "Google News" and the content of the article doesn't load. 
![Screenshot_20230414-120532_Handy Reading](https://user-images.githubusercontent.com/25079585/232126580-2de8c7dc-39fa-415e-9ab7-fc1c32ae7599.jpg)

Same behaviour on different terminals. Apparently Google changed the semantics of the links and HNR doesn't cope with change. 
Does anyone else have the same problem?

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1704321667
