### ISSUE TITLE
Categories as a feed specific setting

### ISSUE THREAD

**Issue by Mrnofish** [yanus171/Handy-News-Reader#871]
**Is your feature request related to a problem? Please describe.**
Some feeds use a large number of categories, which take up a lot of room in the article list, and reduce the number of articles visible in one screen

**Describe the solution you'd like**
It would be useful if Show Categories could be toggled on an individual feed basis.

This would allow showing categories for some feeds and not another.

**Describe alternatives you've considered**
An alternative solution could be making the categories container an extensible one.

In this scenario, the categories would take up a maximum of one or two lines, and tapping on them would expand the container, showing them all.

**Additional context**
It is kind of odd that categories are only show in the article list but not the article itself

**Comment by yanus171** [comment]
I suppose there is no sense in so much categories set, so you can disable 
them at all for selected feed (for selected url). Go on advanced settings, 
content extract rules, article categories and add new string there: 
site.com:class=never-found-class
So for URL contains site.com an app would try to find the categories in 
never-found-class and never succeeds in it. To apply these changes you 
should reset feed and refresh it
