### ISSUE TITLE
tap zones still active when turned off

### ISSUE THREAD

**Issue by JesseRacine** [yanus171/Handy-News-Reader#877]
I'm new to using Handy News Reader so this could be a misunderstanding on how this feature is supposed to work. using version 0.18.18 and I have tap zones turned off (unchecked) in the "Operation" section of the settings. However, disabling it appears to have had no effect. The top bar will still hide if I press in the area where the top right tap bar is. The top left tap zone is also still active.

**Comment by yanus171** [comment]
Try this version https://disk.yandex.ru/d/udvt7DuGvb0JOQ



JesseRacine ***@***.***> 3 июня 2023 г. 15:24:03 написал:

**Comment by JesseRacine** [comment]
I haven't been able to figure out how to download it from that website.

**Comment by yanus171** [comment]
https://drive.google.com/file/d/1j0EKrgo-iwFeeysCmOdk3vhzmD-VtG2g/view?usp=drivesdk

**Comment by JesseRacine** [comment]
> https://drive.google.com/file/d/1j0EKrgo-iwFeeysCmOdk3vhzmD-VtG2g/view?usp=drivesdk

I did get the download to work earlier from your Yandex link. I tested it and this new version fixed the problem with the touch zones. Thank you

**Comment by JesseRacine** [comment]
> https://drive.google.com/file/d/1j0EKrgo-iwFeeysCmOdk3vhzmD-VtG2g/view?usp=drivesdk

I did get the download to work earlier from your Yandex link. I tested it and this new version fixed the problem with the touch zones. That

**Comment by JesseRacine** [comment]
I just noticed a problem. When I disable the tap zones in your new version, the whole top row of buttons doesn't turn.

The 3-dot menu, search icon, and check box icon on the top of the screen stop working. They don't respond to touch.

**Comment by yanus171** [comment]
Can't reproduce it

**Comment by yanus171** [comment]
Try 
https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1575958090


JesseRacine ***@***.***> 4 июня 2023 г. 00:03:07 написал:

**Comment by JesseRacine** [comment]
> Try [#683 (comment)](https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1575958090)

Ok this appears to be fixed now
