### ISSUE TITLE
wrong rendering

### ISSUE THREAD

**Issue by emdete** [yanus171/Handy-News-Reader#879]
for this feed HNR renders the whole content as headline: http://blog.fefe.de/rss.xml . whats wrong? 

furthermore because links are not shown in headlines one cannot use the links.

**Comment by yanus171** [comment]
Add blog.fefe.de:class=Handy_News_Reader_root to advanced settings - full 
text root. And in this feed the article content is placed in the title section

**Comment by emdete** [comment]
thank you, this works! 🙂
