### ISSUE TITLE
question: age check and preservation time?

### ISSUE THREAD

**Issue by JesseRacine** [yanus171/Handy-News-Reader#880]
Hello,

I was wondering if someone could explain the "articles age check" and "articles preservation time" settings in the app. How do these two settings interact with each other? Thanks.

**Comment by yanus171** [comment]
Articles preservation time: During refresh operation do not load articles with date older than this duration
Articles age check interval: How often check and delete old (including already read) articles

I have updated settings summary

**Comment by JesseRacine** [comment]
> Articles preservation time: During refresh operation do not load articles with date older than this duration Articles age check interval: How often check and delete old (including already read) articles
>

Do any of the settings effect the "delete old articles" function?

**Comment by yanus171** [comment]
The second one does

**Comment by JunkyardCat** [comment]
So lets say i want all my articles that i fetched to be intact and never deleted no matter how old they are. What option do i need

**Comment by yanus171** [comment]
This is impossible. Your case is not logical from the delete old content sence.

**Comment by yanus171** [comment]
You can just mark all your articles as favourite and then reset each feed from menu
