### ISSUE TITLE
Add ability to set an html class for web page links

### ISSUE THREAD

**Issue by JesseRacine** [yanus171/Handy-News-Reader#881]
Forgive me if there is a way to do this, but I think it would be helpful to be able to set an HTML class or set of tags to define what gets used as links for the "Web Page - Links" feature.

It looks like it just uses all the links on a page. Is there a way to limit this to just use a set of defined links?

**Comment by yanus171** [comment]
You should setup the root text element for the page with links to include 
only needed links  or removes  unnecessary links from that page. You can do 
it in Edit content mode.
Another way of to setup filters on the whole feed
