### ISSUE TITLE
Does saving the auto-backup really need a toast?

### ISSUE THREAD

**Issue by ChaosNicro** [yanus171/Handy-News-Reader#882]
**Is your feature request related to a problem? Please describe.**
I swapped from Feeder recently to have filter expressions. And was quite confused when HNR sporadically send a toast I couldn't read in time. I used "Toast Source" to capture and read the toast. To me toasts should be short and linked to the current activity, since they only stay for a second. Debug output can be put there in a pinch, but you already use the bottom of the app screen for that.

**Describe the solution you'd like**
Do not trigger a toast on copying the auto backup.
**Describe alternatives you've considered**
Make it a full, maybe timed or toggleable, silent notification.

**Additional context**
-

**Comment by yanus171** [comment]
Ok, I will make a setting to disable it

**Comment by yanus171** [comment]
try it https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1595661175
