### ISSUE TITLE
Make the "clearing old posts" notification a progress type

### ISSUE THREAD

**Issue by ChaosNicro** [yanus171/Handy-News-Reader#883]
**Is your feature request related to a problem? Please describe.**
The "clearing old posts" notification seems to be liked to a process, given the abort-action on it. But it does seem to stick around until manually dismissed for me.

**Describe the solution you'd like**
Auto-dismiss the notification when the task is done.

**Comment by ChaosNicro** [comment]
It was probably not. The notification disappears as soon as I next open HNR. So it might just get stuck. Battery optimizations are off.

**Comment by yanus171** [comment]
May be so had crashed during this operation?

**Comment by yanus171** [comment]
May be app had crashed during this operation?
