### ISSUE TITLE
Duplicated content in tek-tips.com entries

### ISSUE THREAD

**Issue by gautxori-yuyu** [yanus171/Handy-News-Reader#884]
I have configured the link [https://www.tek-tips.com/threadminder.cfm?pid=329&page=1](https://www.tek-tips.com/threadminder.cfm?pid=329&page=1) as a web link, with an ACCEPT filter for the thread URLs (regular expession: `.+viewthread\.cfm.+`). Then I reload, and I edit content view for an article, marking `tgml` class as full text root.
So in advanced options, I get a new rule for full text (`tek-tips.com:class=tgml`)

Then, when I refresh any article (such as the one titled "[Self-Elevate Code Stops Script from Running Executable](https://www.tek-tips.com/viewthread.cfm?qid=1818036)"), **I see the text for the article duplicated**!

Furthermore, could you help me configure some advanced options,
- to change font format in the articles: i set up a rule stating `tek-tips.com:class=question=font-size:30;color:blue;` but i see no changes.
- is it possible to identify classes for any kind of tag? be it HTML 5, such as `<article>`, `<aside>`...
- is it possible to detect the pagination section in this tek-tips.com forum? I see no class to identify "next" page, but the full pagination section. 
- how should we use the "custom CSS text" option in advanced options?

**Steps to reproduce the behavior:**
1. Configure the link as stated above
2. Configure the filter as sated above
3. Define "tgml" class as a full text rule, either in "edit content view" or in advanced options
4. Refresh articles, see error

**Expected behavior**
Article text should not be duplicated.

**Screenshots**
Not available.

**Desktop (please complete the following information):**
not applicable

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 
 - OS: Android 7.0
 - Browser: not applicable
 - Version: latest HANDY NEWS READER

**Additional context**
None

**Comment by yanus171** [comment]
Change full text root string to 
tek-tips.com/threadminder.cfm:class=threadmindercontent , select Reset feed 
... menu item and refresh feed to get rid of duplicates

**Comment by gautxori-yuyu** [comment]
Thanks yanus. I guess I messed with the HTML for the topics page and the HTML for each thread. 
Does Handy Reader recognize any specific content in phpbb forums, or should there be any class tags in the root block to _automagically_ identify "title", "url", ... fields, with a pattern such as `<a[^>]+thead[^>]*>([^<]+)</a>`?
And finally, if you or anyone can provide a link to a better explanation for "advanced options" than the one given in the app or [here](https://handynewsreader.blogspot.com/2020/04/read-non-rss-websites.html)...:
- I still do not know how to make use of "Custom font", or "Custom CSS text", 
- I want to get the threads in a forum, for the newest 3 pages, but in reverse order, (https://www.tek-tips.com/threadminder.cfm?pid=329&page=3, then https://www.tek-tips.com/threadminder.cfm?pid=329&page=2, then https://www.tek-tips.com/threadminder.cfm?pid=329&page=1). Oldest, first. Is that possible?

**Comment by yanus171** [comment]
Custom funny setting allows set custom font ttf file for specific class in 
specific web site (domain). For example string
bible:tsk=PochKUcs.ttf=font-size:22; font-weight:100
sets "PochKUcs.ttf" font with "font-size:22; font-weight:100" css options 
for class "tsk" in all domains containing key word "bible". Fonts should be 
from app font preference list.

**Comment by yanus171** [comment]
Custom CSS text is just added to article CSS generated text. You can 
examine it via Share - Show HTML article menu item. If you understand CSS 
notation you can apply almost any special formatting to the article.

**Comment by yanus171** [comment]
There is no special link with explanation. I tried to explain setup items 
meaning in their description. Propose better ones if you have ideas

**Comment by gautxori-yuyu** [comment]
> Custom funny setting allows set custom font ttf file for specific class in specific web site (domain). For example string bible:tsk=PochKUcs.ttf=font-size:22; font-weight:100 sets "PochKUcs.ttf" font with "font-size:22; font-weight:100" css options for class "tsk" in all domains containing key word "bible". 
> Fonts should be from app font preference list.
Don't get this last sentence. My phone is Android 7.0, there is no "font preference list" here, and I do not know which ttf fonts may I have installed. Can the font choice be left blank? (Did not test it)
Your example could be written in the app tip, it's really helpful.

**Comment by gautxori-yuyu** [comment]
> Custom CSS text is just added to article CSS generated text.
> You can examine it via Share - Show HTML article menu item.
One more useful tip, thanks.

**Comment by yanus171** [comment]
See settings, theme, font
