### ISSUE TITLE
Error 403 with some Feeds

### ISSUE THREAD

**Issue by ArtexJay** [yanus171/Handy-News-Reader#896]
**Describe the bug**
Certain feeds such as  "https://nationalpost.com/category/news/feed.xml" and "https://thenationalpulse.com/feed/"  return error 403 forbidden when the user clicks on "reload full text" or if the option in the feed settings to fetch full text is enabled. This replaces the title to be permanently error 403.

**To Reproduce**
1. Add the feeds mentioned
2. Load the feeds in to the article list
3. Open an article and click on "reload full text"
4. See error 403

**Expected behavior**
I expect that either the full text is loaded. I've tried these feeds in other rss readers like Newsflow (on windows) and  which is able to load the full text or in Flym which only retained the original title as well as the original text.

**Smartphone (please complete the following information):**
 - Device: Xiaomi 9t pro
 - OS: android 11
 - Version 0.18.25

**Comment by yanus171** [comment]
Yes, that's strange ...

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1826837912

**Comment by ArtexJay** [comment]
I can confirm that this issue is fixed for both of these sources. Sorry for checking up on this so late.
