### ISSUE TITLE
Parse Exception for Feed

### ISSUE THREAD

**Issue by ArtexJay** [yanus171/Handy-News-Reader#897]
**Describe the bug**
When adding this feed "https://www.publishedreporter.com/feed/" I get the following error:
org.apache.harmony.xml.ExpatParser$ParseException:
At line 8, column 45: duplicate attribute

**To Reproduce**
1. Add the feed "https://www.publishedreporter.com/feed/"
2. Click on Refresh
3. See error

**Expected behavior**
To fetch the news articles correctly.

**Screenshots**
![IMG_20230830_155630](https://github.com/yanus171/Handy-News-Reader/assets/32932497/6d4923a7-e81a-4d63-af2c-dfa2e6f696d2)

**Smartphone (please complete the following information):**
 - Device: Xiaomi 9T Pro
 - OS: Android 11
 - Browser [e.g. stock browser, safari] Stock
 - Version 0.18.25

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1704321667

**Comment by ArtexJay** [comment]
This has been resolved.
