### ISSUE TITLE
please add source of the article (name of the feed) to the article view

### ISSUE THREAD

**Issue by emdete** [yanus171/Handy-News-Reader#901]
i often read atticle after atticle from the  list of unread articles without going back to the list just by swiping. often i want to know where that article comes from. a line in the header would be handy to know the source.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1751806447

**Comment by touwys** [comment]
**Release v0.19.3:**

Not any additional information related to the source is seen in the (full text reader) header. Presumably, this would be the feed name?

**Comment by yanus171** [comment]
Its only visible in non single feed sections like groups or labels

**Comment by touwys** [comment]
> Its only visible in non single feed sections like groups or labels

Thanks. 

For overall consistency in the app, is it then not feasible to provide the same support for headers elsewhere too, for e.g. in the full text reader view, where it is available at a glance? (Even though the feed name may be gleaned from information that already appear in the article text?

**Comment by ArtexJay** [comment]
I see the article sources in labels/tagged sections of articles, but I don't see them appear in custom article groups.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.19.7

**Comment by emdete** [comment]
i now see the soirce in the article view (current fdroid version), thank you very much!
