### ISSUE TITLE
Full text reload changes title

### ISSUE THREAD

**Issue by ArtexJay** [yanus171/Handy-News-Reader#904]
**Describe the bug**
Loading full article texts for Voz.us removes the article title and makes all article titles as "#preloader{display:none;}"

**To Reproduce**
1.  Add "https://voz.us/feed/?lang=en" as rss feed
2.  Click on "Load Full article" or "reload all texts"
3. See all titles changed to "#preloader{display:none;}"

**Expected behavior**
The title should not be replaced or change.

**Screenshots**
![Screenshot_2023-09-30-19-18-13-762_ru yanus171 feedexfork](https://github.com/yanus171/Handy-News-Reader/assets/32932497/2d898104-1dfb-4c9f-89bf-dcdc7f48c58e)

**Smartphone (please complete the following information):**
 - Device: Xiaomi mi 9t pro
 - OS: Android 11
 - Browser stock
 - Version 0.19.1

**Comment by touwys** [comment]
@yanus171 

Could this issue perhaps be related to this one: https://github.com/yanus171/Handy-News-Reader/issues/903#issue-1906243572

**Comment by ArtexJay** [comment]
> @yanus171
> 
> Could this issue perhaps be related to this one: [#903 (comment)](https://github.com/yanus171/Handy-News-Reader/issues/903#issue-1906243572)

Doesn't look like it to me #903 you said was using page links, while this one is using the websites official RSS feed.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1751806447

**Comment by ArtexJay** [comment]
Refresh no longer changes the title of the article from the RSS feed.
