### ISSUE TITLE
Filtered label articles are not getting shared

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#906]
Filtered label articles, getting shared via these two menu entries, flags the following two error messages:

#### 1. Menu > Share starred entries via file:
   _`"unsupported attachment"`_

#### 2. Menu > Share starred entries via text:
   _`"unsupported content"`_

The result is that the sharing process, for either instance, does not complete.

•
### [Screenshot](https://github.com/yanus171/Handy-News-Reader/assets/65730626/8682ec16-498f-4bed-b51a-d4d085342149)
•

**Comment by yanus171** [comment]
Its strange that there are no articles in your list. This operation sends only visible articles. Try to change feed section and or remove label filter

**Comment by touwys** [comment]
> Its strange that there are no articles in your list. This operation sends only visible articles. Try to change feed section and or remove label filter

I am still trying to figure this out, too. Initially, just after updating to v0.19.3 it did not work either. A little later on, I tried it again and everything went well. The third time around, it failed again, so I posted it as an issue. Even if there is a workaround, and whatever approach is used to share the entries, should it happen at all?

**Comment by yanus171** [comment]
The article list if formed according to selected feed or group, label 
filter and show unread only filter checkbox - the visible article list.
