### ISSUE TITLE
Display the total number of articles of the feed next to the feed title at the top panel. 

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#907]
Support for the display of the total number of articles of the feed next to the feed title at the top panel. 

As per screenshot:

•

![image](https://github.com/yanus171/Handy-News-Reader/assets/65730626/fb2692c6-a688-426d-b1a4-bc61f0a415f8)

•

**Comment by yanus171** [comment]
Only total articles? Or unread? Or read? There are no free space for it in 
phone's layout. And this info in available from feed list

**Comment by yanus171** [comment]
When you do left right swipe through the articles the toast with this info 
already appears
