### ISSUE TITLE
"Unstarring" labelled articles should not "unstar" all starred articles

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#911]
**STEPS:**

   1. Side-swipe.
   2. Click on the "LABELS" arrow to present all labels.
   3. Select, and click on a label that contains articles.
   4. Click to open the hamburger menu, top-right.
   5. Select "Unstar articles".
   6. Unexpectedly, this action does not "unstar" **only** the articles visible in the selected label, but **all** the articles that are classified under "Starred".

Please change this behaviour so that only the articles, which are classified to a specific, selected label, are "unstarred".

**Comment by yanus171** [comment]
Try Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1837165118

**Comment by touwys** [comment]
Fixed, thank you @yanus171
