### ISSUE TITLE
Add label name and export date to the generic text file name when sharing articles

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#912]
![image](https://github.com/yanus171/Handy-News-Reader/assets/65730626/58b685d2-5e5c-46e1-b11a-00313c57c63a)

***

Handy exports all **shared articles text files** bearing the identical generic name: **"shared_article_links.txt"**.

Please provide support that adds the **label name** to the generic text file name. In addition, also consider to include the date of export in the file name.

Example:

   1. Russia_shared_article_links_20231015
   2. Pandemic_shared_article_links_20231017
   3. Environment _shared_article_links_20231019
   4. War__shared_article_links_20231020
   5. Starred_shared_article_links_20231020 👈🏻 

As per example 5. — Starred articles, when shared, could be named thus to distinguish them from the individually labelled ones.

**Comment by touwys** [comment]
> Try [#683 (comment)](https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1826837912)

Partially provided for. The generic file name gets saved along with the date and time, but the Label prefix is missing:

[Screenshot](https://github.com/yanus171/Handy-News-Reader/assets/65730626/45bd416f-c7d6-470a-a0b5-5b034267db7f)

**Comment by yanus171** [comment]
Try to select label in feed list and share starred articles and send me a video with the this process

**Comment by touwys** [comment]
> Try to select label in feed list and share starred articles and send me a video with the this process

Whenever sharing/saving/exporting from the individual labels, the Label name is indeed correctly prefixed to the exported file name. The same does not apply to the file name of the **Starred** group of articles. (As per example 5 in the OP.)

There are further anomalies as far as exporting the labelled and starred files go. Please take a look at the annotated screenshot below, with which an attempt is made to explain the perceived anomalies:

**[HNR — Saving labelled & starred article lists](https://github.com/yanus171/Handy-News-Reader/assets/65730626/5c53cccd-1345-4026-bf5b-59e20bd0c429)**

**Comment by yanus171** [comment]
What label in file name are you waiting when activated from Starred section?

**Comment by touwys** [comment]
> What label in file name are you waiting when activated from Starred section?

Put in "Starred" as the prefix to the generic file name to distinguish it from the Labelled files, e.g.

`Starred_shared_article_links_20231128_1120`

**Comment by touwys** [comment]
> What label in file name are you waiting when activated from Starred section?
 
_Note: I am not exactly sure how to interpret what you are asking. Please read my reply below in view of that:_

Put in "Starred" as the prefix to the generic file name to distinguish it from the Labelled files, e.g.

`Starred_shared_article_links_20231128_1120`

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1837165118

**Comment by touwys** [comment]
> Try [#683 (comment)](https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1826837912)

Solved with release v0.19.11. Thank you.
