### ISSUE TITLE
Toast to indicate that not all feeds have updated

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#913]
When Handy holds numerous feeds to refresh, the user is left immediately unaware of those feeds that have not updated, once the refresh-process completes. Is it possible to support a toast that pops up after the refresh-event, to indicate that not all feeds were refreshed? Such a toast, could, very usefully, also contain of display the number of feeds that have not updated out of the total, and, at the same time, give access to resume the refresh-operation.

![Habe a Toast!](https://github.com/yanus171/Handy-News-Reader/assets/65730626/18dfe6df-3c4a-4cae-b13e-4d230d4f2ce0)

**Comment by yanus171** [comment]
#909 duplicate
