### ISSUE TITLE
Uncaught Exception: StartNotAllowedException

### ISSUE THREAD

**Issue by kanehekili** [yanus171/Handy-News-Reader#916]
**Describe the bug**
Exception is thrown when app tries to update as a backend service on Android 12

**To Reproduce**
Install the app on Android 12 and turn on automatic updates

**Expected behavior**
No exception is expected.
An explanation for the problem can be found here:
https://stackoverflow.com/questions/70044393/fatal-android-12-exception-startforegroundservice-not-allowed-due-to-mallows

**Screenshots**
None

**Smartphone :**
 - OS: Android 12
 - Browser Chrome (but not relevant - the app is in the background)

**Additional context**
Since API 31 you should use "Worker" instead of "Service", the latter will not be allowed to run in background...

**Comment by yanus171** [comment]
Update app version to last beta 
https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1783793858
