### ISSUE TITLE
Search "all articles/unread" checkbox problem

### ISSUE THREAD

**Issue by JohnVeness** [yanus171/Handy-News-Reader#917]
**Describe the bug**
When I do a search in an article list, the checkbox that toggles between "all articles" and "unread" doesn't act as expected.

**To Reproduce**
1. View the article list of a feed with several read and several unread articles
2. Ensure the checkbox at the top of the screen is empty, meaning you are viewing just unread articles
3. Click the search icon and type in a search term that would match a lot of articles, both read and unread, e.g. the word "the"

**Observed behavior**
Scrolling up and down the search results you'll see that both read and unread articles that match the search text are listed, even though the checkbox is empty (which should mean you're viewing just unread articles). You have to click the checkbox *twice* (toggle it on then off again) to make the app show just unread articles that match the search text.

**Expected behavior**
Scrolling up and down the search results you should see that just unread articles that match the search text are listed.

**Screenshots**
![Screenshot_20231106_170443_Handy Reading](https://github.com/yanus171/Handy-News-Reader/assets/2512915/cc2818fa-1080-437b-83be-021af70bc0b5)
Screenshot immediately after searching a feed for a particular word - notice a mix of both read and unread articles, even though the checkbox is empty.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A54 5G
 - OS: Android 13 (OneUI 5.1)
 - Version: 0.18.18

Thanks!

**Comment by JohnVeness** [comment]
I've just realised that the search doesn't work as I thought it did. I thought it was a filter on the current list of articles shown - so if you were viewing a single feed, the search would be limited to articles in that feed, as that seemed the expected behavour to me.

In fact, it seems that the search acts as a filter in the All Articles view, regardless of which view you were previously in.

So, if search was changed to be within the current view, that would presumably fix this issue. People who wanted to search globally could choose All Articles or Unread from the slideout menu before searching.

**Comment by yanus171** [comment]
Yes, I am also going to change search behavior as you explained

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.19.7

**Comment by touwys** [comment]
It is the release I am using.
----------------------------------------

15 Nov 2023 19:43:27 yanus171 ***@***.***>:

**Comment by JohnVeness** [comment]
Thanks, yes, searches work exactly as expected (as a filter) now. Very many thanks - that improves usability a lot.

There's still a slight UX oddness regarding the method to get *out* of the search/filter, but I'll leave that for another issue :)
