### ISSUE TITLE
Marking article search results as having been read, marks all unread articles as having been read

### ISSUE THREAD

**Issue by touwys** [yanus171/Handy-News-Reader#920]
Whenever the results of a search is marked as having been read — with the `"Mark all as read"` button — **all** the **Unread** articles are immediately similarly marked as having been read, and as such cannot be restored their to their previous, unread state.

**Steps:**

1. Go to "All articles".

2. Type in the desired search words/string.

3. Scroll through a few of the results of the search.

4. Press `"Mark all as read"` button.

5. Press the "x" next to the search box twice to clear the search string and to close the search box.

6. Issue: All the articles contained in "All articles" are now marked as read, instead of only the results of the search.

***

**Additional comments**

1. This issue was first exhibited by release v0.19.7, but repeated through to v0.19.9.
2. It appears to be related to the modification to the old search method.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1826837912

**Comment by touwys** [comment]
> Try [#683 (comment)](https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1826837912)

Issue resolved with release v0.19.10.

Thank you.
