### ISSUE TITLE
Very old articles appear on the feed as just published

### ISSUE THREAD

**Issue by hak814** [yanus171/Handy-News-Reader#921]
v0.19.9:

I import an opml file with the following contents:

```
<?xml version='1.0' encoding='utf-8'?>
<opml version='1.1'>
<head>
<title>Handy Reading export</title>
<dateCreated>1681484699110</dateCreated>
</head>
<body>
		<outline title='Bruzz - mobiliteit' type='rss' xmlUrl='https://www.bruzz.be/topic/mobiliteit/rss.xml'>
	</outline>
		<outline title='Bruzz - milieu' type='rss' xmlUrl='https://www.bruzz.be/topic/milieu/rss.xml'>
	</outline>
</body>
</opml>

```
Then I go to the 'Unread' folder and press the 'Refresh' button. The first time it seems to load correctly the recent articles, but with repeated presses, old articles appear (after up to 3 presses) with an incorrect recent date, again and again.

**Comment by yanus171** [comment]
try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1826837912

**Comment by yanus171** [comment]
+7 929 565-82-99 Наталья Петрова 500

**Comment by yanus171** [comment]
Try to reset the feed

**Comment by hak814** [comment]
The issue stays the same. The behaviour within the individual feeds is (and always was) as expected, but when pushing the refresh button within the general 'Unread' category, old articles still keep appearing.

Not every time, but just now I pushed the refresh button repeatedly and 27 out of 40 times old articles appeared.

**Comment by AI-IMED** [comment]
Yes, it happens to me like the case also sometimes

**Comment by yanus171** [comment]
For what feeds?

**Comment by yanus171** [comment]
I cant universally determine the article date in web page link feeds.

**Comment by yanus171** [comment]
What atom feeds?

**Comment by AI-IMED** [comment]
> What atom feeds?

Feeds similar to this: https://github.com/yanus171/Handy-News-Reader/releases.atom 
Sometimes I get notifications from them for old articles as being recent

**Comment by GFNIAE** [comment]
Hello,
I guess I met a similar issue, with following stream : https://ploum.net/atom.xml
Articles are not with the right dates, and not in the right order
When I reset the feed, all the articles are given with 00:00 date, which feel like the dates are not read.
This stream works well with read you and feeder.

**Comment by AI-IMED** [comment]
> I cant universally determine the article date in web page link feeds

How about using libraries that generate RSS from websites?:

https://github.com/wezm/rsspls

https://github.com/damoeb/rss-proxy

https://github.com/aphedges/rss-shim

There are many similar libraries on Github.

**Comment by yanus171** [comment]
@GFNIAE these 00 times are in the RSS, so this is correct

**Comment by yanus171** [comment]
I need a screenshots when old articles appear

**Comment by hak814** [comment]
**
![Screenshot_20231205-083317](https://github.com/yanus171/Handy-News-Reader/assets/108346580/b2acc238-6c08-43b0-b227-2201df34617d)
![Screenshot_20231205-083430](https://github.com/yanus171/Handy-News-Reader/assets/108346580/59e9a59c-12b8-4409-9ddb-c0cde7932af8)
![Screenshot_20231205-083442](https://github.com/yanus171/Handy-News-Reader/assets/108346580/c6ed31aa-bbb6-4b41-9a8c-35e7575147c1)
**

**Comment by yanus171** [comment]
And what does it mean?

**Comment by hak814** [comment]
Bruzz is a news website for Dutch speaking people in Brussels. These are all news articles about mobility (mobiliteit) en the environment (milieu).

**Comment by GFNIAE** [comment]
Hello @yanus171 ,
Here are 2 screenshots of the same stream (ploum.net/atom.xml) with handy reader and feeder. We can see that the times on handy reader (upper picture) are not the right ones.
![Screenshot_20231205-223132_Handy Reading](https://github.com/yanus171/Handy-News-Reader/assets/73499983/b853d066-5b99-4662-9dac-cb4b0c628385)
![Screenshot_20231205-223151_Feeder](https://github.com/yanus171/Handy-News-Reader/assets/73499983/94f604d2-a1dd-4d60-b100-a67944fd214d)
[_0073900868_.pdf](https://github.com/yanus171/Handy-News-Reader/files/13573201/_0073900868_.pdf)

**Comment by yanus171** [comment]
@GFNIAE what is your handy reader app version?

**Comment by yanus171** [comment]
@hak814 how does it refer to current issue?

**Comment by hak814** [comment]
See original post: the issue was about that website.
You asked for screenshots.

**Comment by GFNIAE** [comment]
Hello @yanus171 ,
My app version is 0.19.7, on Android 11 and Samsung A20e

**Comment by yanus171** [comment]
@GFNIAE install the latest beta https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1826837912

**Comment by yanus171** [comment]
@hak814 are these articles on screenshot old?

**Comment by yanus171** [comment]
@hak814 remind me feed url please

**Comment by hak814** [comment]
https://www.bruzz.be/topic/mobiliteit/rss.xml
https://www.bruzz.be/topic/milieu/rss.xml

Both feeds need to be present. If only one of them is present, the behaviour in the 'unread' folder is as expected.

**Comment by GFNIAE** [comment]
Hello @yanus171 ,

I have installed 0.19.12 on your link and it seem to work well for the same rss stream : the dates are the same as on feeder… and as the genuine website. You rock !

Thanks for your work on handy reader. I use the app everyday. The «read later» share link for every article we meet on the web is useful.

**Comment by hak814** [comment]
I'm glad to hear your issue has been solved, GFNIAE.
I've also tried version 0.19.12, but my issue is not solved yet.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1848991519

**Comment by hak814** [comment]
The new version seems to solve the issue. 
Thanks, yanus171!

**Comment by yanus171** [comment]
@GFNIAE thank you for this issue too. It was very interesting error.
