### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by paulle** [yanus171/Handy-News-Reader#93]
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void ru.yanus171.feedexfork.view.StatusText$FetcherObservable.ClearError()' on a null object reference
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:210)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:280)
	at android.os.HandlerThread.run(HandlerThread.java:65)

-------------------
Version : 0.7.40
Version Code: 138
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: H8266
Android Version : 9
User : BuildUser
Total Internal memory : 50505924608
Available Internal memory : 43339608064
-------------------
Nearly every day I get a error message like this. I don't understand it, because I've no coding skills. But it seems related to your nice newsreader.
Android 9, Sony xperia xz2

**Comment by yanus171** [comment]
Install the latest release from github or wait until fdroid update

**Comment by SIRSteiner** [comment]
@paulle Did you installed the latest release? Any news?

**Comment by paulle** [comment]
I've now version 0.86 (from f-droid) installed and now everything is working fine.
