### ISSUE TITLE
Layout with big pictures

### ISSUE THREAD

**Issue by sandoxy** [yanus171/Handy-News-Reader#94]
A facebooklike layout in the overview section would be great, with big pictures. I think many people get faster orientetation throught pictures, than text.

Thanks

**Comment by yanus171** [comment]
Yes, the picture would be great to understand your issue :)

**Comment by sandoxy** [comment]
Of course. Like this: 

http://skiilight.com/wp-content/uploads/2014/06/facebook-mobile.png

I would like to enter a feed an see each article with a headline a big picture. The same headline and picture as now, but with bigger size of the picture and different organized. I hope, it helps.

**Comment by yanus171** [comment]
Yes, I think I can make a setting for such a mode. May be it can be combined with https://github.com/yanus171/Flym/issues/64

**Comment by ThomasLeigh** [comment]
The other day I saw this and I find it a good piece to inspire Handy new article list view:
https://drive.google.com/file/d/1mS3pxtulYzRn5WANBqff_w0_VuQ_81bv/view?usp=sharing

What do You think?

**Comment by yanus171** [comment]
Implemented in Show Text mode
