### ISSUE TITLE
RTL Languages Support 

### ISSUE THREAD

**Issue by afmbsr** [yanus171/Handy-News-Reader#95]
Hi, 

I hope the app developers will implement this fix and debug within the application👇

https://gitlab.com/spacecowboy/Feeder/commit/41b751ab4280903b4a86fd39a21c6d7cc0456ce4?merge_request_iid=165

Because The application displays RTL entries horribly
![Screenshot_٢٠١٩٠٣٢١_١١٥٧٢٢](https://user-images.githubusercontent.com/38974362/54742418-6e76b700-4bd2-11e9-8f82-3742bfeaa184.jpg)
![Screenshot_٢٠١٩٠٣٢١_١١٥٨٢٣](https://user-images.githubusercontent.com/38974362/54742446-83ebe100-4bd2-11e9-9796-55e673e946bc.jpg)
![Screenshot_٢٠١٩٠٣٢١_١١٥٩٣٧](https://user-images.githubusercontent.com/38974362/54742498-a7169080-4bd2-11e9-9569-771677592097.jpg)
![Screenshot_٢٠١٩٠٣٢١_١٢٠٠٣٧](https://user-images.githubusercontent.com/38974362/54742514-b564ac80-4bd2-11e9-8b9f-de2275dcfec2.jpg)

**Comment by yanus171** [comment]
Why did you closed the issue?

**Comment by afmbsr** [comment]
I wish I could use the application but because it does not support the correct formats of the languages ​​RTL prevents me from using it.  The issue has been raised for a long time and has not reacted to it.  And now I open the case again with a link to the comprehensive correction of the case and I hope to solve the problem .. And thank you

**Comment by Ryuno-Ki** [comment]
https://www.smashingmagazine.com/2017/11/right-to-left-mobile-design/ could give you an idea on what to consider.

(Hint: It's not a „flip everything “)

**Comment by yanus171** [comment]
Give me an url to that page

**Comment by afmbsr** [comment]
@yanus171 
https://gitlab.com/spacecowboy/Feeder/commit/41b751ab4280903b4a86fd39a21c6d7cc0456ce4?merge_request_iid=165

**Comment by afmbsr** [comment]
@yanus171 
https://gitlab.com/spacecowboy/Feeder/commit/41b751ab4280903b4a86fd39a21c6d7cc0456ce4?merge_request_iid=165

**Comment by afmbsr** [comment]
@yanus171, For more information, this is the link to discussions on the subject

https://gitlab.com/spacecowboy/Feeder/issues/176

**Comment by yanus171** [comment]
I ask you again: give me an url of problem page. I use webview, not textview

**Comment by afmbsr** [comment]
https://www.electrony.net/
The problem includes all URLs that run in RTL languages ​​and on all pages and articles

**Comment by yanus171** [comment]
Try this version https://drive.google.com/file/d/1Mt-GDEFV-9wESbxgHTqsWh355JKxkyoI/view?usp=drivesdk

**Comment by afmbsr** [comment]
@yanus171, Excuse .. What changes have you made?  I did not find any change!

**Comment by yanus171** [comment]
I set textDirection=locale to articles webview (what is your phone locale?). So this is insufficient. The next step is to set dir=rtl to body html tag of article. But I can try it only after week later.

**Comment by yanus171** [comment]
By the way please look if your articles source html has attribute dir in body tag.

**Comment by yanus171** [comment]
One more try https://drive.google.com/file/d/1LUeEytLuUoKa8NhlEpZxmcNv5qbmFw5v/view?usp=sharing
Make sure you have rtl language in system settings

**Comment by afmbsr** [comment]
RTL articles appear correctly only when the show original text on article list option is enabled for any type of upload, either on RSS or WEB
![Screenshot_٢٠١٩٠٨٠٤_٠٩٣٠٤٨](https://user-images.githubusercontent.com/38974362/62420444-1df08980-b69b-11e9-82cd-1b1675304ee3.jpg)
This situation does not help me because it lacks many advantages such as articles with a star and the emergence of images and scrolling to the right or left .. Etc

**Comment by yanus171** [comment]
I can't understand you clearly. Give me a screenshot of problem, and the 
correct one

**Comment by afmbsr** [comment]
![Screenshot_٢٠١٩٠٨٠٤_١٤٤٧٢٤](https://user-images.githubusercontent.com/38974362/62423246-78074400-b6c7-11e9-8d95-2113e600b3dd.jpg)
However, there is no button for favorite articles, no images in the details of the article, but only small squares, there is no left or right scrolling feature to navigate between the articles, and many other features and options that I need

The only thing I hope is RTL support in the textview
![Screenshot_٢٠١٩٠٨٠٤_١٤٥٠١٤](https://user-images.githubusercontent.com/38974362/62423556-7db25900-b6ca-11e9-8fac-3d90361f8007.jpg)

**Comment by yanus171** [comment]
Ok. Please give me an URL of that article and the screenshot of the correct view from your browser.

**Comment by afmbsr** [comment]
https://www.electrony.net/343097/sony-%d8%aa%d9%8f%d8%b9%d9%84%d9%86-%d8%b9%d9%86-%d8%a3%d8%b1%d8%a8%d8%a7%d8%ad-%d9%82%d9%8a%d8%a7%d8%b3%d9%8a%d8%a9-%d9%84%d9%84%d8%b1%d8%a8%d8%b9-%d8%a7%d9%84%d8%a3%d9%88%d9%84-%d9%85%d9%86-%d8%a7/
![Screenshot_٢٠١٩٠٨٠٤-١٨٥١٤٩](https://user-images.githubusercontent.com/38974362/62426303-b31b6e80-b6eb-11e9-9df3-97a3940797f5.png)
![Screenshot_٢٠١٩٠٨٠٤_١٨٥٤٣٢](https://user-images.githubusercontent.com/38974362/62426307-bdd60380-b6eb-11e9-8e5b-504a4f696401.jpg)
NOTE: The problem has been fixed in article titles. 
 The article's details need only RTL support and everything becomes great

**Comment by yanus171** [comment]
I can't find the difference between browser and HNR variant marked with a cross from previous post (except wrap line)

**Comment by afmbsr** [comment]
Yes, exactly (except wrap line)
![Screenshot_٢٠١٩٠٨٠٥_٠٦٠٥٤١](https://user-images.githubusercontent.com/38974362/62436384-2357dd80-b748-11e9-979d-76cc2001a7a7.jpg)

**Comment by yanus171** [comment]
So I don't understand what's wrong if HNR shows text as in browser.

**Comment by afmbsr** [comment]
Yes I agree with you that there is no error in the order of the texts, but it is desirable that the head of the lines is adjacent to the right.  Displaying the lines in this way causes headaches and loss of focus because we are not used to seeing RTL lines aligned to the left

**Comment by yanus171** [comment]
Try https://drive.google.com/file/d/1pfHi3ic4WLskU0FbKUQBdqda4u02LJ-m/view?usp=sharing

**Comment by afmbsr** [comment]
Yes, RTL feeds now appear in the correct alignment but unfortunately at the expense of LTR feeds that have lost the correct alignment
![Screenshot_٢٠١٩٠٨٠٧_١٧٤٨٥٤](https://user-images.githubusercontent.com/38974362/62632839-cfade580-b93b-11e9-81ad-5465c7e459fa.jpg)

**Comment by yanus171** [comment]
And how an app can understand if article is RTL or not?

**Comment by afmbsr** [comment]
This rule:
RTL articles can be intertwined with LTR texts or come without LTR texts, while LTR articles do not come with RTL texts at all

**Comment by yanus171** [comment]
Try https://drive.google.com/file/d/11IzCednJ0iGri-dQy0X4ycqoYrws9Vcj/view?usp=sharing

**Comment by afmbsr** [comment]
Now, very good, thank you so much😍

**Comment by yanus171** [comment]
Glad to hear it! May be it's time to translate the app to one of this RTL languages?

**Comment by afmbsr** [comment]
I hope so, but unfortunately I do not know anything in programming

**Comment by yanus171** [comment]
@afmbsr , there is a link in app about section for those who can help with translation (no special knowloged required)

@ThomasLeigh , its our failture (app design and gui) that users do not know about this :(

**Comment by ThomasLeigh** [comment]
@yanus171 

I've created https://github.com/yanus171/Handy-News-Reader/issues/315 .

**Comment by afmbsr** [comment]
@yanus171, The Arabic language isn't available in the translation project on Crowdin

**Comment by ThomasLeigh** [comment]
@afmbsr 

In case of [the website translation](https://crowdin.com/project/handy-news-reader-website) (*Handy News Reader* how-to's, help, etc.) I've just added Arabic language. Alexey probably will add it soon, too. Thanks for pointing this out.

**Comment by yanus171** [comment]
@afmbsr, I have added the arabic language to crowdin. You can try now. Use the link in the app about section

**Comment by afmbsr** [comment]
Hi, yanus171
I have completed the translation into Arabic

**Comment by yanus171** [comment]
Thank you much, I will merge it into next app release

**Comment by yanus171** [comment]
Test it please https://drive.google.com/file/d/1EtLq4arjO_YrjerctSkfpmMYUYXSHaum/view?usp=sharing

**Comment by afmbsr** [comment]
@yanus171, Thank you for providing this test version, I only need some time (maybe two days) to refine the translation.  I'll tell you when you're done

**Comment by afmbsr** [comment]
Hi, yanus171
I have completed the process of improving the Arabic translation

**Comment by ThomasLeigh** [comment]
@yanus171 

> Test it please https://drive.google.com/file/d/1EtLq4arjO_YrjerctSkfpmMYUYXSHaum/view?usp=sharing

[off-topic] I wonder if that version maybe include also non-clickable full screen article headers? :)

**Comment by yanus171** [comment]
Not yet

**Comment by ThomasLeigh** [comment]
@afmbsr 

Would You be interested in translating the _[HNR website](https://handynewsreader.blogspot.com)_ for the Arabic as well? (more info [here](https://handynewsreader.blogspot.com/2019/05/translations.html))

**Comment by yanus171** [comment]
App version with updated translation https://drive.google.com/file/d/11SpmsE-gGEDbrPDLkgeOuapgF0YNpuEk/view?usp=drivesdk

**Comment by afmbsr** [comment]
@yanus171 
Now everything is wonderful.
 Reminder: I've translated the new option as well (Title Link)

**Comment by afmbsr** [comment]
@yanus171, 
An error occurs in RTL articles (in the list of article titles only), when the article starts with text from LTR.  Although the error has no negative effect when viewing the same article.  But fixing the error would be great, especially for people who want to preview only article titles
![Screenshot_20190909_073931](https://user-images.githubusercontent.com/38974362/64505131-7985e680-d2db-11e9-9632-f44d0a867ce8.jpg)

Comparison
![Screenshot_20190909_080459](https://user-images.githubusercontent.com/38974362/64505223-cb2e7100-d2db-11e9-8555-44bfe9ee92fb.jpg)

This is the link to the first article page
https://www.electrony.net/345450/acer-%d8%aa%d9%8f%d8%ad%d8%b0%d8%b1-%d9%85%d9%86-%d8%aa%d8%b1%d8%a7%d8%ac%d8%b9-%d8%a3%d8%b1%d8%a8%d8%a7%d8%ad-%d8%b5%d8%a7%d9%86%d8%b9%d9%8a-%d8%a7%d9%84%d8%ad%d9%88%d8%a7%d8%b3%d9%8a%d8%a8-%d8%a7/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+electronynet+%28%D8%A5%D9%84%D9%83%D8%AA%D8%B1%D9%88%D9%86%D9%8A%29
