### ISSUE TITLE
error 0.7.46

### ISSUE THREAD

**Issue by cemcem7** [yanus171/Handy-News-Reader#96]
UNCAUGHT EXCEPTION ------------------- Stacktrace: java.lang.NoClassDefFoundError: ru.yanus171.feedexfork.service.AutoJobService 	at ru.yanus171.feedexfork.activity.HomeActivity.onCreate(HomeActivity.java:182) 	at android.app.Activity.performCreate(Activity.java:5451) 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358) 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2452) 	at android.app.ActivityThread.access$900(ActivityThread.java:172) 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302) 	at android.os.Handler.dispatchMessage(Handler.java:102) 	at android.os.Looper.loop(Looper.java:136) 	at android.app.ActivityThread.main(ActivityThread.java:5586) 	at java.lang.reflect.Method.invokeNative(Native Method) 	at java.lang.reflect.Method.invoke(Method.java:515) 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 	at dalvik.system.NativeStart.main(Native Method)  ------------------- Version : 0.7.46 Version Code: 144 Package : ru.yanus171.feedexfork FilePath : /data/data/ru.yanus171.feedexfork/files Phone Model: SM-G900FQ Android Version : 4.4.2 User : dpi Total Internal memory : 12667727872 Available Internal memory : 468754432 -------------------

**Comment by yanus171** [comment]
Guess you have Android 4? Try this release https://github.com/yanus171/Flym/releases/tag/v0.7.47

**Comment by yanus171** [comment]
By the way Android 4 has no auto refresh and backup features. But it is a subject of another issue

**Comment by SIRSteiner** [comment]
Does this problem still exist? If not, please close, because I think that due to the large number of issues it is difficult for @yanus171 to work through everything.
