### ISSUE TITLE
Message sorting.

### ISSUE THREAD

**Issue by hochl** [yanus171/Handy-News-Reader#98]
I think Handy News Reader could use a better sorting option than "show oldest articles first". I suggest the following option toggles:
[ ] sort order:
    newest first
    oldest first
[ ] display unread messages first

So a combination of newest first / unread messages first would display a list of all unread messages ordered so that the latest entry is at the top, and after this a list of read messages with the first being the latest one.

**Comment by yanus171** [comment]
It would be better to separate your ideas into several issues. So we could discuss them separately

**Comment by hochl** [comment]
I adjusted the issue text accordingly.

**Comment by yanus171** [comment]
So we need an additional item in app setting to display unread first?

**Comment by hochl** [comment]
I suggest to have a sort order option (newest first / oldest first / as-is) and then an option "show unread items first" or "group unread messages", so that you can have a view where all unread items are either at the top or at the bottom of the list, grouped together, without read items intermixed. If all options are disabled you just show the messages in their normal sorting order. If the newest / oldest option is set you order them according to their timestamp, and if the unread option is set, too, you additionally order them by their unread status first, then by their date sort order. For example, if you activate "newest first / group unread" you have a display where on the top of the screen all unread messages are displayed, with the latest one on top, and then, below those unread messages, all read items will be listen, with the newest one first and the oldest entry at the bottom.

I hope this description was not too confusing :^)

**Comment by yanus171** [comment]
Yes, now it's clear. One more question. Should it be in settings or on the article list screen action bar ?

**Comment by hochl** [comment]
I guess this is a more general setting that can be hidden in the configuration menu, I doubt many people will constantly change the sort order. The hide read messages checkbox is pretty nice to have in the action bar like it is now, tho.
